// Code generated by kit from design/observe/logger.yaml (sha256 661b8e45687b4fc539f4a30a2a6ecede4ad4143101750fa6ad29deaf9487a0e5, body b6192deb0955cef7c8ce8b8ea42e0d93b12a7b47259c20bbfed81bd25b3f0b49). DO NOT EDIT.

package memory_test

import (
	"context"

	corelogger "github.com/kitsunium/sdk/internal/core/observe/logger"
	"github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory"
)

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.Memory type struct{}
var _ *memory.Memory

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.(*Memory).Close method func() error
var _ func(*memory.Memory) error = (*memory.Memory).Close

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.(*Memory).Flush method func(ctx context.Context) error
var _ func(_ *memory.Memory, ctx context.Context) error = (*memory.Memory).Flush

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.(*Memory).Len method func() int
var _ func(*memory.Memory) int = (*memory.Memory).Len

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.(*Memory).Records method func() []github.com/kitsunium/sdk/internal/core/observe/logger.RecordEvent
var _ func(*memory.Memory) []corelogger.RecordEvent = (*memory.Memory).Records

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.(*Memory).Reset method func()
var _ func(*memory.Memory) = (*memory.Memory).Reset

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.(*Memory).Write method func(ctx context.Context, r github.com/kitsunium/sdk/internal/core/observe/logger.RecordEvent, p []byte) (n int, err error)
var _ func(_ *memory.Memory, ctx context.Context, r corelogger.RecordEvent, p []byte) (n int, err error) = (*memory.Memory).Write

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.NewMemory func func() *github.com/kitsunium/sdk/internal/service/observe/logger/sink/memory.Memory
var _ func() *memory.Memory = memory.NewMemory
