// Code generated by kit from design/kernel/collections.yaml (sha256 ba5c15432feeda1977e0eb169ce38c271b544127cb78836361cbca94da2c5f0c, body c74522ad1e4a94f72f27400fe778f6b4559447a6ee0e5b561ade8ef1e9319a1e). DO NOT EDIT.

package ring_test

import (
	kring "github.com/kitsunium/sdk/internal/kernel/collections/ring"
	"github.com/kitsunium/sdk/pkg/v1/collections/ring"
)

// go:github.com/kitsunium/sdk/pkg/v1/collections/ring.CapZero var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &ring.CapZero
	x = &kring.CapZero
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/collections/ring.Empty var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &ring.Empty
	x = &kring.CapZero
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/collections/ring.Full var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &ring.Full
	x = &kring.CapZero
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/collections/ring.New[...] func func[T any](capacity int) (github.com/kitsunium/sdk/pkg/v1/collections/ring.Queue[T], error)
func _[T any]() {
	var _ func(capacity int) (ring.Queue[T], error) = ring.New[T]
}

// go:github.com/kitsunium/sdk/pkg/v1/collections/ring.Queue alias [T any] github.com/kitsunium/sdk/internal/kernel/collections/ring.Queue[T]
func _[T any]() {
	var _ *kring.Queue[T] = (*ring.Queue[T])(nil)
}
