load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "syslog",
    srcs = [
        "codes.go",
        "config.go",
        "errors.go",
        "priority.go",
        "syslog_sink.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/logger/sink/syslog",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":syslog",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "syslog_test",
    srcs = [
        "priority_internal_test.go",
        "syslog_sink_external_test.go",
        "syslog_sink_internal_test.go",
    ],
    embed = [":syslog"],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
        "//internal/kernel/errs",
    ],
)
