// Code generated by kit from design/data/codec/asn1.yaml (sha256 ccbd5c135d5971bbe9a74049d611424340e0fd6bf6140be9076d5d514f7828cf, body 9a35a52cc72c408e45357df67669cce4a6bd4474027760c099d873c50835660b). DO NOT EDIT.

package asn1_test

import (
	"github.com/kitsunium/sdk/internal/core/data/codec/asn1"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/data/codec/asn1.CodeASN1MarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := asn1.CodeASN1MarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, asn1.CodeASN1MarshalFailed == 0x00_03_09_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/asn1.CodeASN1UnmarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := asn1.CodeASN1UnmarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, asn1.CodeASN1UnmarshalFailed == 0x00_03_09_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/asn1.MarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &asn1.MarshalFailed

// go:github.com/kitsunium/sdk/internal/core/data/codec/asn1.UnmarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &asn1.UnmarshalFailed
