// Code generated by kit from design/data/codec/asn1.yaml (sha256 62f3427c51f841b69b24f9c6168f321b503d376f8d971a3f38f0eccb77656522, body 8777084f800f2a9fc1dbc8f68469212dff29c2b61d2e0152574ac9d37ced0f8a). DO NOT EDIT.

package asn1

import "github.com/kitsunium/sdk/internal/kernel/errs"

// range: 0.3.9.0 - 0.3.9.255

// CodeASN1MarshalFailed identifies a failure inside encoding/asn1.Marshal.
const CodeASN1MarshalFailed errs.Code = 0x00_03_09_01 // 0.3.9.1

// CodeASN1UnmarshalFailed identifies a failure inside encoding/asn1.Unmarshal.
const CodeASN1UnmarshalFailed errs.Code = 0x00_03_09_02 // 0.3.9.2

var (
	// MarshalFailed wraps a failure from encoding/asn1.Marshal.
	MarshalFailed = errs.Define(CodeASN1MarshalFailed, "MARSHAL_FAILED",
		"ASN.1 DER encoding failed",
		"service/data/codec/asn1: encoding/asn1.Marshal returned an error")

	// UnmarshalFailed wraps a failure from encoding/asn1.Unmarshal.
	UnmarshalFailed = errs.Define(CodeASN1UnmarshalFailed, "UNMARSHAL_FAILED",
		"ASN.1 DER decoding failed",
		"service/data/codec/asn1: encoding/asn1.Unmarshal returned an error")
)
