// Code generated by kit from design/observe/trace.yaml (sha256 a0da8a669a18bf1d40ce26b17072c283286d34484ae78fe6733d98412b1d69af, body baadd7eca66cddc60eb73c8c223e0f675e9c5ca6db886ff3290591fc82e3fe2d). DO NOT EDIT.

package trace_test

// package github.com/kitsunium/sdk/pkg/v1/observe/trace doc:304b44da26fe9cb96c7a76bb66d05f5d373d4cfa8b1ef0ed7bd2451b2149c7dd

import (
	"context"
	"io"
	"net/http"
	"time"

	corenet "github.com/kitsunium/sdk/internal/core/net"
	coreotel "github.com/kitsunium/sdk/internal/core/observe/otel"
	coretrace "github.com/kitsunium/sdk/internal/core/observe/trace"
	svctrace "github.com/kitsunium/sdk/internal/service/observe/trace"
	"github.com/kitsunium/sdk/pkg/v1/observe/trace"
)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AlwaysSample func func(params github.com/kitsunium/sdk/pkg/v1/observe/trace.SamplingParams) bool doc:01b9883f72ff189fc65d5cea6ad1b556018bc9aa32bb3165d599e83f3120bc0f
var _ func(params trace.SamplingParams) bool = trace.AlwaysSample

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Attr alias github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue doc:b97a4994aa598b5d8495b6b4de87828f49779a30878a0e930a0b8eff5998b6a0
var _ *coreotel.AttrValue = (*trace.Attr)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKind alias github.com/kitsunium/sdk/internal/core/observe/otel.AttrKind doc:d7a308a3fd7626488da2b772b502a123078b1379366a172496b1748f48b3c223
var _ *coreotel.AttrKind = (*trace.AttrKind)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKindBool const github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKind doc:c4a05a1c0c90dee8628f7f422d123daa34975e3c7d38262d1966ba4e6220d48a
func _() {
	x := trace.AttrKindBool
	var _ *trace.AttrKind = &x
	_ = map[bool]int{false: 0, trace.AttrKindBool == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKindFloat64 const github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKind doc:ea10d9b4578f9df605a55d542790e7901f7451df3e66251f9a47e6f9396f8251
func _() {
	x := trace.AttrKindFloat64
	var _ *trace.AttrKind = &x
	_ = map[bool]int{false: 0, trace.AttrKindFloat64 == 4: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKindInt64 const github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKind doc:e5b1b3a9353c18f2294607604dbe1bbc464104c4d49819fa256406bd6ad5f7b0
func _() {
	x := trace.AttrKindInt64
	var _ *trace.AttrKind = &x
	_ = map[bool]int{false: 0, trace.AttrKindInt64 == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKindInvalid const github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKind doc:badc2d6b264869b05da2c4118e2e42d5354ee9bf35d60c2b8716aed08646b92c
func _() {
	x := trace.AttrKindInvalid
	var _ *trace.AttrKind = &x
	_ = map[bool]int{false: 0, trace.AttrKindInvalid == 0: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKindString const github.com/kitsunium/sdk/pkg/v1/observe/trace.AttrKind doc:7ddc322ccd7f3ccb5a51724d14fcf5ea0c44d2eaebbba8f46c2435307b068d18
func _() {
	x := trace.AttrKindString
	var _ *trace.AttrKind = &x
	_ = map[bool]int{false: 0, trace.AttrKindString == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.AvailableExporters func func() []github.com/kitsunium/sdk/pkg/v1/observe/trace.ExporterName doc:69c800a5992818789d19a30898ce62d65ae5b374667871ab24c42ace50367e1e
var _ func() []trace.ExporterName = trace.AvailableExporters

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Bool func func(key string, value bool) github.com/kitsunium/sdk/pkg/v1/observe/trace.Attr doc:2c2745f20cf54814591072ed7bc71147d070aec9273e9d60a0fdbd5f5d030779
var _ func(key string, value bool) trace.Attr = trace.Bool

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Carrier alias github.com/kitsunium/sdk/internal/core/observe/trace.Carrier doc:295f0396e0f57d797040af8e6f9c5094dd65117646674f8339e764468a671b31
var _ *coretrace.Carrier = (*trace.Carrier)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ClientMiddleware func func(tracer github.com/kitsunium/sdk/pkg/v1/observe/trace.Tracer) github.com/kitsunium/sdk/internal/core/net.Middleware[net/http.RoundTripper] doc:de628513038881b651a23aaf609ff68513b4fe654a69606e8c0139903c5814b2
var _ func(tracer trace.Tracer) corenet.Middleware[http.RoundTripper] = trace.ClientMiddleware

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ContextWithSpanContext func func(parent context.Context, spanContext github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContext) context.Context doc:da70bd6ff225c496bd439c6c83269a88b1640588e8d701d73f4a5d6a7d24ca34
var _ func(parent context.Context, spanContext trace.SpanContext) context.Context = trace.ContextWithSpanContext

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.DefaultMaxSpans const int doc:c976a420271addaed5c62f0f81e7624e114bf8536c8450b1661c01727beff22b
func _() {
	x := trace.DefaultMaxSpans
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.DefaultMaxSpans == 2048: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.DefaultOTLPMaxResponseBytes const int64 doc:b2bf34c3246035b73c87d40facca1054bcd4c4830a7b323789a30b9703fc1d41
func _() {
	x := trace.DefaultOTLPMaxResponseBytes
	var _ *int64 = &x
	_ = map[bool]int{false: 0, trace.DefaultOTLPMaxResponseBytes == (1 << 20): 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.DefaultOTLPTimeout const time.Duration doc:6857d5628fab71f824ef8d11b16c303c4bde77d1fa426938ad813d40f91f8530
func _() {
	x := trace.DefaultOTLPTimeout
	var _ *time.Duration = &x
	_ = map[bool]int{false: 0, trace.DefaultOTLPTimeout == 10000000000: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.DefaultScopeName const string doc:fa1d8fb1f5d04646326e99086afee7da1301dba9c07b379f20c0f82ae4f55dc7
func _() {
	x := trace.DefaultScopeName
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.DefaultScopeName == "github.com/kitsunium/sdk/pkg/v1/observe/trace": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.DuplicateRegistration var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:050431a6bc9cb36750a7890101580f31c5dda4eab0948352d0afe8e588b7325b
func _() {
	x := &trace.DuplicateRegistration
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.EncodeOTLPJSON func func(spans github.com/kitsunium/sdk/pkg/v1/observe/trace.Spans) (doc []byte, err error) doc:777b64fee89c2e4d55fe51083ac8acf70e4af6946bc16070e577be7755006ae5
var _ func(spans trace.Spans) (doc []byte, err error) = trace.EncodeOTLPJSON

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.EntropyFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:6088269d3f0f36af426d5c2434d3975004974464b96e5e6be676c872fba3bbb2
func _() {
	x := &trace.EntropyFailed
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Event alias github.com/kitsunium/sdk/internal/core/observe/trace.EventValue doc:392eeb31bdd42a0f1b0ba0921eaaaada48f6bffa4f2ff46aa18ee13877994132
var _ *coretrace.EventValue = (*trace.Event)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ExceptionEventName const string doc:2751271d2594777167878acd6d43fb70aa6243207cc19ec039dfc679f3c982c7
func _() {
	x := trace.ExceptionEventName
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ExceptionEventName == "exception": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ExceptionMessageKey const string doc:9fdc8962efa2f613ee64cddf3d25b8816554a61096502321a01a5b4c10131b96
func _() {
	x := trace.ExceptionMessageKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ExceptionMessageKey == "exception.message": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ExceptionTypeKey const string doc:20fbccb3293ef77dd55d5bb692a530967218010217f1701105fb81ca359064c1
func _() {
	x := trace.ExceptionTypeKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ExceptionTypeKey == "exception.type": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Export func func(name github.com/kitsunium/sdk/pkg/v1/observe/trace.ExporterName, spans github.com/kitsunium/sdk/pkg/v1/observe/trace.Spans) error doc:3cc736939854a3e1aff6978edf2e12702ec6b4d40dfbf472582ba9b6319dc5a0
var _ func(name trace.ExporterName, spans trace.Spans) error = trace.Export

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ExportFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:75e3f0a0fffa40c61c6d7179b3b2fb0f39cabb070c5d0dcfb78d5463c14da0b2
func _() {
	x := &trace.ExportFailed
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ExporterName alias github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName doc:df0e1d4bfd308da2e7458f0f2314be8d8c345c8abc953393b556100e5f8760b9
var _ *coretrace.ExporterName = (*trace.ExporterName)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Extract func func(carrier github.com/kitsunium/sdk/pkg/v1/observe/trace.Carrier) github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContext doc:2ae68fd7715f53770e4bdac67166919d8b5380e6d8439e220bb805007974aa98
var _ func(carrier trace.Carrier) trace.SpanContext = trace.Extract

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.FlagSampled const github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceFlags doc:bcd610014837da2f36fc19211fa57402b34977f49d6dca26b5e73cbc5b30b2d8
func _() {
	x := trace.FlagSampled
	var _ *trace.TraceFlags = &x
	_ = map[bool]int{false: 0, trace.FlagSampled == 0x01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Float64 func func(key string, value float64) github.com/kitsunium/sdk/pkg/v1/observe/trace.Attr doc:b67ad38c615d66bae207c909f33a064e2ea11ce464288260b42eb021250f2da1
var _ func(key string, value float64) trace.Attr = trace.Float64

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.FormatTraceParent func func(context github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContext) (header string, ok bool) doc:f9ecacb02f9f1a01a6df045ef6026849d383e68aebcc787d8bcfb4e638e02a09
var _ func(context trace.SpanContext) (header string, ok bool) = trace.FormatTraceParent

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.HTTPRequestMethodKey const string doc:9883e590f89d0df9e68be6c50ce3e2901c6deb8c349de5a368848b955635b936
func _() {
	x := trace.HTTPRequestMethodKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.HTTPRequestMethodKey == "http.request.method": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.HTTPResponseStatusCodeKey const string doc:df25a9690afdc020238ea82ea596077ba06a3c8a3658b8428b5725f7f849d8d9
func _() {
	x := trace.HTTPResponseStatusCodeKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.HTTPResponseStatusCodeKey == "http.response.status_code": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Inject func func(context github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContext, carrier github.com/kitsunium/sdk/pkg/v1/observe/trace.Carrier) doc:9798cc237910e737000d4f39cfd5031f54e362c8bed65f50e8098b5d2a622be8
var _ func(context trace.SpanContext, carrier trace.Carrier) = trace.Inject

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Int64 func func(key string, value int64) github.com/kitsunium/sdk/pkg/v1/observe/trace.Attr doc:d521a22e4f4eb7b32c2dc154fc51f0904a5de6caf4a0bfd8db7abe751fa4f36b
var _ func(key string, value int64) trace.Attr = trace.Int64

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.InvalidAttribute var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:53fa31b8373d8d9e36b547c56d8071d35a4d9c030aa709b2ae85f183a1d059a2
func _() {
	x := &trace.InvalidAttribute
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.InvalidSampleRatio var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:4a74887f6de409f80a85dc050a0421b70bae868515726814ddc8257078bd2ca6
func _() {
	x := &trace.InvalidSampleRatio
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.InvalidSpanName var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:1f3c9319b3a219faaa0162a9b4169b07031fc2971d9d9f48efb7931410b152e7
func _() {
	x := &trace.InvalidSpanName
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.InvalidTraceParent var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:92a534a1b5243035105ea2b8d7d00a24314ee53c1af7671f119942231b0fc0d1
func _() {
	x := &trace.InvalidTraceParent
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.InvalidTraceState var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:19f3ad91bcc939fa3beaf73bf9c6325ba4ca7826f31643d03cc4f91a612d13ca
func _() {
	x := &trace.InvalidTraceState
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Kind alias github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:1c4ceab02b11f347b8fc434506dfa0718425115b266fe934b0a324855f06883f
var _ *coretrace.SpanKind = (*trace.Kind)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.KindClient const github.com/kitsunium/sdk/pkg/v1/observe/trace.Kind doc:cc57510c69ff8977892d7d7f66b2f5be1b3fafa17ba1dd7b8bf9a074504565ac
func _() {
	x := trace.KindClient
	var _ *trace.Kind = &x
	_ = map[bool]int{false: 0, trace.KindClient == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.KindConsumer const github.com/kitsunium/sdk/pkg/v1/observe/trace.Kind doc:ea3bf3dfff5ecb61dd4a8bd40706bf9c07ddff07ce940ab9e9292ed019c41c87
func _() {
	x := trace.KindConsumer
	var _ *trace.Kind = &x
	_ = map[bool]int{false: 0, trace.KindConsumer == 5: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.KindInternal const github.com/kitsunium/sdk/pkg/v1/observe/trace.Kind doc:fe2c9c0e61f5e4b6626aaea2f5b0d41c0c52b7fb2a1eabc81b5fac289ed117f6
func _() {
	x := trace.KindInternal
	var _ *trace.Kind = &x
	_ = map[bool]int{false: 0, trace.KindInternal == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.KindProducer const github.com/kitsunium/sdk/pkg/v1/observe/trace.Kind doc:b805d52183ded61c854175e4a16e67881a6a203c7449be035f01196f6265e343
func _() {
	x := trace.KindProducer
	var _ *trace.Kind = &x
	_ = map[bool]int{false: 0, trace.KindProducer == 4: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.KindServer const github.com/kitsunium/sdk/pkg/v1/observe/trace.Kind doc:d6dffc21d5ba7c5710372da51e3916ad76852bd399c990ac5b91016a08179fbc
func _() {
	x := trace.KindServer
	var _ *trace.Kind = &x
	_ = map[bool]int{false: 0, trace.KindServer == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.KindUnspecified const github.com/kitsunium/sdk/pkg/v1/observe/trace.Kind doc:36d461547ea006c1e082fd54ee9ffbe5f751366acf2e3964a20a26beaab4a259
func _() {
	x := trace.KindUnspecified
	var _ *trace.Kind = &x
	_ = map[bool]int{false: 0, trace.KindUnspecified == 0: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Link alias github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue doc:0b5e25f7ba67817dd0417d4fc9e22a1622aad692aadd1e2281d6ec45751a76fe
var _ *coretrace.LinkValue = (*trace.Link)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.LookupExporter func func(name github.com/kitsunium/sdk/pkg/v1/observe/trace.ExporterName) (e github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanExporter, ok bool) doc:f90593b37498102c02b0367fc54c49073947abd0ea63eff4ac30d2280c9d8c96
var _ func(name trace.ExporterName) (e trace.SpanExporter, ok bool) = trace.LookupExporter

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.MaxTraceStateMembers const int doc:abb0bc69aebee664d711bd90072d8667039f8263f6eb335a80691e9c118eb2ad
func _() {
	x := trace.MaxTraceStateMembers
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.MaxTraceStateMembers == 32: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.NeverSample func func(params github.com/kitsunium/sdk/pkg/v1/observe/trace.SamplingParams) bool doc:216eadd431caa3f4c5aa785d075639311b027ec4d72fe9e156e8a3f3633f74f0
var _ func(params trace.SamplingParams) bool = trace.NeverSample

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.NewOTLPHTTPExporter func func(name github.com/kitsunium/sdk/pkg/v1/observe/trace.ExporterName, cfg github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPHTTPConfig) (exporter github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanExporter, err error) doc:3fc631ecba109ddf61d57986fb3f4dc591d7af502d898a9dec12953d816876f4
var _ func(name trace.ExporterName, cfg trace.OTLPHTTPConfig) (exporter trace.SpanExporter, err error) = trace.NewOTLPHTTPExporter

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.NewOTLPJSONExporter func func(name github.com/kitsunium/sdk/pkg/v1/observe/trace.ExporterName, dst io.Writer) github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanExporter doc:e07bde871193f6d3a5c6a58b268abe39c1f1cb4c4abdf8da9de74ab6f85afee1
var _ func(name trace.ExporterName, dst io.Writer) trace.SpanExporter = trace.NewOTLPJSONExporter

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.NewRecorder func func(cfg github.com/kitsunium/sdk/pkg/v1/observe/trace.RecorderConfig) *github.com/kitsunium/sdk/pkg/v1/observe/trace.Recorder doc:dd96c1e71fd3ec3f744472cf21497393a237a7bcd417ddccc52a46b32aa8d3a1
var _ func(cfg trace.RecorderConfig) *trace.Recorder = trace.NewRecorder

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.NewSpanID func func() (id github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanID, err error) doc:9a5121d05a8e917df0d5b10f77e9d15e7c2877d9157f0b6679f1eddda8a7a881
var _ func() (id trace.SpanID, err error) = trace.NewSpanID

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.NewTraceID func func() (id github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceID, err error) doc:61226a0892d1fb5d4e189624256d55790cdba2476cda5f2db4e4276afd0bb10f
var _ func() (id trace.TraceID, err error) = trace.NewTraceID

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.NewTracer func func(cfg github.com/kitsunium/sdk/pkg/v1/observe/trace.TracerConfig) *github.com/kitsunium/sdk/pkg/v1/observe/trace.SDKTracer doc:d0a15ce4698a944122148129f0ef6ac0779d601fc9673bdada4a1f75ff185c7c
var _ func(cfg trace.TracerConfig) *trace.SDKTracer = trace.NewTracer

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPEndpointInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:8535afdf3a6237c06ac1851617bb694e133ee8b56b1768ec28c3997f878db218
func _() {
	x := &trace.OTLPEndpointInvalid
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPExportRejected var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:2973b3ba628a796dacefdffcdedf94e29b0652463fbe01cd1c55d666e9c518cd
func _() {
	x := &trace.OTLPExportRejected
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPExportUnavailable var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:2e79e89e8ea68c07712ea90f8de7780c7a0a87e2643b176d69c2d64bb4ae7f84
func _() {
	x := &trace.OTLPExportUnavailable
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPHTTPConfig alias github.com/kitsunium/sdk/internal/service/observe/trace.OTLPHTTPConfig doc:2ded56725fa1c4552b5c335d19a3698b456d6c41d175b7846c9cc4f4205516a6
var _ *svctrace.OTLPHTTPConfig = (*trace.OTLPHTTPConfig)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPInvalidSpanContext var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:e9c0fc484d5d5a1ed0814ca5310acc3e88e6d0e62029aa23ea5712d674118cd5
func _() {
	x := &trace.OTLPInvalidSpanContext
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPPartialSuccess var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:bf9aaaac494ce01efc3867225e354797a3d9913bce0869cc4f4bf607757aba2f
func _() {
	x := &trace.OTLPPartialSuccess
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPRetryable func func(err error) bool doc:c3d2b62f7bebd3f6871e4ca698a41bf8e7cc7a8f1679eb1e51eadc492fc9fd20
var _ func(err error) bool = trace.OTLPRetryable

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPSpanNotEnded var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:9dda10ce7f73c8c6d2761021bd7532c3c4d7b296dd343e504bfbc5fbbbdf61f2
func _() {
	x := &trace.OTLPSpanNotEnded
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.OTLPTracesPath const string doc:18ca7529ee594687c00d84857ec83fdd31931c6f0d5fe7fb9319b313d0c2050d
func _() {
	x := trace.OTLPTracesPath
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.OTLPTracesPath == "/v1/traces": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ParentBased func func(root github.com/kitsunium/sdk/pkg/v1/observe/trace.Sampler) github.com/kitsunium/sdk/pkg/v1/observe/trace.Sampler doc:0ed09fc631c96075c197323eda7fec0c5f42702be4ec3f2745c9406fd0edecd3
var _ func(root trace.Sampler) trace.Sampler = trace.ParentBased

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ParseSpanID func func(text string) (id github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanID, err error) doc:d114fc51a58a5461d1aab45a0dd3259c8f3eed38b121955d0dbdbeca7e846ecf
var _ func(text string) (id trace.SpanID, err error) = trace.ParseSpanID

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ParseTraceID func func(text string) (id github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceID, err error) doc:77ef8e5ddc5bb3dac94df4fb1e782246bd42d44acf0c4c1ea86da3425c7a096a
var _ func(text string) (id trace.TraceID, err error) = trace.ParseTraceID

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ParseTraceParent func func(header string) (context github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContext, err error) doc:335ccc06b71d15d31eb5316d5a14a96e2df2fc32a71a268ee4c5a58d7e25f886
var _ func(header string) (context trace.SpanContext, err error) = trace.ParseTraceParent

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ParseTraceState func func(header string) (state github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceState, err error) doc:06a48c23a8d247afdede6b35474a0527da0564826cb5528f140e19cfc267e228
var _ func(header string) (state trace.TraceState, err error) = trace.ParseTraceState

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Ratio func func(fraction float64) (sampler github.com/kitsunium/sdk/pkg/v1/observe/trace.Sampler, err error) doc:056fe3d7f36a30bd96b52cc16384cc37b9cbe426b6e622d2927b6520c783c49a
var _ func(fraction float64) (sampler trace.Sampler, err error) = trace.Ratio

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.RecordError func func(span github.com/kitsunium/sdk/pkg/v1/observe/trace.Span, err error) doc:a4a3a02a9ea825678d3eb77ce7d71e8168c882430d11bea41d08c90deabe7602
var _ func(span trace.Span, err error) = trace.RecordError

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Recorder alias github.com/kitsunium/sdk/internal/service/observe/trace.Recorder doc:73f2eb4a8fc0464c6bb17cb3249b5d141f900b1f58177dbab0018893706148dd
var _ *svctrace.Recorder = (*trace.Recorder)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.RecorderConfig alias github.com/kitsunium/sdk/internal/service/observe/trace.RecorderConfig doc:0d12d13490994ba0f0c1e54182dd3b5e48abb782ec41dffe2a885f7b26c21b96
var _ *svctrace.RecorderConfig = (*trace.RecorderConfig)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.RegisterExporter func func(e github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanExporter) github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanExporter doc:fd15852848c06e95e39a650271ef40f15cc3b084bb76d61845df06402cf758ad
var _ func(e trace.SpanExporter) trace.SpanExporter = trace.RegisterExporter

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Resource alias github.com/kitsunium/sdk/internal/core/observe/otel.ResourceValue doc:6c23a8d14c64997ef267e98f9874cc68e3829e8d934bc658d5a30963b241b993
var _ *coreotel.ResourceValue = (*trace.Resource)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SDKTracer alias github.com/kitsunium/sdk/internal/service/observe/trace.Tracer doc:9a58778cbff7f28f97547ff6e0ad28dc858c7178d1379b6258d0fd38f42d0e64
var _ *svctrace.Tracer = (*trace.SDKTracer)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Sampler alias github.com/kitsunium/sdk/internal/core/observe/trace.Sampler doc:22cadd73952bac062701e80c13a9c6525fa4df7eb93a215b3cecc2ceb097166e
var _ *coretrace.Sampler = (*trace.Sampler)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SamplingParams alias github.com/kitsunium/sdk/internal/core/observe/trace.SamplingParams doc:ccd040aec2edb59a41748b0be1c8732bb3e5b7dd00f2a03ea0fca5fd8593dd9f
var _ *coretrace.SamplingParams = (*trace.SamplingParams)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Scope alias github.com/kitsunium/sdk/internal/core/observe/otel.ScopeValue doc:ba0e6abc88491013ec0816c3a71491138c6b410775b98d5aee31c3324a573aa2
var _ *coreotel.ScopeValue = (*trace.Scope)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ServerAddressKey const string doc:8aab4fdb91be5e56c5193518522d4cff2494bc4de9a751bae882287dcfe77097
func _() {
	x := trace.ServerAddressKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ServerAddressKey == "server.address": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ServerMiddleware func func(tracer github.com/kitsunium/sdk/pkg/v1/observe/trace.Tracer) github.com/kitsunium/sdk/internal/core/net.Middleware[net/http.Handler] doc:bd76a5d0585f6d734b6dfe015e0acb347b5932a260e8970b90175666e3b3dada
var _ func(tracer trace.Tracer) corenet.Middleware[http.Handler] = trace.ServerMiddleware

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.ServiceNameKey const string doc:ed7592d4694c6145ac664a038e0e259e5f92855f10a65b047b89c62f70fb3217
func _() {
	x := trace.ServiceNameKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ServiceNameKey == "service.name": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Span alias github.com/kitsunium/sdk/internal/core/observe/trace.Span doc:fa27aaabf422facafe8036db6a367b05bd28264d322491efc1b6c2d328fda42f
var _ *coretrace.Span = (*trace.Span)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContext alias github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue doc:aa63817b8bb79cf06b1480d11a2bf24d18abd8265e9aa6cdad1f8a2ec10fbe59
var _ *coretrace.SpanContextValue = (*trace.SpanContext)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContextFromContext func func(ctx context.Context) github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanContext doc:9acdd5615b856a9aa64b3414eb74031d8d3bfe585ae5ed033f1e0aef4172246c
var _ func(ctx context.Context) trace.SpanContext = trace.SpanContextFromContext

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanData alias github.com/kitsunium/sdk/internal/core/observe/trace.SpanValue doc:4221d15fbc6a0844fce8eb2738f4e2a485188444b2cc02377d5b2647bb47a4cf
var _ *coretrace.SpanValue = (*trace.SpanData)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanExporter alias github.com/kitsunium/sdk/internal/core/observe/trace.SpanExporter doc:440a2926c84e0a21632eedd6248e9d8c3a848a15296a9e4f0b7f5cf05969fd97
var _ *coretrace.SpanExporter = (*trace.SpanExporter)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanID alias github.com/kitsunium/sdk/internal/core/observe/trace.SpanID doc:d71b3f36cbce9342b401e17d365d1eeac7986b15b494150f9057bd1508b25bbf
var _ *coretrace.SpanID = (*trace.SpanID)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanParams alias github.com/kitsunium/sdk/internal/core/observe/trace.SpanParams doc:e8139d493d154b178a82b983bde2ec95ef44fd72fcb558bcb17adc696db5a62d
var _ *coretrace.SpanParams = (*trace.SpanParams)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.SpanSink alias github.com/kitsunium/sdk/internal/core/observe/trace.SpanSink doc:a2f20af5dc99877896edfd9f8eba37dd2e1f36dc27deee893540455c45cd7801
var _ *coretrace.SpanSink = (*trace.SpanSink)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Spans alias github.com/kitsunium/sdk/internal/core/observe/trace.SpansValue doc:6efee11c94856351c01e59cb9f6d583f91063bfd74e43d4d85c37b485ac041ee
var _ *coretrace.SpansValue = (*trace.Spans)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Status alias github.com/kitsunium/sdk/internal/core/observe/trace.StatusValue doc:3f9c90a37ec34335d98a22947df2e1e8d1854586b3335ea8e5017c453d553efd
var _ *coretrace.StatusValue = (*trace.Status)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.StatusCode alias github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode doc:a64048242e2d21c2548bda63894d54e21953f095f5529e2c5c29889802aef1c7
var _ *coretrace.StatusCode = (*trace.StatusCode)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.StatusError const github.com/kitsunium/sdk/pkg/v1/observe/trace.StatusCode doc:1b5d1528015db8a24041cb4d6e80f63b9bf8e1f82a3ea0a6bd938920c4e1dd30
func _() {
	x := trace.StatusError
	var _ *trace.StatusCode = &x
	_ = map[bool]int{false: 0, trace.StatusError == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.StatusOK const github.com/kitsunium/sdk/pkg/v1/observe/trace.StatusCode doc:eb5c1df8f06d3da265a64765e933c730032e3086f970b6854e88dc467f1d3a66
func _() {
	x := trace.StatusOK
	var _ *trace.StatusCode = &x
	_ = map[bool]int{false: 0, trace.StatusOK == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.StatusUnset const github.com/kitsunium/sdk/pkg/v1/observe/trace.StatusCode doc:16df40123c4f47b9e6187d55b2219b96f80eb0567dacfc653813f2a3180fb375
func _() {
	x := trace.StatusUnset
	var _ *trace.StatusCode = &x
	_ = map[bool]int{false: 0, trace.StatusUnset == 0: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.String func func(key string, value string) github.com/kitsunium/sdk/pkg/v1/observe/trace.Attr doc:d3894d8306b7120945fa59778f5e2d974ecfd83966c6f8545b3dbcd605c3c310
var _ func(key, value string) trace.Attr = trace.String

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceFlags alias github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags doc:b6a5cbfc0537a0c572ed202da39b292a539231dba349eaf559e5b7b8096031ca
var _ *coretrace.TraceFlags = (*trace.TraceFlags)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceID alias github.com/kitsunium/sdk/internal/core/observe/trace.TraceID doc:6478ce265b5d2441dff98016e8fb515d57d9dda1867243c3b3ec08c3fac9dc9e
var _ *coretrace.TraceID = (*trace.TraceID)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceParentHeader const string doc:f1f53e3978056c021710d7555be8a3fa435d9f6f970336e9e3a6ea57b019a968
func _() {
	x := trace.TraceParentHeader
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.TraceParentHeader == "traceparent": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceParentLen const int doc:f484b8f29b81e5a119f93dd160e8b6f54ad50d6862c7184aff0fbb95802fbe78
func _() {
	x := trace.TraceParentLen
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.TraceParentLen == 55: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceState alias github.com/kitsunium/sdk/internal/core/observe/trace.StateValue doc:21dd60655be36647fa7134a65b0aa109a5d8d814ed68e89fd648367857b04ff6
var _ *coretrace.StateValue = (*trace.TraceState)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.TraceStateHeader const string doc:65c07b12d44cea889a5b19b48117bb0cf1fd8aedbe7f984aa7448d5b52a56ed1
func _() {
	x := trace.TraceStateHeader
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.TraceStateHeader == "tracestate": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.Tracer alias github.com/kitsunium/sdk/internal/core/observe/trace.Tracer doc:5b4631a044f3c98a88b9ae37c8106e403c297a9b8b8070be79cb8e7021bcc28d
var _ *coretrace.Tracer = (*trace.Tracer)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.TracerConfig alias github.com/kitsunium/sdk/internal/service/observe/trace.TracerConfig doc:e4c173d7a1f482e5f25fd0a4eeeda462dcc537b386900ae0a5b117b856192ad1
var _ *svctrace.TracerConfig = (*trace.TracerConfig)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.URLFullKey const string doc:e9ed79fe33b9b20660e453a358b3cefce5d20ccc3c903ad97ff2ae0d4997ce7c
func _() {
	x := trace.URLFullKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.URLFullKey == "url.full": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.URLPathKey const string doc:32f8fe78cf9eaa1c1bc070ef341192370e4336ca76811a46f7071ebe0bcf2644
func _() {
	x := trace.URLPathKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.URLPathKey == "url.path": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.URLSchemeKey const string doc:be5177a35a8fa015ae45bfe0c07a58ee341de3bbe13fc17bc2b7163a1e0ca539
func _() {
	x := trace.URLSchemeKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.URLSchemeKey == "url.scheme": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.UnknownExporter var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:7de1fd48d22c790ce2da0a5b4e9b7f91295f80899df4fcf9decf77d6c70bc2fb
func _() {
	x := &trace.UnknownExporter
	x = &corenet.AlreadyStarted
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/observe/trace.VersionSupported const string doc:6d9d1d32578a156bc832c4dd9d2d57bb4e9bc33659d1a27c0171ed5abf3e1a0d
func _() {
	x := trace.VersionSupported
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.VersionSupported == "00": 1}
}
