load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "signal",
    srcs = ["signal.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/proc/signal",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/proc",
        "//internal/service/proc/signal",
    ],
)

alias(
    name = "go_default_library",
    actual = ":signal",
    visibility = ["//visibility:public"],
)

go_test(
    name = "signal_test",
    srcs = [
        "api_gen_test.go",
        "signal_external_test.go",
        "signal_other_test.go",
        "signal_windows_test.go",
    ],
    deps = [
        ":signal",
        "//internal/core/proc",
        "//internal/service/proc/signal",
    ] + select({
        "@rules_go//go/platform:js": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:osx": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:plan9": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:qnx": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:windows": [
            "//internal/kernel/errs",
        ],
        "//conditions:default": [],
    }),
)
