package kit

import (
	"context"
	"errors"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/kitsunium/sdk/framework/model"
	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/sdk/pkg/v1/observe/logger"
	"github.com/kitsunium/sdk/pkg/v1/security/secret"
)

// Limits and defaults of a secret.
const (
	// defaultRotation and defaultKeep are a generated secret's schedule when
	// the declaration does not give one.
	defaultRotation time.Duration = 30 * 24 * time.Hour
	defaultKeep     int           = 3
	// minSecretBytes and maxSecretBytes bound a generated version: below 128
	// bits a secret can be guessed, and above 4 KiB it is not a key.
	minSecretBytes int = 16
	maxSecretBytes int = 4096
	// kitSecretPrefix names kit's own secrets in the environment's store, so
	// that no product secret can take one's place.
	kitSecretPrefix = "kit-"
)

// Secrets. A product declares the secrets it needs on its services —
// provided by the operator, or generated by kit and rotated on a schedule —
// and kit finds each one in the environment it runs in: the environment
// variable first, the operator's word, then the store the environment keeps
// (secretstore.go). A value never reaches a log, a span, a response, the
// graph or the Studio: only its name, where it was found, its version and
// when it rotates next.

// Secret is a secret the product declares: provided by the operator — an SMTP
// URL, an API token — or generated by kit — a signing or sealing key — and
// rotated on its schedule.
type Secret struct {
	nodeBase
	opts secretOptions
	// inUse and afterRotation are kit's own data-key's (seal.go): the
	// oldest version something still needs, which a rotation does not
	// prune, and what runs after a rotation — the data keys re-wrapped. nil
	// for a product's secret.
	inUse         func(ctx context.Context) (int, error)
	afterRotation func(ctx context.Context)

	mu  sync.Mutex
	run *secretRun
}

// secretRun is a secret in a running app: where it was found and, for one
// kit rotates, its rotator and the loop that drives it.
type secretRun struct {
	app *App
	// store holds it, and name is its name there.
	store secret.Store
	name  string
	// from is one of the model.SecretFrom constants.
	from string
	// pinned: a generated secret the environment provides.
	pinned  bool
	keyring *secret.Keyring
	// rotator, loop, cancel and done are set when kit rotates it.
	rotator *secret.Rotator
	loop    *loopState
	cancel  context.CancelFunc
	done    chan struct{}
	// rotations counts the rotations of this run, guarded by Secret.mu.
	rotations int
}

// SecretConfigurer configures a secret.
type SecretConfigurer interface {
	secretConfigure(o *secretOptions)
}

type secretOptions struct {
	generated bool
	// optional: a provided secret the product can do without (Optional).
	optional bool
	// bytes is the size of a generated version.
	bytes int
	every time.Duration
	keep  int
	// rotates and keeps say RotateEvery and KeepVersions were given.
	rotates, keeps bool
}

type secretOption func(o *secretOptions)

// secretConfigure sets the option on what it configures.
func (f secretOption) secretConfigure(o *secretOptions) { f(o) }

// Generated makes the secret kit's to make: versions of bytes random bytes —
// 32 for a key — the first made on the first start, a new one every 30 days,
// the last 3 kept, unless [RotateEvery] and [KeepVersions] say otherwise.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Generated(bytes int) SecretConfigurer {
	return secretOption(func(o *secretOptions) { o.generated, o.bytes = true, bytes })
}

// Optional makes a provided secret one the product can do without — the key
// of a feature that stays off while nobody gives it. A start where it is set
// nowhere goes on; [Secret.Present] says whether it is set now, and a use of
// it while it is absent — [Secret.Value], Seal, Open, Sign or Verify —
// answers an error errs.HasCode matches with [CodeSecretMissing]. It is read
// where it lives at every use, as every provided secret is: given later —
// `secrets set` in the environment's store, a new content in the file its
// _FILE variable names —, it is found at its next use. A generated secret
// is kit's to make and never absent: Optional with [Generated] is refused.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Optional() SecretConfigurer {
	return secretOption(func(o *secretOptions) { o.optional = true })
}

// RotateEvery is how often kit makes a new version of a generated secret.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func RotateEvery(d time.Duration) SecretConfigurer {
	return secretOption(func(o *secretOptions) { o.every, o.rotates = d, true })
}

// KeepVersions is how many versions of a generated secret a rotation leaves,
// the new one included: at least 2, so that what the version it replaces
// sealed or signed still opens and verifies. Cover the longest-lived box or
// signature in flight: its lifetime divided by the interval, plus one.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func KeepVersions(n int) SecretConfigurer {
	return secretOption(func(o *secretOptions) { o.keep, o.keeps = n, true })
}

// Secret declares a secret the product needs.
//
// Without an option it is provided: the operator gives it in the
// environment — the variable <APP>_<NAME>, TODO_STRIPE_KEY for the secret
// "stripe-key" of the app "todo", or TODO_STRIPE_KEY_FILE naming a file that
// holds it, the Docker and Kubernetes way — or in the environment's store,
// with `kit secrets set`. It is read at every use, so replacing it where it
// lives takes effect without a restart, and a start without it fails, naming
// the variable to set.
//
// With [Optional], a start without it goes on: the product asks
// [Secret.Present] before it uses the secret.
//
// With [Generated], kit makes it: version 1 on the first start, a new version
// on its schedule, the previous ones kept so that what they sealed or signed
// still opens and verifies. It lives in the store the environment keeps — an
// encrypted file store in dev, KIT_SECRETS elsewhere. Its variable pins it:
// kit then uses the value as it is and does not rotate it.
//
// name is 1 to 63 lower-case letters, digits and dashes, starting and ending
// with a letter or a digit — one grammar for a file name and a variable — and
// unique in the app.
//
//go:noinline
func (s *Service) Secret(name string, opts ...SecretConfigurer) *Secret {
	sec := NewSecret()
	for _, o := range opts {
		if o != nil {
			o.secretConfigure(&sec.opts)
		}
	}
	sec.kind, sec.name, sec.decl = model.KindSecret, name, callerPos()
	s.add(sec, false)
	sec.checkName(s)
	sec.checkOptions(s)
	return sec
}

// checkName refuses a name a secret may not take.
func (s *Secret) checkName(svc *Service) {
	name := s.name
	switch {
	case secret.ValidateName(name) != nil:
		svc.problem(s.decl, s.id, "secret.name", "name", name, "max", secret.MaxNameLen)
	case strings.HasSuffix(name, "-file"):
		svc.problem(s.decl, s.id, "secret.file-suffix", "name", name)
	case strings.HasPrefix(name, kitSecretPrefix):
		svc.problem(s.decl, s.id, "secret.kit-prefix", "name", name, "prefix", kitSecretPrefix)
	}
}

// checkOptions refuses options that do not fit: rotation for a secret the
// operator gives, a size, a rotation or a count out of bounds.
func (s *Secret) checkOptions(svc *Service) {
	o, name := s.opts, s.name
	if !o.generated {
		if o.rotates || o.keeps {
			svc.problem(s.decl, s.id, "secret.provided-options", "name", name)
		}
		return
	}
	s.checkGenerated(svc)
}

// checkGenerated refuses the options of a generated secret that do not fit:
// optional, a size, a rotation or a count out of bounds.
func (s *Secret) checkGenerated(svc *Service) {
	o, name := s.opts, s.name
	switch {
	case o.optional:
		svc.problem(s.decl, s.id, "secret.optional-generated", "name", name)
	case o.bytes < minSecretBytes || o.bytes > maxSecretBytes:
		svc.problem(s.decl, s.id, "secret.bytes", "name", name, "min", minSecretBytes, "max", maxSecretBytes, "bytes", o.bytes)
	case o.every <= 0:
		svc.problem(s.decl, s.id, "secret.rotate", "name", name)
	case o.keep < 2:
		svc.problem(s.decl, s.id, "secret.keep", "name", name)
	}
}

// Value returns the secret's current version. A provided secret is read
// where it lives at every call.
func (s *Secret) Value(ctx context.Context) (secret.Value, error) {
	r := s.running()
	if r == nil {
		return secret.Value{}, notRunning(&s.nodeBase)
	}
	_, sp := r.app.begin(ctx, &spanStart{node: s.id, from: currentNode(ctx), edge: model.EdgeUses, op: model.OpSecret, name: "Value"})
	v, err := r.store.Get(ctx, r.name)
	err = s.failed(err)
	sp.end(err)
	return v.Value, err
}

// Present reports whether the secret is set now, where it lives: false, and
// no error, when an [Optional] secret is given nowhere — which the product
// answers by leaving off what needs it. An error says its store could not
// be read. A secret the start required is present, unless the operator took
// it back since.
//
//	if ok, err := OpenAIKey.Present(ctx); err != nil || !ok {
//		return Verdict{}, err // no key, no automatic screening
//	}
func (s *Secret) Present(ctx context.Context) (bool, error) {
	r := s.running()
	if r == nil {
		return false, notRunning(&s.nodeBase)
	}
	_, sp := r.app.begin(ctx, &spanStart{node: s.id, from: currentNode(ctx), edge: model.EdgeUses, op: model.OpSecret, name: "Present"})
	_, err := r.store.Get(ctx, r.name)
	if errors.Is(err, secret.NotFound) {
		sp.attr("verdict", "absent")
		sp.end(nil)
		return false, nil
	}
	err = s.failed(err)
	sp.end(err)
	return err == nil, err
}

// Seal encrypts plaintext under the secret's current version, binding aad:
// data that travels beside the box in the clear and must come back
// unchanged for the box to open.
func (s *Secret) Seal(ctx context.Context, plaintext, aad []byte) ([]byte, error) {
	return s.use(ctx, "Seal", func(ctx context.Context, k *secret.Keyring) ([]byte, error) {
		return k.Seal(ctx, plaintext, aad)
	})
}

// Open decrypts a box any kept version sealed, with the aad it was sealed
// with. A box no kept version opens — forged, altered, or sealed by a
// version pruned since — is refused with an error errors.Is matches with
// secret.SealInvalid.
func (s *Secret) Open(ctx context.Context, box, aad []byte) ([]byte, error) {
	return s.use(ctx, "Open", func(ctx context.Context, k *secret.Keyring) ([]byte, error) {
		return k.Open(ctx, box, aad)
	})
}

// Sign signs message with the secret's current version.
func (s *Secret) Sign(ctx context.Context, message []byte) ([]byte, error) {
	return s.use(ctx, "Sign", func(ctx context.Context, k *secret.Keyring) ([]byte, error) {
		return k.Sign(ctx, message)
	})
}

// Verify reports whether a kept version signed message: nil when one did,
// and an error errors.Is matches with secret.SignatureInvalid when none did.
func (s *Secret) Verify(ctx context.Context, message, signature []byte) error {
	_, err := s.use(ctx, "Verify", func(ctx context.Context, k *secret.Keyring) ([]byte, error) {
		return nil, k.Verify(ctx, message, signature)
	})
	return err
}

// use runs one keyring operation inside a span of the secret. A box or a
// signature the keyring refuses is the caller's answer, not a failure: the
// span says so and ends without an error.
func (s *Secret) use(ctx context.Context, op string, fn func(context.Context, *secret.Keyring) ([]byte, error)) ([]byte, error) {
	r := s.running()
	if r == nil {
		return nil, notRunning(&s.nodeBase)
	}
	ctx, sp := r.app.begin(ctx, &spanStart{node: s.id, from: currentNode(ctx), edge: model.EdgeUses, op: model.OpSecret, name: op})
	out, err := fn(ctx, r.keyring)
	if errors.Is(err, secret.SealInvalid) || errors.Is(err, secret.SignatureInvalid) {
		sp.attr("verdict", "refused")
		sp.end(nil)
		return nil, err
	}
	err = s.failed(err)
	sp.end(err)
	return out, err
}

// failed turns a store's refusal into kit's error, naming the secret — never
// its value, which no error of the SDK's secret domain carries either.
func (s *Secret) failed(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, secret.NotFound):
		return explain(CodeSecretMissing, "SECRET_MISSING", "a secret is found nowhere", err, errs.String("secret", s.id))
	default:
		return explain(CodeSecretRead, "SECRET_READ", "a secret could not be read", err, errs.String("secret", s.id))
	}
}

// key is the secret's name as a product says it — to the secrets command,
// in a message: "<module>.<name>" for a module's service's (ADR 0008), its
// name for the product's own.
func (s *Secret) key() string { return qualifiedKey(s.svc, s.name) }

// stored is its name where the environment keeps it — its variable's
// stem, its name in the kept store: "moderation-openai-key".
func (s *Secret) stored() string { return flatKey(s.key()) }

// kitOwn reports whether the secret is kit's own — data-key, on kit's own
// service —: read from KIT_<NAME>, kept as kit-<name>, like the mail
// connector's smtp-url.
func (s *Secret) kitOwn() bool { return kitOwn(s.svc) }

// envName is the secret's name in the environment it is read from first:
// its variable's stem under the app's prefix, or kit's.
func (s *Secret) envName() string {
	if s.kitOwn() {
		return s.name
	}
	return s.stored()
}

// keptName is its name in the environment's store.
func (s *Secret) keptName() string {
	if s.kitOwn() {
		return kitSecretPrefix + s.name
	}
	return s.stored()
}

// variable is the variable that provides it, or pins it: <APP>_<NAME>, or
// KIT_<NAME> for kit's own.
func (s *Secret) variable(a *App) string {
	if s.kitOwn() {
		return secretVariable("KIT", s.name)
	}
	return variableOf(appPrefix(a.name), s.key())
}

// envOf is where the secret's variable is read: the app's, or kit's.
func (st *secretStores) envOf(s *Secret) secret.Store {
	if s.kitOwn() {
		return st.kitEnv
	}
	return st.env
}

// running returns the secret's run, or nil when its app is not running.
func (s *Secret) running() *secretRun {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.run
}

// describe fills the graph node out with what the Secret declares, and returns
// its edges.
func (s *Secret) describe(a *App, out *model.Node) []model.Edge {
	info := &model.SecretInfo{Origin: model.SecretProvided, Optional: s.opts.optional}
	if s.opts.generated {
		info.Origin, info.Bytes, info.RotateEvery, info.Keep = model.SecretGenerated, s.opts.bytes, s.opts.every.String(), s.opts.keep
	}
	if a != nil {
		info.Variable = s.variable(a)
		if r := s.running(); r != nil {
			s.describeRun(a, r, info)
		}
	}
	out.Secret = info
	return nil
}

// describeRun says what the secret's run knows: where it was found, its
// versions, its next rotation, how often it rotated.
func (s *Secret) describeRun(a *App, r *secretRun, info *model.SecretInfo) {
	info.From, info.Pinned = r.from, r.pinned
	ctx := context.Background()
	if s.opts.optional {
		// Where it is now: it may have come, or gone, since the start.
		st := a.secretsNow()
		_, from, err := st.find(ctx, st.envOf(s), s.envName(), s.keptName())
		info.From = from
		if err != nil && !errors.Is(err, secret.NotFound) {
			info.Problem = "its store could not be read"
		}
	}
	s.describeVersions(ctx, r, info)
	if r.rotator != nil {
		if due, err := r.rotator.Due(ctx); err == nil {
			info.NextRotation = new(due.UTC())
		}
	}
	s.mu.Lock()
	info.Rotations = r.rotations
	s.mu.Unlock()
}

// describeVersions says the secret's versions, as its store keeps them:
// none, and found nowhere, for an optional secret absent as it may be.
func (s *Secret) describeVersions(ctx context.Context, r *secretRun, info *model.SecretInfo) {
	switch versions, err := r.store.Versions(ctx, r.name); {
	case errors.Is(err, secret.NotFound) && s.opts.optional:
		// Absent, as it may be: found nowhere, and no problem.
		info.From = ""
	case err != nil:
		info.Problem = "its store could not be read"
	case len(versions) > 0:
		info.Version, info.Versions = versions[0].Version, len(versions)
		if created := versions[0].Created; !created.IsZero() {
			info.Created = new(created.UTC())
		}
	}
}

// start finds the secret in the environment. A generated secret kit rotates
// is made now if its store has no version yet, and its rotation starts.
//
// Goroutine lifecycle: one goroutine rotates the secret until stop cancels its
// context and waits for it.
func (s *Secret) start(ctx context.Context, a *App) error {
	r, err := a.secretsNow().resolve(ctx, a, s)
	if err != nil {
		return err
	}
	keyring, err := secret.NewKeyring(r.store, r.name)
	if err != nil {
		return failure(CodeSecretStore, "SECRET_KEYRING", "a secret's keyring could not be built", err, errs.String("secret", s.id))
	}
	r.keyring = keyring
	if !s.opts.generated || r.pinned {
		s.mu.Lock()
		s.run = r
		s.mu.Unlock()
		return nil
	}
	r.rotator, err = secret.NewRotator(secret.RotatorConfig{
		Store: r.store, Name: r.name, Clock: a.clock,
		Policy:   secret.Policy{Every: s.opts.every, Keep: s.opts.keep, Generate: secret.Random(s.opts.bytes)},
		OnRotate: func(v secret.Versioned) { s.rotated(a, v) },
		InUse:    s.inUse,
	})
	if err != nil {
		return failure(CodeSecretRotate, "SECRET_ROTATOR", "a generated secret's rotation could not be set up", err, errs.String("secret", s.id))
	}
	if _, err := r.rotator.Ensure(ctx); err != nil {
		return failure(CodeSecretRotate, "SECRET_CREATE", "a generated secret could not be made", err, errs.String("secret", s.id))
	}
	if s.kitOwn() {
		// The configuration the start read said it was set nowhere: kit
		// made it in the environment's store, if it was not there.
		a.settingFoundIn(s.variable(a), model.SettingStore)
	}
	r.loop = a.loop(s.id+" rotation", s.id, model.LoopRotation, "every "+s.opts.every.String()+" · keeps "+strconv.Itoa(s.opts.keep))
	loopCtx, cancel := context.WithCancel(context.WithoutCancel(a.baseCtx))
	r.cancel, r.done = cancel, make(chan struct{})
	s.mu.Lock()
	s.run = r
	s.mu.Unlock()
	go s.rotate(withNode(loopCtx, s.id, a), a, r)
	return nil
}

// stop ends the secret's rotation loop.
func (s *Secret) stop(ctx context.Context, a *App) error {
	s.mu.Lock()
	r := s.run
	s.run = nil
	s.mu.Unlock()
	if r == nil || r.cancel == nil {
		return nil
	}
	r.cancel()
	select {
	case <-r.done:
	case <-ctx.Done():
		return ctx.Err()
	}
	r.loop.setState(a, model.LoopStopped)
	return nil
}

// rotate makes a new version each time the current one is due, on the app's
// clock, until the app stops. A rotation that fails is tried again after a
// backoff — one second, doubling up to a minute — and the versions already
// kept go on opening what they sealed meanwhile.
func (s *Secret) rotate(ctx context.Context, a *App, r *secretRun) {
	done := r.done
	defer close(done)
	ctx = a.asLoop(ctx, s.id)
	failures := 0
	// next is this loop's own, written again after every rotation: the loop
	// state is handed a copy (idle), which the Studio may read meanwhile.
	next := s.nextRotation(ctx, a, r, failures)
	r.loop.idle(a, next)
	for {
		timer := a.clock.NewTimer(max(next.Sub(a.clock.Now()), 0))
		select {
		case <-ctx.Done():
			timer.Stop()
			return
		case _, open := <-timer.C():
			if !open {
				return
			}
		}
		started := a.clock.Now()
		r.loop.begin(a, model.WakeDeadline)
		err := s.rotateOnce(ctx, r)
		ended := a.clock.Now()
		if ctx.Err() != nil {
			r.loop.idle(a, time.Time{})
			r.loop.ran(a, started, ended, nil)
			return
		}
		if err != nil {
			failures++
			logger.Warn(ctx, a.log, "a secret's rotation failed; kit tries again", logger.String("node", s.id),
				logger.String("after", backoff(failures).String()), logger.String("error", errs.PublicOf(err)))
		} else {
			failures = 0
		}
		next = s.nextRotation(ctx, a, r, failures)
		r.loop.idle(a, next)
		r.loop.ran(a, started, ended, err)
	}
}

// rotateOnce makes a new version when the current one is due. Once a
// version is kept, the data keys move to it: a prune that failed does not
// keep them from moving.
func (s *Secret) rotateOnce(ctx context.Context, r *secretRun) error {
	_, rotated, err := r.rotator.RotateIfDue(ctx)
	if rotated && s.afterRotation != nil {
		s.afterRotation(ctx)
	}
	return err
}

// nextRotation is when the rotation loop looks again: when the current
// version is due, after the backoff of a failure, and never sooner than a
// second from now — a version already due is rotated then.
func (s *Secret) nextRotation(ctx context.Context, a *App, r *secretRun, failures int) time.Time {
	now := a.clock.Now()
	if failures > 0 {
		return now.Add(backoff(failures)).UTC()
	}
	due, err := r.rotator.Due(ctx)
	if err != nil {
		// The version went missing from the store: RotateIfDue makes it again.
		due = now
	}
	return later(due, now.Add(minDeadlineGap)).UTC()
}

// later is the later of two instants.
func later(x, y time.Time) time.Time {
	if x.After(y) {
		return x
	}
	return y
}

// rotated is told of every rotation, once the new version is kept and the
// old ones pruned.
func (s *Secret) rotated(a *App, v secret.Versioned) {
	s.mu.Lock()
	if s.run != nil {
		s.run.rotations++
	}
	s.mu.Unlock()
	logger.Info(context.Background(), a.log, "a secret rotated", logger.String("node", s.id), logger.Int("version", v.Version))
}

// secretVariable is the environment variable that carries the secret name
// under prefix: the name upper-cased, its dashes turned into underscores.
func secretVariable(prefix, name string) string {
	return prefix + "_" + strings.ToUpper(strings.ReplaceAll(name, "-", "_"))
}

// appPrefix is the prefix of a product's variables: its name upper-cased,
// every character a variable cannot hold turned into '_' — TODO for "todo",
// MY_APP for "my-app".
func appPrefix(name string) string {
	b := []byte(strings.ToUpper(name))
	for i, c := range b {
		if (c < 'A' || c > 'Z') && (c < '0' || c > '9') {
			b[i] = '_'
		}
	}
	return string(b)
}

// secretProblems judges the declared secrets: a name two services declare —
// always — and, once the environment's stores are open, a provided secret
// set nowhere — unless it is optional — or a generated one with no store to
// live in — errors, reported together — and a generated one its variable
// pins — a warning.
func (a *App) secretProblems() []model.Diagnostic {
	secrets, out := a.distinctSecrets()
	st := a.secrets.Load()
	if st == nil {
		return out
	}
	for _, w := range st.warnings {
		out = append(out, diagnosticOf("warning", "", nil, w))
	}
	for _, s := range secrets {
		if severity, said, found := st.secretProblem(s, s.variable(a)); found {
			out = append(out, diagnosticOf(severity, s.id, a.source(&s.decl), said))
		}
	}
	return out
}

// distinctSecrets are the app's secrets, and a problem for each that names a
// secret another already names.
func (a *App) distinctSecrets() ([]*Secret, []model.Diagnostic) {
	var out []model.Diagnostic
	var secrets []*Secret
	owner := map[string]string{}
	for _, s := range a.declaredSecrets() {
		if first, dup := owner[s.keptName()]; dup {
			out = append(out, diagnosticOf("error", s.id, a.source(&s.decl),
				say("secret.twice", "name", s.key(), "first", first, "second", s.id, "variable", s.variable(a))))
			continue
		}
		owner[s.keptName()] = s.id
		secrets = append(secrets, s)
	}
	return secrets, out
}

// declaredSecrets are the secrets the app's services declare, in order.
func (a *App) declaredSecrets() []*Secret {
	var out []*Secret
	for _, svc := range a.services {
		if svc == nil {
			continue
		}
		nodes, _ := svc.snapshot()
		for _, n := range nodes {
			if s, ok := n.(*Secret); ok {
				out = append(out, s)
			}
		}
	}
	return out
}

// secretProblem is what is wrong with where the stores find s, whose
// variable is variable; found is false when nothing is.
func (st *secretStores) secretProblem(s *Secret, variable string) (severity string, said phrase, found bool) {
	_, from, err := st.find(context.Background(), st.envOf(s), s.envName(), s.keptName())
	switch {
	case err == nil && from == model.SecretFromEnv && s.opts.generated:
		return "warning", say("secret.pinned", "secret", s.id, "variable", variable), true
	case err == nil, s.opts.generated && st.kept != nil, s.opts.optional && errors.Is(err, secret.NotFound):
		// Found; or kit makes it; or absent, as an optional secret may be:
		// the product asks Present.
		return "", phrase{}, false
	default:
		return "error", st.missing(s, variable, err), true
	}
}

// missing says why the stores do not find s, whose variable is variable:
// unreadable, not in the environment for a secret kit makes, or unset.
func (st *secretStores) missing(s *Secret, variable string, err error) phrase {
	switch {
	case !errors.Is(err, secret.NotFound):
		return say("secret.unreadable", "secret", s.id, "detail", errs.PublicOf(err))
	case s.opts.generated:
		return say("secret.generated-env", "secret", s.id, "variable", variable)
	case st.from == model.SecretFromFile:
		return say("secret.unset-store", "secret", s.id, "variable", variable, "name", s.key())
	default:
		return say("secret.unset", "secret", s.id, "variable", variable)
	}
}

// NewSecret is a secret no service declares yet, rotated and kept as by
// default: [Service.Secret] makes one and declares it, which is how a product
// gets one.
func NewSecret() *Secret {
	return &Secret{opts: secretOptions{every: defaultRotation, keep: defaultKeep}}
}
