// Code generated by kit from design/crypto.yaml (sha256 577c3f96523a547b3b254db5fe68cbf7a380c6192ec46ce7608f8b01e1299de0, body f393b03c89cfd465dac9f77693d0e42ea2ac5ead6a56eee0a766d470f75cb5d5). DO NOT EDIT.

package agree

import corecrypto "github.com/kitsunium/sdk/internal/core/crypto"

// Algorithm is the stable identifier of a key-agreement scheme. It is a defined
// type distinct from the other crypto-family Algorithm types (hash, mac, sign,
// …), so the compiler rejects feeding a hash or signature constant into an
// agreement call (V104) — the seven registries are separate keyspaces, and the
// type system now enforces that separation the way typed Format/Level discipline
// does elsewhere.
type Algorithm corecrypto.Algorithm
