// Code generated by kit from design/framework/kit.yaml (sha256 ba5866050deae773d5dbf24a16c27fa5d069495a837ab539e899897b5dfbfc24, body ce51899e9aa17036010d4b5fc216cdd50814d2948d70b9fd3cca6f23d31e9d39). DO NOT EDIT.

package plug_test

import (
	"context"
	"io/fs"
	"net/http"
	"sync/atomic"
	"time"

	"github.com/kitsunium/sdk/framework/internal/kit/plug"
	"github.com/kitsunium/sdk/framework/model"
)

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.EventStream type interface{Close() error; Done() <-chan struct{}; Send(data string) error}
// go:github.com/kitsunium/sdk/framework/internal/kit/plug.EventStream.Close method func() error
// go:github.com/kitsunium/sdk/framework/internal/kit/plug.EventStream.Done method func() <-chan struct{}
// go:github.com/kitsunium/sdk/framework/internal/kit/plug.EventStream.Send method func(data string) error
var (
	_ interface {
		Send(data string) error
		Done() <-chan struct{}
		Close() error
	} = plug.EventStream(nil)
	_ plug.EventStream = interface {
		Send(data string) error
		Done() <-chan struct{}
		Close() error
	}(nil)
)

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPConfig type struct{Addr string; Shards int; ReadHeader time.Duration; Read time.Duration; Write time.Duration; Idle time.Duration; MaxHeaderBytes int; Handler net/http.Handler}
func _(x plug.HTTPConfig) {
	var _ *string = &x.Addr
	var _ *int = &x.Shards
	var _ *time.Duration = &x.ReadHeader
	var _ *time.Duration = &x.Read
	var _ *time.Duration = &x.Write
	var _ *time.Duration = &x.Idle
	var _ *int = &x.MaxHeaderBytes
	var _ *http.Handler = &x.Handler
}

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPServer type interface{Shutdown(ctx context.Context) error; Start(ctx context.Context) error; State() github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPState}
// go:github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPServer.Shutdown method func(ctx context.Context) error
// go:github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPServer.Start method func(ctx context.Context) error
// go:github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPServer.State method func() github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPState
var (
	_ interface {
		Start(ctx context.Context) error
		State() plug.HTTPState
		Shutdown(ctx context.Context) error
	} = plug.HTTPServer(nil)
	_ plug.HTTPServer = interface {
		Start(ctx context.Context) error
		State() plug.HTTPState
		Shutdown(ctx context.Context) error
	}(nil)
)

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPState type struct{Addr string; Listeners int; Active int64; Total uint64; Rejected uint64}
func _(x plug.HTTPState) {
	var _ *string = &x.Addr
	var _ *int = &x.Listeners
	var _ *int64 = &x.Active
	var _ *uint64 = &x.Total
	var _ *uint64 = &x.Rejected
}

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.LabelLoop const string
func _() {
	x := plug.LabelLoop
	var _ *string = &x
	_ = map[bool]int{false: 0, plug.LabelLoop == "kit_loop": 1}
}

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.LabelNode const string
func _() {
	x := plug.LabelNode
	var _ *string = &x
	_ = map[bool]int{false: 0, plug.LabelNode == "kit_node": 1}
}

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.NewHTTPServer var sync/atomic.Pointer[func(cfg github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPConfig) github.com/kitsunium/sdk/framework/internal/kit/plug.HTTPServer]
var _ *atomic.Pointer[func(cfg plug.HTTPConfig) plug.HTTPServer] = &plug.NewHTTPServer

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.NewStaticFiles var sync/atomic.Pointer[func(fsys io/fs.FS, csp string) (net/http.Handler, error)]
var _ *atomic.Pointer[func(fsys fs.FS, csp string) (http.Handler, error)] = &plug.NewStaticFiles

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.OpenEventStream var sync/atomic.Pointer[func(w net/http.ResponseWriter, r *net/http.Request) (github.com/kitsunium/sdk/framework/internal/kit/plug.EventStream, error)]
var _ *atomic.Pointer[func(w http.ResponseWriter, r *http.Request) (plug.EventStream, error)] = &plug.OpenEventStream

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.ProfilerConfig type struct{Heap func(g *github.com/kitsunium/sdk/framework/model.Graph, source github.com/kitsunium/sdk/framework/internal/kit/plug.SourceFunc) (*github.com/kitsunium/sdk/framework/model.Profile, error); Goroutines func(at time.Time) (*github.com/kitsunium/sdk/framework/model.Goroutines, error)}
func _(x plug.ProfilerConfig) {
	var _ *func(g *model.Graph, source plug.SourceFunc) (*model.Profile, error) = &x.Heap
	var _ *func(at time.Time) (*model.Goroutines, error) = &x.Goroutines
}

func kitPinSourceFunc[X ~func(file string, line int, fn string) *model.Source]() {}

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.SourceFunc type func(file string, line int, fn string) *github.com/kitsunium/sdk/framework/model.Source
var _ = kitPinSourceFunc[plug.SourceFunc]

// go:github.com/kitsunium/sdk/framework/internal/kit/plug.StudioProfiler var sync/atomic.Pointer[github.com/kitsunium/sdk/framework/internal/kit/plug.ProfilerConfig]
var _ *atomic.Pointer[plug.ProfilerConfig] = &plug.StudioProfiler
