load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "plug",
    srcs = ["plug.go"],
    importpath = "github.com/kitsunium/sdk/framework/internal/kit/plug",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
    deps = ["//framework/model"],
)

alias(
    name = "go_default_library",
    actual = ":plug",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
)
