load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "plug",
    srcs = [
        "decl_gen.go",
        "doc.go",
        "plug.go",
    ],
    importpath = "github.com/kitsunium/sdk/framework/internal/kit/plug",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
    deps = ["//framework/model"],
)

alias(
    name = "go_default_library",
    actual = ":plug",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
)

go_test(
    name = "plug_test",
    srcs = ["api_gen_test.go"],
    deps = [
        ":plug",
        "//framework/model",
    ],
)
