load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/kernel:kernel_consumers"])

go_library(
    name = "backoff",
    srcs = [
        "backoff.go",
        "decl_gen.go",
        "doc.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/kernel/backoff",
    visibility = [
        "//:__subpackages__",
        "//internal/kernel:kernel_consumers",
    ],
)

alias(
    name = "go_default_library",
    actual = ":backoff",
    visibility = [
        "//:__subpackages__",
        "//internal/kernel:kernel_consumers",
    ],
)

go_test(
    name = "backoff_test",
    size = "small",
    srcs = [
        "api_gen_test.go",
        "backoff_external_test.go",
        "backoff_internal_test.go",
    ],
    embed = [":backoff"],
)
