// Code generated by kit from design/framework/model.yaml (sha256 540fba64b93266c3b8d841706e52d882ab9c04b40ff934d7b4ae76dc44e48efe, body a9e11515eeb4df6a7dd3abeb4a65203de1f38d4a4cde28bf818cbf83c89255de). DO NOT EDIT.

package model

// IsEngine reports whether backend names an engine a database runs on.
func IsEngine(backend string) bool {
	return isEngine(backend)
}

// ConnectorCatalog is every connector kit ships, sorted by ID: what a
// product may plug into.
func ConnectorCatalog() []ConnectorInfo {
	return connectorCatalog()
}

// ConnectorsOf derives the connectors a product uses from its nodes: an
// endpoint, a frontend or an auth handler means HTTP, a mailer mail, a store
// stores — and a database when one keeps it —, a topic, a subscription or
// a queued command queues. Sorted by ID.
func ConnectorsOf(nodes []Node) []Connector {
	return connectorsOf(nodes)
}

// EdgeID builds the ID of an edge. The label is part of the identity: two
// transitions of one workflow fired from one endpoint are two edges.
func EdgeID(from string, kind EdgeKind, to, label string) string {
	return edgeID(from, kind, to, label)
}

// CompareSource orders sources by root, file, then line.
func CompareSource(a, b Source) int {
	return compareSource(a, b)
}

// Merge enriches a graph with what another description of the same product
// knows. base is authoritative on which nodes exist — a runtime graph describes
// what the process actually serves —, on the modules it mounts, on what each
// of its ports calls and on which stores feed each of its watches: the app
// chose them when it started, where the analysis only reads the same rules
// over the whole module. extra, typically
// the static analysis, contributes documentation, handler ranges — an
// authorization function's too —, transition callers and the edges it
// found. Nodes only extra knows about are dropped: code that is compiled but
// not mounted in this app is not part of this product — save a node of a
// module's service the base mounts, which a package the binary does not link
// declares: a warning says so.
func Merge(base, extra *Graph) *Graph {
	return merge(base, extra)
}

// ServiceOf returns the service part of a node ID.
func ServiceOf(id string) string {
	return serviceOf(id)
}

// ValidSegment reports whether s is a legal service, module, binary, role or
// library name.
func ValidSegment(s string) bool {
	return validSegment(s)
}

// ValidName reports whether s is a legal node name. An endpoint named by its
// route is legal as an ID but is not a name a declaration may give.
func ValidName(s string) bool {
	return validName(s)
}

// ValidContract reports whether s names a versioned contract: "render/v1".
func ValidContract(s string) bool {
	return validContract(s)
}

// BinaryID is the ID of a binary.
func BinaryID(binary string) string {
	return binaryID(binary)
}

// RoleID is the ID of one process role of a binary.
func RoleID(binary, role string) string {
	return roleID(binary, role)
}

// LibraryID is the ID of a library.
func LibraryID(library string) string {
	return libraryID(library)
}

// Mermaid renders the architecture of a graph as a Mermaid flowchart: one
// subgraph per service — a module's inside the module's own, ADR 0008 —, one
// arrow per edge. GitHub renders it in Markdown, which makes a product's
// README carry its own, always regenerable, diagram.
//
// Each kind has its shape: an endpoint a box (marked "auth" when it asks for
// a user; an implementation of a port by its name), a store a cylinder, a
// topic a flag, a subscription a parallelogram (a watch, ADR 0008, marked
// with the mark it watches — its stores' arrows say where from), a
// workflow a hexagon, a job a
// stadium, the auth handler a trapezoid — a gate —, a mailer a subroutine
// box, a declared loop a circle, a hand-written loop a double circle, a
// port an inverted trapezoid — a socket, UML's required interface —, a
// command a parallelogram leaning back — a subscription's leans forward —,
// marked "queued" when it waits in its queue, and a query a rhombus, a
// question. An arrow is solid when it exists by construction or was
// observed, dotted when only the code says so — or when it is a port's
// binding to its own fallback, the default the app may replace, as the
// Studio draws it.
func Mermaid(g *Graph) string {
	return mermaid(g)
}

// QualifiedService is the name a module gives a service it lists: the
// module's own name for the service named like it, "<module>.<service>"
// otherwise. The runtime and the analyzer both qualify with it.
func QualifiedService(module, service string) string {
	return qualifiedService(module, service)
}

// ModulePrefix is a module's default mount prefix: "/<name>/".
func ModulePrefix(name string) string {
	return modulePrefix(name)
}

// UnderPrefix is a route declared at path, served under a module's mount
// prefix: "/reports" under "/moderation/" is "/moderation/reports", and
// under "/" it stays "/reports".
func UnderPrefix(prefix, path string) string {
	return underPrefix(prefix, path)
}

// TableName is the table a database keeps a kit table in (ADR 0004): the
// service's name — qualified, for a module's —, two underscores and the
// node's name, then suffix, '-' and '.' written '_', lower case —
// "moderation.intake"'s store "cases" is moderation_intake__cases. A name
// the rule cannot keep as it is — upper case, longer than MaxTableLen,
// three underscores in a row, SQLite's own prefix — is cut and ends with a
// digest of the whole, so it stays one table's. The runtime and the
// analyzer name tables with it.
func TableName(service, node, suffix string) string {
	return tableName(service, node, suffix)
}
