// Code generated by kit from design/app/config.yaml (sha256 26cb6f9bffd43c5d389efe472faa6c0794abdf7a4e0d41fac471e7151cd6c939, body 525ccbdb37e82e6407ae9e9180f9e68763de4d6768eeb4dc786257fa97736330). DO NOT EDIT.

package config_test

import (
	"io/fs"
	"time"

	coreconfig "github.com/kitsunium/sdk/internal/core/app/config"
	corevalidation "github.com/kitsunium/sdk/internal/core/app/validation"
	"github.com/kitsunium/sdk/internal/core/data/codec"
	"github.com/kitsunium/sdk/internal/service/app/config"
)

// go:github.com/kitsunium/sdk/internal/service/app/config.EnvSource func func(prefix string) github.com/kitsunium/sdk/internal/core/app/config.Source
var _ func(prefix string) coreconfig.Source = config.EnvSource

// go:github.com/kitsunium/sdk/internal/service/app/config.FSSource func func(fsys io/fs.FS, format github.com/kitsunium/sdk/internal/core/data/codec.Format, path string) github.com/kitsunium/sdk/internal/core/app/config.Source
var _ func(fsys fs.FS, format codec.Format, path string) coreconfig.Source = config.FSSource

// go:github.com/kitsunium/sdk/internal/service/app/config.FileSource func func(format github.com/kitsunium/sdk/internal/core/data/codec.Format, path string) github.com/kitsunium/sdk/internal/core/app/config.Source
var _ func(format codec.Format, path string) coreconfig.Source = config.FileSource

// go:github.com/kitsunium/sdk/internal/service/app/config.Load[...] func func[T any](target *T, sources ...github.com/kitsunium/sdk/internal/core/app/config.Source) error
func _[T any]() {
	var _ func(target *T, sources ...coreconfig.Source) error = config.Load[T]
}

// go:github.com/kitsunium/sdk/internal/service/app/config.LoadSchema[...] func func[T any](target *T, schema *github.com/kitsunium/sdk/internal/service/app/config.SchemaValue[T], sources ...github.com/kitsunium/sdk/internal/core/app/config.Source) error
func _[T any]() {
	var _ func(target *T, schema *config.SchemaValue[T], sources ...coreconfig.Source) error = config.LoadSchema[T]
}

// go:github.com/kitsunium/sdk/internal/service/app/config.LoadSchemaWithOrigins[...] func func[T any](target *T, schema *github.com/kitsunium/sdk/internal/service/app/config.SchemaValue[T], sources ...github.com/kitsunium/sdk/internal/core/app/config.Source) (origins []github.com/kitsunium/sdk/internal/core/app/config.OriginValue, err error)
func _[T any]() {
	var _ func(target *T, schema *config.SchemaValue[T], sources ...coreconfig.Source) (origins []coreconfig.OriginValue, err error) = config.LoadSchemaWithOrigins[T]
}

// go:github.com/kitsunium/sdk/internal/service/app/config.LoadWithOrigins[...] func func[T any](target *T, sources ...github.com/kitsunium/sdk/internal/core/app/config.Source) (origins []github.com/kitsunium/sdk/internal/core/app/config.OriginValue, err error)
func _[T any]() {
	var _ func(target *T, sources ...coreconfig.Source) (origins []coreconfig.OriginValue, err error) = config.LoadWithOrigins[T]
}

// go:github.com/kitsunium/sdk/internal/service/app/config.NewSchemaValue[...] func func[T any](spec github.com/kitsunium/sdk/internal/service/app/config.SchemaSpec[T]) (schema *github.com/kitsunium/sdk/internal/service/app/config.SchemaValue[T], err error)
func _[T any]() {
	var _ func(spec config.SchemaSpec[T]) (schema *config.SchemaValue[T], err error) = config.NewSchemaValue[T]
}

// go:github.com/kitsunium/sdk/internal/service/app/config.PollWatcher func func(path string, interval time.Duration) github.com/kitsunium/sdk/internal/core/app/config.Watcher
var _ func(path string, interval time.Duration) coreconfig.Watcher = config.PollWatcher

// go:github.com/kitsunium/sdk/internal/service/app/config.SchemaSpec type [T any] struct{Required []string; Defaults []github.com/kitsunium/sdk/internal/core/app/config.DeclaredValue; AllowUnknownKeys bool; Rule github.com/kitsunium/sdk/internal/core/app/validation.Constraint[T]}
func _[T any](x config.SchemaSpec[T]) {
	var _ *[]string = &x.Required
	var _ *[]coreconfig.DeclaredValue = &x.Defaults
	var _ *bool = &x.AllowUnknownKeys
	var _ *corevalidation.Constraint[T] = &x.Rule
}

// go:github.com/kitsunium/sdk/internal/service/app/config.SchemaValue type [T any] struct{}
func _[T any]() {
	var _ *config.SchemaValue[T]
}

// go:github.com/kitsunium/sdk/internal/service/app/config.(*SchemaValue[...]).Check method func(value T) github.com/kitsunium/sdk/internal/core/app/validation.ReportValue
func _[T any]() {
	var _ func(_ *config.SchemaValue[T], value T) corevalidation.ReportValue = (*config.SchemaValue[T]).Check
}

// go:github.com/kitsunium/sdk/internal/service/app/config.(*SchemaValue[...]).Source method func() github.com/kitsunium/sdk/internal/core/app/config.Source
func _[T any]() {
	var _ func(*config.SchemaValue[T]) coreconfig.Source = (*config.SchemaValue[T]).Source
}
