// Code generated by kit from design/data/codec/scratch.yaml (sha256 3ffa42d7696a29f3969fd7a48c6a40fa560a8cbf22acb6b146e23d2320e739f7, body 62ea918ee147374274b9877bfd514924655408070af328bdab97ca97b7ccd12e). DO NOT EDIT.

package scratch_test

// package github.com/kitsunium/sdk/internal/core/data/codec/scratch doc:ba403a2467b268542c9b454ac0b6496544fc6bcfa1c0325eec6de7c9fcc39340

import (
	"bytes"

	"github.com/kitsunium/sdk/internal/core/data/codec/scratch"
)

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.AcquireBuffer func func() *bytes.Buffer doc:80f3b25dabeed0067c1a8c7cd8fbe6f6200c2481f16185020f60641020533839
var _ func() *bytes.Buffer = scratch.AcquireBuffer

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.AcquireReader func func(src []byte) *bytes.Reader doc:5bac4776b3003f5a620b372efe918d0073c0d6559a26691d4463a8d50b5bb54a
var _ func(src []byte) *bytes.Reader = scratch.AcquireReader

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.DetachBuffer func func(buf *bytes.Buffer) []byte doc:b21f4663102192bdd539a96f111743951deeadf2141f36955270b1e124615585
var _ func(buf *bytes.Buffer) []byte = scratch.DetachBuffer

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.MaxRetainedBufBytes const int doc:85df884b878e7bf26c2c590c52124e1dfad03135ca777ee79b3cd486a0aedf4e
func _() {
	x := scratch.MaxRetainedBufBytes
	var _ *int = &x
	_ = map[bool]int{false: 0, scratch.MaxRetainedBufBytes == (256 << 10): 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.ReleaseBuffer func func(buf *bytes.Buffer) doc:dc2e3d973df5dfedc8693b39a78aafffa312f7104522ea47b59c5e9f7358fead
var _ func(buf *bytes.Buffer) = scratch.ReleaseBuffer

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.ReleaseReader func func(r *bytes.Reader) doc:a6147bb0fdc19aa4968a947777073f2d7c106163cdf8849a60d7414ad31fbfc0
var _ func(r *bytes.Reader) = scratch.ReleaseReader
