// Code generated by kit from design/data/codec/scratch.yaml (sha256 e60bc277c405faf5ed6e1433414c879d2699f3f33d8efc8224661165cd2b74a8, body 5648915ed88480f9a72d8e51bfc4a2e646ce0f4ab4ff10294716d5009840b08b). DO NOT EDIT.

package scratch_test

import (
	"bytes"

	"github.com/kitsunium/sdk/internal/core/data/codec/scratch"
)

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.AcquireBuffer func func() *bytes.Buffer
var _ func() *bytes.Buffer = scratch.AcquireBuffer

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.AcquireReader func func(src []byte) *bytes.Reader
var _ func(src []byte) *bytes.Reader = scratch.AcquireReader

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.DetachBuffer func func(buf *bytes.Buffer) []byte
var _ func(buf *bytes.Buffer) []byte = scratch.DetachBuffer

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.MaxRetainedBufBytes const int
func _() {
	x := scratch.MaxRetainedBufBytes
	var _ *int = &x
	_ = map[bool]int{false: 0, scratch.MaxRetainedBufBytes == (256 << 10): 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.ReleaseBuffer func func(buf *bytes.Buffer)
var _ func(buf *bytes.Buffer) = scratch.ReleaseBuffer

// go:github.com/kitsunium/sdk/internal/core/data/codec/scratch.ReleaseReader func func(r *bytes.Reader)
var _ func(r *bytes.Reader) = scratch.ReleaseReader
