load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "json",
    srcs = [
        "codec.go",
        "codes.go",
        "decoder.go",
        "encoder.go",
        "errors.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/codec/json",
    visibility = ["//internal/service:service_consumers"],
    deps = [
        "//internal/core/codec",
        "//internal/core/codec/scratch",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":json",
    visibility = ["//internal/service:service_consumers"],
)

go_test(
    name = "json_test",
    size = "small",
    srcs = [
        "codec_external_test.go",
        "codec_internal_test.go",
        "decoder_internal_test.go",
        "encoder_internal_test.go",
    ],
    embed = [":json"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
    ],
)

filegroup(
    name = "audit_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
