load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "sample",
    srcs = [
        "codes.go",
        "errors.go",
        "sample_sink.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/logger/middleware/sample",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/logger",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":sample",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "sample_test",
    srcs = [
        "sample_sink_external_test.go",
        "sample_sink_internal_test.go",
    ],
    embed = [":sample"],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
        "//internal/kernel/errs",
    ],
)
