load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "yaml",
    srcs = [
        "codec.go",
        "codes.go",
        "decoder.go",
        "encoder.go",
        "errors.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/codec/yaml",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)

alias(
    name = "go_default_library",
    actual = ":yaml",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "yaml_test",
    srcs = [
        "codec_external_test.go",
        "codec_internal_test.go",
        "decoder_internal_test.go",
        "encoder_internal_test.go",
    ],
    embed = [":yaml"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)
