load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/kernel:kernel_consumers"])

go_library(
    name = "singleflight",
    srcs = [
        "call.go",
        "panic.go",
        "singleflight.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/kernel/singleflight",
    visibility = [
        "//:__subpackages__",
        "//internal/kernel:kernel_consumers",
    ],
)

alias(
    name = "go_default_library",
    actual = ":singleflight",
    visibility = [
        "//:__subpackages__",
        "//internal/kernel:kernel_consumers",
    ],
)

go_test(
    name = "singleflight_test",
    size = "small",
    srcs = [
        "singleflight_bench_test.go",
        "singleflight_external_test.go",
        "singleflight_internal_test.go",
    ],
    embed = [":singleflight"],
)
