// Code generated by kit from design/data/codec/pem.yaml (sha256 6578caa358d986cb5f750c49a4a0993ef807a2a63b548a16b3a15c3e9498f185, body bd2073350e2715f82f4eea9af220ab6e3673f135b7ae0f1e9e709bc9f1041e9a). DO NOT EDIT.

package pem_test

// package github.com/kitsunium/sdk/pkg/v1/data/codec/pem doc:b6efeaca5ccfd72fe68d2105a749ced9407e1bafad8776c9fcc2a5eb158776ef

import (
	"github.com/kitsunium/sdk/internal/kernel/errs"
	"github.com/kitsunium/sdk/pkg/v1/data/codec/pem"
)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/pem.CodeMarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:a872fa009034344cef14bfd472601ef533e2a24104c8bf28f13a63821bf35c9f
func _() {
	x := pem.CodeMarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, pem.CodeMarshalFailed == 0x00_03_0A_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/pem.CodeUnmarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:b5d394a56e80cf4ec531e542de1c8499e1290330465d7e5757657ba4f7471122
func _() {
	x := pem.CodeUnmarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, pem.CodeUnmarshalFailed == 0x00_03_0A_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/pem.CodeValueInvalid const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:83de03a2284d4a8a3391bcf3c47a84e8aebce696eb26735622b0a68adcacc7ce
func _() {
	x := pem.CodeValueInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, pem.CodeValueInvalid == 0x00_03_0A_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/pem.Format const untyped string doc:ea983eb5d4051d3aa47736a833bf5eed0c8d66a7b8c50898e717b5ec2d86b4d8
func _() {
	type untyped string
	var _ untyped = pem.Format
	_ = map[bool]int{false: 0, pem.Format == "pem": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/pem.MarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:f3aa742445ccd47c91e7869ae4d31fe998dcc2f5d83823e24dca936e244fd975
var _ **errs.Error = &pem.MarshalFailed

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/pem.UnmarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:b5d0862b6075c2cfed75a8bd5f2c0196457ac83309dc42aa1cb71a1c834ca4ab
var _ **errs.Error = &pem.UnmarshalFailed

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/pem.ValueInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:7cb5d46a21ff0cd137b53aca3fafbf3be55cd93a451388dabdcb604399d09cb0
var _ **errs.Error = &pem.ValueInvalid
