load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "pem",
    srcs = [
        "doc.go",
        "facade_gen.go",
        "pem.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/pem",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/data/codec/pem",
        "//internal/kernel/errs",
        "//internal/service/data/codec/pem",
    ],
)

alias(
    name = "go_default_library",
    actual = ":pem",
    visibility = ["//visibility:public"],
)

go_test(
    name = "pem_test",
    srcs = [
        "api_gen_test.go",
        "pem_external_test.go",
    ],
    deps = [
        ":pem",
        "//internal/core/data/codec",
        "//internal/kernel/errs",
        "//pkg/v1/errs",
    ],
)
