// Code generated by kit from design/observe/logger/middleware/sample.yaml (sha256 b4c5e412c9b335f370819faeeee1373ba8d06f84b1f7dbef965b4a59fb10a086, body cd441f4a5abdd671df32e06a4f740f64ee094074e2a7be7053128d3265831d41). DO NOT EDIT.

package sample_test

import (
	"github.com/kitsunium/sdk/internal/core/observe/logger/middleware/sample"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/observe/logger/middleware/sample.CodeSampleDownstreamNil const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := sample.CodeSampleDownstreamNil
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, sample.CodeSampleDownstreamNil == 0x00_03_14_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/logger/middleware/sample.CodeSampleRateInvalid const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := sample.CodeSampleRateInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, sample.CodeSampleRateInvalid == 0x00_03_14_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/logger/middleware/sample.DownstreamNil var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &sample.DownstreamNil

// go:github.com/kitsunium/sdk/internal/core/observe/logger/middleware/sample.RateInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &sample.RateInvalid
