// Code generated by kit from design/crypto.yaml (sha256 fcdf412b06317e35532b814da96e4407340f303c4f49fe41495b6195a61beab1, body e0161f4dc103aefef71aac3a600e2794cf92715baa39e18f15e9b5cbc93c1649). DO NOT EDIT.

package kdf

import corecrypto "github.com/kitsunium/sdk/internal/core/crypto"

// Algorithm is the stable identifier of a key-derivation scheme. It is a defined
// type distinct from the other crypto-family Algorithm types (hash, mac, sign,
// …), so the compiler rejects feeding a hash or MAC constant into a KDF call
// (V104) — the seven registries are separate keyspaces, and the type system now
// enforces that separation the way typed Format/Level discipline does elsewhere.
type Algorithm corecrypto.Algorithm
