// Code generated by kit from design/framework/kit.yaml (sha256 5c0612cd3f4761a36962121298f8d4c963f3e98b52dad5b878a17f832eb81074, body ec684ae6ac97ebdce877a15613396aaaedd87cb68c292a3d557a208e757e995e). DO NOT EDIT.

package serverkit_test

import "github.com/kitsunium/sdk/framework/internal/kit/serverkit"

// go:github.com/kitsunium/sdk/framework/internal/kit/serverkit.Enable func func()
var _ func() = serverkit.Enable
