load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "serverkit",
    srcs = [
        "doc.go",
        "serverkit.go",
        "serverkit_compliance.go",
    ],
    importpath = "github.com/kitsunium/sdk/framework/internal/kit/serverkit",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
    deps = [
        "//framework/internal/kit/plug",
        "//pkg/v1/net/server",
        "//pkg/v1/net/static",
    ],
)

alias(
    name = "go_default_library",
    actual = ":serverkit",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
)

go_test(
    name = "serverkit_test",
    srcs = ["api_gen_test.go"],
    deps = [":serverkit"],
)
