// Code generated by kit from design/observe/logger/writer.yaml (sha256 bcee3ef1d61ef86362c46f15f9929513545cf67bf86404dc3329ccf28e058b98, body 8607a8f8c55155eaec7ec2e1456e85c9b7aa2d421ae42344174671ba6c49f9c2). DO NOT EDIT.

package console_test

import (
	"github.com/kitsunium/sdk/internal/core/observe/logger/writer"
	"github.com/kitsunium/sdk/internal/service/observe/logger/writer/console"
)

// go:github.com/kitsunium/sdk/internal/service/observe/logger/writer/console.Writer var github.com/kitsunium/sdk/internal/core/observe/logger/writer.Factory
var _ *writer.Factory = &console.Writer
