// Code generated by kit from design/observe/logger/writer.yaml (sha256 136c770907244cdf85f5c722b2bea368bf058d26b2693f3b0f74eb20e206cfd5, body 8607a8f8c55155eaec7ec2e1456e85c9b7aa2d421ae42344174671ba6c49f9c2). DO NOT EDIT.

package console_test

import (
	"github.com/kitsunium/sdk/internal/core/observe/logger/writer"
	"github.com/kitsunium/sdk/internal/service/observe/logger/writer/console"
)

// go:github.com/kitsunium/sdk/internal/service/observe/logger/writer/console.Writer var github.com/kitsunium/sdk/internal/core/observe/logger/writer.Factory
var _ *writer.Factory = &console.Writer
