// Code generated by kit from design/framework/git.yaml (sha256 f8de9e7344f83e0137ef9670bdebfb5b0d0ed9b60c8a10fb37c87f910e43fabe, body 41862625d8259e87531d3503a56927c8ac334ab4249e868fbcbd8e7514ce49b3). DO NOT EDIT.

package git_test

// package github.com/kitsunium/sdk/framework/internal/core/git doc:c320fe89ac6425689d98949a8a60c13a5b908f8b98e255b4f52955ed62afd8c3

import (
	"github.com/kitsunium/sdk/framework/internal/core/git"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/framework/internal/core/git.ChangedSet type interface{ContainsDir(absDir string) bool; ContainsFile(absFile string) bool; ContainsLine(absFile string, line int) bool; IsEmpty() bool} doc:7fbecf32e94371c335de3f6732dea6b86dcff9ce211e8d24d4888cc2f75fd13b
// go:github.com/kitsunium/sdk/framework/internal/core/git.ChangedSet.ContainsDir method func(absDir string) bool doc:4ce37248f39ef1d588aab4bdb405eb0ee7cce31e74af3c61c376ae4f96061a78
// go:github.com/kitsunium/sdk/framework/internal/core/git.ChangedSet.ContainsFile method func(absFile string) bool doc:43a579a5e01ffa618fb9705b4f94c279b0924b8a5cd1c895c250a0d09f48eba2
// go:github.com/kitsunium/sdk/framework/internal/core/git.ChangedSet.ContainsLine method func(absFile string, line int) bool doc:9e07fd8b480ed131ab54e0e429cb836e72519c79edf4e711870fd53822db6c2b
// go:github.com/kitsunium/sdk/framework/internal/core/git.ChangedSet.IsEmpty method func() bool doc:4634f2434f17c37e2a684dfbdef5db6941d5483b7fa41c2089dd8cb0a0709e11
var (
	_ interface {
		ContainsLine(absFile string, line int) bool
		ContainsFile(absFile string) bool
		ContainsDir(absDir string) bool
		IsEmpty() bool
	} = git.ChangedSet(nil)
	_ git.ChangedSet = interface {
		ContainsLine(absFile string, line int) bool
		ContainsFile(absFile string) bool
		ContainsDir(absDir string) bool
		IsEmpty() bool
	}(nil)
)

// go:github.com/kitsunium/sdk/framework/internal/core/git.CodeCommandFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:87cb0da88756007c88c574d6967df5840ac231df6a1e8994977cec18e8bd23d6
func _() {
	x := git.CodeCommandFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, git.CodeCommandFailed == 0x00_02_21_02: 1}
}

// go:github.com/kitsunium/sdk/framework/internal/core/git.CodePathAbsent const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:312bc09cbc6015d0e59395ea7da9b326a50ba71109b2732a5e4e3f6dd162b74e
func _() {
	x := git.CodePathAbsent
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, git.CodePathAbsent == 0x00_02_21_03: 1}
}

// go:github.com/kitsunium/sdk/framework/internal/core/git.CodeRepositoryUnresolved const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:f4a5447d971190cbeb4bfad4446e86602751436847aced6eacb760f46edea9c3
func _() {
	x := git.CodeRepositoryUnresolved
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, git.CodeRepositoryUnresolved == 0x00_02_21_01: 1}
}

// go:github.com/kitsunium/sdk/framework/internal/core/git.CommandFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:54f20e1d52a592837aaf8fa31dd2a2d4ceabbe9ab389ed1f2dec9ac5f331891f
var _ **errs.Error = &git.CommandFailed

// go:github.com/kitsunium/sdk/framework/internal/core/git.LineRangeValue type struct{Start int; End int} doc:3fe0651aa38ab3b21f15bd2484adc0683594c115e4274e35f2e4d83f3020aaa7
func _(x git.LineRangeValue) {
	var _ *int = &x.Start
	var _ *int = &x.End
}

// go:github.com/kitsunium/sdk/framework/internal/core/git.LineRangeValue.Contains method func(line int) bool doc:6478678165211adf84e0dc482505d8a907f05334838999788cc1d278a0f8b5cc
var _ func(_ git.LineRangeValue, line int) bool = git.LineRangeValue.Contains

// go:github.com/kitsunium/sdk/framework/internal/core/git.PathAbsent var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:8c70f4825682f36e78fe56665147048a77e535155541a988ef72a180ad9d7dd5
var _ **errs.Error = &git.PathAbsent

// go:github.com/kitsunium/sdk/framework/internal/core/git.RepositoryUnresolved var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:47c9c3ec76dab757fbb6af88a66a4473d506538f52ff4affa596a6a289d1bf9d
var _ **errs.Error = &git.RepositoryUnresolved

// go:github.com/kitsunium/sdk/framework/internal/core/git.ResolutionValue type struct{Set github.com/kitsunium/sdk/framework/internal/core/git.ChangedSet; BaseRef string; BaseSHA string; HeadSHA string; FullFallback bool; Reason string} doc:54c1ffe64bd4cf6c36210b3666b7948e4244693d6c965fceae5022f713404d76
func _(x git.ResolutionValue) {
	var _ *git.ChangedSet = &x.Set
	var _ *string = &x.BaseRef
	var _ *string = &x.BaseSHA
	var _ *string = &x.HeadSHA
	var _ *bool = &x.FullFallback
	var _ *string = &x.Reason
}

// go:github.com/kitsunium/sdk/framework/internal/core/git.(*ResolutionValue).Degraded method func() bool doc:cc3e77473c94e51849fc40f7327f2a6a843f14cc51be288919ed64688e00cd5c
var _ func(*git.ResolutionValue) bool = (*git.ResolutionValue).Degraded
