// Code generated by kit from design/app/statemachine.yaml (sha256 263d20fe1d0c0b7c176e4f4502a7c1b65f8f1977a10c02c5b6d673dd10e145a5, body d8606cec2ee9c80d7604a5187415713d1b3ce353c9084d8442924ab700b7ed50). DO NOT EDIT.

package statemachine_test

import (
	"context"
	"time"

	corestm "github.com/kitsunium/sdk/internal/core/app/statemachine"
	"github.com/kitsunium/sdk/internal/kernel/errs"
	svcstm "github.com/kitsunium/sdk/internal/service/app/statemachine"
	"github.com/kitsunium/sdk/pkg/v1/app/statemachine"
)

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Change alias [E any, S comparable] github.com/kitsunium/sdk/internal/service/app/statemachine.ChangeValue[E, S]
func _[E any, S comparable]() {
	var _ *svcstm.ChangeValue[E, S] = (*statemachine.Change[E, S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeDelayInvalid const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeDelayInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeDelayInvalid == 0x00_03_58_11: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeEntityExists const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeEntityExists
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeEntityExists == 0x00_03_58_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeEntityMissing const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeEntityMissing
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeEntityMissing == 0x00_03_58_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeEventInvalid const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeEventInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeEventInvalid == 0x00_03_58_0F: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeFunctionMissing const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeFunctionMissing
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeFunctionMissing == 0x00_03_58_12: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeFunctionPanicked const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeFunctionPanicked
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeFunctionPanicked == 0x00_03_58_0D: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeHookChangedKey const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeHookChangedKey
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeHookChangedKey == 0x00_03_58_08: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeHookChangedState const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeHookChangedState
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeHookChangedState == 0x00_03_58_07: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeHookFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeHookFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeHookFailed == 0x00_03_58_05: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeHookPanicked const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeHookPanicked
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeHookPanicked == 0x00_03_58_06: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeInitialMissing const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeInitialMissing
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeInitialMissing == 0x00_03_58_0E: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeJournalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeJournalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeJournalFailed == 0x00_03_58_0B: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeKeyEmpty const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeKeyEmpty
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeKeyEmpty == 0x00_03_58_04: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeLoopPanicked const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeLoopPanicked
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeLoopPanicked == 0x00_03_58_15: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeLoopRunning const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeLoopRunning
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeLoopRunning == 0x00_03_58_0C: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeReentrant const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeReentrant
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeReentrant == 0x00_03_58_09: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeStoreFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeStoreFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeStoreFailed == 0x00_03_58_0A: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeStoreMissing const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeStoreMissing
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeStoreMissing == 0x00_03_58_13: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeTransitionDuplicate const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeTransitionDuplicate
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeTransitionDuplicate == 0x00_03_58_10: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeTransitionRefused const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeTransitionRefused
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeTransitionRefused == 0x00_03_58_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeTriggerUnknown const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeTriggerUnknown
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeTriggerUnknown == 0x00_02_38_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CodeWaitAbandoned const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := statemachine.CodeWaitAbandoned
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, statemachine.CodeWaitAbandoned == 0x00_03_58_14: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Config alias [E any, S comparable] github.com/kitsunium/sdk/internal/service/app/statemachine.Config[E, S]
func _[E any, S comparable]() {
	var _ *svcstm.Config[E, S] = (*statemachine.Config[E, S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.CreateEvent const string
func _() {
	x := statemachine.CreateEvent
	var _ *string = &x
	_ = map[bool]int{false: 0, statemachine.CreateEvent == "create": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.DefaultMaxHistory const int
func _() {
	x := statemachine.DefaultMaxHistory
	var _ *int = &x
	_ = map[bool]int{false: 0, statemachine.DefaultMaxHistory == 20: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.DefaultMinGap const time.Duration
func _() {
	x := statemachine.DefaultMinGap
	var _ *time.Duration = &x
	_ = map[bool]int{false: 0, statemachine.DefaultMinGap == 1000000000: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Define[...] func func[E any, S comparable](state func(*E) *S) *github.com/kitsunium/sdk/pkg/v1/app/statemachine.Definition[E, S]
func _[E any, S comparable]() {
	var _ func(state func(*E) *S) *statemachine.Definition[E, S] = statemachine.Define[E, S]
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Definition alias [E any, S comparable] github.com/kitsunium/sdk/internal/service/app/statemachine.MachineSpec[E, S]
func _[E any, S comparable]() {
	var _ *svcstm.MachineSpec[E, S] = (*statemachine.Definition[E, S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.DelayInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.DelayInvalid

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.EntityExists var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.EntityExists

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.EntityMissing var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.EntityMissing

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.EventInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.EventInvalid

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Firing alias [S comparable] github.com/kitsunium/sdk/internal/service/app/statemachine.FiringValue[S]
func _[S comparable]() {
	var _ *svcstm.FiringValue[S] = (*statemachine.Firing[S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.FunctionMissing var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.FunctionMissing

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.FunctionPanicked var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.FunctionPanicked

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.HookChangedKey var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.HookChangedKey

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.HookChangedState var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.HookChangedState

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.HookFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.HookFailed

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.HookPanicked var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.HookPanicked

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.InitialMissing var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.InitialMissing

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Journal alias [S comparable] github.com/kitsunium/sdk/internal/core/app/statemachine.Journal[S]
func _[S comparable]() {
	var _ *corestm.Journal[S] = (*statemachine.Journal[S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.JournalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.JournalFailed

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.KeyEmpty var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.KeyEmpty

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopEvent alias github.com/kitsunium/sdk/internal/service/app/statemachine.LoopEvent
var _ *svcstm.LoopEvent = (*statemachine.LoopEvent)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopEventKind alias github.com/kitsunium/sdk/internal/service/app/statemachine.LoopEventKind
var _ *svcstm.LoopEventKind = (*statemachine.LoopEventKind)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopPanicked var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.LoopPanicked

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopRunEnded const github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopEventKind
func _() {
	x := statemachine.LoopRunEnded
	var _ *statemachine.LoopEventKind = &x
	_ = map[bool]int{false: 0, statemachine.LoopRunEnded == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopRunStarted const github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopEventKind
func _() {
	x := statemachine.LoopRunStarted
	var _ *statemachine.LoopEventKind = &x
	_ = map[bool]int{false: 0, statemachine.LoopRunStarted == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopRunning var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.LoopRunning

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopWaiting const github.com/kitsunium/sdk/pkg/v1/app/statemachine.LoopEventKind
func _() {
	x := statemachine.LoopWaiting
	var _ *statemachine.LoopEventKind = &x
	_ = map[bool]int{false: 0, statemachine.LoopWaiting == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Machine alias [E any, S comparable] github.com/kitsunium/sdk/internal/service/app/statemachine.StateMachine[E, S]
func _[E any, S comparable]() {
	var _ *svcstm.StateMachine[E, S] = (*statemachine.Machine[E, S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.New[...] func func[E any, S comparable](ctx context.Context, def *github.com/kitsunium/sdk/pkg/v1/app/statemachine.Definition[E, S], cfg *github.com/kitsunium/sdk/pkg/v1/app/statemachine.Config[E, S]) (*github.com/kitsunium/sdk/pkg/v1/app/statemachine.Machine[E, S], error)
func _[E any, S comparable]() {
	var _ func(ctx context.Context, def *statemachine.Definition[E, S], cfg *statemachine.Config[E, S]) (*statemachine.Machine[E, S], error) = statemachine.New[E, S]
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.ParseTrigger func func(name string) (github.com/kitsunium/sdk/pkg/v1/app/statemachine.Trigger, error)
var _ func(name string) (statemachine.Trigger, error) = statemachine.ParseTrigger

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Record alias [S comparable] github.com/kitsunium/sdk/internal/core/app/statemachine.RecordValue[S]
func _[S comparable]() {
	var _ *corestm.RecordValue[S] = (*statemachine.Record[S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Reentrant var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.Reentrant

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Step alias [S comparable] github.com/kitsunium/sdk/internal/core/app/statemachine.StepValue[S]
func _[S comparable]() {
	var _ *corestm.StepValue[S] = (*statemachine.Step[S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Store alias [E any] github.com/kitsunium/sdk/internal/core/app/statemachine.Store[E]
func _[E any]() {
	var _ *corestm.Store[E] = (*statemachine.Store[E])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.StoreFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.StoreFailed

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.StoreMissing var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.StoreMissing

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Transition alias [S comparable] github.com/kitsunium/sdk/internal/service/app/statemachine.TransitionValue[S]
func _[S comparable]() {
	var _ *svcstm.TransitionValue[S] = (*statemachine.Transition[S])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TransitionDuplicate var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.TransitionDuplicate

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TransitionRefused var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.TransitionRefused

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Trigger alias github.com/kitsunium/sdk/internal/core/app/statemachine.Trigger
var _ *corestm.Trigger = (*statemachine.Trigger)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TriggerDeadline const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Trigger
func _() {
	x := statemachine.TriggerDeadline
	var _ *statemachine.Trigger = &x
	_ = map[bool]int{false: 0, statemachine.TriggerDeadline == 4: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TriggerDelay const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Trigger
func _() {
	x := statemachine.TriggerDelay
	var _ *statemachine.Trigger = &x
	_ = map[bool]int{false: 0, statemachine.TriggerDelay == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TriggerEvent const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Trigger
func _() {
	x := statemachine.TriggerEvent
	var _ *statemachine.Trigger = &x
	_ = map[bool]int{false: 0, statemachine.TriggerEvent == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TriggerGuard const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Trigger
func _() {
	x := statemachine.TriggerGuard
	var _ *statemachine.Trigger = &x
	_ = map[bool]int{false: 0, statemachine.TriggerGuard == 5: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TriggerStart const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Trigger
func _() {
	x := statemachine.TriggerStart
	var _ *statemachine.Trigger = &x
	_ = map[bool]int{false: 0, statemachine.TriggerStart == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.TriggerUnknown var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.TriggerUnknown

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.WaitAbandoned var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &statemachine.WaitAbandoned

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.Wake alias github.com/kitsunium/sdk/internal/service/app/statemachine.Wake
var _ *svcstm.Wake = (*statemachine.Wake)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.WakeChange const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Wake
func _() {
	x := statemachine.WakeChange
	var _ *statemachine.Wake = &x
	_ = map[bool]int{false: 0, statemachine.WakeChange == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.WakeDue const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Wake
func _() {
	x := statemachine.WakeDue
	var _ *statemachine.Wake = &x
	_ = map[bool]int{false: 0, statemachine.WakeDue == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/statemachine.WakeStart const github.com/kitsunium/sdk/pkg/v1/app/statemachine.Wake
func _() {
	x := statemachine.WakeStart
	var _ *statemachine.Wake = &x
	_ = map[bool]int{false: 0, statemachine.WakeStart == 1: 1}
}
