// Code generated by kit from design/app/id.yaml (sha256 f0ee63f9b7d08b21e33c0259c4807b5e770c5cebc8382dc07b6b507437eda07d, body db5eb93b5178a2a5b452d750bac262b2e8d89625d1c53bd7c037b36f8cb4d651). DO NOT EDIT.

package id

// Generator is the contract every identifier scheme satisfies. Instances MUST
// be safe for concurrent use (New is called from many goroutines). Scheme-
// specific options (snowflake node id, etc.) are supplied via the scheme's
// constructor, not via this interface.
//
// IFACE-PLUGIN: the registry stores plug-in scheme instances behind this
// interface — concrete scheme types stay unexported per package.
type Generator interface {
	Scheme() Scheme
	New() (newID string, err error)
}
