load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "flatbuffers",
    srcs = [
        "codec.go",
        "codes.go",
        "errors.go",
        "types.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/codec/flatbuffers",
    visibility = ["//internal/service:service_consumers"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":flatbuffers",
    visibility = ["//internal/service:service_consumers"],
)

go_test(
    name = "flatbuffers_test",
    size = "small",
    srcs = [
        "codec_external_test.go",
        "codec_integration_test.go",
        "codec_internal_test.go",
    ],
    embed = [":flatbuffers"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
    ],
)

filegroup(
    name = "audit_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
