load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/kernel:kernel_consumers"])

go_library(
    name = "group",
    srcs = [
        "collect.go",
        "doc.go",
        "group.go",
        "panic.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/kernel/concur/group",
    visibility = [
        "//:__subpackages__",
        "//internal/kernel:kernel_consumers",
    ],
)

alias(
    name = "go_default_library",
    actual = ":group",
    visibility = [
        "//:__subpackages__",
        "//internal/kernel:kernel_consumers",
    ],
)

go_test(
    name = "group_test",
    size = "small",
    srcs = [
        "api_gen_1_test.go",
        "api_gen_2_test.go",
        "api_gen_test.go",
        "group_bench_test.go",
        "group_external_test.go",
        "group_internal_test.go",
        "joined_external_test.go",
    ],
    embed = [":group"],
    deps = ["//internal/kernel/errs"],
)
