load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "ndjson",
    srcs = [
        "codec.go",
        "codes.go",
        "errors.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/codec/ndjson",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":ndjson",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "ndjson_test",
    srcs = [
        "codec_external_test.go",
        "codec_internal_test.go",
    ],
    embed = [":ndjson"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
    ],
)

filegroup(
    name = "audit_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
