load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "csv",
    srcs = [
        "codec.go",
        "decl_gen.go",
        "doc.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/data/codec/csv",
    visibility = ["//internal/service:service_consumers"],
    deps = [
        "//internal/core/data/codec",
        "//internal/core/data/codec/csv",
        "//internal/core/data/codec/scratch",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":csv",
    visibility = ["//internal/service:service_consumers"],
)

go_test(
    name = "csv_test",
    size = "small",
    srcs = [
        "api_gen_test.go",
        "codec_external_test.go",
        "codec_integration_test.go",
        "codec_internal_test.go",
    ],
    embed = [":csv"],
    deps = [
        "//internal/core/data/codec",
        "//internal/kernel/errs",
    ],
)
