// Code generated by kit from design/security/token.yaml (sha256 014e5ee73d0bd2fed2274e355ad039d1d826b49eb56a9427ef75424362520afd, body 9d76497f91c65b044a71568dff0b7e71a7d724e38217095b6d1c05d7c1281765). DO NOT EDIT.

package token_test

import (
	"crypto/ecdsa"
	"crypto/ed25519"

	corecrypto "github.com/kitsunium/sdk/internal/core/crypto"
	coretoken "github.com/kitsunium/sdk/internal/core/security/token"
	"github.com/kitsunium/sdk/internal/service/crypto/key/jwk"
	svctoken "github.com/kitsunium/sdk/internal/service/security/token"
	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/sdk/pkg/v1/security/token"
)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Algorithm alias github.com/kitsunium/sdk/internal/core/security/token.Algorithm
var _ *coretoken.Algorithm = (*token.Algorithm)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.AlgorithmES256 const github.com/kitsunium/sdk/pkg/v1/security/token.Algorithm
func _() {
	x := token.AlgorithmES256
	var _ *token.Algorithm = &x
	_ = map[bool]int{false: 0, token.AlgorithmES256 == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.AlgorithmEdDSA const github.com/kitsunium/sdk/pkg/v1/security/token.Algorithm
func _() {
	x := token.AlgorithmEdDSA
	var _ *token.Algorithm = &x
	_ = map[bool]int{false: 0, token.AlgorithmEdDSA == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.AlgorithmHS256 const github.com/kitsunium/sdk/pkg/v1/security/token.Algorithm
func _() {
	x := token.AlgorithmHS256
	var _ *token.Algorithm = &x
	_ = map[bool]int{false: 0, token.AlgorithmHS256 == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.AlgorithmMismatch var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.AlgorithmMismatch
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.AlgorithmNone var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.AlgorithmNone
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.AlgorithmPasetoV4Public const github.com/kitsunium/sdk/pkg/v1/security/token.Algorithm
func _() {
	x := token.AlgorithmPasetoV4Public
	var _ *token.Algorithm = &x
	_ = map[bool]int{false: 0, token.AlgorithmPasetoV4Public == 4: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.AudienceMismatch var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.AudienceMismatch
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimAudience const string
func _() {
	x := token.ClaimAudience
	var _ *string = &x
	_ = map[bool]int{false: 0, token.ClaimAudience == "aud": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimExpiry const string
func _() {
	x := token.ClaimExpiry
	var _ *string = &x
	_ = map[bool]int{false: 0, token.ClaimExpiry == "exp": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimID const string
func _() {
	x := token.ClaimID
	var _ *string = &x
	_ = map[bool]int{false: 0, token.ClaimID == "jti": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimIssuedAt const string
func _() {
	x := token.ClaimIssuedAt
	var _ *string = &x
	_ = map[bool]int{false: 0, token.ClaimIssuedAt == "iat": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimIssuer const string
func _() {
	x := token.ClaimIssuer
	var _ *string = &x
	_ = map[bool]int{false: 0, token.ClaimIssuer == "iss": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimNameInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.ClaimNameInvalid
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimNotBefore const string
func _() {
	x := token.ClaimNotBefore
	var _ *string = &x
	_ = map[bool]int{false: 0, token.ClaimNotBefore == "nbf": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ClaimSubject const string
func _() {
	x := token.ClaimSubject
	var _ *string = &x
	_ = map[bool]int{false: 0, token.ClaimSubject == "sub": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Claims alias github.com/kitsunium/sdk/internal/core/security/token.ClaimsValue
var _ *coretoken.ClaimsValue = (*token.Claims)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeAlgorithmMismatch const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeAlgorithmMismatch
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeAlgorithmMismatch == 0x00_02_0D_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeAlgorithmNone const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeAlgorithmNone
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeAlgorithmNone == 0x00_02_0D_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeAudienceMismatch const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeAudienceMismatch
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeAudienceMismatch == 0x00_02_0D_08: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeClaimNameInvalid const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeClaimNameInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeClaimNameInvalid == 0x00_02_0D_0F: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeDuplicateMember const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeDuplicateMember
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeDuplicateMember == 0x00_03_2C_07: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeExpired const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeExpired
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeExpired == 0x00_02_0D_05: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeExpiryRequired const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeExpiryRequired
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeExpiryRequired == 0x00_02_0D_07: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeFooterMismatch const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeFooterMismatch
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeFooterMismatch == 0x00_03_2C_05: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeHeaderUnsupported const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeHeaderUnsupported
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeHeaderUnsupported == 0x00_03_2C_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeIssueFailed const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeIssueFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeIssueFailed == 0x00_02_0D_0E: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeIssuerMismatch const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeIssuerMismatch
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeIssuerMismatch == 0x00_02_0D_09: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeJWKInvalidEncoding const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeJWKInvalidEncoding
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeJWKInvalidEncoding == 0x00_03_2A_05: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeJWKKeyMismatch const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeJWKKeyMismatch
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeJWKKeyMismatch == 0x00_03_2A_06: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeJWKMalformed const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeJWKMalformed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeJWKMalformed == 0x00_03_2A_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeJWKMissingMember const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeJWKMissingMember
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeJWKMissingMember == 0x00_03_2A_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeJWKUnsupportedCurve const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeJWKUnsupportedCurve
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeJWKUnsupportedCurve == 0x00_03_2A_04: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeJWKUnsupportedKeyType const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeJWKUnsupportedKeyType
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeJWKUnsupportedKeyType == 0x00_03_2A_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeKeyIDAmbiguous const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeKeyIDAmbiguous
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeKeyIDAmbiguous == 0x00_03_2C_04: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeKeyIDMissing const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeKeyIDMissing
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeKeyIDMissing == 0x00_03_2C_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeKeyNotFound const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeKeyNotFound
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeKeyNotFound == 0x00_03_2C_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeKeyUnsuitable const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeKeyUnsuitable
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeKeyUnsuitable == 0x00_02_0D_0C: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeLifetimeTooLong const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeLifetimeTooLong
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeLifetimeTooLong == 0x00_02_0D_10: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeMalformed const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeMalformed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeMalformed == 0x00_02_0D_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeNotYetValid const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeNotYetValid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeNotYetValid == 0x00_02_0D_06: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodePolicyMisconfigured const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodePolicyMisconfigured
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodePolicyMisconfigured == 0x00_02_0D_0D: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeSchemeUnsupported const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeSchemeUnsupported
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeSchemeUnsupported == 0x00_03_2C_06: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeSignatureInvalid const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeSignatureInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeSignatureInvalid == 0x00_02_0D_04: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeTooDeep const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeTooDeep
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeTooDeep == 0x00_02_0D_0B: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CodeTooLarge const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := token.CodeTooLarge
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, token.CodeTooLarge == 0x00_02_0D_0A: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Curve alias github.com/kitsunium/sdk/internal/service/crypto/key/jwk.Curve
var _ *jwk.Curve = (*token.Curve)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CurveEd25519 const github.com/kitsunium/sdk/pkg/v1/security/token.Curve
func _() {
	x := token.CurveEd25519
	var _ *token.Curve = &x
	_ = map[bool]int{false: 0, token.CurveEd25519 == "Ed25519": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CurveP256 const github.com/kitsunium/sdk/pkg/v1/security/token.Curve
func _() {
	x := token.CurveP256
	var _ *token.Curve = &x
	_ = map[bool]int{false: 0, token.CurveP256 == "P-256": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CurveP384 const github.com/kitsunium/sdk/pkg/v1/security/token.Curve
func _() {
	x := token.CurveP384
	var _ *token.Curve = &x
	_ = map[bool]int{false: 0, token.CurveP384 == "P-384": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.CurveP521 const github.com/kitsunium/sdk/pkg/v1/security/token.Curve
func _() {
	x := token.CurveP521
	var _ *token.Curve = &x
	_ = map[bool]int{false: 0, token.CurveP521 == "P-521": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.DuplicateMember var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.DuplicateMember
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Expired var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.Expired
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ExpiryRequired var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.ExpiryRequired
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.FooterMismatch var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.FooterMismatch
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.HeaderUnsupported var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.HeaderUnsupported
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.IssueFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.IssueFailed
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Issuer alias github.com/kitsunium/sdk/internal/core/security/token.Issuer
var _ *coretoken.Issuer = (*token.Issuer)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.IssuerConfig alias github.com/kitsunium/sdk/internal/service/security/token.IssuerConfig
var _ *svctoken.IssuerConfig = (*token.IssuerConfig)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.IssuerMismatch var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.IssuerMismatch
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWK alias github.com/kitsunium/sdk/internal/service/crypto/key/jwk.KeyValue
var _ *jwk.KeyValue = (*token.JWK)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWKInvalidEncoding var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.JWKInvalidEncoding
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWKKeyMismatch var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.JWKKeyMismatch
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWKMalformed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.JWKMalformed
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWKMissingMember var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.JWKMissingMember
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWKSet alias github.com/kitsunium/sdk/internal/service/crypto/key/jwk.Set
var _ *jwk.Set = (*token.JWKSet)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWKUnsupportedCurve var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.JWKUnsupportedCurve
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.JWKUnsupportedKeyType var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.JWKUnsupportedKeyType
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Key alias github.com/kitsunium/sdk/internal/core/crypto.Key
var _ *corecrypto.Key = (*token.Key)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyIDAmbiguous var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.KeyIDAmbiguous
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyIDMissing var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.KeyIDMissing
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyNotFound var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.KeyNotFound
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyType alias github.com/kitsunium/sdk/internal/service/crypto/key/jwk.Type
var _ *jwk.Type = (*token.KeyType)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyTypeEC const github.com/kitsunium/sdk/pkg/v1/security/token.KeyType
func _() {
	x := token.KeyTypeEC
	var _ *token.KeyType = &x
	_ = map[bool]int{false: 0, token.KeyTypeEC == "EC": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyTypeOKP const github.com/kitsunium/sdk/pkg/v1/security/token.KeyType
func _() {
	x := token.KeyTypeOKP
	var _ *token.KeyType = &x
	_ = map[bool]int{false: 0, token.KeyTypeOKP == "OKP": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyTypeOct const github.com/kitsunium/sdk/pkg/v1/security/token.KeyType
func _() {
	x := token.KeyTypeOct
	var _ *token.KeyType = &x
	_ = map[bool]int{false: 0, token.KeyTypeOct == "oct": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.KeyUnsuitable var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.KeyUnsuitable
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.LifetimeTooLong var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.LifetimeTooLong
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Malformed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.Malformed
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewClaims func func() github.com/kitsunium/sdk/pkg/v1/security/token.Claims
var _ func() token.Claims = token.NewClaims

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewES256Issuer func func(priv *crypto/ecdsa.PrivateKey, cfg github.com/kitsunium/sdk/pkg/v1/security/token.IssuerConfig) (issuer github.com/kitsunium/sdk/pkg/v1/security/token.Issuer, err error)
var _ func(priv *ecdsa.PrivateKey, cfg token.IssuerConfig) (issuer token.Issuer, err error) = token.NewES256Issuer

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewES256Verifier func func(pub *crypto/ecdsa.PublicKey, cfg github.com/kitsunium/sdk/pkg/v1/security/token.VerifierConfig) (verifier github.com/kitsunium/sdk/pkg/v1/security/token.Verifier, err error)
var _ func(pub *ecdsa.PublicKey, cfg token.VerifierConfig) (verifier token.Verifier, err error) = token.NewES256Verifier

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewEdDSAIssuer func func(priv crypto/ed25519.PrivateKey, cfg github.com/kitsunium/sdk/pkg/v1/security/token.IssuerConfig) (issuer github.com/kitsunium/sdk/pkg/v1/security/token.Issuer, err error)
var _ func(priv ed25519.PrivateKey, cfg token.IssuerConfig) (issuer token.Issuer, err error) = token.NewEdDSAIssuer

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewEdDSAVerifier func func(pub crypto/ed25519.PublicKey, cfg github.com/kitsunium/sdk/pkg/v1/security/token.VerifierConfig) (verifier github.com/kitsunium/sdk/pkg/v1/security/token.Verifier, err error)
var _ func(pub ed25519.PublicKey, cfg token.VerifierConfig) (verifier token.Verifier, err error) = token.NewEdDSAVerifier

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewHS256Issuer func func(secret github.com/kitsunium/sdk/pkg/v1/security/token.Key, cfg github.com/kitsunium/sdk/pkg/v1/security/token.IssuerConfig) (issuer github.com/kitsunium/sdk/pkg/v1/security/token.Issuer, err error)
var _ func(secret token.Key, cfg token.IssuerConfig) (issuer token.Issuer, err error) = token.NewHS256Issuer

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewHS256Verifier func func(secret github.com/kitsunium/sdk/pkg/v1/security/token.Key, cfg github.com/kitsunium/sdk/pkg/v1/security/token.VerifierConfig) (verifier github.com/kitsunium/sdk/pkg/v1/security/token.Verifier, err error)
var _ func(secret token.Key, cfg token.VerifierConfig) (verifier token.Verifier, err error) = token.NewHS256Verifier

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewJWKSet func func(keys ...github.com/kitsunium/sdk/pkg/v1/security/token.JWK) github.com/kitsunium/sdk/pkg/v1/security/token.JWKSet
var _ func(keys ...token.JWK) token.JWKSet = token.NewJWKSet

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewPasetoV4Issuer func func(priv crypto/ed25519.PrivateKey, cfg github.com/kitsunium/sdk/pkg/v1/security/token.PasetoIssuerConfig) (issuer github.com/kitsunium/sdk/pkg/v1/security/token.Issuer, err error)
var _ func(priv ed25519.PrivateKey, cfg token.PasetoIssuerConfig) (issuer token.Issuer, err error) = token.NewPasetoV4Issuer

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewPasetoV4Verifier func func(pub crypto/ed25519.PublicKey, cfg github.com/kitsunium/sdk/pkg/v1/security/token.PasetoVerifierConfig) (verifier github.com/kitsunium/sdk/pkg/v1/security/token.Verifier, err error)
var _ func(pub ed25519.PublicKey, cfg token.PasetoVerifierConfig) (verifier token.Verifier, err error) = token.NewPasetoV4Verifier

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewSetVerifier func func(set github.com/kitsunium/sdk/pkg/v1/security/token.JWKSet, cfg github.com/kitsunium/sdk/pkg/v1/security/token.VerifierConfig) (verifier github.com/kitsunium/sdk/pkg/v1/security/token.Verifier, err error)
var _ func(set token.JWKSet, cfg token.VerifierConfig) (verifier token.Verifier, err error) = token.NewSetVerifier

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NewVerifierFromJWK func func(key github.com/kitsunium/sdk/pkg/v1/security/token.JWK, cfg github.com/kitsunium/sdk/pkg/v1/security/token.VerifierConfig) (verifier github.com/kitsunium/sdk/pkg/v1/security/token.Verifier, err error)
var _ func(key token.JWK, cfg token.VerifierConfig) (verifier token.Verifier, err error) = token.NewVerifierFromJWK

// go:github.com/kitsunium/sdk/pkg/v1/security/token.NotYetValid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.NotYetValid
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ParseJWK func func(document []byte) (key github.com/kitsunium/sdk/pkg/v1/security/token.JWK, err error)
var _ func(document []byte) (key token.JWK, err error) = token.ParseJWK

// go:github.com/kitsunium/sdk/pkg/v1/security/token.ParseJWKSet func func(document []byte) (set github.com/kitsunium/sdk/pkg/v1/security/token.JWKSet, err error)
var _ func(document []byte) (set token.JWKSet, err error) = token.ParseJWKSet

// go:github.com/kitsunium/sdk/pkg/v1/security/token.PasetoIssuerConfig alias github.com/kitsunium/sdk/internal/service/security/token.PasetoIssuerConfig
var _ *svctoken.PasetoIssuerConfig = (*token.PasetoIssuerConfig)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.PasetoVerifierConfig alias github.com/kitsunium/sdk/internal/service/security/token.PasetoVerifierConfig
var _ *svctoken.PasetoVerifierConfig = (*token.PasetoVerifierConfig)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.PolicyMisconfigured var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.PolicyMisconfigured
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.PrivateClaim[...] func func[T any](claims github.com/kitsunium/sdk/pkg/v1/security/token.Claims, name string) (value T, found bool, err error)
func _[T any]() {
	var _ func(claims token.Claims, name string) (value T, found bool, err error) = token.PrivateClaim[T]
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.SchemeUnsupported var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.SchemeUnsupported
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.SetPrivateClaim[...] func func[T any](claims github.com/kitsunium/sdk/pkg/v1/security/token.Claims, name string, value T) (updated github.com/kitsunium/sdk/pkg/v1/security/token.Claims, err error)
func _[T any]() {
	var _ func(claims token.Claims, name string, value T) (updated token.Claims, err error) = token.SetPrivateClaim[T]
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.SignatureInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.SignatureInvalid
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.TooDeep var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.TooDeep
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.TooLarge var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &token.TooLarge
	x = &corecrypto.AgreementFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/security/token.Verifier alias github.com/kitsunium/sdk/internal/core/security/token.Verifier
var _ *coretoken.Verifier = (*token.Verifier)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/security/token.VerifierConfig alias github.com/kitsunium/sdk/internal/service/security/token.VerifierConfig
var _ *svctoken.VerifierConfig = (*token.VerifierConfig)(nil)
