// Code generated by kit from design/proc.yaml (sha256 262996f254edc28898bf98f5fb221bbca59f14b5dd921719524681ed50e619c3, body 42479e71ab78878e92c3bbcb955a3f4f49cd9945a3fbb822c1039aa9fcc8e67f). DO NOT EDIT.

//go:build unix

package listen_test

import (
	"net"
	"os"

	coreproc "github.com/kitsunium/sdk/internal/core/proc"
	"github.com/kitsunium/sdk/internal/service/proc/systemd/listen"
)

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.Files func func(unsetEnv bool) (files []*os.File, err error)
var _ func(unsetEnv bool) (files []*os.File, err error) = listen.Files

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.Listeners func func(unsetEnv bool) (lns []net.Listener, err error)
var _ func(unsetEnv bool) (lns []net.Listener, err error) = listen.Listeners

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.Prepare func func(child *github.com/kitsunium/sdk/internal/core/proc.Spec, named map[string]net.Listener) error
var _ func(child *coreproc.Spec, named map[string]net.Listener) error = listen.Prepare

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.WithNames func func(unsetEnv bool) (byName map[string][]*os.File, err error)
var _ func(unsetEnv bool) (byName map[string][]*os.File, err error) = listen.WithNames
