// Code generated by kit from design/proc.yaml (sha256 262996f254edc28898bf98f5fb221bbca59f14b5dd921719524681ed50e619c3, body 0fb3e22a5fd0f3aaf781523052900541d55e24874831c6ab7c4052db6a27848b). DO NOT EDIT.

//go:build !unix

package listen_test

import (
	"net"
	"os"

	coreproc "github.com/kitsunium/sdk/internal/core/proc"
	"github.com/kitsunium/sdk/internal/service/proc/systemd/listen"
)

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.Files func func(_ bool) ([]*os.File, error)
var _ func(_ bool) ([]*os.File, error) = listen.Files

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.Listeners func func(_ bool) ([]net.Listener, error)
var _ func(_ bool) ([]net.Listener, error) = listen.Listeners

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.Prepare func func(_ *github.com/kitsunium/sdk/internal/core/proc.Spec, _ map[string]net.Listener) error
var _ func(_ *coreproc.Spec, _ map[string]net.Listener) error = listen.Prepare

// go:github.com/kitsunium/sdk/internal/service/proc/systemd/listen.WithNames func func(_ bool) (map[string][]*os.File, error)
var _ func(_ bool) (map[string][]*os.File, error) = listen.WithNames
