// Code generated by kit from design/crypto.yaml (sha256 b933f455f7267a4e318afcb25aebbe0e2c97266efd36d80da420b2fbdb6428eb, body d97d1a385183bfe04a86b0396667ff8c4264bc494ac02c5a85a32701d232cf9c). DO NOT EDIT.

package crypto_test

// package github.com/kitsunium/sdk/pkg/v1/crypto doc:58884740bd8d0e25f0f644f244fa67e3b2bddb23b63f49bb65e96931c1669a03

import (
	"io"

	corecrypto "github.com/kitsunium/sdk/internal/core/crypto"
	"github.com/kitsunium/sdk/pkg/v1/crypto"
)

// go:github.com/kitsunium/sdk/pkg/v1/crypto.AESGCM const github.com/kitsunium/sdk/pkg/v1/crypto.Algorithm doc:a502ea4221ba7f39498919dd9efe26912705972d2b415c002e672f87c20636ae
func _() {
	x := crypto.AESGCM
	var _ *crypto.Algorithm = &x
	_ = map[bool]int{false: 0, crypto.AESGCM == "aes-256-gcm": 1}
}

func kitPinAlgorithm[X ~string]() {}

// go:github.com/kitsunium/sdk/pkg/v1/crypto.Algorithm type string doc:6629a191a31bc1b99cbaf724cb055feb996e8a782d1278bfcbf10ffb035586ed
var _ = kitPinAlgorithm[crypto.Algorithm]

// go:github.com/kitsunium/sdk/pkg/v1/crypto.Key alias github.com/kitsunium/sdk/internal/core/crypto.Key doc:e5f396ee2ce3e8d64dea739bccfea6868698a869c182555c07d8fe1cf3e3872a
var _ *corecrypto.Key = (*crypto.Key)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/crypto.KeyLen const int doc:ee4142c8a9439c4a2ed57bd61e4a24baf8b6b0899bad72074f7f761de7ebf2e2
func _() {
	x := crypto.KeyLen
	var _ *int = &x
	_ = map[bool]int{false: 0, crypto.KeyLen == 32: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/crypto.NewKey func func(raw []byte) (key github.com/kitsunium/sdk/pkg/v1/crypto.Key, err error) doc:935dbc1fa1c437f237182ea7fcc48dee7480183490ef19f5bb2b8514d2e2aa6e
var _ func(raw []byte) (key crypto.Key, err error) = crypto.NewKey

// go:github.com/kitsunium/sdk/pkg/v1/crypto.Open func func(k github.com/kitsunium/sdk/pkg/v1/crypto.Key, box []byte, aad []byte) (plaintext []byte, err error) doc:991a6f4e728f65426370c48931b0676f95f7db9fcfb35851c7f5b455781cd7ad
var _ func(k crypto.Key, box, aad []byte) (plaintext []byte, err error) = crypto.Open

// go:github.com/kitsunium/sdk/pkg/v1/crypto.OpenStream func func(src io.Reader, k github.com/kitsunium/sdk/pkg/v1/crypto.Key, aad []byte) (opened io.Reader, err error) doc:96f5b82bd60e994e3fbe95379f2c4e5814b3eb8b259031a50f9d888449903e1a
var _ func(src io.Reader, k crypto.Key, aad []byte) (opened io.Reader, err error) = crypto.OpenStream

// go:github.com/kitsunium/sdk/pkg/v1/crypto.Seal func func(k github.com/kitsunium/sdk/pkg/v1/crypto.Key, plaintext []byte, aad []byte) (box []byte, err error) doc:5605efdca34d97c422e06e335acf3e6ebfd83db07edb41e0b36d78865af24b91
var _ func(k crypto.Key, plaintext, aad []byte) (box []byte, err error) = crypto.Seal

// go:github.com/kitsunium/sdk/pkg/v1/crypto.SealAs func func(a github.com/kitsunium/sdk/pkg/v1/crypto.Algorithm, k github.com/kitsunium/sdk/pkg/v1/crypto.Key, plaintext []byte, aad []byte) (box []byte, err error) doc:53bb72b6530e154067a04c2ed401823a5614b58ba7f7c62d8a87da5190950068
var _ func(a crypto.Algorithm, k crypto.Key, plaintext, aad []byte) (box []byte, err error) = crypto.SealAs

// go:github.com/kitsunium/sdk/pkg/v1/crypto.SealStream func func(dst io.Writer, k github.com/kitsunium/sdk/pkg/v1/crypto.Key, aad []byte) (sealed io.WriteCloser, err error) doc:80f1479bc490caeb127a1416b47dac4c8cf2527664873908439d488189f0b5ff
var _ func(dst io.Writer, k crypto.Key, aad []byte) (sealed io.WriteCloser, err error) = crypto.SealStream

// go:github.com/kitsunium/sdk/pkg/v1/crypto.UnwrapKey func func(passphrase []byte, envelope string) (dek github.com/kitsunium/sdk/pkg/v1/crypto.Key, err error) doc:3089622c2e3922c8783fc0e7258b1fb1f1e61a74e2e0781472dc79810b8b9b92
var _ func(passphrase []byte, envelope string) (dek crypto.Key, err error) = crypto.UnwrapKey

// go:github.com/kitsunium/sdk/pkg/v1/crypto.WrapKey func func(passphrase []byte, dek github.com/kitsunium/sdk/pkg/v1/crypto.Key) (envelope string, err error) doc:a87f77b6274fd55173438fc8821e3aca577c235f843a785466fdc6defb539e69
var _ func(passphrase []byte, dek crypto.Key) (envelope string, err error) = crypto.WrapKey

// go:github.com/kitsunium/sdk/pkg/v1/crypto.XChaCha20Poly1305 const github.com/kitsunium/sdk/pkg/v1/crypto.Algorithm doc:7c573ef2642bf41798f81035d1aed275a412f514202b559f15907e3d7b5ad312
func _() {
	x := crypto.XChaCha20Poly1305
	var _ *crypto.Algorithm = &x
	_ = map[bool]int{false: 0, crypto.XChaCha20Poly1305 == "xchacha20poly1305": 1}
}
