load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "password",
    srcs = [
        "doc.go",
        "facade_gen.go",
        "password.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/crypto/password",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/crypto",
        "//internal/service/crypto/password/commonpw",
        "//internal/service/crypto/password/pbkdf2pw",
    ],
)

alias(
    name = "go_default_library",
    actual = ":password",
    visibility = ["//visibility:public"],
)

go_test(
    name = "password_test",
    srcs = [
        "api_gen_test.go",
        "password_bench_test.go",
        "password_external_test.go",
    ],
    deps = [":password"],
)
