// Code generated by kit from design/proc.yaml (sha256 fed56107ef01d02b7fc15ab89ee1fdbe2f6c8ef1e779eacb3a6ca7d3c43fa5bc, body 9483de243227564fe26089ccf2504aaac9b2b333f515fdaf9924900798ebf628). DO NOT EDIT.

package childwait

// Claim is a spawner's hold on one child's exit status. It is created by Spawn,
// filled by a sweep that collects the child, and ended by the owner once the
// status is in hand. A Claim is safe for concurrent use. A nil *Claim holds
// nothing: every method answers as for a claim no sweep ever filled.
type Claim struct {
	// book is the ledger that holds this claim.
	book *ledger
	// pid is the claimed child's process id, and the ledger key.
	pid int
	// collected reports that a sweep took the child and stored its status. It
	// and status are guarded by the ledger's mu.
	collected bool
	// status is the exit status the sweep collected, valid once collected.
	status StatusValue
}
