// Code generated by kit from design/data/codec/json.yaml (sha256 5bfea450ef098efa22443469b9bde48635952ba447e36ab06e80a5e9a0670a1d, body 4cd339b59135422f95361edbe27c401dad3c0470dce1a7720f148dfef5eede46). DO NOT EDIT.

package json

import (
	corejson "github.com/kitsunium/sdk/internal/core/data/codec/json"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// The error codes, range 0.3.2.*, declared in the core (ADR 0160).
const (
	// CodeMarshalFailed identifies a value encoding/json could not encode (0.3.2.1).
	CodeMarshalFailed errs.Code = corejson.CodeJSONMarshalFailed
	// CodeUnmarshalFailed identifies input that is not JSON the target can hold (0.3.2.2).
	CodeUnmarshalFailed errs.Code = corejson.CodeJSONUnmarshalFailed
)

// The sentinels, for errors.Is: each carries the code of the same name.
var (
	// MarshalFailed is the sentinel of [CodeMarshalFailed].
	MarshalFailed = corejson.MarshalFailed
	// UnmarshalFailed is the sentinel of [CodeUnmarshalFailed].
	UnmarshalFailed = corejson.UnmarshalFailed
)
