// Code generated by kit from design/proc/ipc.yaml (sha256 86e32a0d9262ef53ce119f0773d7747968e56c4be7721554a31dd41fff7bcb8e, body 8d1223139a32e4f1afaf687df637f0d4a8f43485c86ee72f7c566a5f5c6cf9ea). DO NOT EDIT.

package ipc_test

import (
	"context"

	coreipc "github.com/kitsunium/sdk/internal/core/proc/ipc"
	"github.com/kitsunium/sdk/internal/kernel/errs"
	svcipc "github.com/kitsunium/sdk/internal/service/proc/ipc"
	"github.com/kitsunium/sdk/pkg/v1/proc/ipc"
)

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodeClosed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodeClosed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodeClosed == 0x00_03_5B_08: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodeDialFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodeDialFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodeDialFailed == 0x00_03_5B_06: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodeDirectoryUnsafe const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodeDirectoryUnsafe
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodeDirectoryUnsafe == 0x00_03_5B_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodeEndpointForeign const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodeEndpointForeign
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodeEndpointForeign == 0x00_03_5B_07: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodeInUse const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodeInUse
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodeInUse == 0x00_03_5B_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodeListenFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodeListenFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodeListenFailed == 0x00_03_5B_04: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodeMisconfigured const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodeMisconfigured
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodeMisconfigured == 0x00_03_5B_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodePathUnsafe const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodePathUnsafe
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodePathUnsafe == 0x00_03_5B_09: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.CodePeerRefused const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := ipc.CodePeerRefused
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, ipc.CodePeerRefused == 0x00_03_5B_05: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.Config alias github.com/kitsunium/sdk/internal/service/proc/ipc.Config
var _ *svcipc.Config = (*ipc.Config)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.Conn alias github.com/kitsunium/sdk/internal/core/proc/ipc.Conn
var _ *coreipc.Conn = (*ipc.Conn)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.Dial func func(ctx context.Context, cfg github.com/kitsunium/sdk/pkg/v1/proc/ipc.Config) (*github.com/kitsunium/sdk/pkg/v1/proc/ipc.Conn, error)
var _ func(ctx context.Context, cfg ipc.Config) (*ipc.Conn, error) = ipc.Dial

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.Dialer alias github.com/kitsunium/sdk/internal/core/proc/ipc.Dialer
var _ *coreipc.Dialer = (*ipc.Dialer)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.Listen func func(cfg github.com/kitsunium/sdk/pkg/v1/proc/ipc.Config) (github.com/kitsunium/sdk/pkg/v1/proc/ipc.Listener, error)
var _ func(cfg ipc.Config) (ipc.Listener, error) = ipc.Listen

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.Listener alias github.com/kitsunium/sdk/internal/core/proc/ipc.Listener
var _ *coreipc.Listener = (*ipc.Listener)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.NewDialer func func(cfg github.com/kitsunium/sdk/pkg/v1/proc/ipc.Config) (github.com/kitsunium/sdk/pkg/v1/proc/ipc.Dialer, error)
var _ func(cfg ipc.Config) (ipc.Dialer, error) = ipc.NewDialer

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.Peer alias github.com/kitsunium/sdk/internal/core/proc/ipc.PeerValue
var _ *coreipc.PeerValue = (*ipc.Peer)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/ipc.RuntimeDir func func(app string) string
var _ func(app string) string = ipc.RuntimeDir
