load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "logger",
    srcs = [
        "attr.go",
        "handler.go",
        "logger.go",
        "record.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/core/logger",
    visibility = ["//:__subpackages__"],
    deps = ["//internal/core/logger/level"],
)

alias(
    name = "go_default_library",
    actual = ":logger",
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "audit_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
