// Code generated by kit from design/observe/logger/writer.yaml (sha256 e9d1e81b585bb50f163e78f09cfc692d2c951d669d5d65b3edf440cf74e7606c, body e9ec853f9410ca122a1d97e0ae5b18b46ea3f0b6cd494995d144725f2fc66649). DO NOT EDIT.

package dbsink_test

// package github.com/kitsunium/sdk/internal/service/observe/logger/writer/dbsink doc:c226490d782f7edb40b80f4af0af7916393c7e88ef44ded9a0ea69bfaf6ea51e

import (
	"time"

	"github.com/kitsunium/sdk/internal/core/observe/logger/level"
	"github.com/kitsunium/sdk/internal/kernel/clock"
	"github.com/kitsunium/sdk/internal/service/observe/logger/writer/dbsink"
)

// go:github.com/kitsunium/sdk/internal/service/observe/logger/writer/dbsink.Compose func func(exec github.com/kitsunium/sdk/internal/service/observe/logger/writer/dbsink.execBatch, cfg github.com/kitsunium/sdk/internal/service/observe/logger/writer/dbsink.Config) github.com/kitsunium/sdk/internal/core/observe/logger.Sink doc:4cdab79fa6b43a03098e5c7790bb2b71e823b4e73529c9deee6350d6af74190f
var _ = dbsink.Compose

// go:github.com/kitsunium/sdk/internal/service/observe/logger/writer/dbsink.Config type struct{MaxRows int; FlushEvery time.Duration; MinLevel github.com/kitsunium/sdk/internal/core/observe/logger/level.Level; BufferSize int; OnDrop func(dropped int); OnError func(err error); Clock github.com/kitsunium/sdk/internal/kernel/clock.Clock} doc:182ab8fe91b2764c24c910e9f0d2c1cdb31554359c27e6e3ae95f17405374930
func _(x dbsink.Config) {
	var _ *int = &x.MaxRows
	var _ *time.Duration = &x.FlushEvery
	var _ *level.Level = &x.MinLevel
	var _ *int = &x.BufferSize
	var _ *func(dropped int) = &x.OnDrop
	var _ *func(err error) = &x.OnError
	var _ *clock.Clock = &x.Clock
}
