load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "dbsink",
    srcs = [
        "dbsink.go",
        "dbsink_config.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/observe/logger/writer/dbsink",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/observe/logger",
        "//internal/core/observe/logger/level",
        "//internal/kernel/clock",
        "//internal/kernel/concur/batcher",
        "//internal/service/observe/logger/middleware/async",
        "//internal/service/observe/logger/writer/levelgate",
    ],
)

alias(
    name = "go_default_library",
    actual = ":dbsink",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "dbsink_test",
    srcs = [
        "dbsink_bench_test.go",
        "dbsink_config_external_test.go",
        "dbsink_internal_test.go",
    ],
    embed = [":dbsink"],
    deps = [
        "//internal/core/observe/logger",
        "//internal/core/observe/logger/level",
        "//internal/kernel/concur/batcher",
        "//internal/kernel/errs",
        "//internal/service/observe/logger",
        "//internal/service/observe/logger/encoder",
        "//internal/service/observe/logger/middleware/async",
    ],
)
