load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "listen",
    srcs = [
        "facade_gen.go",
        "sdlisten.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/proc/systemd/listen",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/proc",
        "//internal/service/proc/systemd/listen",
    ],
)

alias(
    name = "go_default_library",
    actual = ":listen",
    visibility = ["//visibility:public"],
)

go_test(
    name = "listen_test",
    srcs = [
        "api_gen_test.go",
        "sdlisten_external_test.go",
        "sdlisten_other_test.go",
    ],
    deps = [
        ":listen",
        "//internal/core/proc",
    ] + select({
        "@rules_go//go/platform:js": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:osx": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:plan9": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:qnx": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:windows": [
            "//internal/kernel/errs",
        ],
        "//conditions:default": [],
    }),
)
