// Code generated by kit from design/data/codec.yaml (sha256 8066d02d5d769ca31c445c23c896e803d2742891d5a74ac31e264269c170227d, body 97296cfae784158ad5277299f319f33d3eeabf7e2c9c4b790b6a023cecaa347c). DO NOT EDIT.

package jsonshape_test

import (
	"reflect"

	"github.com/kitsunium/sdk/internal/service/data/codec/jsonshape"
)

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Any const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Any
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Any == 0: 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Array const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Array
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Array == 2: 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Boolean const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Boolean
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Boolean == 7: 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.FieldValue type struct{Name string "json:\"name\""; Shape *github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.ShapeValue "json:\"shape\""; Optional bool "json:\"optional,omitempty\""; Quoted bool "json:\"quoted,omitempty\""; Rules string "json:\"rules,omitempty\""; GoName string "json:\"-\""; Tag reflect.StructTag "json:\"-\""; Index []int "json:\"-\""}
func _(x jsonshape.FieldValue) {
	var _ *string = &x.Name
	var _ **jsonshape.ShapeValue = &x.Shape
	var _ *bool = &x.Optional
	var _ *bool = &x.Quoted
	var _ *string = &x.Rules
	var _ *string = &x.GoName
	var _ *reflect.StructTag = &x.Tag
	var _ *[]int = &x.Index
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.For[...] func func[T any]() *github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.ShapeValue
func _[T any]() {
	var _ func() *jsonshape.ShapeValue = jsonshape.For[T]
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Integer const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Integer
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Integer == 5: 1}
}

func kitPinKind[X ~uint8]() {}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind type uint8
var _ = kitPinKind[jsonshape.Kind]

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind.MarshalText method func() ([]byte, error)
var _ func(jsonshape.Kind) ([]byte, error) = jsonshape.Kind.MarshalText

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind.String method func() string
var _ func(jsonshape.Kind) string = jsonshape.Kind.String

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Map const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Map
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Map == 3: 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Number const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Number
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Number == 6: 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Object const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Object
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Object == 1: 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Of func func(t reflect.Type) *github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.ShapeValue
var _ func(t reflect.Type) *jsonshape.ShapeValue = jsonshape.Of

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.ShapeValue type struct{Kind github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind "json:\"kind\""; Name string "json:\"name,omitempty\""; Format string "json:\"format,omitempty\""; Nullable bool "json:\"nullable,omitempty\""; Fields []github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.FieldValue "json:\"fields,omitempty\""; Items *github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.ShapeValue "json:\"items,omitempty\""; Values *github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.ShapeValue "json:\"values,omitempty\""; Ref string "json:\"ref,omitempty\""}
func _(x jsonshape.ShapeValue) {
	var _ *jsonshape.Kind = &x.Kind
	var _ *string = &x.Name
	var _ *string = &x.Format
	var _ *bool = &x.Nullable
	var _ *[]jsonshape.FieldValue = &x.Fields
	var _ **jsonshape.ShapeValue = &x.Items
	var _ **jsonshape.ShapeValue = &x.Values
	var _ *string = &x.Ref
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.String const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.String
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.String == 4: 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Unsupported const github.com/kitsunium/sdk/internal/service/data/codec/jsonshape.Kind
func _() {
	x := jsonshape.Unsupported
	var _ *jsonshape.Kind = &x
	_ = map[bool]int{false: 0, jsonshape.Unsupported == 8: 1}
}
