// Code generated by kit from design/observe/logger.yaml (sha256 8da0f4de0bb2c78d79ca19c19b00a4b90cfaaa212b37ebc0e03022b9b8ee72f5, body 2afde2eb5be49bce2981b15c9d04e597768576eb009b90817f82362573271525). DO NOT EDIT.

package logger

import "github.com/kitsunium/sdk/internal/kernel/errs"

// range: 1.1.0.0 - 1.1.0.255

// CodeWriterRequired identifies a NewText call with Config.Writer == nil;
// the v1 façade refuses to default silently to stderr.
const CodeWriterRequired errs.Code = 0x01_01_00_01 // 1.1.0.1

// CodeSinkConfigRequired identifies a NewWithSink call with
// SinkConfig.Sink == nil; the v1 façade refuses to default silently to
// a console sink so callers see the misconfiguration immediately. The
// identifier is qualified with "Config" so the AST audit can distinguish
// it from the service-layer sink/handler validation (0.3.1.4).
const CodeSinkConfigRequired errs.Code = 0x01_01_00_02 // 1.1.0.2

// CodeWriterSpecInvalid identifies a NewMulti call with no WriterSpec entries;
// the façade refuses to build a logger that fans out to nothing (ADR 0012).
const CodeWriterSpecInvalid errs.Code = 0x01_01_00_03 // 1.1.0.3

// CodeTopologyInvalid identifies a FromConfig call whose config blob is
// malformed, names an unregistered writer, or whose Factory/DecodeConfig
// rejected its options. The error path is redacted: it names only the writer
// and the failure kind, never any decoded credential or option value (ADR 0014).
const CodeTopologyInvalid errs.Code = 0x01_01_00_04 // 1.1.0.4

var (
	// WriterRequired is returned when NewText is called with Config.Writer==nil.
	// Callers that want the "stderr convenience" use Default() instead.
	WriterRequired = errs.Define(CodeWriterRequired, "WRITER_REQUIRED",
		"Logger config requires an explicit writer",
		"pkg/v1/observe/logger.NewText called with Config.Writer==nil; supply an io.Writer or use logger.Default()")

	// SinkConfigRequired is returned when NewWithSink is called with
	// SinkConfig.Sink==nil. Callers that want a console sink use
	// logger.ConsoleStderr / ConsoleStdout or stick to logger.Default()
	// for the legacy text-on-stderr wiring.
	SinkConfigRequired = errs.Define(CodeSinkConfigRequired, "SINK_CONFIG_REQUIRED",
		"Logger SinkConfig requires an explicit sink",
		"pkg/v1/observe/logger.NewWithSink called with SinkConfig.Sink==nil; supply a Sink or use logger.Default()")

	// WriterSpecInvalid is returned when NewMulti is called with zero
	// WriterSpec entries. Supply at least one named writer (and blank-import
	// its package) so the fan-out has a destination.
	WriterSpecInvalid = errs.Define(CodeWriterSpecInvalid, "WRITER_SPEC_INVALID",
		"NewMulti requires at least one writer spec",
		"pkg/v1/observe/logger.NewMulti called with no WriterSpec entries; supply at least one named writer")

	// TopologyInvalid is returned by FromConfig when the config blob cannot be
	// decoded, names a writer no imported package has registered, or a writer's
	// Factory/DecodeConfig rejected its options. The message is redacted: it
	// names only the writer and the failure kind, never a decoded credential or
	// option value (the SECRET GATE of ADR 0014 §D5).
	TopologyInvalid = errs.Define(CodeTopologyInvalid, "TOPOLOGY_INVALID",
		"Logger topology config is invalid",
		"pkg/v1/observe/logger.FromConfig: blob undecodable, unknown writer name, or a writer rejected its options (option values redacted)")
)
