// Code generated by kit from design/data/codec/bson.yaml (sha256 e77ac102be2a87d4a23911e611374e2283a10c7afdc1e156ba56884b3ed9f0b7, body d7b25c3a8a9b477b4546a4be27d96b991f2eef6747072a3cf1a661ccef3a3b85). DO NOT EDIT.

package bson_test

import (
	"time"

	"github.com/kitsunium/sdk/internal/kernel/errs"
	svcbson "github.com/kitsunium/sdk/internal/service/data/codec/bson"
	"github.com/kitsunium/sdk/pkg/v1/data/codec/bson"
)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.A alias github.com/kitsunium/sdk/internal/service/data/codec/bson.A
var _ *svcbson.A = (*bson.A)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Append func func(dst []byte, v any) ([]byte, error)
var _ func(dst []byte, v any) ([]byte, error) = bson.Append

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Binary alias github.com/kitsunium/sdk/internal/service/data/codec/bson.Binary
var _ *svcbson.Binary = (*bson.Binary)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryColumn const byte
func _() {
	x := bson.BinaryColumn
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryColumn == 0x07: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryEncrypted const byte
func _() {
	x := bson.BinaryEncrypted
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryEncrypted == 0x06: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryFunction const byte
func _() {
	x := bson.BinaryFunction
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryFunction == 0x01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryGeneric const byte
func _() {
	x := bson.BinaryGeneric
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryGeneric == 0x00: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryMD5 const byte
func _() {
	x := bson.BinaryMD5
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryMD5 == 0x05: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryOld const byte
func _() {
	x := bson.BinaryOld
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryOld == 0x02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinarySensitive const byte
func _() {
	x := bson.BinarySensitive
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinarySensitive == 0x08: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryUUID const byte
func _() {
	x := bson.BinaryUUID
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryUUID == 0x04: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryUUIDOld const byte
func _() {
	x := bson.BinaryUUIDOld
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryUUIDOld == 0x03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryUserDefined const byte
func _() {
	x := bson.BinaryUserDefined
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryUserDefined == 0x80: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.BinaryVector const byte
func _() {
	x := bson.BinaryVector
	var _ *byte = &x
	_ = map[bool]int{false: 0, bson.BinaryVector == 0x09: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.CodeDepthExceeded const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := bson.CodeDepthExceeded
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeDepthExceeded == 0x00_03_24_04: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.CodeMarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := bson.CodeMarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeMarshalFailed == 0x00_03_24_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.CodeSizeExceeded const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := bson.CodeSizeExceeded
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeSizeExceeded == 0x00_03_24_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.CodeUnmarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := bson.CodeUnmarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeUnmarshalFailed == 0x00_03_24_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.CodeValueInvalid const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := bson.CodeValueInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeValueInvalid == 0x00_03_24_05: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.CodeWithScope alias github.com/kitsunium/sdk/internal/service/data/codec/bson.CodeWithScope
var _ *svcbson.CodeWithScope = (*bson.CodeWithScope)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.D alias github.com/kitsunium/sdk/internal/service/data/codec/bson.D
var _ *svcbson.D = (*bson.D)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.DBPointer alias github.com/kitsunium/sdk/internal/service/data/codec/bson.DBPointer
var _ *svcbson.DBPointer = (*bson.DBPointer)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.DateTime alias github.com/kitsunium/sdk/internal/service/data/codec/bson.DateTime
var _ *svcbson.DateTime = (*bson.DateTime)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Decimal128 alias github.com/kitsunium/sdk/internal/service/data/codec/bson.Decimal128
var _ *svcbson.Decimal128 = (*bson.Decimal128)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.DepthExceeded var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &bson.DepthExceeded

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.E alias github.com/kitsunium/sdk/internal/service/data/codec/bson.E
var _ *svcbson.E = (*bson.E)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Format const untyped string
func _() {
	type untyped string
	var _ untyped = bson.Format
	_ = map[bool]int{false: 0, bson.Format == "bson": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.JavaScript alias github.com/kitsunium/sdk/internal/service/data/codec/bson.JavaScript
var _ *svcbson.JavaScript = (*bson.JavaScript)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.M alias github.com/kitsunium/sdk/internal/service/data/codec/bson.M
var _ *svcbson.M = (*bson.M)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Marshal func func(v any) ([]byte, error)
var _ func(v any) ([]byte, error) = bson.Marshal

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.MarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &bson.MarshalFailed

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.MaxKey alias github.com/kitsunium/sdk/internal/service/data/codec/bson.MaxKey
var _ *svcbson.MaxKey = (*bson.MaxKey)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.MinKey alias github.com/kitsunium/sdk/internal/service/data/codec/bson.MinKey
var _ *svcbson.MinKey = (*bson.MinKey)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.NewDateTimeFromTime func func(t time.Time) github.com/kitsunium/sdk/pkg/v1/data/codec/bson.DateTime
var _ func(t time.Time) bson.DateTime = bson.NewDateTimeFromTime

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.NewDecimal128 func func(high uint64, low uint64) github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Decimal128
var _ func(high, low uint64) bson.Decimal128 = bson.NewDecimal128

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.NilObjectID var github.com/kitsunium/sdk/pkg/v1/data/codec/bson.ObjectID
var _ *bson.ObjectID = &bson.NilObjectID

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Null alias github.com/kitsunium/sdk/internal/service/data/codec/bson.Null
var _ *svcbson.Null = (*bson.Null)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.ObjectID alias github.com/kitsunium/sdk/internal/service/data/codec/bson.ObjectID
var _ *svcbson.ObjectID = (*bson.ObjectID)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.ObjectIDFromHex func func(s string) (github.com/kitsunium/sdk/pkg/v1/data/codec/bson.ObjectID, error)
var _ func(s string) (bson.ObjectID, error) = bson.ObjectIDFromHex

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.ParseDecimal128 func func(s string) (github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Decimal128, error)
var _ func(s string) (bson.Decimal128, error) = bson.ParseDecimal128

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Regex alias github.com/kitsunium/sdk/internal/service/data/codec/bson.Regex
var _ *svcbson.Regex = (*bson.Regex)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.SizeExceeded var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &bson.SizeExceeded

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Symbol alias github.com/kitsunium/sdk/internal/service/data/codec/bson.Symbol
var _ *svcbson.Symbol = (*bson.Symbol)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Timestamp alias github.com/kitsunium/sdk/internal/service/data/codec/bson.Timestamp
var _ *svcbson.Timestamp = (*bson.Timestamp)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Undefined alias github.com/kitsunium/sdk/internal/service/data/codec/bson.Undefined
var _ *svcbson.Undefined = (*bson.Undefined)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.Unmarshal func func(data []byte, v any) error
var _ func(data []byte, v any) error = bson.Unmarshal

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.UnmarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &bson.UnmarshalFailed

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/bson.ValueInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &bson.ValueInvalid
