load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "bson",
    srcs = ["bson.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/bson",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/kernel/errs",
        "//internal/service/data/codec/bson",
    ],
)

alias(
    name = "go_default_library",
    actual = ":bson",
    visibility = ["//visibility:public"],
)

go_test(
    name = "bson_test",
    srcs = ["bson_external_test.go"],
    deps = [
        ":bson",
        "//internal/core/data/codec",
        "//pkg/v1/config",
        "//pkg/v1/errs",
    ],
)
