// Code generated by kit from design/kernel/concur.yaml (sha256 e45acc291d0f218ac1d1cb5bae17540a7158bba4af6612959ae235ae6f064f18, body 77227989cd399d4d0669abfe214135eba2019a97f82ae8bddacdaf420a16d92a). DO NOT EDIT.

package batcher_test

import (
	kbatcher "github.com/kitsunium/sdk/internal/kernel/concur/batcher"
	"github.com/kitsunium/sdk/pkg/v1/concur/batcher"
)

// go:github.com/kitsunium/sdk/pkg/v1/concur/batcher.Batcher alias [T any] github.com/kitsunium/sdk/internal/kernel/concur/batcher.Batcher[T]
func _[T any]() {
	var _ *kbatcher.Batcher[T] = (*batcher.Batcher[T])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/concur/batcher.BatcherClosed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &batcher.BatcherClosed
	x = &kbatcher.BatcherClosed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/concur/batcher.BatcherDeliverFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &batcher.BatcherDeliverFailed
	x = &kbatcher.BatcherClosed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/concur/batcher.Config alias [T any] github.com/kitsunium/sdk/internal/kernel/concur/batcher.Config[T]
func _[T any]() {
	var _ *kbatcher.Config[T] = (*batcher.Config[T])(nil)
}

// go:github.com/kitsunium/sdk/pkg/v1/concur/batcher.NewBatcher[...] func func[T any](deliver github.com/kitsunium/sdk/pkg/v1/concur/batcher.Sink[T], cfg github.com/kitsunium/sdk/pkg/v1/concur/batcher.Config[T]) *github.com/kitsunium/sdk/pkg/v1/concur/batcher.Batcher[T]
func _[T any]() {
	var _ func(deliver batcher.Sink[T], cfg batcher.Config[T]) *batcher.Batcher[T] = batcher.NewBatcher[T]
}

// go:github.com/kitsunium/sdk/pkg/v1/concur/batcher.Sink alias [T any] github.com/kitsunium/sdk/internal/kernel/concur/batcher.Sink[T]
func _[T any]() {
	var _ *kbatcher.Sink[T] = (*batcher.Sink[T])(nil)
}
