// Code generated by kit from design/kernel/concur.yaml (sha256 c21ba407fd9c0c6592e2623967cb478d018ec5183e677dbaac9a9e3e81f0d188, body 6db15788c61930d740cd1e2dc769af1a8bd76a9aeb36c97815bf8aeabd784bd4). DO NOT EDIT.

package batcher

import kbatcher "github.com/kitsunium/sdk/internal/kernel/concur/batcher"

// Batcher coalesces added items into batches delivered through its [Sink].
//
// [Batcher].Add appends an item and delivers the batch at once when a cap is
// reached; [Batcher].Flush delivers what is pending; [Batcher].Close stops the
// ticker, delivers what is pending with the context it is given, and closes
// the batcher — idempotently, a second Close returning nil. Each takes a
// context and returns the delivery's error, wrapped as
// [BatcherDeliverFailed], or [BatcherClosed] after Close.
type Batcher[T any] = kbatcher.Batcher[T]

// Config tunes a [Batcher]: MaxItems and MaxWeight, the caps that deliver
// eagerly (non-positive disables each); WeightOf, an item's weight (nil counts
// items); FlushEvery, the background delivery interval (non-positive starts no
// ticker); Clock, the clock.Waiter that ticker runs on (nil is the wall
// clock); and OnError, which observes the ticker path's failures (nil ignores
// them). The zero Config is usable.
type Config[T any] = kbatcher.Config[T]

// Sink delivers one coalesced batch. A non-nil error fails the batch: it is
// returned to the caller of Add, Flush or Close that triggered the delivery,
// and handed to [Config].OnError on the ticker path. A Sink is never entered
// concurrently.
type Sink[T any] = kbatcher.Sink[T]

// NewBatcher builds a [Batcher] over deliver with cfg. A positive
// cfg.FlushEvery spawns the ticker goroutine, which Close joins.
func NewBatcher[T any](deliver Sink[T], cfg Config[T]) *Batcher[T] {
	return kbatcher.NewBatcher(deliver, cfg)
}

// The sentinels a caller matches with errors.Is or errs.HasCode.
var (
	// BatcherClosed is returned by Add and Flush once Close has run: the
	// batcher accepts no more items, and its ticker, if any, has been joined.
	BatcherClosed = kbatcher.BatcherClosed

	// BatcherDeliverFailed wraps the error a deliver function returned, so a
	// caller routes on one code while the original cause stays reachable
	// through errors.Is and errors.As.
	BatcherDeliverFailed = kbatcher.BatcherDeliverFailed
)
