load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "jsonpatch",
    srcs = ["jsonpatch.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/codec/jsonpatch",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/kernel/errs",
        "//internal/service/codec/jsonpatch",
    ],
)

alias(
    name = "go_default_library",
    actual = ":jsonpatch",
    visibility = ["//visibility:public"],
)

go_test(
    name = "jsonpatch_test",
    srcs = ["jsonpatch_external_test.go"],
    deps = [
        ":jsonpatch",
        "//pkg/v1/errs",
    ],
)
