// Code generated by kit from design/proc.yaml (sha256 f6f7644eb6f21da80a05f3358ba2b5c2796a7d07076480c8919168b289cf4994, body 714bc8ccb2abac9a7845d778865328368e00be95d53ee2bfbdd24f1826c1d49e). DO NOT EDIT.

package process_test

import (
	"context"
	"runtime/debug"

	coreproc "github.com/kitsunium/sdk/internal/core/proc"
	svcself "github.com/kitsunium/sdk/internal/service/proc/self"
	"github.com/kitsunium/sdk/pkg/v1/proc/process"
)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Build func func() (info github.com/kitsunium/sdk/pkg/v1/proc/process.BuildInfo, ok bool)
var _ func() (info process.BuildInfo, ok bool) = process.Build

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.BuildInfo alias github.com/kitsunium/sdk/internal/service/proc/self.BuildValue
var _ *svcself.BuildValue = (*process.BuildInfo)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Distribution alias github.com/kitsunium/sdk/internal/service/proc/self.DistributionValue
var _ *svcself.DistributionValue = (*process.Distribution)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.ExitResult alias github.com/kitsunium/sdk/internal/core/proc.ExitValue
var _ *coreproc.ExitValue = (*process.ExitResult)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Limit alias github.com/kitsunium/sdk/internal/core/proc.LimitValue
var _ *coreproc.LimitValue = (*process.Limit)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Module alias github.com/kitsunium/sdk/internal/service/proc/self.ModuleValue
var _ *svcself.ModuleValue = (*process.Module)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.MustStart func func(ctx context.Context, spec github.com/kitsunium/sdk/pkg/v1/proc/process.Spec) github.com/kitsunium/sdk/pkg/v1/proc/process.Process
var _ func(ctx context.Context, spec process.Spec) process.Process = process.MustStart

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.ParseBuild func func(info *runtime/debug.BuildInfo) github.com/kitsunium/sdk/pkg/v1/proc/process.BuildInfo
var _ func(info *debug.BuildInfo) process.BuildInfo = process.ParseBuild

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Process alias github.com/kitsunium/sdk/internal/core/proc.Process
var _ *coreproc.Process = (*process.Process)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Resource alias github.com/kitsunium/sdk/internal/core/proc.Resource
var _ *coreproc.Resource = (*process.Resource)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.ResourceAS const github.com/kitsunium/sdk/pkg/v1/proc/process.Resource
func _() {
	x := process.ResourceAS
	var _ *process.Resource = &x
	_ = map[bool]int{false: 0, process.ResourceAS == 4: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.ResourceCPU const github.com/kitsunium/sdk/pkg/v1/proc/process.Resource
func _() {
	x := process.ResourceCPU
	var _ *process.Resource = &x
	_ = map[bool]int{false: 0, process.ResourceCPU == 5: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.ResourceCore const github.com/kitsunium/sdk/pkg/v1/proc/process.Resource
func _() {
	x := process.ResourceCore
	var _ *process.Resource = &x
	_ = map[bool]int{false: 0, process.ResourceCore == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.ResourceNoFile const github.com/kitsunium/sdk/pkg/v1/proc/process.Resource
func _() {
	x := process.ResourceNoFile
	var _ *process.Resource = &x
	_ = map[bool]int{false: 0, process.ResourceNoFile == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.SIGHUP const github.com/kitsunium/sdk/pkg/v1/proc/process.Signal
func _() {
	x := process.SIGHUP
	var _ *process.Signal = &x
	_ = map[bool]int{false: 0, process.SIGHUP == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.SIGINT const github.com/kitsunium/sdk/pkg/v1/proc/process.Signal
func _() {
	x := process.SIGINT
	var _ *process.Signal = &x
	_ = map[bool]int{false: 0, process.SIGINT == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.SIGKILL const github.com/kitsunium/sdk/pkg/v1/proc/process.Signal
func _() {
	x := process.SIGKILL
	var _ *process.Signal = &x
	_ = map[bool]int{false: 0, process.SIGKILL == 9: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.SIGQUIT const github.com/kitsunium/sdk/pkg/v1/proc/process.Signal
func _() {
	x := process.SIGQUIT
	var _ *process.Signal = &x
	_ = map[bool]int{false: 0, process.SIGQUIT == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.SIGTERM const github.com/kitsunium/sdk/pkg/v1/proc/process.Signal
func _() {
	x := process.SIGTERM
	var _ *process.Signal = &x
	_ = map[bool]int{false: 0, process.SIGTERM == 15: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Self func func() github.com/kitsunium/sdk/pkg/v1/proc/process.Stats
var _ func() process.Stats = process.Self

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Signal alias github.com/kitsunium/sdk/internal/core/proc.Signal
var _ *coreproc.Signal = (*process.Signal)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Spec alias github.com/kitsunium/sdk/internal/core/proc.Spec
var _ *coreproc.Spec = (*process.Spec)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Start func func(ctx context.Context, spec github.com/kitsunium/sdk/pkg/v1/proc/process.Spec) (proc github.com/kitsunium/sdk/pkg/v1/proc/process.Process, err error)
var _ func(ctx context.Context, spec process.Spec) (proc process.Process, err error) = process.Start

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.Stats alias github.com/kitsunium/sdk/internal/service/proc/self.StatsValue
var _ *svcself.StatsValue = (*process.Stats)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.StdioCapture const github.com/kitsunium/sdk/pkg/v1/proc/process.StdioMode
func _() {
	x := process.StdioCapture
	var _ *process.StdioMode = &x
	_ = map[bool]int{false: 0, process.StdioCapture == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.StdioInherit const github.com/kitsunium/sdk/pkg/v1/proc/process.StdioMode
func _() {
	x := process.StdioInherit
	var _ *process.StdioMode = &x
	_ = map[bool]int{false: 0, process.StdioInherit == 0: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.StdioMode alias github.com/kitsunium/sdk/internal/core/proc.StdioMode
var _ *coreproc.StdioMode = (*process.StdioMode)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/process.StdioNull const github.com/kitsunium/sdk/pkg/v1/proc/process.StdioMode
func _() {
	x := process.StdioNull
	var _ *process.StdioMode = &x
	_ = map[bool]int{false: 0, process.StdioNull == 1: 1}
}
