// Code generated by kit from design/data/transform.yaml (sha256 406ee3e9ca4a38fee05183d7aae4dbace7537b249fb5615ee1060408558a93b5, body 13121a78463ce4b509939f25175fd48e29cb334413e58724d42286c124af9ef1). DO NOT EDIT.

package transform

// Algorithm is the typed key under which a Compressor registers (e.g. "gzip",
// "flate", "zlib"). The zero value Algorithm("") is reserved invalid, mirroring
// codec.Format and crypto.Algorithm. Note that "flate" is the raw DEFLATE
// stream of RFC 1951 and "zlib" is the RFC 1950 envelope HTTP misnames
// "deflate" — distinct Algorithms, not aliases.
type Algorithm string

// Available returns the sorted list of registered Algorithms, or nil before
// any Register.
func Available() []Algorithm {
	return available()
}
