// Package sql implements the relational-database ports declared in
// internal/core/sql (ADR 0055): the transaction manager, the pool policy, the
// health check and the migration runner.
//
// It ships NO DRIVER and imports none. A driver is a connector to a
// third-party system, so pgx / go-sql-driver / the sqlite bindings belong
// under third-party/ by the rule that put the AWS writers there (ADR 0012).
// The caller opens its own *sql.DB and hands it over.
//
// It is also NOT an ORM, has no query builder, no entity mapping and no lazy
// loading, and never will (ADR 0055 §D1).
//
// # Transaction ownership is structural
//
// [NewTransactor] hands the unit of work a core/sql.Executor — three methods,
// none of which is Commit or Rollback. A function that receives a transaction
// therefore cannot end it: the mistake does not compile. The manager commits
// when the function returns nil and rolls back otherwise, and it is the only
// thing that ever does either.
//
// # Nesting is a savepoint, and the traps are handled rather than avoided
//
// database/sql has no nested transactions. A [core/sql.Transactor.Transact]
// whose context already carries a transaction from THIS manager opens a
// SAVEPOINT instead:
//
//   - The savepoint NAME is generated by the SDK from a counter that never
//     resets inside one transaction. It is never caller-supplied, because an
//     identifier cannot be a bound parameter; and it is never reused, because
//     a repeated name shadows rather than replaces, so RELEASE would release
//     the wrong one.
//   - The three statements are IDENTICAL on postgres, mysql and sqlite, which
//     is why those three are the supported set. Engines that spell nesting
//     differently are refused BY NAME at ParseDialect (ADR 0055 §D4).
//   - Non-zero [core/sql.TxOptionsValue] on a nested call is REFUSED: a
//     savepoint cannot change isolation or read-only mode, and silently
//     downgrading a caller's Serializable is worse than saying no.
//
// # What a failed sub-transaction does
//
// It rolls back to its savepoint and returns the error to the caller of the
// inner Transact — verbatim, so errors.Is still answers. The OUTER
// transaction survives, and that is not optimism: ROLLBACK TO SAVEPOINT is
// exactly the statement that clears PostgreSQL's aborted state (SQLSTATE
// 25P02), so a caller who CATCHES the inner error has a usable transaction to
// continue in. A caller who does not catch it propagates it, and the outer
// scope rolls back in turn — the common case, and the safe default.
//
// If the ROLLBACK TO SAVEPOINT statement itself fails, the transaction is
// POISONED: every later operation is refused with [TxPoisoned], the commit
// never happens, and the whole transaction is rolled back. The engine's state
// is unknown at that point, and committing work the SDK believes it undid is
// the one outcome worse than failing.
//
// # A partially applied migration, and what MySQL does to the guarantee
//
// Each migration runs in ITS OWN transaction, and the version-table row is
// written by that SAME transaction on that SAME executor. On PostgreSQL and
// SQLite — where DDL is transactional — that is a real guarantee: a migration
// that fails rolls back both halves, the database sits exactly at version
// n-1, and re-running is safe.
//
// On MySQL and MariaDB it is NOT, and the difference is not one this package
// can close. DDL causes an IMPLICIT COMMIT: the server has already committed
// the schema change before the runner's transaction reaches COMMIT. A
// migration whose second statement fails therefore leaves the first
// statement's ALTER TABLE applied and committed, while the version row — in
// the same transaction — is rolled back. The database is then in a state no
// version number describes.
//
// No client-side code can make MySQL's DDL transactional, so this package
// does three things instead of pretending: it says so (here, in the package
// CLAUDE.md, in pkg/v1/sql's doc and in MigrationFailed's Private), it stops
// at the first failure rather than continuing, and it reports the version and
// the direction so the migration to inspect by hand is named.
//
// The operational rule that follows is the CONSUMER's: one DDL statement per
// migration on MySQL, which makes the failure atomic by construction. This
// package cannot enforce it — it does not parse SQL — and does not pretend to.
// See ADR 0055 D8.
//
// # Nothing here waits on the wall clock
//
// Every budget — the health-check probe, the migration-lock retry — is read
// from an injected kernel/clock.Timed, so the suite advances a ManualClock
// instead of sleeping.
package sql

import (
	"errors"

	kerrs "github.com/kitsunium/sdk/internal/kernel/errs"
)

// failed returns the SDK's verdict for a driver-level failure, side by side
// with the driver's own error.
//
// errors.Join rather than errs.Wrap, for the reason ADR 0050 gives: origin-wins
// (CLAUDE.md rule 6) would make the driver's error the origin and relabel the
// SDK's verdict with whatever code the driver happened to carry. Side by side,
// errs.HasCode(err, CodeCommitFailed) and the caller's own
// errors.Is(err, driver.ErrBadConn) both answer.
//
// The driver's error is never read into a Public: the verdict's own Public is
// a fixed literal, and the join only affects Error() and errors.Is.
func failed(sentinel *kerrs.Error, cause error, fields ...kerrs.FieldValue) error {
	//: the SDK's verdict carries the code, the reason and the wire-safe text.
	verdict := kerrs.Wrap(sentinel, kerrs.WrapParams{}, fields...)
	//: a refusal with no driver behind it stands alone.
	if cause == nil {
		//: one error, one code.
		return verdict
	}
	//: both, so neither question loses its answer.
	return errors.Join(verdict, cause)
}
