load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "toml",
    srcs = [
        "doc.go",
        "facade_gen.go",
        "toml.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/toml",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/data/codec/toml",
        "//internal/kernel/errs",
        "//internal/service/data/codec/toml",
    ],
)

alias(
    name = "go_default_library",
    actual = ":toml",
    visibility = ["//visibility:public"],
)

go_test(
    name = "toml_test",
    srcs = [
        "api_gen_test.go",
        "toml_external_test.go",
    ],
    deps = [
        ":toml",
        "//internal/core/data/codec",
        "//internal/kernel/errs",
        "//internal/service/data/codec/toml",
        "//pkg/v1/app/config",
        "//pkg/v1/errs",
    ],
)
