// Code generated by kit from design/observe/metrics.yaml (sha256 fadae848ce9a826193a28b7308b640628daeb59110a564d58430357c20d440a0, body bbf4cdde28e157665a89ee3d7a57aef0ced1e93aeca335dd11d3e1cf35e06824). DO NOT EDIT.

package metrics_test

// package github.com/kitsunium/sdk/internal/service/observe/metrics doc:8f97a913c775890d751cc5144a369ff887a166eec10506c7e5b75be9042ec71d

import (
	"io"
	"net/http"
	"time"

	coremetrics "github.com/kitsunium/sdk/internal/core/observe/metrics"
	coreotel "github.com/kitsunium/sdk/internal/core/observe/otel"
	"github.com/kitsunium/sdk/internal/kernel/clock"
	"github.com/kitsunium/sdk/internal/service/observe/metrics"
)

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.DefaultMaxSeriesPerInstrument const int doc:6bdf6c0ddb134a77a983c4b8666cd1faed7d41d1b363893322981968ce73ae81
func _() {
	x := metrics.DefaultMaxSeriesPerInstrument
	var _ *int = &x
	_ = map[bool]int{false: 0, metrics.DefaultMaxSeriesPerInstrument == 2000: 1}
}

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.DefaultOTLPMaxResponseBytes const int64 doc:b322704b01b56f74f83e907915670927fac404f275018b84de69c08fa334ac30
func _() {
	x := metrics.DefaultOTLPMaxResponseBytes
	var _ *int64 = &x
	_ = map[bool]int{false: 0, metrics.DefaultOTLPMaxResponseBytes == (1 << 20): 1}
}

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.DefaultOTLPTimeout const time.Duration doc:313e48a2ab884d16e90147e51858c54cb348d3806e7e45522642ceb5a665dc92
func _() {
	x := metrics.DefaultOTLPTimeout
	var _ *time.Duration = &x
	_ = map[bool]int{false: 0, metrics.DefaultOTLPTimeout == 10000000000: 1}
}

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.EncodeOTLPJSON func func(snap github.com/kitsunium/sdk/internal/core/observe/metrics.SnapshotValue) (doc []byte, err error) doc:ae06109277f24177e20f577a00292709c04f6bc0cf655e4a27e2c10fc57d8493
var _ func(snap coremetrics.SnapshotValue) (doc []byte, err error) = metrics.EncodeOTLPJSON

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.MeterConfig type struct{MaxSeriesPerInstrument int; Temporality github.com/kitsunium/sdk/internal/core/observe/metrics.Temporality; Resource github.com/kitsunium/sdk/internal/core/observe/otel.ResourceValue; Scope github.com/kitsunium/sdk/internal/core/observe/otel.ScopeValue; Clock github.com/kitsunium/sdk/internal/kernel/clock.Clock} doc:f6390dd6e31cce24c782fb2490251828d15419c17cfd98bd3dbe5cb397c6a8b0
func _(x metrics.MeterConfig) {
	var _ *int = &x.MaxSeriesPerInstrument
	var _ *coremetrics.Temporality = &x.Temporality
	var _ *coreotel.ResourceValue = &x.Resource
	var _ *coreotel.ScopeValue = &x.Scope
	var _ *clock.Clock = &x.Clock
}

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.NewMeter func func() github.com/kitsunium/sdk/internal/core/observe/metrics.FullMeter doc:a8d3dc5761e4752214a1422b57f54d38f22eee83dfd285129fc3b868067bf635
var _ func() coremetrics.FullMeter = metrics.NewMeter

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.NewMeterWithConfig func func(cfg github.com/kitsunium/sdk/internal/service/observe/metrics.MeterConfig) github.com/kitsunium/sdk/internal/core/observe/metrics.FullMeter doc:144acb1b10781e6d75802d4e79cf6858f00d39fbae12c77498bc40744a7ca101
var _ func(cfg metrics.MeterConfig) coremetrics.FullMeter = metrics.NewMeterWithConfig

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.NewOTLPHTTPExporter func func(name github.com/kitsunium/sdk/internal/core/observe/metrics.ExporterName, cfg github.com/kitsunium/sdk/internal/service/observe/metrics.OTLPHTTPConfig) (exporter github.com/kitsunium/sdk/internal/core/observe/metrics.Exporter, err error) doc:d2941c098dbc81de2b014520382b8273f0437598ffc07bd0fd9e1787762c7ee8
var _ func(name coremetrics.ExporterName, cfg metrics.OTLPHTTPConfig) (exporter coremetrics.Exporter, err error) = metrics.NewOTLPHTTPExporter

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.NewOTLPJSONExporter func func(name github.com/kitsunium/sdk/internal/core/observe/metrics.ExporterName, dst io.Writer) github.com/kitsunium/sdk/internal/core/observe/metrics.Exporter doc:5a1d7120f482a850a0cd5bbdad9b1c6284af8997f64a3282e763b0dde422effa
var _ func(name coremetrics.ExporterName, dst io.Writer) coremetrics.Exporter = metrics.NewOTLPJSONExporter

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.NewPrometheusExporter func func(name github.com/kitsunium/sdk/internal/core/observe/metrics.ExporterName, dst io.Writer) github.com/kitsunium/sdk/internal/core/observe/metrics.Exporter doc:87234ad71d013fd984fa014d933a51ab9c6f80a1008dfe17f572368addd894aa
var _ func(name coremetrics.ExporterName, dst io.Writer) coremetrics.Exporter = metrics.NewPrometheusExporter

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.NewTextExporter func func(name github.com/kitsunium/sdk/internal/core/observe/metrics.ExporterName, dst io.Writer) github.com/kitsunium/sdk/internal/core/observe/metrics.Exporter doc:460c7d23fe5035159d6e1218e3b69f5b33ac3019ec787381a11328c47e7d42d6
var _ func(name coremetrics.ExporterName, dst io.Writer) coremetrics.Exporter = metrics.NewTextExporter

func kitPinOTLPHTTPConfig[X ~struct {
	Endpoint         string
	Client           *http.Client
	Headers          map[string]string
	Timeout          time.Duration
	MaxResponseBytes int64
}]() {
}

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.OTLPHTTPConfig type struct{Endpoint string; Client *net/http.Client; Headers map[string]string; Timeout time.Duration; MaxResponseBytes int64} doc:cb2bfd3c88b95aefa78a1428f389cc57cc3b8cf4a5ad45177768e86f36a6fdb5
var _ = kitPinOTLPHTTPConfig[metrics.OTLPHTTPConfig]

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.OTLPJSON var github.com/kitsunium/sdk/internal/core/observe/metrics.Exporter doc:1ba5b79c4f4ee0b2ee1d7f2839b87af3f3439591005ac6a927ed9be62fc80801
var _ *coremetrics.Exporter = &metrics.OTLPJSON

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.OTLPMetricsPath const string doc:14f649a92a19a0877a091fed59df97921cfdaa84844a939514ba7036492f2337
func _() {
	x := metrics.OTLPMetricsPath
	var _ *string = &x
	_ = map[bool]int{false: 0, metrics.OTLPMetricsPath == "/v1/metrics": 1}
}

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.OTLPRetryable func func(err error) bool doc:7fa76096db905adb6ca3e0f5a425098f08fbc5fdd4acbd50a5e30fb8172e7662
var _ func(err error) bool = metrics.OTLPRetryable

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.Prometheus var github.com/kitsunium/sdk/internal/core/observe/metrics.Exporter doc:5970a715c407f03d9f917182e69153a47aa74c558510a7b964951fec620005e7
var _ *coremetrics.Exporter = &metrics.Prometheus

// go:github.com/kitsunium/sdk/internal/service/observe/metrics.Text var github.com/kitsunium/sdk/internal/core/observe/metrics.Exporter doc:37e2047179e6410a89d0f063e0645deead9dff48beb307a742ac5f3c096e952c
var _ *coremetrics.Exporter = &metrics.Text
