// Code generated by kit from design/observe/metrics.yaml (sha256 17921d2d9ab2e12cffb22897b0a6a793db6e036f4890e194654207e72a44ea11, body e24a10b53fa4342043bee513f40e7c4254b437aa7bb7266e7675ce35f6772fdc). DO NOT EDIT.

package metrics

import (
	coremetrics "github.com/kitsunium/sdk/internal/core/observe/metrics"
	coreotel "github.com/kitsunium/sdk/internal/core/observe/otel"
	"github.com/kitsunium/sdk/internal/kernel/clock"
	"github.com/kitsunium/sdk/internal/service/observe/internal/otlp"
)

// MeterConfig configures a Meter. Every field has a resolved meaning when left
// unset — none of them is inert (ADR 0031).
type MeterConfig struct {
	// MaxSeriesPerInstrument bounds how many distinct attribute sets ONE
	// instrument name may hold. Beyond it, further sets fold into a single
	// aggregated overflow series rather than allocating — see
	// seriesStore.admit for that policy and what it costs.
	//
	// Non-positive CLAMPS to DefaultMaxSeriesPerInstrument. It does NOT mean
	// "unbounded", and there is no setting that does (ADR 0031): a caller who
	// leaves this zero has not decided that memory is free, they have not yet
	// learned the question exists, and the zero value must not be the
	// dangerous answer. A caller who genuinely wants a huge bound types a
	// huge number, and the number is then in their source where a reviewer
	// can see it.
	//
	// The bound is PER NAME rather than per meter so that one exploding
	// attribute on http_requests_total cannot starve db_queries_total of the
	// series it needs; each metric's failure stays its own.
	MaxSeriesPerInstrument int
	// Temporality says which window a collected sum or histogram covers.
	//
	// Unset CLAMPS to TemporalityCumulative, because that is what this meter
	// DOES when nothing tells it otherwise: it accumulates into atomics and
	// never resets them. TemporalityDelta makes Collect consume the window it
	// reports, which means a delta meter has exactly one reader — two
	// independent collectors would each receive part of the observations.
	// Any value that is neither of the three constants panics
	// (InvalidTemporality); it can only come from a cast.
	Temporality coremetrics.Temporality
	// Resource identifies the producer of the telemetry and is carried once
	// per snapshot. An absent service.name is filled with
	// coreotel.UnknownService, which is what the OpenTelemetry
	// specification mandates rather than a value this SDK invented.
	Resource coreotel.ResourceValue
	// Scope identifies the instrumentation that mints the instruments. An
	// empty Name resolves to coremetrics.DefaultScopeName; Version stays
	// empty when the caller has none, because it is optional in the
	// specification and inventing one would be a claim about code this
	// package cannot see.
	Scope coreotel.ScopeValue
	// Clock supplies the snapshot window's endpoints. Nil resolves to
	// clock.System, matching every other port in this SDK that takes one.
	// Only Now and Since are used, so the frozen two-method clock.Clock is
	// enough and a two-method test double still satisfies it (ADR 0039).
	Clock clock.Clock
}

// OTLPHTTPConfig configures an OTLP/HTTP exporter. Every field has a resolved
// meaning when left unset except Endpoint, which has none that could be right:
// a full URL used as-is, so a caller writes
// "http://collector:4318" + OTLPMetricsPath, and an endpoint that is not an
// absolute http(s) URL with a non-root path is REFUSED at construction
// (OTLPEndpointInvalid). Timeout clamps to DefaultOTLPTimeout and is ignored
// when Client is set; MaxResponseBytes clamps to DefaultOTLPMaxResponseBytes.
//
// It is a DEFINED type over the configuration of the transport both signals
// share (internal/service/observe/internal/otlp.HTTPConfig, where each field is
// documented once), not an alias of it: metrics.OTLPHTTPConfig and
// trace.OTLPHTTPConfig stay two types a caller cannot hand to the wrong
// signal's constructor.
type OTLPHTTPConfig otlp.HTTPConfig
