load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "file",
    srcs = ["file.go"],
    importpath = "github.com/kitsunium/sdk/internal/service/writer/file",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
        "//internal/core/writer",
        "//internal/kernel/errs",
        "//internal/service/logger/sink/file",
        "//internal/service/writer/levelgate",
    ],
)

alias(
    name = "go_default_library",
    actual = ":file",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "file_test",
    srcs = [
        "file_alloc_external_test.go",
        "file_external_test.go",
        "file_internal_test.go",
        "file_linux_bench_test.go",
    ],
    embed = [":file"],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
        "//internal/core/writer",
        "//internal/kernel/clock",
        "//internal/kernel/errs",
        "//internal/service/logger",
        "//internal/service/logger/encoder",
        "//internal/service/logger/sink/file",
    ],
)
