// Code generated by kit from design/data/codec/asn1.yaml (sha256 62f3427c51f841b69b24f9c6168f321b503d376f8d971a3f38f0eccb77656522, body 01a32c46f0e0284fafd2ee3bb97ffa44e9203dbe09d0034bda975c9b9d168039). DO NOT EDIT.

package asn1_test

import (
	"github.com/kitsunium/sdk/internal/kernel/errs"
	"github.com/kitsunium/sdk/pkg/v1/data/codec/asn1"
)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/asn1.CodeMarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := asn1.CodeMarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, asn1.CodeMarshalFailed == 0x00_03_09_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/asn1.CodeUnmarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := asn1.CodeUnmarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, asn1.CodeUnmarshalFailed == 0x00_03_09_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/asn1.Format const untyped string
func _() {
	type untyped string
	var _ untyped = asn1.Format
	_ = map[bool]int{false: 0, asn1.Format == "asn1-der": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/asn1.MarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &asn1.MarshalFailed

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/asn1.UnmarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &asn1.UnmarshalFailed
