load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "asn1",
    srcs = [
        "asn1.go",
        "facade_gen.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/asn1",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/data/codec/asn1",
        "//internal/kernel/errs",
        "//internal/service/data/codec/asn1",
    ],
)

alias(
    name = "go_default_library",
    actual = ":asn1",
    visibility = ["//visibility:public"],
)

go_test(
    name = "asn1_test",
    srcs = [
        "api_gen_test.go",
        "asn1_external_test.go",
    ],
    deps = [
        ":asn1",
        "//internal/core/data/codec",
        "//internal/kernel/errs",
        "//pkg/v1/errs",
    ],
)
