load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "yaml",
    srcs = ["yaml.go"],
    importpath = "github.com/kitsunium/sdk/framework/kit/config/yaml",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/internal/kit",
        "//pkg/v1/data/codec/yaml",
    ],
)

alias(
    name = "go_default_library",
    actual = ":yaml",
    visibility = ["//visibility:public"],
)
