// Code generated by kit from design/observe/logger/sink/file.yaml (sha256 4e07b6755d93fc0061efe0e3add36283bb67c5db06cbf3426a58e246364052c4, body e731097cec40d650d6963b1657c5aeb6215b22d547500f4f38dffc3112b9ee9c). DO NOT EDIT.

package file_test

import (
	corelogger "github.com/kitsunium/sdk/internal/core/observe/logger"
	"github.com/kitsunium/sdk/internal/service/observe/logger/sink/file"
)

// go:github.com/kitsunium/sdk/internal/service/observe/logger/sink/file.New func func(path string) (sink github.com/kitsunium/sdk/internal/core/observe/logger.Sink, err error)
var _ func(path string) (sink corelogger.Sink, err error) = file.New
