load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "client",
    srcs = [
        "conjunction.go",
        "deny_policy.go",
        "method_policy.go",
        "path.go",
        "path_policy.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/net/client",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/net",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":client",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)
