// Code generated by kit from design/framework/connectors/mysql.yaml (sha256 332f61d3d1c529a456b88e534f13eef6012a486d0eec98528cb0926cc56dac19, body 3f3a0ed00f152a779888c7b822e42dace45dc9237ef89e5ad2b05244215b150e). DO NOT EDIT.

package mysql_test

import (
	"github.com/kitsunium/sdk/framework/connectors/mysql"
	"github.com/kitsunium/sdk/framework/kit"
	"github.com/kitsunium/sdk/pkg/v1/errs"
)

// go:github.com/kitsunium/sdk/framework/connectors/mysql.CodeURLMalformed const github.com/kitsunium/sdk/pkg/v1/errs.Code
func _() {
	x := mysql.CodeURLMalformed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, mysql.CodeURLMalformed == 0x00_04_11_01: 1}
}

// go:github.com/kitsunium/sdk/framework/connectors/mysql.Engine func func() github.com/kitsunium/sdk/framework/kit.Engine
var _ func() kit.Engine = mysql.Engine
