load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "jsonpatch",
    srcs = ["jsonpatch.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/jsonpatch",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/data/codec/jsonpatch",
        "//internal/kernel/errs",
        "//internal/service/data/codec/jsonpatch",
    ],
)

alias(
    name = "go_default_library",
    actual = ":jsonpatch",
    visibility = ["//visibility:public"],
)

go_test(
    name = "jsonpatch_test",
    srcs = [
        "api_gen_test.go",
        "jsonpatch_external_test.go",
    ],
    deps = [
        ":jsonpatch",
        "//internal/kernel/errs",
        "//internal/service/data/codec/jsonpatch",
        "//pkg/v1/errs",
    ],
)
