load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "proc",
    srcs = ["capability.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/proc",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/proc",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":proc",
    visibility = ["//visibility:public"],
)

go_test(
    name = "proc_test",
    srcs = ["capability_test.go"],
    deps = [
        ":proc",
        "//pkg/v1/errs",
    ],
)
