// Code generated by kit from design/app/view.yaml (sha256 ae569ee0d52b1420a1dbbdeb2317f90d2d84671b0b4c0323ea7a53511e197e61, body 687839ec57a41176c107f8a6a593f3765e060e530cf2aba8dc303245095fe11b). DO NOT EDIT.

package view

import "io/fs"

// Config parameterises every [Factory]. It is deliberately small: this domain
// ships an extension point, not a template language.
type Config struct {
	// FS is the tree the templates are read from. Required.
	//
	// It is an fs.FS rather than a directory path so that embed.FS, os.DirFS
	// and fstest.MapFS are all first-class, and so that the domain never
	// touches the filesystem API. It also removes path traversal from the
	// problem statement: fs.ValidPath rejects "..", so no template name can
	// address a file outside the tree the caller handed over.
	//
	// Every regular file under FS is parsed, and each template is named by its
	// SLASH PATH relative to the root — "admin/page.html", not "page.html".
	// See [Factory] for why that is not a cosmetic choice.
	FS fs.FS
	// Ext optionally restricts which files are parsed, by extension including
	// the dot (".html", ".gohtml").
	//
	// Empty means every regular file in FS, which is the honest default: the
	// caller already chose the tree, and second-guessing its contents is the
	// SDK inventing a naming convention. Set it when templates share a
	// directory with assets.
	Ext []string
	// MaxBytes caps a single render's output. Not positive clamps to
	// [DefaultMaxBytes]; there is deliberately no spelling for "unlimited".
	//
	// The cap is the only bound that exists. text/template's Execute takes no
	// context, so a render cannot be cancelled, and the stdlib's own guard is a
	// recursion DEPTH limit (100000 frames) that says nothing about output
	// size: a {{range}} over an attacker-influenced collection has no depth at
	// all and will write until the machine stops. The same "no unbounded
	// setting" reasoning applies here as to the WebSocket ceilings in ADR 0047.
	MaxBytes int
}

// Engine names a registered template engine.
//
// The zero value is the reserved invalid name: [Register] refuses it at boot,
// so it can never reach [Lookup], [Open] or [Available].
type Engine string

// Available returns every registered [Engine], sorted, so a caller can print
// what its imports actually wired up. It is nil before any Register.
func Available() []Engine {
	return available()
}

// TrustHTML marks s as HTML that is already safe to write unescaped.
//
// Every call is an assertion that s was produced by the server and sanitised —
// a Markdown renderer's output, a fragment from a template the same program
// authored. It is never correct to hand it a string that arrived from a
// request, a database field a user controls, or a third-party API.
//
// The function exists because the conversion it performs needs a NAME. A
// reviewer scanning a diff for `template.HTML(` has to know that identifier
// matters; a reviewer scanning for `TrustHTML` is reading the word "trust" in
// the SDK's own vocabulary, at the call site where the decision was actually
// made.
func TrustHTML(s string) TrustedHTML {
	return trustHTML(s)
}
