// Code generated by kit from design/observe/logger/middleware/route.yaml (sha256 476e1e1706f9a38f59197c4f8d9849d76c698a2bcb390277becb04d8be5218c7, body 1162d6fb7fd00e27ff645c265569709dccce9690c3feeea18a3407b5b93e305a). DO NOT EDIT.

package route

import "github.com/kitsunium/sdk/internal/kernel/errs"

// range: 0.3.18.0 - 0.3.18.255

// CodeRouteNoMatch identifies a Write call whose record matched none of
// the registered predicates. The default sink (when configured) handles
// this case; without a default the Write returns this sentinel.
const CodeRouteNoMatch errs.Code = 0x00_03_12_01 // 0.3.18.1

// NoMatch is returned by Write when no predicate matched the record AND
// no default sink was configured. Callers that want a catch-all should
// pass a default sink to New so writes never silently disappear.
var NoMatch = errs.Define(CodeRouteNoMatch, "ROUTE_NO_MATCH",
	"No route predicate matched the record",
	"service/observe/logger/middleware/route.Write found no matching predicate and no default sink")
