load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "sdnotify",
    srcs = [
        "listen_linux.go",
        "listen_other.go",
        "notify.go",
        "sdnotify.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/proc/sdnotify",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/proc",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":sdnotify",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "sdnotify_test",
    srcs = [
        "sdnotify_external_test.go",
        "sdnotify_internal_test.go",
    ],
    embed = [":sdnotify"],
    deps = [
        "//internal/core/proc",
        "//internal/kernel/errs",
    ],
)
