load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "ndjson",
    srcs = ["ndjson.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/ndjson",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/data/codec/ndjson",
        "//internal/kernel/errs",
        "//internal/service/data/codec/ndjson",
    ],
)

alias(
    name = "go_default_library",
    actual = ":ndjson",
    visibility = ["//visibility:public"],
)

go_test(
    name = "ndjson_test",
    srcs = ["ndjson_external_test.go"],
    deps = [
        ":ndjson",
        "//internal/core/data/codec",
        "//pkg/v1/errs",
    ],
)
