// Code generated by kit from design/data/codec/ndjson.yaml (sha256 0de55d77b1535bf6793edc814b2992e9f0065e95cd4e5d12284ad0fdecede43c, body 432227dad8430986c35fdd39862434e7d81937aa0f749e5f837be15dd5910fc3). DO NOT EDIT.

package ndjson

import (
	corendjson "github.com/kitsunium/sdk/internal/core/data/codec/ndjson"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// The error codes, range 0.3.11.*, declared in the core (ADR 0160).
const (
	// CodeMarshalFailed is 0.3.11.1: a record has no JSON encoding.
	CodeMarshalFailed errs.Code = corendjson.CodeNDJSONMarshalFailed
	// CodeUnmarshalFailed is 0.3.11.2: a line is not JSON its element can
	// hold.
	CodeUnmarshalFailed errs.Code = corendjson.CodeNDJSONUnmarshalFailed
	// CodeValueInvalid is 0.3.11.3: the value or the target is not a slice.
	CodeValueInvalid errs.Code = corendjson.CodeNDJSONValueInvalid
)

// The sentinels, for errors.Is: each carries the code of the same name.
var (
	// MarshalFailed is the sentinel of [CodeMarshalFailed].
	MarshalFailed = corendjson.MarshalFailed
	// UnmarshalFailed is the sentinel of [CodeUnmarshalFailed].
	UnmarshalFailed = corendjson.UnmarshalFailed
	// ValueInvalid is the sentinel of [CodeValueInvalid].
	ValueInvalid = corendjson.ValueInvalid
)
