load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "studiokit",
    srcs = [
        "doc.go",
        "events.go",
        "profile.go",
        "studiokit.go",
        "studiokit_compliance.go",
    ],
    importpath = "github.com/kitsunium/sdk/framework/internal/kit/studiokit",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
    deps = [
        "//framework/internal/kit/plug",
        "//framework/model",
        "//pkg/v1/net/sse",
        "//pkg/v1/observe/profiling",
    ],
)

alias(
    name = "go_default_library",
    actual = ":studiokit",
    visibility = [
        "//framework:__subpackages__",
        "//visibility:public",
    ],
)

go_test(
    name = "studiokit_test",
    srcs = [
        "api_gen_test.go",
        "profile_internal_test.go",
    ],
    embed = [":studiokit"],
    deps = [
        "//framework/internal/kit/plug",
        "//framework/model",
        "//pkg/v1/observe/profiling",
    ],
)
