// Code generated by kit from design/observe/logger/sink/console.yaml (sha256 2202e71482acd26d69a99206e6ea5f16959e345121c5d522ba1d29cce0395e29, body a1eb52c81b34b628cbc29e7ca06d8c699630a5e08786e1b240ef1cbde55388bf). DO NOT EDIT.

package console

import corelogger "github.com/kitsunium/sdk/internal/core/observe/logger"

// NewStderr is a convenience constructor binding the sink to os.Stderr.
func NewStderr() corelogger.Sink {
	return newStderr()
}

// NewStdout is a convenience constructor binding the sink to os.Stdout.
func NewStdout() corelogger.Sink {
	return newStdout()
}
