load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "writer",
    srcs = ["writer.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/logger/writer",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/service/writer/console",
        "//internal/service/writer/file",
    ],
)

alias(
    name = "go_default_library",
    actual = ":writer",
    visibility = ["//visibility:public"],
)
