// Code generated by kit from design/app/i18n.yaml (sha256 afed989177a6e4e285b5b1c373d4bcb5c79df1308a7baf0a90d313bc57e7b2ab, body f131433f68c7fb16cef53903503907cc1a0c45cc8d23abcbd0d56e1a86ba8e8f). DO NOT EDIT.

package i18n_test

import (
	"io/fs"

	corei18n "github.com/kitsunium/sdk/internal/core/app/i18n"
	"github.com/kitsunium/sdk/internal/core/data/codec"
	svci18n "github.com/kitsunium/sdk/internal/service/app/i18n"
	"github.com/kitsunium/sdk/pkg/v1/app/i18n"
)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Args alias github.com/kitsunium/sdk/internal/core/app/i18n.Args
var _ *corei18n.Args = (*i18n.Args)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.ArgumentMissing var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.ArgumentMissing
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Catalog alias github.com/kitsunium/sdk/internal/core/app/i18n.Catalog
var _ *corei18n.Catalog = (*i18n.Catalog)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.CatalogInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.CatalogInvalid
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.CatalogLoadFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.CatalogLoadFailed
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Catalogue alias github.com/kitsunium/sdk/internal/service/app/i18n.Catalogue
var _ *svci18n.Catalogue = (*i18n.Catalogue)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Count alias github.com/kitsunium/sdk/internal/core/app/i18n.CountValue
var _ *corei18n.CountValue = (*i18n.Count)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Decimal func func(value float64, fractionDigits int) (count github.com/kitsunium/sdk/pkg/v1/app/i18n.Count, err error)
var _ func(value float64, fractionDigits int) (count i18n.Count, err error) = i18n.Decimal

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Entry alias github.com/kitsunium/sdk/internal/service/app/i18n.EntryValue
var _ *svci18n.EntryValue = (*i18n.Entry)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Fallbacker alias github.com/kitsunium/sdk/internal/core/app/i18n.Fallbacker
var _ *corei18n.Fallbacker = (*i18n.Fallbacker)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Form alias github.com/kitsunium/sdk/internal/core/app/i18n.Form
var _ *corei18n.Form = (*i18n.Form)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.FormFew const github.com/kitsunium/sdk/pkg/v1/app/i18n.Form
func _() {
	x := i18n.FormFew
	var _ *i18n.Form = &x
	_ = map[bool]int{false: 0, i18n.FormFew == 4: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.FormMany const github.com/kitsunium/sdk/pkg/v1/app/i18n.Form
func _() {
	x := i18n.FormMany
	var _ *i18n.Form = &x
	_ = map[bool]int{false: 0, i18n.FormMany == 5: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.FormOne const github.com/kitsunium/sdk/pkg/v1/app/i18n.Form
func _() {
	x := i18n.FormOne
	var _ *i18n.Form = &x
	_ = map[bool]int{false: 0, i18n.FormOne == 2: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.FormOther const github.com/kitsunium/sdk/pkg/v1/app/i18n.Form
func _() {
	x := i18n.FormOther
	var _ *i18n.Form = &x
	_ = map[bool]int{false: 0, i18n.FormOther == 0: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.FormTwo const github.com/kitsunium/sdk/pkg/v1/app/i18n.Form
func _() {
	x := i18n.FormTwo
	var _ *i18n.Form = &x
	_ = map[bool]int{false: 0, i18n.FormTwo == 3: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.FormZero const github.com/kitsunium/sdk/pkg/v1/app/i18n.Form
func _() {
	x := i18n.FormZero
	var _ *i18n.Form = &x
	_ = map[bool]int{false: 0, i18n.FormZero == 1: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Int func func(n int64) github.com/kitsunium/sdk/pkg/v1/app/i18n.Count
var _ func(n int64) i18n.Count = i18n.Int

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.InvalidCount var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.InvalidCount
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.InvalidForm var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.InvalidForm
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.InvalidKey var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.InvalidKey
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.InvalidPattern var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.InvalidPattern
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.InvalidTag var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.InvalidTag
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Key alias github.com/kitsunium/sdk/internal/core/app/i18n.Key
var _ *corei18n.Key = (*i18n.Key)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.KeyLister alias github.com/kitsunium/sdk/internal/core/app/i18n.KeyLister
var _ *corei18n.KeyLister = (*i18n.KeyLister)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.LoadFS func func(fsys io/fs.FS, dir string, format github.com/kitsunium/sdk/internal/core/data/codec.Format, fallback github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag) (store *github.com/kitsunium/sdk/pkg/v1/app/i18n.Store, err error)
var _ func(fsys fs.FS, dir string, format codec.Format, fallback i18n.Tag) (store *i18n.Store, err error) = i18n.LoadFS

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Message alias github.com/kitsunium/sdk/internal/core/app/i18n.MessageValue
var _ *corei18n.MessageValue = (*i18n.Message)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.MessageNotFound var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.MessageNotFound
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.NegotiationEmpty var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.NegotiationEmpty
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Negotiator alias github.com/kitsunium/sdk/internal/service/app/i18n.Negotiator
var _ *svci18n.Negotiator = (*i18n.Negotiator)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.NewMessage func func(text string) (message github.com/kitsunium/sdk/pkg/v1/app/i18n.Message, err error)
var _ func(text string) (message i18n.Message, err error) = i18n.NewMessage

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.NewNegotiator func func(supported []github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag, fallback github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag) (negotiator *github.com/kitsunium/sdk/pkg/v1/app/i18n.Negotiator, err error)
var _ func(supported []i18n.Tag, fallback i18n.Tag) (negotiator *i18n.Negotiator, err error) = i18n.NewNegotiator

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.NewPluralMessage func func(forms map[github.com/kitsunium/sdk/pkg/v1/app/i18n.Form]string) (message github.com/kitsunium/sdk/pkg/v1/app/i18n.Message, err error)
var _ func(forms map[i18n.Form]string) (message i18n.Message, err error) = i18n.NewPluralMessage

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.NewPrinter func func(catalog github.com/kitsunium/sdk/pkg/v1/app/i18n.Catalog, tag github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag) (printer *github.com/kitsunium/sdk/pkg/v1/app/i18n.Printer, err error)
var _ func(catalog i18n.Catalog, tag i18n.Tag) (printer *i18n.Printer, err error) = i18n.NewPrinter

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.NewStore func func(fallback github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag, catalogues map[github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag]github.com/kitsunium/sdk/pkg/v1/app/i18n.Catalogue) (store *github.com/kitsunium/sdk/pkg/v1/app/i18n.Store, err error)
var _ func(fallback i18n.Tag, catalogues map[i18n.Tag]i18n.Catalogue) (store *i18n.Store, err error) = i18n.NewStore

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.ParseForm func func(name string) (form github.com/kitsunium/sdk/pkg/v1/app/i18n.Form, err error)
var _ func(name string) (form i18n.Form, err error) = i18n.ParseForm

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.ParseTag func func(text string) (tag github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag, err error)
var _ func(text string) (tag i18n.Tag, err error) = i18n.ParseTag

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Plain func func(text string) github.com/kitsunium/sdk/pkg/v1/app/i18n.Entry
var _ func(text string) i18n.Entry = i18n.Plain

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Plural alias github.com/kitsunium/sdk/internal/service/app/i18n.PluralValue
var _ *svci18n.PluralValue = (*i18n.Plural)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.PluralFormMissing var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.PluralFormMissing
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.PluralForms func func(forms map[string]string) github.com/kitsunium/sdk/pkg/v1/app/i18n.Entry
var _ func(forms map[string]string) i18n.Entry = i18n.PluralForms

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.PluralRule alias github.com/kitsunium/sdk/internal/core/app/i18n.PluralRule
var _ *corei18n.PluralRule = (*i18n.PluralRule)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Printer alias github.com/kitsunium/sdk/internal/service/app/i18n.Printer
var _ *svci18n.Printer = (*i18n.Printer)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Rules func func(tag github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag) (plural github.com/kitsunium/sdk/pkg/v1/app/i18n.Plural, ok bool)
var _ func(tag i18n.Tag) (plural i18n.Plural, ok bool) = i18n.Rules

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Store alias github.com/kitsunium/sdk/internal/service/app/i18n.Store
var _ *svci18n.Store = (*i18n.Store)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.SupportedTags func func() []github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag
var _ func() []i18n.Tag = i18n.SupportedTags

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.Tag alias github.com/kitsunium/sdk/internal/core/app/i18n.TagValue
var _ *corei18n.TagValue = (*i18n.Tag)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.TranslationIncomplete var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.TranslationIncomplete
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.UnsupportedLanguage var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &i18n.UnsupportedLanguage
	x = &corei18n.ArgumentMissing
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/app/i18n.ValidateKey func func(key github.com/kitsunium/sdk/pkg/v1/app/i18n.Key) error
var _ func(key i18n.Key) error = i18n.ValidateKey
