// Code generated by kit from design/net.yaml (sha256 272f8b2074c12151570d75413302eefc44586f47c40447c60b12b761538248eb, body cd972e7fbaf6184e1d21ab2e59d1b320a7fb433130822ea4611a2f3d3e76fd27). DO NOT EDIT.

package tlsid

import (
	corenet "github.com/kitsunium/sdk/internal/core/net"
	svctlsid "github.com/kitsunium/sdk/internal/service/net/tlsid"
)

// Identity is an opaque TLS identity. Its String and GoString output is always
// "<redacted>"; ClientConfig and ServerConfig are the only ways to reach the
// material, and each returns a fresh *tls.Config.
type Identity = corenet.IdentityValue

// Params carries TLS material already held in memory.
type Params = corenet.IdentityParams

// FileParams names TLS material to read from the filesystem.
type FileParams = corenet.IdentityFileParams

// Sentinels returned by this package. Match with errors.Is or errs.HasCode.
var (
	// MaterialInvalid reports TLS material that is missing, unreadable,
	// malformed, or that yields no usable certificate. It is never downgraded to
	// an empty trust store.
	MaterialInvalid = corenet.TLSMaterialInvalid
	// HandshakeFailed reports a TLS or mutual-TLS handshake that did not complete.
	HandshakeFailed = corenet.TLSHandshakeFailed
)

// New validates TLS material held in memory and returns the opaque identity. It
// applies exactly the same rules as Load; only the source of the bytes differs.
func New(p Params) (id Identity, err error) {
	return corenet.NewIdentityValue(p)
}

// Load reads the named TLS material from disk and returns the opaque identity.
// A configured-but-unreadable file is an error, never a silently skipped one.
func Load(p FileParams) (id Identity, err error) {
	return svctlsid.Load(p)
}
