// Code generated by kit from design/framework/connectors/ssh.yaml (sha256 5a1b7b56fca1e4ae13b9532d70bbf13e0908363997509d6a82ac5ec3e4ee843e, body b4817b334ea55d683e04b3dc1a693fe2728fbca6560a610241f1d1306f2618ea). DO NOT EDIT.

package ssh

import "github.com/kitsunium/sdk/framework/entitlement"

// SSHIdentity proves a machine's identity from the ssh key material already in
// a user's key directory.
//
// It is a module of its own, framework/connectors/ssh, because
// golang.org/x/crypto/ssh brings golang.org/x/term and through it
// golang.org/x/sys, which the SDK and its framework ban (ADR 0078, ADR 0158). A
// consumer that wants it requires this module and its dependency graph; one
// that already handles its own key material implements the three-method port
// instead and inherits nothing.
//
// Why ssh key material rather than a keypair this package would mint: the whole
// point is that possession is proven against something the user ALREADY has and
// already protects. A file this package invented would need a lifecycle — where
// it lives, who may read it, what happens on rotation — that the user's own key
// directory already has.
type SSHIdentity struct {
	// dir is the key directory, conventionally ~/.ssh.
	dir string
}

var (
	_ entitlement.Identity    = (*SSHIdentity)(nil)
	_ entitlement.BoundProver = (*SSHIdentity)(nil)
)
