// Code generated by kit from design/app/view.yaml (sha256 c3e9ac70c59fae13b9afed611ab7c5c4a58eef5c8e2d9ab432eb587c3abbc9e6, body aea032c62341792a507a69d781edec859006132da0f694d93e86533377f15e98). DO NOT EDIT.

package view_test

import (
	coreview "github.com/kitsunium/sdk/internal/core/app/view"
	"github.com/kitsunium/sdk/internal/service/app/view"
)

// go:github.com/kitsunium/sdk/internal/service/app/view.HTML var github.com/kitsunium/sdk/internal/core/app/view.Factory
var _ *coreview.Factory = &view.HTML

// go:github.com/kitsunium/sdk/internal/service/app/view.NewHTML func func(cfg github.com/kitsunium/sdk/internal/core/app/view.Config) (renderer github.com/kitsunium/sdk/internal/core/app/view.Renderer, err error)
var _ func(cfg coreview.Config) (renderer coreview.Renderer, err error) = view.NewHTML
