load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "toml",
    srcs = ["toml.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/codec/toml",
    visibility = ["//visibility:public"],
    deps = ["//internal/service/codec/toml"],
)

alias(
    name = "go_default_library",
    actual = ":toml",
    visibility = ["//visibility:public"],
)

go_test(
    name = "toml_test",
    srcs = ["toml_external_test.go"],
    deps = [
        ":toml",
        "//internal/core/codec",
        "//pkg/v1/config",
    ],
)
