load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "mac",
    srcs = ["mac.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/mac",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/crypto",
        "//internal/service/crypto/hmacsha2",
    ],
)

alias(
    name = "go_default_library",
    actual = ":mac",
    visibility = ["//visibility:public"],
)

go_test(
    name = "mac_test",
    srcs = ["mac_external_test.go"],
    deps = [
        ":mac",
        "//pkg/v1/errs",
    ],
)
