// Code generated by kit from design/data/cache.yaml (sha256 6a0b4d26914e24d31cb477b087ccde3b0de0d33994e443b4eaae3b9d55811e14, body 53f5d0a3efdd091cc231ce75bf7c5b4c6d70e9523e425c9587415b892b22713e). DO NOT EDIT.

package cache

import (
	"context"
	"time"
)

// Fill computes the entry for a key that the cache does not hold. It is the
// caller's code: a database query, an HTTP call, a derivation.
//
// It is a FUNC port rather than a one-method interface, the shape
// internal/core already admits for resilience.Operation, scheduler.Job and
// validation.Constraint — and, per ADR 0039, a func type satisfies the
// no-widening rule structurally, because it cannot grow a method at all.
type Fill[V any] func(ctx context.Context) (EntryValue[V], error)

// EntryValue is what a caller stores: the value, how long it should live, and
// the tags by which it can later be invalidated in bulk.
//
// It is a VALUE — a store copies what it needs and never retains the slice the
// caller passed, so a caller may reuse or mutate its Tags slice afterwards.
type EntryValue[V any] struct {
	// Value is the payload.
	Value V
	// TTL is how long the entry stays fetchable.
	//
	//   > 0        this exact lifetime
	//   0          the store's configured default
	//   [NoExpiry] no deadline at all
	//
	// Any other negative value is a mistake, not a third meaning, and is
	// refused with [CacheEntryRejected] rather than reinterpreted.
	TTL time.Duration
	// Tags label the entry for bulk invalidation. Order is not significant and
	// duplicates are collapsed. An empty tag is refused: it names a set nobody
	// can ask for, so accepting it would index the entry under a key that can
	// only ever be reached by accident.
	//
	// Tags cost memory in the store's reverse index — see
	// internal/service/data/cache/CLAUDE.md, which states the per-pair cost and
	// measures it.
	Tags []string
}
