// Code generated by kit from design/data/codec/bson.yaml (sha256 ea318dea6443bff5ceb711c92c866b94988d9759beff219e65d976b87d1af60c, body dd41fa99e7fc22d8ce92bc99a118725e0c32dc060cb5105a98855953dedff1b1). DO NOT EDIT.

package bson_test

// package github.com/kitsunium/sdk/internal/core/data/codec/bson doc:9648a60ce2b9fb1ab98d7315f5c28344ace705e612346e4316be8bff6116b196

import (
	"github.com/kitsunium/sdk/internal/core/data/codec/bson"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.CodeBSONDepthExceeded const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:e1af3d53939e11c1e1df91a254080adccd91c0d0dd61a415b9a07f9f05ea17fb
func _() {
	x := bson.CodeBSONDepthExceeded
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeBSONDepthExceeded == 0x00_03_24_04: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.CodeBSONMarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:5c8a78a871860824857b7fdff387a2943f319d40c383cae98b9352f880cfbd25
func _() {
	x := bson.CodeBSONMarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeBSONMarshalFailed == 0x00_03_24_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.CodeBSONSizeExceeded const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:6e58635975ba6e082caa6cd5e27eb1544b7cca2ffe0f81a0d3ea418c37f24fa7
func _() {
	x := bson.CodeBSONSizeExceeded
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeBSONSizeExceeded == 0x00_03_24_03: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.CodeBSONUnmarshalFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:7924e7c98e86eb52ae4a1ceeecfae50386049a8804f35408e1a5240808903d54
func _() {
	x := bson.CodeBSONUnmarshalFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeBSONUnmarshalFailed == 0x00_03_24_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.CodeBSONValueInvalid const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:2fd8bad49349f7a201f14999e5f2991ec2394e80e2ca9d39e59e2cfb821c93dc
func _() {
	x := bson.CodeBSONValueInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, bson.CodeBSONValueInvalid == 0x00_03_24_05: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.DepthExceeded var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:ccf7376ac522ca5b0cae6c7fa770d60692960412b13741e13826f233d28aa22a
var _ **errs.Error = &bson.DepthExceeded

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.MarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:4cea797e7220b50b161dac478bc1607dbb4a3256fb17d0a16e84b9a89d8a7c07
var _ **errs.Error = &bson.MarshalFailed

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.SizeExceeded var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:24c68128268ea336c8fbb3a11c88101d729f6f7bc5a21cabe092c627b126c905
var _ **errs.Error = &bson.SizeExceeded

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.UnmarshalFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:c5e09bd2f62ef1802d8ee2343c42f17a4d8b6f4ad8fe19f738ffa98f2d5d411a
var _ **errs.Error = &bson.UnmarshalFailed

// go:github.com/kitsunium/sdk/internal/core/data/codec/bson.ValueInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:31709239d308afa0294985b8e06b125dfa750265c3dc4d47d941d17b6f8c3efc
var _ **errs.Error = &bson.ValueInvalid
