load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "logger",
    srcs = [
        "builder.go",
        "codes.go",
        "errors.go",
        "logger.go",
        "sink.go",
        "version.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/logger",
    visibility = ["//visibility:public"],
    # keep
    x_defs = {
        "github.com/kitsunium/sdk/pkg/v1/logger.Version": "{STABLE_VERSION}",
    },
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
        "//internal/kernel/clock",
        "//internal/kernel/errs",
        "//internal/service/logger",
        "//internal/service/logger/encoder",
        "//internal/service/logger/middleware/multi",
        "//internal/service/logger/sink/console",
    ],
)

alias(
    name = "go_default_library",
    actual = ":logger",
    visibility = ["//visibility:public"],
)

go_test(
    name = "logger_test",
    size = "small",
    srcs = [
        "builder_external_test.go",
        "logger_external_test.go",
        "sink_external_test.go",
        "version_external_test.go",
    ],
    deps = [
        ":logger",
        "//internal/core/logger",
        "//pkg/v1/errs",
    ],
)

filegroup(
    name = "audit_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
