// Code generated by kit from design/crypto.yaml (sha256 825cf641ff7952855a9842ba4d91de763db19b0e4fd7b6688683ffa03356c788, body 27a6318afbbc24905c08132218c3835eda4711e7154d68fe8f8746b20a797fd6). DO NOT EDIT.

package ecdsasig_test

// package github.com/kitsunium/sdk/internal/service/crypto/sign/ecdsasig doc:b80a5b98e22f06dc52e4609b6c14af27aaf3c60f95e8f8a39d18ef7c48e2aced

import (
	corecrypto "github.com/kitsunium/sdk/internal/core/crypto"
	"github.com/kitsunium/sdk/internal/service/crypto/sign/ecdsasig"
)

// go:github.com/kitsunium/sdk/internal/service/crypto/sign/ecdsasig.Signer var github.com/kitsunium/sdk/internal/core/crypto.Signer doc:e9ff2d61864316a4f7852985e07e9d761efb94a6ec30c683a2581c26cb2c5101
var _ *corecrypto.Signer = &ecdsasig.Signer
