load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "encoder",
    srcs = [
        "encoder.go",
        "text.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/logger/encoder",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/logger",
        "//internal/kernel/clock",
    ],
)

alias(
    name = "go_default_library",
    actual = ":encoder",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "encoder_test",
    srcs = [
        "text_external_test.go",
        "text_internal_test.go",
    ],
    embed = [":encoder"],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
        "//internal/kernel/clock",
    ],
)
