load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "entitlement",
    srcs = ["entitlement.go"],
    importpath = "github.com/kitsunium/sdk/framework/entitlement",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/internal/core/entitlement",
        "//framework/internal/service/entitlement",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":entitlement",
    visibility = ["//visibility:public"],
)

go_test(
    name = "entitlement_test",
    srcs = ["entitlement_external_test.go"],
    deps = [
        ":entitlement",
        "//pkg/v1/errs",
    ],
)
