load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "httpbody",
    srcs = [
        "facade_gen.go",
        "httpbody.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/strictjson/httpbody",
    visibility = ["//visibility:public"],
    deps = ["//internal/service/data/codec/strictjson/httpbody"],
)

alias(
    name = "go_default_library",
    actual = ":httpbody",
    visibility = ["//visibility:public"],
)

go_test(
    name = "httpbody_test",
    srcs = [
        "api_gen_test.go",
        "httpbody_external_test.go",
    ],
    deps = [
        ":httpbody",
        "//pkg/v1/data/codec/strictjson",
        "//pkg/v1/errs",
    ],
)
