// Code generated by kit from design/framework/telemetry.yaml (sha256 3268efb38d50cc8c9faf5217ca32e9f44b252606bbc6e6c8fa40a30573473b3d, body 68c4e2014b3d23efc4592305f75647c2940dd271697be5cb147092468bbfb716). DO NOT EDIT.

package telemetry_test

import (
	"context"

	"github.com/kitsunium/sdk/framework/telemetry"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/framework/telemetry.CodeMisconfigured const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := telemetry.CodeMisconfigured
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, telemetry.CodeMisconfigured == 0x00_04_03_01: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.CodeRunning const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := telemetry.CodeRunning
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, telemetry.CodeRunning == 0x00_04_03_02: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.Decode func func(b []byte) (e github.com/kitsunium/sdk/framework/telemetry.Event, seq uint64, ok bool)
var _ func(b []byte) (e telemetry.Event, seq uint64, ok bool) = telemetry.Decode

// go:github.com/kitsunium/sdk/framework/telemetry.DefaultBuffer const int
func _() {
	x := telemetry.DefaultBuffer
	var _ *int = &x
	_ = map[bool]int{false: 0, telemetry.DefaultBuffer == 4096: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.Emitter type interface{Emit(e *github.com/kitsunium/sdk/framework/telemetry.Event)}
// go:github.com/kitsunium/sdk/framework/telemetry.Emitter.Emit method func(e *github.com/kitsunium/sdk/framework/telemetry.Event)
var (
	_ interface {
		Emit(e *telemetry.Event)
	} = telemetry.Emitter(nil)
	_ telemetry.Emitter = interface {
		Emit(e *telemetry.Event)
	}(nil)
)

// go:github.com/kitsunium/sdk/framework/telemetry.Event type struct{Kind github.com/kitsunium/sdk/framework/telemetry.Kind; Op github.com/kitsunium/sdk/framework/telemetry.Op; Outcome github.com/kitsunium/sdk/framework/telemetry.Outcome; Node github.com/kitsunium/sdk/framework/telemetry.NodeRef; From github.com/kitsunium/sdk/framework/telemetry.NodeRef; Code uint32; Start int64; Duration int64; TraceID [16]byte; SpanID [8]byte}
func _(x telemetry.Event) {
	var _ *telemetry.Kind = &x.Kind
	var _ *telemetry.Op = &x.Op
	var _ *telemetry.Outcome = &x.Outcome
	var _ *telemetry.NodeRef = &x.Node
	var _ *telemetry.NodeRef = &x.From
	var _ *uint32 = &x.Code
	var _ *int64 = &x.Start
	var _ *int64 = &x.Duration
	var _ *[16]byte = &x.TraceID
	var _ *[8]byte = &x.SpanID
}

// go:github.com/kitsunium/sdk/framework/telemetry.Exporter type struct{}
var _ *telemetry.Exporter

// go:github.com/kitsunium/sdk/framework/telemetry.(*Exporter).Dropped method func() uint64
var _ func(*telemetry.Exporter) uint64 = (*telemetry.Exporter).Dropped

// go:github.com/kitsunium/sdk/framework/telemetry.(*Exporter).Emit method func(ev *github.com/kitsunium/sdk/framework/telemetry.Event)
var _ func(_ *telemetry.Exporter, ev *telemetry.Event) = (*telemetry.Exporter).Emit

// go:github.com/kitsunium/sdk/framework/telemetry.(*Exporter).Instance method func() string
var _ func(*telemetry.Exporter) string = (*telemetry.Exporter).Instance

// go:github.com/kitsunium/sdk/framework/telemetry.(*Exporter).Ref method func(id string) github.com/kitsunium/sdk/framework/telemetry.NodeRef
var _ func(_ *telemetry.Exporter, id string) telemetry.NodeRef = (*telemetry.Exporter).Ref

// go:github.com/kitsunium/sdk/framework/telemetry.(*Exporter).Sent method func() uint64
var _ func(*telemetry.Exporter) uint64 = (*telemetry.Exporter).Sent

// go:github.com/kitsunium/sdk/framework/telemetry.(*Exporter).Start method func(ctx context.Context) error
var _ func(_ *telemetry.Exporter, ctx context.Context) error = (*telemetry.Exporter).Start

// go:github.com/kitsunium/sdk/framework/telemetry.(*Exporter).Stop method func(ctx context.Context) error
var _ func(_ *telemetry.Exporter, ctx context.Context) error = (*telemetry.Exporter).Stop

// go:github.com/kitsunium/sdk/framework/telemetry.ExporterConfig type struct{Path string; AllowUIDs []int; AllowGIDs []int; Buffer int; Hello github.com/kitsunium/sdk/framework/telemetry.HelloValue}
func _(x telemetry.ExporterConfig) {
	var _ *string = &x.Path
	var _ *[]int = &x.AllowUIDs
	var _ *[]int = &x.AllowGIDs
	var _ *int = &x.Buffer
	var _ *telemetry.HelloValue = &x.Hello
}

// go:github.com/kitsunium/sdk/framework/telemetry.HelloValue type struct{Product string; Binary string; Role string; Revision string; Digest string; Nodes []string}
func _(x telemetry.HelloValue) {
	var _ *string = &x.Product
	var _ *string = &x.Binary
	var _ *string = &x.Role
	var _ *string = &x.Revision
	var _ *string = &x.Digest
	var _ *[]string = &x.Nodes
}

func kitPinKind[X ~uint8]() {}

// go:github.com/kitsunium/sdk/framework/telemetry.Kind type uint8
var _ = kitPinKind[telemetry.Kind]

// go:github.com/kitsunium/sdk/framework/telemetry.KindPhase const github.com/kitsunium/sdk/framework/telemetry.Kind
func _() {
	x := telemetry.KindPhase
	var _ *telemetry.Kind = &x
	_ = map[bool]int{false: 0, telemetry.KindPhase == 2: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.KindSpan const github.com/kitsunium/sdk/framework/telemetry.Kind
func _() {
	x := telemetry.KindSpan
	var _ *telemetry.Kind = &x
	_ = map[bool]int{false: 0, telemetry.KindSpan == 1: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.MaxBuffer const int
func _() {
	x := telemetry.MaxBuffer
	var _ *int = &x
	_ = map[bool]int{false: 0, telemetry.MaxBuffer == (1 << 20): 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.MinBuffer const int
func _() {
	x := telemetry.MinBuffer
	var _ *int = &x
	_ = map[bool]int{false: 0, telemetry.MinBuffer == 64: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.Misconfigured var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &telemetry.Misconfigured

// go:github.com/kitsunium/sdk/framework/telemetry.NewExporter func func(cfg *github.com/kitsunium/sdk/framework/telemetry.ExporterConfig) (*github.com/kitsunium/sdk/framework/telemetry.Exporter, error)
var _ func(cfg *telemetry.ExporterConfig) (*telemetry.Exporter, error) = telemetry.NewExporter

func kitPinNodeRef[X ~uint32]() {}

// go:github.com/kitsunium/sdk/framework/telemetry.NodeRef type uint32
var _ = kitPinNodeRef[telemetry.NodeRef]

// go:github.com/kitsunium/sdk/framework/telemetry.Nop var github.com/kitsunium/sdk/framework/telemetry.Emitter
var _ *telemetry.Emitter = &telemetry.Nop

func kitPinOp[X ~uint8]() {}

// go:github.com/kitsunium/sdk/framework/telemetry.Op type uint8
var _ = kitPinOp[telemetry.Op]

// go:github.com/kitsunium/sdk/framework/telemetry.OpAsk const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpAsk
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpAsk == 14: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpAuth const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpAuth
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpAuth == 9: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpCLI const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpCLI
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpCLI == 17: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpCall const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpCall
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpCall == 2: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpConnect const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpConnect
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpConnect == 16: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpDeliver const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpDeliver
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpDeliver == 6: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpDeliverMail const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpDeliverMail
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpDeliverMail == 11: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpDispatch const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpDispatch
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpDispatch == 13: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpDraining const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpDraining
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpDraining == 20: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpFailed const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpFailed
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpFailed == 22: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpHandle const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpHandle
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpHandle == 15: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpNames var [23]string
var _ *[23]string = &telemetry.OpNames

// go:github.com/kitsunium/sdk/framework/telemetry.OpNone const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpNone
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpNone == 0: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpOf func func(name string) github.com/kitsunium/sdk/framework/telemetry.Op
var _ func(name string) telemetry.Op = telemetry.OpOf

// go:github.com/kitsunium/sdk/framework/telemetry.OpPublish const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpPublish
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpPublish == 5: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpRead const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpRead
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpRead == 3: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpRequest const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpRequest
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpRequest == 1: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpRun const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpRun
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpRun == 8: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpSecret const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpSecret
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpSecret == 12: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpSend const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpSend
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpSend == 10: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpServing const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpServing
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpServing == 19: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpStarting const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpStarting
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpStarting == 18: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpStopped const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpStopped
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpStopped == 21: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpTransition const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpTransition
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpTransition == 7: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OpWrite const github.com/kitsunium/sdk/framework/telemetry.Op
func _() {
	x := telemetry.OpWrite
	var _ *telemetry.Op = &x
	_ = map[bool]int{false: 0, telemetry.OpWrite == 4: 1}
}

func kitPinOutcome[X ~uint8]() {}

// go:github.com/kitsunium/sdk/framework/telemetry.Outcome type uint8
var _ = kitPinOutcome[telemetry.Outcome]

// go:github.com/kitsunium/sdk/framework/telemetry.OutcomeError const github.com/kitsunium/sdk/framework/telemetry.Outcome
func _() {
	x := telemetry.OutcomeError
	var _ *telemetry.Outcome = &x
	_ = map[bool]int{false: 0, telemetry.OutcomeError == 2: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.OutcomeOK const github.com/kitsunium/sdk/framework/telemetry.Outcome
func _() {
	x := telemetry.OutcomeOK
	var _ *telemetry.Outcome = &x
	_ = map[bool]int{false: 0, telemetry.OutcomeOK == 1: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.Protocol const string
func _() {
	x := telemetry.Protocol
	var _ *string = &x
	_ = map[bool]int{false: 0, telemetry.Protocol == "kit-telemetry/v1": 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.RecordSize const int
func _() {
	x := telemetry.RecordSize
	var _ *int = &x
	_ = map[bool]int{false: 0, telemetry.RecordSize == 64: 1}
}

// go:github.com/kitsunium/sdk/framework/telemetry.Running var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &telemetry.Running
