// Code generated by kit from design/proc.yaml (sha256 29c1524d17d932c78d70f180fcb26eb11774b2936fb9164c2b543d857031303c, body f4a23dac67f5f69c824f3e4a9fce2c448bb3a50d459bd11747a284881b0e7700). DO NOT EDIT.

package reaper_test

import (
	coreproc "github.com/kitsunium/sdk/internal/core/proc"
	svc "github.com/kitsunium/sdk/internal/service/proc/reaper"
	"github.com/kitsunium/sdk/pkg/v1/proc/reaper"
)

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.IsPID1 func func() bool
var _ func() bool = reaper.IsPID1

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.New func func(opts ...github.com/kitsunium/sdk/pkg/v1/proc/reaper.Option) github.com/kitsunium/sdk/pkg/v1/proc/reaper.Reaper
var _ func(opts ...reaper.Option) reaper.Reaper = reaper.New

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.Option alias github.com/kitsunium/sdk/internal/service/proc/reaper.Option
var _ *svc.Option = (*reaper.Option)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.ReapFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &reaper.ReapFailed
	x = &coreproc.CgroupCreateFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.Reaper alias github.com/kitsunium/sdk/internal/core/proc.Reaper
var _ *coreproc.Reaper = (*reaper.Reaper)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.SetChildSubreaper func func() error
var _ func() error = reaper.SetChildSubreaper

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.SubreaperFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &reaper.SubreaperFailed
	x = &coreproc.CgroupCreateFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.UnsupportedPlatform var *github.com/kitsunium/sdk/internal/kernel/errs.Error
func _() {
	x := &reaper.UnsupportedPlatform
	x = &coreproc.CgroupCreateFailed
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/proc/reaper.WithOnReap func func(fn func(int)) github.com/kitsunium/sdk/pkg/v1/proc/reaper.Option
var _ func(fn func(int)) reaper.Option = reaper.WithOnReap
