load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "levelgate",
    srcs = ["gate.go"],
    importpath = "github.com/kitsunium/sdk/internal/service/writer/levelgate",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
    ],
)

alias(
    name = "go_default_library",
    actual = ":levelgate",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "levelgate_test",
    srcs = [
        "gate_external_test.go",
        "gate_internal_test.go",
    ],
    embed = [":levelgate"],
    deps = [
        "//internal/core/logger",
        "//internal/core/logger/level",
    ],
)
