// Code generated by kit from design/framework/connectors/sqlite.yaml (sha256 fa54813f1689900cc3e17813419ee01750043d57f60e32f2f5973703b125ec14, body 28ec3ffe43b083883217b6120ce5582edcfaa063a10997d42a74b68e4f5ae82c). DO NOT EDIT.

package sqlite_test

// package github.com/kitsunium/sdk/framework/connectors/sqlite doc:2661e8a645f9eef78d542ccb9df9847f1059e1e359f3ff441515eaaebbaf64f0

import (
	"github.com/kitsunium/sdk/framework/connectors/sqlite"
	"github.com/kitsunium/sdk/framework/kit"
	"github.com/kitsunium/sdk/pkg/v1/errs"
)

// go:github.com/kitsunium/sdk/framework/connectors/sqlite.CodeURLMalformed const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:ca6aa71b6bad343f0194c9594684b7cb8817444e58c435ffc7a9030242aa1f1d
func _() {
	x := sqlite.CodeURLMalformed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, sqlite.CodeURLMalformed == 0x00_04_12_01: 1}
}

// go:github.com/kitsunium/sdk/framework/connectors/sqlite.Engine func func() github.com/kitsunium/sdk/framework/kit.Engine doc:7aed983dcca88843342947b984e80c8c47e844b440bc6bf18a7a5666a7d97ffd
var _ func() kit.Engine = sqlite.Engine
