// Code generated by kit from design/data/vfs.yaml (sha256 557fc8d3ddafda2db318e3bf569c19133642ce4ae90e7ebfebcdf7563bb2bada, body d4980878f59d7d2709bcc95ec98b5dde8ceba957509660eeee9990c3bfc34dde). DO NOT EDIT.

package vfs_test

import (
	corevfs "github.com/kitsunium/sdk/internal/core/data/vfs"
	"github.com/kitsunium/sdk/internal/service/data/vfs"
)

// go:github.com/kitsunium/sdk/internal/service/data/vfs.NewMem func func() github.com/kitsunium/sdk/internal/core/data/vfs.FullFS
var _ func() corevfs.FullFS = vfs.NewMem

// go:github.com/kitsunium/sdk/internal/service/data/vfs.NewOS func func(root string) (filesystem github.com/kitsunium/sdk/internal/core/data/vfs.FullFS, err error)
var _ func(root string) (filesystem corevfs.FullFS, err error) = vfs.NewOS
