load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "git",
    srcs = [
        "doc.go",
        "git.go",
    ],
    importpath = "github.com/kitsunium/sdk/framework/git",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/internal/core/git",
        "//framework/internal/service/git",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":git",
    visibility = ["//visibility:public"],
)

go_test(
    name = "git_test",
    srcs = [
        "api_gen_test.go",
        "git_external_test.go",
    ],
    deps = [
        ":git",
        "//framework/internal/core/git",
        "//framework/internal/service/git",
        "//internal/kernel/errs",
        "//pkg/v1/errs",
    ],
)
