// Code generated by kit from design/data/codec/flatbuffers.yaml (sha256 088400fe62c14910c3b1726381f8b3d257ff0d0aa335b512aa43d00f24330710, body c931b1101f05727bf952a9905704a843f825ae5838d89e041b3ef23eff858ad8). DO NOT EDIT.

package flatbuffers_test

import (
	"github.com/kitsunium/sdk/internal/kernel/errs"
	svcflatbuffers "github.com/kitsunium/sdk/internal/service/data/codec/flatbuffers"
	"github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers"
)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.BadTarget var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &flatbuffers.BadTarget

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.BadType var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &flatbuffers.BadType

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.BytesAcceptor alias github.com/kitsunium/sdk/internal/service/data/codec/flatbuffers.BytesAcceptor
var _ *svcflatbuffers.BytesAcceptor = (*flatbuffers.BytesAcceptor)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.BytesProvider alias github.com/kitsunium/sdk/internal/service/data/codec/flatbuffers.BytesProvider
var _ *svcflatbuffers.BytesProvider = (*flatbuffers.BytesProvider)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.CodeBadTarget const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := flatbuffers.CodeBadTarget
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeBadTarget == 0x00_03_17_02: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.CodeBadType const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := flatbuffers.CodeBadType
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeBadType == 0x00_03_17_01: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.CodeTruncated const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := flatbuffers.CodeTruncated
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeTruncated == 0x00_03_17_03: 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.Format const untyped string
func _() {
	type untyped string
	var _ untyped = flatbuffers.Format
	_ = map[bool]int{false: 0, flatbuffers.Format == "flatbuffers": 1}
}

// go:github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers.Truncated var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &flatbuffers.Truncated
