load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "flatbuffers",
    srcs = ["flatbuffers.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/flatbuffers",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/data/codec/flatbuffers",
        "//internal/kernel/errs",
        "//internal/service/data/codec/flatbuffers",
    ],
)

alias(
    name = "go_default_library",
    actual = ":flatbuffers",
    visibility = ["//visibility:public"],
)

go_test(
    name = "flatbuffers_test",
    srcs = [
        "api_gen_test.go",
        "flatbuffers_external_test.go",
    ],
    deps = [
        ":flatbuffers",
        "//internal/core/data/codec",
        "//internal/kernel/errs",
        "//internal/service/data/codec/flatbuffers",
        "//pkg/v1/errs",
    ],
)
