load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/kernel:kernel_consumers"])

go_library(
    name = "buffer",
    srcs = ["buffer.go"],
    importpath = "github.com/kitsunium/sdk/internal/kernel/buffer",
    visibility = ["//:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":buffer",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "buffer_test",
    size = "small",
    srcs = [
        "buffer_external_test.go",
        "buffer_internal_test.go",
    ],
    embed = [":buffer"],
)

filegroup(
    name = "audit_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
