// Code generated by kit from design/observe/logger.yaml (sha256 593e3f6e397c040c99b59dcf6983b192752f4320cbd42bbaa74fca679203d281, body 52eac34661180ead68f76ab8742df22d3ae593e53284a5b6a2ac19e77fce60d1). DO NOT EDIT.

package encoder

// ReservesKey reports whether a TOP-LEVEL attribute key must be renamed under
// [ReservedPrefix]: the two the SDK emits as fields of its own — trace_id and
// span_id, the correlation OpenTelemetry prescribes and ADR 0062 writes on
// every record emitted inside a span — and anything already in the reserved
// namespace.
//
// Two members of one JSON object cannot both be "trace_id" — a decoder keeps
// one of them, and which one is the decoder's business — so an attribute
// carrying that key beside the SDK's field could replace the correlation on the
// way in, and could carry a value from anywhere. It is renamed rather than
// dropped: nothing a caller logged is lost, and nothing it logged can be
// mistaken for the span this line came from.
//
// The namespace is reserved WITH the two keys because the rename has to be
// injective, and prefixing alone is not: a caller logging both trace_id and a
// literal attr.trace_id would otherwise land both on "attr.trace_id" and the
// ambiguity would survive one name over. Prefixing anything already inside the
// namespace makes the mapping one-to-one — attr.trace_id becomes
// attr.attr.trace_id — so two distinct keys always render distinct.
//
// Inside a group the key is already prefixed ("http.trace_id"), so it cannot
// collide and is left alone.
func ReservesKey(key string) bool {
	return reservesKey(key)
}
