// Code generated by kit from design/observe/profiling.yaml (sha256 92f6caf237e323e970be85c62a6ea6dba68e361551ca45928d46eaa5ce2d7096, body 4c88d46b75802b07caf38993e2d42694ac0fbc34dc7a21ae6a569182594e2ea9). DO NOT EDIT.

package profiling

import coreprofiling "github.com/kitsunium/sdk/internal/core/observe/profiling"

// FoldConfig says how Fold reads a profile: which sample type, whose each
// sample is, how many functions to rank and how much of the flame to keep.
// Every zero field has a default.
type FoldConfig struct {
	// Attribute returns the owner a sample is charged to — a pprof label's
	// value, the component whose code is on the stack — or "" when the
	// sample belongs to nobody in particular. The attribution is the
	// caller's: Fold only adds up. Nil charges every sample to nobody.
	Attribute func(sample coreprofiling.SampleValue) string
	// SampleType names the value folded — "cpu", "inuse_space". Empty is
	// the profile's default sample type, else its last one.
	SampleType string
	// TopFunctions is how many functions FoldedValue.Top lists; not
	// positive means DefaultTopFunctions.
	TopFunctions int
	// TopPerOwner is how many functions each owner's Top lists; not positive
	// means DefaultTopPerOwner.
	TopPerOwner int
	// FlameMinShare prunes a flame frame costing less than this share of
	// the total. Outside (0, 1), or NaN, means DefaultFlameMinShare.
	FlameMinShare float64
	// FlameMaxDepth is how deep the flame graph goes from its root; not
	// positive means DefaultFlameMaxDepth.
	FlameMaxDepth int
}

// GroupConfig says how GroupGoroutines groups: by which labels, and how many
// groups and frames to keep.
type GroupConfig struct {
	// Labels are the label keys a group is keyed by, in order — "kit_node",
	// "kit_loop" — beside the state and the top frame. None groups by state
	// and top frame alone.
	Labels []string
	// MaxGroups keeps the largest groups only; not positive keeps them all.
	MaxGroups int
	// MaxStack cuts each group's stack to its innermost frames; not
	// positive keeps it whole.
	MaxStack int
}
