// Code generated by kit from design/observe/logger/writer/journald.yaml (sha256 570bc2bc5f8242f42355b6282e79887ce8216b1b9f074ae5d022a2fb62dd9ec0, body ec507c51dc52ff46889c814febc4798426d5fe04fa015282226074a056aaeb80). DO NOT EDIT.

package journald_test

import (
	"github.com/kitsunium/sdk/internal/core/observe/logger/writer/journald"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/observe/logger/writer/journald.CodeJournaldOpenFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := journald.CodeJournaldOpenFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, journald.CodeJournaldOpenFailed == 0x00_03_1F_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/logger/writer/journald.CodeJournaldWriteFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := journald.CodeJournaldWriteFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, journald.CodeJournaldWriteFailed == 0x00_03_1F_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/logger/writer/journald.JournaldOpenFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &journald.JournaldOpenFailed

// go:github.com/kitsunium/sdk/internal/core/observe/logger/writer/journald.JournaldWriteFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &journald.JournaldWriteFailed
