load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "singleflight",
    srcs = [
        "doc.go",
        "facade_gen.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/concur/singleflight",
    visibility = ["//visibility:public"],
    deps = ["//internal/kernel/concur/singleflight"],
)

alias(
    name = "go_default_library",
    actual = ":singleflight",
    visibility = ["//visibility:public"],
)

go_test(
    name = "singleflight_test",
    srcs = [
        "api_gen_test.go",
        "singleflight_external_test.go",
    ],
    deps = [
        ":singleflight",
        "//internal/kernel/concur/singleflight",
    ],
)
