// Code generated by kit from design/app/mail/spool.yaml (sha256 9d1632c8d00bf1cbd9bbde871e520295b740a6bcafcae66c00bc551610ea81ed, body 31475cc7cfba60aa961b36003403c42e1bf2cf56000fe583520082d4d2f7d4a6). DO NOT EDIT.

package spool_test

// package github.com/kitsunium/sdk/internal/core/app/mail/spool doc:dcbf556275aa6245c860145badaf20a490c644ef8523f4afaa28df7bb46ca86e

import (
	"github.com/kitsunium/sdk/internal/core/app/mail/spool"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.CodeInvalidMailID const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:84e0574337504df1f9cafba188830becd202258648abfe3ad4925736945dacec
func _() {
	x := spool.CodeInvalidMailID
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, spool.CodeInvalidMailID == 0x00_03_51_06: 1}
}

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.CodeMessageUndecodable const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:a01a9b4575a2c80e935f84c73b5287b2a2e1e0f45317c4b9b1e459f7eb9b4c66
func _() {
	x := spool.CodeMessageUndecodable
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, spool.CodeMessageUndecodable == 0x00_03_51_03: 1}
}

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.CodeMessageUnencodable const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:fbd7a09159628bedc103f86fb646350392d5929fff8668c15dd132c4f0f201d5
func _() {
	x := spool.CodeMessageUnencodable
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, spool.CodeMessageUnencodable == 0x00_03_51_04: 1}
}

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.CodeSpoolClosed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:e23b5a8bf57c098e904277bf7f5b9bcc21473eafbd83b25bcb4866280a527a97
func _() {
	x := spool.CodeSpoolClosed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, spool.CodeSpoolClosed == 0x00_03_51_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.CodeSpoolMisconfigured const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:4640adb40af156688f4c7fa369fa117e85a2c54fb0baf8c9581d97194b997921
func _() {
	x := spool.CodeSpoolMisconfigured
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, spool.CodeSpoolMisconfigured == 0x00_03_51_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.CodeTransportPanicked const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:cd13d6afadfd821c2a3e4d661af9894707d5d3f8dc5279a5bc6c95d018cca6de
func _() {
	x := spool.CodeTransportPanicked
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, spool.CodeTransportPanicked == 0x00_03_51_05: 1}
}

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.InvalidMailID var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:19f41813daa9ff204007fb03c315f4e851e9971d1ff2aea9a3af2f6718baf929
var _ **errs.Error = &spool.InvalidMailID

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.MessageUndecodable var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:f7064315413d91275bfe02afb5a187db38416002da10fe02022dd72d46f42a10
var _ **errs.Error = &spool.MessageUndecodable

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.MessageUnencodable var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:ebdcf44432c8e9de729c4606c972c3cfe38b471e33e06cdb7803ccb39758f47e
var _ **errs.Error = &spool.MessageUnencodable

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.SpoolClosed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:e8ef28a79a9f03b6b167d1e510c4e75c425da7026c8a192137354a0f156fc38f
var _ **errs.Error = &spool.SpoolClosed

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.SpoolMisconfigured var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:81525ccdd8548f07b9a0417d4d38bbe150d3a05e358fefd7e3348bc5c8f92f86
var _ **errs.Error = &spool.SpoolMisconfigured

// go:github.com/kitsunium/sdk/internal/core/app/mail/spool.TransportPanicked var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:2b286f492fea7c0142c8d18d2a2de8a3601c9e6cc7d354f9498bc97182a457b2
var _ **errs.Error = &spool.TransportPanicked
