// Code generated by kit from design/proc.yaml (sha256 f29abdb35ff3399dbef7a95492e3364a649b831bbbdde5d869cd510d41dd43d6, body 74aac4672d9a90c4b45890f73a94fe1501146f34f1e453d14177ec16fc4db3eb). DO NOT EDIT.

package notify

import "context"

// ReadyContext is [Ready] bounded by ctx — see [NotifyContext].
func ReadyContext(ctx context.Context) error {
	return readyContext(ctx)
}

// StatusContext is [Status] bounded by ctx — see [NotifyContext].
func StatusContext(ctx context.Context, msg string) error {
	return statusContext(ctx, msg)
}
