// Code generated by kit from design/data/sql.yaml (sha256 c767633e25ceeef299579b552274179b6eb94ed36fcd8e84ba7926cce772a6f2, body 8b2d3c94414b3afb925c721558e30116634c987d1f085be869e773e247bcf82d). DO NOT EDIT.

package sql

import (
	"context"
	stdsql "database/sql"
)

// TxFunc is the unit of work a [Transactor] runs inside a transaction.
//
// It is a FUNCTION port, the shape internal/core/CLAUDE.md already admits for
// resilience.Operation, scheduler.Job and lifecycle.Start: one behaviour, so a
// named func IS the contract. ADR 0039 is satisfied structurally — a func type
// cannot grow a method at all.
//
// ctx is the transaction-scoped context. Passing it on is what lets a callee
// join THIS transaction rather than open a second one, and what lets a nested
// [Transactor.Transact] become a savepoint instead of a deadlock against the
// transaction its own caller is holding.
//
// Returning nil commits (or releases the savepoint). Returning an error rolls
// back (or rolls back to the savepoint) and the error is returned to the
// caller VERBATIM, so errors.Is keeps working across the boundary.
//
// ex is valid ONLY for the duration of the call. Using it afterwards is
// refused with a typed error rather than left to database/sql's ErrTxDone.
type TxFunc func(ctx context.Context, ex Executor) error

// Dialect names a SQL engine whose savepoint grammar, placeholder syntax,
// identifier quoting, row-lock clauses and advisory-lock mechanism this SDK
// knows exactly.
//
// The set is CLOSED and small on purpose. Every feature this domain adds — a
// savepoint, a `CREATE TABLE IF NOT EXISTS`, an advisory lock — is spelled
// differently by each engine, and there is no portable subset that covers all
// three. So the domain refuses a dialect it cannot spell AT CONSTRUCTION,
// by name, rather than generating SQL that will fail at the first savepoint of
// the first nested transaction on a production database (ADR 0055 §D4).
//
// The zero value is [DialectUnknown] and is not usable: it is what an unset
// configuration field looks like, and reading it as "probably Postgres" is how
// a MySQL deployment discovers the difference in production (ADR 0031).
type Dialect uint8

// Valid reports whether d is a dialect this domain can actually spell.
func (d Dialect) Valid() bool {
	return d.valid()
}

// SupportsAdvisoryLock reports whether the engine offers a SESSION-SCOPED
// advisory lock — one the server releases when the connection holding it
// drops.
//
// SQLite does not: it has no advisory-lock function, only the file lock that
// serialises writers. That distinction decides HOW [Migrator] promises mutual
// exclusion across processes, so it is a property of the dialect and not a
// runtime discovery (ADR 0055 §D7). On SQLite the runner holds the database
// file's write lock for the whole run instead, which the operating system
// releases when its holder dies, as a server releases an advisory lock
// (ADR 0140).
func (d Dialect) SupportsAdvisoryLock() bool {
	return d.supportsAdvisoryLock()
}

// ForUpdate renders the clause that ends a read by locking the rows it returns
// until the transaction ends, leading space included: " FOR UPDATE" on
// PostgreSQL and MySQL. On MySQL it is also a locking read, which reads the
// latest committed rows rather than a REPEATABLE READ transaction's snapshot.
//
// SQLite has no row lock and no such clause, and renders the empty string: a
// SQLite transaction excludes every other writer with the database's one write
// lock, which it takes at its first WRITE, so a transaction that must read
// under exclusion writes first (ADR 0140). A dialect that is not
// [Dialect.Valid] renders the clause: an engine without one refuses the
// statement, which is louder than a lock dropped in silence.
func (d Dialect) ForUpdate() string {
	return d.forUpdate()
}

// ForUpdateSkipLocked renders the clause that ends a read by locking the rows
// it returns and SKIPPING those another transaction holds, leading space
// included: " FOR UPDATE SKIP LOCKED" on PostgreSQL and MySQL. Two readers
// then never wait on each other's rows and never take the same one.
//
// It needs PostgreSQL 9.5, MySQL 8.0.1 or MariaDB 10.6 — later than the
// floors [DialectPostgres] and [DialectMySQL] name — and an older server
// refuses the statement. SQLite renders the empty string and a dialect that is
// not [Dialect.Valid] the clause, for the reasons [Dialect.ForUpdate] gives: a
// SQLite transaction that has written holds the database's only write lock,
// so no row it reads is held by anybody else.
func (d Dialect) ForUpdateSkipLocked() string {
	return d.forUpdateSkipLocked()
}

// Step is one direction of a migration: the statements that move the schema.
//
// A FUNCTION port, for the same reason [TxFunc] is: one behaviour, so a named
// func IS the contract, and a func type cannot grow a method (ADR 0039).
//
// It receives the SAME [Executor] the surrounding transaction runs on, which
// is what makes a migration and its version-table row commit together.
type Step func(ctx context.Context, ex Executor) error

// MigrationValue is one versioned schema change and its reversal.
//
// The SDK does NOT own a migration FILE FORMAT, a directory layout, or a
// naming convention, and it ships no example directory. A migration is a value
// the consumer constructs, because the moment the SDK reads a directory it has
// invented a convention every consumer must adopt and no consumer asked for
// (ADR 0055 §D8). Where the statements come from — a Go literal, an embed.FS,
// a generator — is the caller's decision and none of the SDK's business.
//
// The zero value is not runnable and is refused at construction.
type MigrationValue struct {
	// Version orders the migration. It must be non-zero and unique within one
	// set: zero is reserved as "before every migration", the value Down takes
	// to reverse everything.
	//
	// Any strictly-increasing scheme works; a UTC timestamp (20260910143000)
	// is the conventional one because two branches developed in parallel then
	// merge without colliding.
	Version uint64
	// Name is the human label recorded in the version table. It must be
	// non-empty: a schema history whose rows say only "42" is a schema
	// history nobody can read during an incident.
	Name string
	// Up applies the change. Required.
	Up Step
	// Down reverses it. Required — and [Irreversible] is how a caller says
	// "this one cannot be reversed" OUT LOUD.
	//
	// A nil Down is refused rather than accepted as "irreversible", because
	// "I forgot the reversal" and "there is no reversal" are the same nil and
	// only one of them is a defect. The same rule core/app/lifecycle applies to a
	// nil Stop, for the same reason.
	Down Step
}

// TxOptionsValue parameterises ONE transaction. It is a value, not a manager
// setting, because isolation is a property of the unit of work and not of the
// pool it runs on.
//
// The zero value is a working configuration: the driver's default isolation
// level, read-write. That is the only non-arbitrary default available — every
// engine defines its own default level and picking one here would silently
// change the semantics of an existing application on migration (ADR 0031's
// clamp side, where the default needs no explanation because it is the
// database's own).
//
// It is deliberately a struct rather than two extra method parameters so
// [Transactor] stays frozen at one method: a new option is a new FIELD, which
// breaks nobody, where a new method breaks every downstream double (ADR 0039).
type TxOptionsValue struct {
	// Isolation is the transaction isolation level. The zero value
	// (sql.LevelDefault) defers to the driver.
	Isolation stdsql.IsolationLevel
	// ReadOnly asks the engine to refuse writes. Not every driver enforces
	// it; those that do not report an error at Begin rather than accepting
	// writes silently, which is why this is passed through rather than
	// emulated.
	ReadOnly bool
}

// IsZero reports whether the options ask for nothing beyond the driver's
// defaults.
//
// It exists because a NESTED scope is a savepoint, and a savepoint can change
// neither the isolation level nor the read-only-ness of the transaction it
// sits inside. Non-zero options on a nested call are therefore refused with
// [NestedIsolation] rather than ignored — silently downgrading a caller's
// explicit `Serializable` to whatever the outer transaction happened to use is
// the kind of "helpful" behaviour that produces a data race nobody can find
// (ADR 0055 §D5).
func (t TxOptionsValue) IsZero() bool {
	return t.isZero()
}

// StdOptions renders the value as the stdlib's own option struct, ready for
// (*sql.DB).BeginTx.
func (t TxOptionsValue) StdOptions() *stdsql.TxOptions {
	return t.stdOptions()
}

// Irreversible is the [Step] a caller assigns to [MigrationValue.Down] to
// declare that the migration cannot be reversed. It always fails, with a typed
// error naming the version.
//
// It is a value rather than a nil convention so the claim appears in the diff
// and in the version-table review, and so `Down` reports a refusal the caller
// wrote rather than a nil dereference the SDK discovered.
func Irreversible(ctx context.Context, ex Executor) error {
	return irreversible(ctx, ex)
}
