// Code generated by kit from design/app/events.yaml (sha256 c6d5e44d9fea8cc84cf04163c21af475361903ae0d7dd6fdcf2392829fecca5d, body 93f9db0ea2d8ad6059a9b9be1de642c632950648902e28906d9f5625aca7d4f8). DO NOT EDIT.

package events

import (
	"context"

	corev "github.com/kitsunium/sdk/internal/core/app/events"
)

// Handler is one typed listener's registration: the [On] argument.
//
// It is the typed front of core/app/events.SubscriptionValue, field for field.
// The duplication is the layer: core owns the ERASED contract a bus can
// actually dispatch, and this owns the shape a caller writes. Collapsing them
// would mean either putting a type parameter in the core port — which would
// make the bus hold exactly one event type — or making every caller write
// their own assertion.
type Handler[E any] struct {
	// Name identifies the listener in every error field and is the handle
	// [Off] removes it by. It must be non-empty and unique among the
	// listeners registered for E.
	Name string
	// Priority orders this listener among the others registered for E. Lower
	// runs first; equal priorities run in registration order. Its zero value,
	// core/app/events.PriorityNormal, is a working default.
	Priority corev.Priority
	// MayHalt authorises Handle to stop the dispatch by returning
	// core/app/events.Halt. False — the zero value — means it cannot.
	MayHalt bool
	// Handle is the reaction. It receives the event ALREADY TYPED. It must be
	// non-nil.
	Handle func(ctx context.Context, event E) error
}
