load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "logfile",
    srcs = [
        "doc.go",
        "logfile.go",
        "open_flags_other.go",
        "open_flags_unix.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/observe/logger/internal/logfile",
    visibility = [
        "//internal/service:service_consumers",
        "//internal/service/observe/logger:__subpackages__",
    ],
    deps = ["//internal/kernel/errs"],
)

alias(
    name = "go_default_library",
    actual = ":logfile",
    visibility = [
        "//internal/service:service_consumers",
        "//internal/service/observe/logger:__subpackages__",
    ],
)

go_test(
    name = "logfile_test",
    srcs = [
        "api_gen_test.go",
        "logfile_external_test.go",
        "open_flags_unix_internal_test.go",
    ],
    embed = [":logfile"],
    deps = ["//internal/kernel/errs"],
)
