load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "worker",
    srcs = ["worker.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/concur/worker",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/kernel/concur/worker",
        "//pkg/v1/clock",
    ],
)

alias(
    name = "go_default_library",
    actual = ":worker",
    visibility = ["//visibility:public"],
)

go_test(
    name = "worker_test",
    srcs = ["worker_external_test.go"],
    deps = [
        ":worker",
        "//pkg/v1/clock",
    ],
)
