// Code generated by kit from design/net.yaml (sha256 0280f7122f5f0ca3b3753e904d68e40b8177f2f8ae6ed21c1298b38280534b9e, body ebc8d1497f4d8ede734c78003876a26bff8a7a19ad0204004fcc8eaf011a23c7). DO NOT EDIT.

package sse_test

import (
	"net/http"
	"time"

	corenet "github.com/kitsunium/sdk/internal/core/net"
	"github.com/kitsunium/sdk/internal/service/net/sse"
)

// go:github.com/kitsunium/sdk/internal/service/net/sse.AppendComment func func(dst []byte, text string) (wire []byte, err error)
var _ func(dst []byte, text string) (wire []byte, err error) = sse.AppendComment

// go:github.com/kitsunium/sdk/internal/service/net/sse.AppendEvent func func(dst []byte, e github.com/kitsunium/sdk/internal/core/net.SSEEventValue) (wire []byte, err error)
var _ func(dst []byte, e corenet.SSEEventValue) (wire []byte, err error) = sse.AppendEvent

// go:github.com/kitsunium/sdk/internal/service/net/sse.DefaultKeepAlive const time.Duration
func _() {
	x := sse.DefaultKeepAlive
	var _ *time.Duration = &x
	_ = map[bool]int{false: 0, sse.DefaultKeepAlive == 15000000000: 1}
}

// go:github.com/kitsunium/sdk/internal/service/net/sse.DefaultWriteTimeout const time.Duration
func _() {
	x := sse.DefaultWriteTimeout
	var _ *time.Duration = &x
	_ = map[bool]int{false: 0, sse.DefaultWriteTimeout == 10000000000: 1}
}

// go:github.com/kitsunium/sdk/internal/service/net/sse.KeepAlive func func(d time.Duration) github.com/kitsunium/sdk/internal/service/net/sse.Option
var _ func(d time.Duration) sse.Option = sse.KeepAlive

// go:github.com/kitsunium/sdk/internal/service/net/sse.New func func(w net/http.ResponseWriter, r *net/http.Request, opts ...github.com/kitsunium/sdk/internal/service/net/sse.Option) (stream *github.com/kitsunium/sdk/internal/service/net/sse.Stream, err error)
var _ func(w http.ResponseWriter, r *http.Request, opts ...sse.Option) (stream *sse.Stream, err error) = sse.New

// go:github.com/kitsunium/sdk/internal/service/net/sse.Option type func(*github.com/kitsunium/sdk/internal/service/net/sse.config)
var _ *sse.Option

// go:github.com/kitsunium/sdk/internal/service/net/sse.Retry func func(d time.Duration) github.com/kitsunium/sdk/internal/service/net/sse.Option
var _ func(d time.Duration) sse.Option = sse.Retry

// go:github.com/kitsunium/sdk/internal/service/net/sse.Stream type struct{}
var _ *sse.Stream

// go:github.com/kitsunium/sdk/internal/service/net/sse.(*Stream).Close method func() error
var _ func(*sse.Stream) error = (*sse.Stream).Close

// go:github.com/kitsunium/sdk/internal/service/net/sse.(*Stream).Comment method func(text string) error
var _ func(_ *sse.Stream, text string) error = (*sse.Stream).Comment

// go:github.com/kitsunium/sdk/internal/service/net/sse.(*Stream).Done method func() <-chan struct{}
var _ func(*sse.Stream) <-chan struct{} = (*sse.Stream).Done

// go:github.com/kitsunium/sdk/internal/service/net/sse.(*Stream).LastEventID method func() string
var _ func(*sse.Stream) string = (*sse.Stream).LastEventID

// go:github.com/kitsunium/sdk/internal/service/net/sse.(*Stream).Send method func(event github.com/kitsunium/sdk/internal/core/net.SSEEventValue) error
var _ func(_ *sse.Stream, event corenet.SSEEventValue) error = (*sse.Stream).Send

// go:github.com/kitsunium/sdk/internal/service/net/sse.WithoutKeepAlive func func() github.com/kitsunium/sdk/internal/service/net/sse.Option
var _ func() sse.Option = sse.WithoutKeepAlive

// go:github.com/kitsunium/sdk/internal/service/net/sse.WriteTimeout func func(d time.Duration) github.com/kitsunium/sdk/internal/service/net/sse.Option
var _ func(d time.Duration) sse.Option = sse.WriteTimeout
