load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "group",
    srcs = ["group.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/concur/group",
    visibility = ["//visibility:public"],
    deps = ["//internal/kernel/concur/group"],
)

alias(
    name = "go_default_library",
    actual = ":group",
    visibility = ["//visibility:public"],
)

go_test(
    name = "group_test",
    srcs = ["group_external_test.go"],
    deps = [":group"],
)
