load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "group",
    srcs = ["group.go"],
    importpath = "github.com/kitsunium/sdk/pkg/v1/concur/group",
    visibility = ["//visibility:public"],
    deps = ["//internal/kernel/concur/group"],
)

alias(
    name = "go_default_library",
    actual = ":group",
    visibility = ["//visibility:public"],
)

go_test(
    name = "group_test",
    srcs = [
        "api_gen_1_test.go",
        "api_gen_2_test.go",
        "api_gen_test.go",
        "group_external_test.go",
    ],
    deps = [
        ":group",
        "//internal/kernel/concur/group",
    ],
)
