// Code generated by kit from design/observe/trace.yaml (sha256 b80ed8fcf08ff68628e0145cfb48fa9eb97a005bc0d5546315cb6d4d4b572fd6, body b733f920ee4aca91d060daf21e41c897f5a3ae98858e093e41024ed729f48020). DO NOT EDIT.

package trace_test

// package github.com/kitsunium/sdk/internal/core/observe/trace doc:0bd20041fe9881ff83f6f63fdbd47ff447b430e5ac324e7bc6a0405e1f02fb07

import (
	"context"
	"time"

	coreotel "github.com/kitsunium/sdk/internal/core/observe/otel"
	"github.com/kitsunium/sdk/internal/core/observe/trace"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/observe/trace.AvailableExporters func func() []github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName doc:7c0ad6a7cde9b5d6664ca11af6f7889bfe690912b1b09cc119146e7d91172235
var _ func() []trace.ExporterName = trace.AvailableExporters

// go:github.com/kitsunium/sdk/internal/core/observe/trace.Carrier type interface{Get(key string) string; Set(key string, value string)} doc:833acb28b065761d0211c7a4fca80b9105183f5843c4ca3f4b06870e8526fac7
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Carrier.Get method func(key string) string doc:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Carrier.Set method func(key string, value string) doc:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
var (
	_ interface {
		Get(key string) string
		Set(key, value string)
	} = trace.Carrier(nil)
	_ trace.Carrier = interface {
		Get(key string) string
		Set(key, value string)
	}(nil)
)

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeDuplicateRegistration const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:0e05b860bc7030b435f25871ade74f06bfefcf10845d5d52c0246e0dd24b5a16
func _() {
	x := trace.CodeDuplicateRegistration
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeDuplicateRegistration == 0x00_02_14_05: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeEntropyFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:706af58f93e8ed59d648765515fa5daad93777fc450eb4a075b61b9ab39fcd8d
func _() {
	x := trace.CodeEntropyFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeEntropyFailed == 0x00_03_32_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeExportFailed const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:422c6b14363a5ee4f4114c6696742cfd0700010a447aad88f8a885b375b54852
func _() {
	x := trace.CodeExportFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeExportFailed == 0x00_02_14_04: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeInvalidAttribute const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:fbde8626c9e29d219745298ff6e90769de5f1ba9a2ab2c7a512589bcff0d6a50
func _() {
	x := trace.CodeInvalidAttribute
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeInvalidAttribute == 0x00_02_14_07: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeInvalidSampleRatio const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:6bfe9bc742cb2f4e9194d91a19da269b1e60950da9c3c84b4a3c2cee3b46c3c0
func _() {
	x := trace.CodeInvalidSampleRatio
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeInvalidSampleRatio == 0x00_03_32_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeInvalidSpanName const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:9397ed1430b64ef0deddad0fde7612dd3daac34351dccedd62b70d0dd6e359db
func _() {
	x := trace.CodeInvalidSpanName
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeInvalidSpanName == 0x00_02_14_06: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeInvalidTraceParent const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:e40fd2a54033833cc95ca97cb9fd119a9d1ac71c6263a99411e9db31126cfac1
func _() {
	x := trace.CodeInvalidTraceParent
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeInvalidTraceParent == 0x00_02_14_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeInvalidTraceState const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:eef9fc4c315588a2fdd0913f4da20e6af465740af6eec4fa8f53e2e03542f427
func _() {
	x := trace.CodeInvalidTraceState
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeInvalidTraceState == 0x00_02_14_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeOTLPEndpointInvalid const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:e45934c1e9467b5bb2d6615b3c43a86cfc4509e68972d584fb367ecfc55b9bc2
func _() {
	x := trace.CodeOTLPEndpointInvalid
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeOTLPEndpointInvalid == 0x00_03_32_05: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeOTLPExportRejected const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:4feac9a40aed7539753916f5b201b364dcd64ae33b2438292096d3a233dd8f9c
func _() {
	x := trace.CodeOTLPExportRejected
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeOTLPExportRejected == 0x00_03_32_06: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeOTLPExportUnavailable const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:abc1f28f49590c1ba373126bb99bc7ea525b40b9cc2d88c1496483c06b105443
func _() {
	x := trace.CodeOTLPExportUnavailable
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeOTLPExportUnavailable == 0x00_03_32_07: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeOTLPInvalidSpanContext const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:b1b3e8b859c71f488bca99fdc04c18dbe11be6c4583b226863cd57e782729c02
func _() {
	x := trace.CodeOTLPInvalidSpanContext
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeOTLPInvalidSpanContext == 0x00_03_32_03: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeOTLPPartialSuccess const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:49a6363744426cfe7b77107eeaee8c6f207d9f6ee05c433df17b86716030f8bc
func _() {
	x := trace.CodeOTLPPartialSuccess
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeOTLPPartialSuccess == 0x00_03_32_08: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeOTLPSpanNotEnded const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:75899ba0977d385b79ccb57dd6cf506a9c816b9b67e4beeb79f85d13be1129e7
func _() {
	x := trace.CodeOTLPSpanNotEnded
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeOTLPSpanNotEnded == 0x00_03_32_04: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.CodeUnknownExporter const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:69204d0cb17b159bef0e26105ebd6b34586fff343cc96344004e351d4a7dffa4
func _() {
	x := trace.CodeUnknownExporter
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, trace.CodeUnknownExporter == 0x00_02_14_03: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ContextWithSpanContext func func(parent context.Context, context github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue) context.Context doc:424e5ce781a3a24ce74f794b44c9511032f6dd3e09d8a4b2f9985b4293fc6b20
var _ func(parent context.Context, context trace.SpanContextValue) context.Context = trace.ContextWithSpanContext

// go:github.com/kitsunium/sdk/internal/core/observe/trace.DefaultScopeName const string doc:14755e29a9ecd3fcc90a4bb0bc463b8e6c8ce4456953dd089c380df537dc039d
func _() {
	x := trace.DefaultScopeName
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.DefaultScopeName == "github.com/kitsunium/sdk/pkg/v1/observe/trace": 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.DuplicateRegistration var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:0f7236084f48d892f6adfc8fefccde39e61d82718b7fea5e1d6959f96e0fc5dd
var _ **errs.Error = &trace.DuplicateRegistration

// go:github.com/kitsunium/sdk/internal/core/observe/trace.EntropyFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:e58ab1396e46df2286c11757d68758b8c593a29ea2f0d595070298e848c0d0dd
var _ **errs.Error = &trace.EntropyFailed

// go:github.com/kitsunium/sdk/internal/core/observe/trace.EventValue type struct{Time time.Time; Name string; Attrs []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue} doc:67cfc2761e6dd3e98d2157a18f352d8dfc377e6a05d867d842fe98ac58b6d839
func _(x trace.EventValue) {
	var _ *time.Time = &x.Time
	var _ *string = &x.Name
	var _ *[]coreotel.AttrValue = &x.Attrs
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.EventValue.Normalized method func() github.com/kitsunium/sdk/internal/core/observe/trace.EventValue doc:cfa73827a61c3e5c55f8a451744f6395d7d238a7dac12449e7417a233f5aa16d
var _ func(trace.EventValue) trace.EventValue = trace.EventValue.Normalized

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ExceptionEventName const string doc:4ade43ef0b2e86e4c4e6a07e888154dfaba4a20dcfc6876d06823c7f0fd03086
func _() {
	x := trace.ExceptionEventName
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ExceptionEventName == "exception": 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ExceptionMessageKey const string doc:33987eb30a4a98a8b7375b25b576831cf6f1003551a3f2c150f4f9dbd4c6ffd3
func _() {
	x := trace.ExceptionMessageKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ExceptionMessageKey == "exception.message": 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ExceptionStacktraceKey const string doc:b7cb4d3c64e3c4b798d28b56acc07597c0a43f4bc06233b12e060edd86d558b3
func _() {
	x := trace.ExceptionStacktraceKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ExceptionStacktraceKey == "exception.stacktrace": 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ExceptionTypeKey const string doc:edcb23fbcf81c32bd0ebb0dbcdf6e0d06e223fc9e512caabeb1555d4b82eb7b4
func _() {
	x := trace.ExceptionTypeKey
	var _ *string = &x
	_ = map[bool]int{false: 0, trace.ExceptionTypeKey == "exception.type": 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.Export func func(name github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName, spans github.com/kitsunium/sdk/internal/core/observe/trace.SpansValue) error doc:2f492ec96621ada6e409006ee9b84c1df0564868e781cb68406a285127355dfc
var _ func(name trace.ExporterName, spans trace.SpansValue) error = trace.Export

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ExportFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:935c97674347931b2d5728bcbc0d20917a94583d33666aa51354a11de8907335
var _ **errs.Error = &trace.ExportFailed

func kitPinExporterName[X ~string]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName type string doc:6f5d7bffe6fe63a4cc38d0fab560ad6b87f5e3937b612f8cee1e23cf8d4dd986
var _ = kitPinExporterName[trace.ExporterName]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName.String method func() string doc:f64bf0b788fdfa54cd4c5fda4b4b8fbdbe19b1f5338e59c6183a166b733c7efd
var _ func(trace.ExporterName) string = trace.ExporterName.String

// go:github.com/kitsunium/sdk/internal/core/observe/trace.FlagSampled const github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags doc:72e3a870628a6b8d3e376dc671f9de8913b89e089ca114b3523b1a4d4794eda9
func _() {
	x := trace.FlagSampled
	var _ *trace.TraceFlags = &x
	_ = map[bool]int{false: 0, trace.FlagSampled == 0x01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.InvalidAttribute var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:e2c24081ad908dc312635c6651eb13ba21efdf9b24c32da6dc96730ba2b57eb1
var _ **errs.Error = &trace.InvalidAttribute

// go:github.com/kitsunium/sdk/internal/core/observe/trace.InvalidSampleRatio var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:a0897ba3983a43fa6e400e9002578383692a51f7b64216793e4b62ac5fca18c0
var _ **errs.Error = &trace.InvalidSampleRatio

// go:github.com/kitsunium/sdk/internal/core/observe/trace.InvalidSpanName var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:9d9c97b26699c60fc716cf1daa36629758af25690cdcce8c857b32f6f8106a7b
var _ **errs.Error = &trace.InvalidSpanName

// go:github.com/kitsunium/sdk/internal/core/observe/trace.InvalidTraceParent var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:3e59ab05768d3c0f0d84a256ab457495f64027d91053704d94ca9cae85471fb8
var _ **errs.Error = &trace.InvalidTraceParent

// go:github.com/kitsunium/sdk/internal/core/observe/trace.InvalidTraceState var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:45a0f06554b0a17933df736825d3d3a124a027f7caabfbded0dfeab087465f21
var _ **errs.Error = &trace.InvalidTraceState

// go:github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue type struct{Context github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue; Attrs []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue} doc:d8ab9fe836aa55e46d55d4516b2cdb50d38e38c75958d5122a198a70bee24141
func _(x trace.LinkValue) {
	var _ *trace.SpanContextValue = &x.Context
	var _ *[]coreotel.AttrValue = &x.Attrs
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue.IsValid method func() bool doc:f17707af796f9da53d54e812e5b10303b43d32343903fa3806bb28f42cbd22c1
var _ func(trace.LinkValue) bool = trace.LinkValue.IsValid

// go:github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue.Normalized method func() github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue doc:23e8096250ee9701043ec4fd7d22d905c789a7af1debdfd03389772ea0d57b62
var _ func(trace.LinkValue) trace.LinkValue = trace.LinkValue.Normalized

// go:github.com/kitsunium/sdk/internal/core/observe/trace.LookupExporter func func(name github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName) (e github.com/kitsunium/sdk/internal/core/observe/trace.SpanExporter, ok bool) doc:5d7bc89a010b083a404e651f5d4926c24073467edb05879a34ee76657c5a1adf
var _ func(name trace.ExporterName) (e trace.SpanExporter, ok bool) = trace.LookupExporter

// go:github.com/kitsunium/sdk/internal/core/observe/trace.MaxTraceStateKeyLen const int doc:a8dc46cc40e025cd8d002b974087d0755ed84d262137576f2822fe24d6a13020
func _() {
	x := trace.MaxTraceStateKeyLen
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.MaxTraceStateKeyLen == 256: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.MaxTraceStateMembers const int doc:bfd28390e9b15182c416f3868ee50afc8f844c4c7fe74c080e559915ca8c47e1
func _() {
	x := trace.MaxTraceStateMembers
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.MaxTraceStateMembers == 32: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.MaxTraceStateValueLen const int doc:f82b1240cd97bd14d26ca16acead8b61516ff73a0222fe27c686863784335c89
func _() {
	x := trace.MaxTraceStateValueLen
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.MaxTraceStateValueLen == 256: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.NewStateBuilder func func(size int) github.com/kitsunium/sdk/internal/core/observe/trace.StateBuilder doc:58c6e0b61c7b325ab7f79f4e515bad47b0013d5594ed0e3d29a612cba66a6fd6
var _ func(size int) trace.StateBuilder = trace.NewStateBuilder

// go:github.com/kitsunium/sdk/internal/core/observe/trace.NormalizeResource func func(resource github.com/kitsunium/sdk/internal/core/observe/otel.ResourceValue) github.com/kitsunium/sdk/internal/core/observe/otel.ResourceValue doc:bca6b28fb673a831593ca1eb5a0926c5003c425e46579fda6aa540c35bb7fc26
var _ func(resource coreotel.ResourceValue) coreotel.ResourceValue = trace.NormalizeResource

// go:github.com/kitsunium/sdk/internal/core/observe/trace.NormalizeScope func func(scope github.com/kitsunium/sdk/internal/core/observe/otel.ScopeValue) github.com/kitsunium/sdk/internal/core/observe/otel.ScopeValue doc:773025c4261691b70746dbe287683af79b23fd22ed537c4dea48de22264301c2
var _ func(scope coreotel.ScopeValue) coreotel.ScopeValue = trace.NormalizeScope

// go:github.com/kitsunium/sdk/internal/core/observe/trace.OTLPEndpointInvalid var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:7f75774dc2cb345a8352a3df535482e662a94c509b3b609dbc2a098dec68062c
var _ **errs.Error = &trace.OTLPEndpointInvalid

// go:github.com/kitsunium/sdk/internal/core/observe/trace.OTLPExportRejected var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:2973b3ba628a796dacefdffcdedf94e29b0652463fbe01cd1c55d666e9c518cd
var _ **errs.Error = &trace.OTLPExportRejected

// go:github.com/kitsunium/sdk/internal/core/observe/trace.OTLPExportUnavailable var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:2e79e89e8ea68c07712ea90f8de7780c7a0a87e2643b176d69c2d64bb4ae7f84
var _ **errs.Error = &trace.OTLPExportUnavailable

// go:github.com/kitsunium/sdk/internal/core/observe/trace.OTLPInvalidSpanContext var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:c1481bfde59c4c6fbbc687aae950df49b9d16ad461e1200119d79286c0d67c66
var _ **errs.Error = &trace.OTLPInvalidSpanContext

// go:github.com/kitsunium/sdk/internal/core/observe/trace.OTLPPartialSuccess var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:bf9aaaac494ce01efc3867225e354797a3d9913bce0869cc4f4bf607757aba2f
var _ **errs.Error = &trace.OTLPPartialSuccess

// go:github.com/kitsunium/sdk/internal/core/observe/trace.OTLPSpanNotEnded var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:3247a125cbced8358d8a14fed5234eb59501d09b40a2d37511923bf82212b88e
var _ **errs.Error = &trace.OTLPSpanNotEnded

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ParseSpanID func func(text string) (id github.com/kitsunium/sdk/internal/core/observe/trace.SpanID, err error) doc:4ba5320a1b01d6eca95771b17436439e01620d4d021c7c1a1f0f676365e1ceda
var _ func(text string) (id trace.SpanID, err error) = trace.ParseSpanID

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ParseTraceID func func(text string) (id github.com/kitsunium/sdk/internal/core/observe/trace.TraceID, err error) doc:574161af53f1f827dccee89d88a7ffedaa031ef2394eb25612e7367e66c08c08
var _ func(text string) (id trace.TraceID, err error) = trace.ParseTraceID

// go:github.com/kitsunium/sdk/internal/core/observe/trace.RegisterExporter func func(e github.com/kitsunium/sdk/internal/core/observe/trace.SpanExporter) github.com/kitsunium/sdk/internal/core/observe/trace.SpanExporter doc:225d90f812fc720d9c8bf44d9a499c7212403d36d6a77f6c0f3b8e601a8f58a3
var _ func(e trace.SpanExporter) trace.SpanExporter = trace.RegisterExporter

func kitPinSampler[X ~func(params trace.SamplingParams) bool]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.Sampler type func(params github.com/kitsunium/sdk/internal/core/observe/trace.SamplingParams) bool doc:0dff880c380f55d2751b5cb6ad08c6c8e1d1a2184a564334a6aafcda5f495674
var _ = kitPinSampler[trace.Sampler]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SamplingParams type struct{Parent github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue; TraceID github.com/kitsunium/sdk/internal/core/observe/trace.TraceID; Name string; Kind github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind; Attrs []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue; Links []github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue} doc:cabc69d0ec2ee9085ce3b0f6c1ab911002b416eeb7021821c354b62adb6c1995
func _(x trace.SamplingParams) {
	var _ *trace.SpanContextValue = &x.Parent
	var _ *trace.TraceID = &x.TraceID
	var _ *string = &x.Name
	var _ *trace.SpanKind = &x.Kind
	var _ *[]coreotel.AttrValue = &x.Attrs
	var _ *[]trace.LinkValue = &x.Links
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SortAttrs func func(attrs []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue) []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue doc:1d9faa68b2f9ad84fe41368dea17203d045a9787a48cf199c184d6e703e2ad7c
var _ func(attrs []coreotel.AttrValue) []coreotel.AttrValue = trace.SortAttrs

// go:github.com/kitsunium/sdk/internal/core/observe/trace.Span type interface{AddEvent(name string, attrs ...github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue); End(); SetAttrs(attrs ...github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue); SetStatus(code github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode, message string); SpanContext() github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue} doc:d6a34646f6a9e97b5e17b9f005c4ce2623a229c9cf6a8660ba7006de60891f08
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Span.AddEvent method func(name string, attrs ...github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue) doc:94b20539cdaa4d107dfc9d57149627f369afa08024d5beb5cce3bf8d15b06235
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Span.End method func() doc:44120ae5663f19dfdd4e33165f3d1db5cde987b5b9f4ee0990e0c0c358657bcb
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Span.SetAttrs method func(attrs ...github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue) doc:f4d4f4e9faec5f6926a628a7c094be05b3ca6173573b2bb3f692e20de1a76232
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Span.SetStatus method func(code github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode, message string) doc:bc89ba23534cb8983313ead00466b5aaa8c4a614fd42448cd51c0c64c544bf8c
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Span.SpanContext method func() github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue doc:3213316f0382d3900336f9531a031a5e7031e8d804570122d72f62483c86d24f
var (
	_ interface {
		SpanContext() trace.SpanContextValue
		SetAttrs(attrs ...coreotel.AttrValue)
		AddEvent(name string, attrs ...coreotel.AttrValue)
		SetStatus(code trace.StatusCode, message string)
		End()
	} = trace.Span(nil)
	_ trace.Span = interface {
		SpanContext() trace.SpanContextValue
		SetAttrs(attrs ...coreotel.AttrValue)
		AddEvent(name string, attrs ...coreotel.AttrValue)
		SetStatus(code trace.StatusCode, message string)
		End()
	}(nil)
)

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextFromContext func func(ctx context.Context) github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue doc:b612c83977ff459883924341da3761d7c53211793a562d6ce23cc3f114f19667
var _ func(ctx context.Context) trace.SpanContextValue = trace.SpanContextFromContext

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue type struct{TraceID github.com/kitsunium/sdk/internal/core/observe/trace.TraceID; SpanID github.com/kitsunium/sdk/internal/core/observe/trace.SpanID; Flags github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags; State github.com/kitsunium/sdk/internal/core/observe/trace.StateValue; Remote bool} doc:8ba7bdd5a0e6cb07792ae97245d2f4704ba3267439e075e29cd441d82c3748c0
func _(x trace.SpanContextValue) {
	var _ *trace.TraceID = &x.TraceID
	var _ *trace.SpanID = &x.SpanID
	var _ *trace.TraceFlags = &x.Flags
	var _ *trace.StateValue = &x.State
	var _ *bool = &x.Remote
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue.IsSampled method func() bool doc:668a24e0b07fb269500ffb23c4244edaeab2095f9de06b4081c8adf693ed6c40
var _ func(trace.SpanContextValue) bool = trace.SpanContextValue.IsSampled

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue.IsValid method func() bool doc:f4377b2e7c0ed2ab33af579adda24c73fbc4a1967e53a38164383e90026dc90b
var _ func(trace.SpanContextValue) bool = trace.SpanContextValue.IsValid

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue.WithState method func(state github.com/kitsunium/sdk/internal/core/observe/trace.StateValue) github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue doc:04aa8be7cb4227102e17b1e891cb6204ce5762a8ecc8588eae3f36e795e5f3d2
var _ func(_ trace.SpanContextValue, state trace.StateValue) trace.SpanContextValue = trace.SpanContextValue.WithState

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanExporter type interface{Export(spans github.com/kitsunium/sdk/internal/core/observe/trace.SpansValue) error; Name() github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName} doc:98e9b69c78925c8e901ea2fbfbd0f53bee21808d6f77f9ce8c25b1f73b6776e4
// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanExporter.Export method func(spans github.com/kitsunium/sdk/internal/core/observe/trace.SpansValue) error doc:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanExporter.Name method func() github.com/kitsunium/sdk/internal/core/observe/trace.ExporterName doc:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
var (
	_ interface {
		Name() trace.ExporterName
		Export(spans trace.SpansValue) error
	} = trace.SpanExporter(nil)
	_ trace.SpanExporter = interface {
		Name() trace.ExporterName
		Export(spans trace.SpansValue) error
	}(nil)
)

func kitPinSpanID[X ~[trace.SpanIDLen]byte]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanID type [8]byte doc:27b8b62e5e0a49f88c830c9ad9354c0012530f5ddfbfe80d7111adb160e7b8ee
var _ = kitPinSpanID[trace.SpanID]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanID.IsValid method func() bool doc:85cd9dc47be8cbb9b23218ce2376d57bfc2575304794bdccf23a839b97421d3b
var _ func(trace.SpanID) bool = trace.SpanID.IsValid

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanID.String method func() string doc:f05d679a9fe1550a230d1e44dc10276a7119c9d98f327496f566be630ccdca40
var _ func(trace.SpanID) string = trace.SpanID.String

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanIDHexLen const int doc:6d11be3b6bcdc391948fd09a79a093404b918f33d992d2ec29d4350d917364ed
func _() {
	x := trace.SpanIDHexLen
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.SpanIDHexLen == 16: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanIDLen const int doc:6fd59fcafe2e9baef7c9a92d54929987aef5969ee811f3f2c077f52cc3cda0aa
func _() {
	x := trace.SpanIDLen
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.SpanIDLen == 8: 1}
}

func kitPinSpanKind[X ~int32]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind type int32 doc:7bc1f18855420033fc9e39d32003621f4e9e09de9877a91831062a12af12e7d8
var _ = kitPinSpanKind[trace.SpanKind]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind.Resolved method func() github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:b9e36acb1a0442237d6ef2f87ff2c596bbd348b3952a2f550b143cc2e9be1d8f
var _ func(trace.SpanKind) trace.SpanKind = trace.SpanKind.Resolved

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind.String method func() string doc:8713fadd13d075b4da6f8bbf07b97e89d630ecec5217aa630bfd124e97684d1f
var _ func(trace.SpanKind) string = trace.SpanKind.String

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKindClient const github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:03c1d38f8be33dbfa283ebc50727749644bf0738804c1070aad9983d80b25a50
func _() {
	x := trace.SpanKindClient
	var _ *trace.SpanKind = &x
	_ = map[bool]int{false: 0, trace.SpanKindClient == 3: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKindConsumer const github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:7091a4b797509725843a9bdc3a58a9e871d18449cb5adf8b5b3dc461765cdb7f
func _() {
	x := trace.SpanKindConsumer
	var _ *trace.SpanKind = &x
	_ = map[bool]int{false: 0, trace.SpanKindConsumer == 5: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKindInternal const github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:13d76cfcca0baa98889ca5634c7937f995c9b8b65f6260371f69efb29db8489a
func _() {
	x := trace.SpanKindInternal
	var _ *trace.SpanKind = &x
	_ = map[bool]int{false: 0, trace.SpanKindInternal == 1: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKindProducer const github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:bdecc0e0af71258dcf1876f7f3e3d8c4edfdbc4a11f8d00c6ef7767f41b3c0db
func _() {
	x := trace.SpanKindProducer
	var _ *trace.SpanKind = &x
	_ = map[bool]int{false: 0, trace.SpanKindProducer == 4: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKindServer const github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:d6d3572b5d6d12aa7a856ada6cd50dbcc630bacf482c53ab7473d56644f02f1c
func _() {
	x := trace.SpanKindServer
	var _ *trace.SpanKind = &x
	_ = map[bool]int{false: 0, trace.SpanKindServer == 2: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanKindUnspecified const github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind doc:5f53e39ec42c7eae68c0f9cefbb5981eb2ac4e475fe20bbecc46eeef01232bc0
func _() {
	x := trace.SpanKindUnspecified
	var _ *trace.SpanKind = &x
	_ = map[bool]int{false: 0, trace.SpanKindUnspecified == 0: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanParams type struct{Kind github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind; Attrs []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue; Links []github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue; StartTime time.Time} doc:1414df40ee4eb4e087a9427a070e57307c93f287773c83f536f27f8fbe33de95
func _(x trace.SpanParams) {
	var _ *trace.SpanKind = &x.Kind
	var _ *[]coreotel.AttrValue = &x.Attrs
	var _ *[]trace.LinkValue = &x.Links
	var _ *time.Time = &x.StartTime
}

func kitPinSpanSink[X ~func(span trace.SpanValue)]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanSink type func(span github.com/kitsunium/sdk/internal/core/observe/trace.SpanValue) doc:e7e2e363e810f5f33272ac0d871e629f3cde02a4257b4ff3184114ec1d21d12a
var _ = kitPinSpanSink[trace.SpanSink]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanValue type struct{Context github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue; Parent github.com/kitsunium/sdk/internal/core/observe/trace.SpanContextValue; Name string; Kind github.com/kitsunium/sdk/internal/core/observe/trace.SpanKind; StartTime time.Time; EndTime time.Time; Attrs []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue; Events []github.com/kitsunium/sdk/internal/core/observe/trace.EventValue; Links []github.com/kitsunium/sdk/internal/core/observe/trace.LinkValue; Status github.com/kitsunium/sdk/internal/core/observe/trace.StatusValue} doc:2f83faca0a348ab332b905f9366a4481c392b2c497703812e78701a65a3e5cb3
func _(x trace.SpanValue) {
	var _ *trace.SpanContextValue = &x.Context
	var _ *trace.SpanContextValue = &x.Parent
	var _ *string = &x.Name
	var _ *trace.SpanKind = &x.Kind
	var _ *time.Time = &x.StartTime
	var _ *time.Time = &x.EndTime
	var _ *[]coreotel.AttrValue = &x.Attrs
	var _ *[]trace.EventValue = &x.Events
	var _ *[]trace.LinkValue = &x.Links
	var _ *trace.StatusValue = &x.Status
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanValue.Duration method func() time.Duration doc:eb75dee7d087a4d17245994320144f5a983aac0d95985e96e8e702631f122dfb
var _ func(trace.SpanValue) time.Duration = trace.SpanValue.Duration

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpanValue.IsRoot method func() bool doc:80f2a484f8273542ddc2becb1673feea87ab9df4e3f879e7b9f0629cfeb69bea
var _ func(trace.SpanValue) bool = trace.SpanValue.IsRoot

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpansValue type struct{Resource github.com/kitsunium/sdk/internal/core/observe/otel.ResourceValue; Scope github.com/kitsunium/sdk/internal/core/observe/otel.ScopeValue; Spans []github.com/kitsunium/sdk/internal/core/observe/trace.SpanValue} doc:74e6a71b4696be7050df3bd4c6cc68d571e81407e9c7571df4d4196738a83562
func _(x trace.SpansValue) {
	var _ *coreotel.ResourceValue = &x.Resource
	var _ *coreotel.ScopeValue = &x.Scope
	var _ *[]trace.SpanValue = &x.Spans
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.SpansValue.IsEmpty method func() bool doc:ad9116501ed7f832a0bb61a4abd82c5bd4f47f6dd3214e1a798fd3c82493d4af
var _ func(trace.SpansValue) bool = trace.SpansValue.IsEmpty

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StateBuilder type struct{} doc:186919800e18c99eed25ea822c321ba238002d5a3176ef3a99114d13f9cd6796
var _ *trace.StateBuilder

// go:github.com/kitsunium/sdk/internal/core/observe/trace.(*StateBuilder).Add method func(key string, value string) bool doc:a1f07b8fc61585aa16e7aea6b15586f4db96ec4dd7adf7497e47140fd98c6e8b
var _ func(_ *trace.StateBuilder, key, value string) bool = (*trace.StateBuilder).Add

// go:github.com/kitsunium/sdk/internal/core/observe/trace.(*StateBuilder).State method func() github.com/kitsunium/sdk/internal/core/observe/trace.StateValue doc:f799f107241187806c7f0f02e05aedddf76a1565b8d45740ae24a0e5ad4494dd
var _ func(*trace.StateBuilder) trace.StateValue = (*trace.StateBuilder).State

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StateValue type struct{} doc:5a3167a5650ae40006f4bc6d5f5936b99f7b82bc03aa953c58df66e1d3cbd9e1
var _ *trace.StateValue

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StateValue.Delete method func(key string) github.com/kitsunium/sdk/internal/core/observe/trace.StateValue doc:9eb6d90bd066c23de835a9cd1e7dba018e8f989195adfed9e693af639ebd625b
var _ func(_ trace.StateValue, key string) trace.StateValue = trace.StateValue.Delete

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StateValue.Get method func(key string) (value string, ok bool) doc:2227248e9d8971fc61c5d21bda3a6d8227d2b9c0f892ac1e8b14f8e90337d67f
var _ func(_ trace.StateValue, key string) (value string, ok bool) = trace.StateValue.Get

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StateValue.Insert method func(key string, value string) (state github.com/kitsunium/sdk/internal/core/observe/trace.StateValue, err error) doc:efa9c80876459b0d9b16340b3dfda2a1110b76986eb95ad68e1afe17301618dc
var _ func(_ trace.StateValue, key, value string) (state trace.StateValue, err error) = trace.StateValue.Insert

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StateValue.Len method func() int doc:10ff9fb34cf5f2ccd5d3792286b23ba5c073fbd2e9d8646b531cef34a7ac1929
var _ func(trace.StateValue) int = trace.StateValue.Len

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StateValue.String method func() string doc:3dd18d7e1ed1c2d8eb5231dfc049a0339bd14cf969e8df83e0f15fe01c2eb1f8
var _ func(trace.StateValue) string = trace.StateValue.String

func kitPinStatusCode[X ~int32]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode type int32 doc:3a2e305fb9e3692c824f2ffe0da40a5e19b295abff1cf659eb4c4e3bcdd9541f
var _ = kitPinStatusCode[trace.StatusCode]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode.String method func() string doc:981e90df324b814e5db4ea7d354cc1090c14fd94c01e1868705f99d050a0eafd
var _ func(trace.StatusCode) string = trace.StatusCode.String

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusError const github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode doc:93e90044326ebccd293cd0492d3108a1a8bca250cb8b150bdf9794f4f6f08990
func _() {
	x := trace.StatusError
	var _ *trace.StatusCode = &x
	_ = map[bool]int{false: 0, trace.StatusError == 2: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusOK const github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode doc:89a944e48452c5c5a5c09055160b95d5c56470fa87ac79f752ac7ed6a2331035
func _() {
	x := trace.StatusOK
	var _ *trace.StatusCode = &x
	_ = map[bool]int{false: 0, trace.StatusOK == 1: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusUnset const github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode doc:90abe2f4bbbf86450676003b982977fa3d8d3869d6d89e639d8bd5c42fbaee86
func _() {
	x := trace.StatusUnset
	var _ *trace.StatusCode = &x
	_ = map[bool]int{false: 0, trace.StatusUnset == 0: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusValue type struct{Code github.com/kitsunium/sdk/internal/core/observe/trace.StatusCode; Message string} doc:3fe44ad4c39ca1bac36811795636cb416969ee78cb7b29804df38c187cc953eb
func _(x trace.StatusValue) {
	var _ *trace.StatusCode = &x.Code
	var _ *string = &x.Message
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusValue.IsUnset method func() bool doc:db70d98526df58ececfff02ed00ab1ba0bafe61e3fbf90524681d046e110f0fc
var _ func(trace.StatusValue) bool = trace.StatusValue.IsUnset

// go:github.com/kitsunium/sdk/internal/core/observe/trace.StatusValue.Resolved method func() github.com/kitsunium/sdk/internal/core/observe/trace.StatusValue doc:7a0a01f94611d2f282edd548e055fe77ca12faa85e6f08f71d17a9020b842eaf
var _ func(trace.StatusValue) trace.StatusValue = trace.StatusValue.Resolved

func kitPinTraceFlags[X ~byte]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags type byte doc:c5ad9622ff82303779ebfa17a651097e598cca43924466fc961d84c89837a63c
var _ = kitPinTraceFlags[trace.TraceFlags]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags.IsSampled method func() bool doc:eb398099dad19e774fe99f8d05057ed2b00c3ed6c2fe88f4043c9c88c01ac443
var _ func(trace.TraceFlags) bool = trace.TraceFlags.IsSampled

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags.Sanitized method func() github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags doc:5487eb5b9650041ebecb9880666924a5de33386651a3c38baee377cd168d1236
var _ func(trace.TraceFlags) trace.TraceFlags = trace.TraceFlags.Sanitized

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags.WithSampled method func(sampled bool) github.com/kitsunium/sdk/internal/core/observe/trace.TraceFlags doc:9ed428df1e1bb1bd5b84897f92dbb36741f3cca84b90eeb7b1ef5f68aa0ee1b9
var _ func(_ trace.TraceFlags, sampled bool) trace.TraceFlags = trace.TraceFlags.WithSampled

func kitPinTraceID[X ~[trace.TraceIDLen]byte]() {}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceID type [16]byte doc:975a61ac838bfb54f03492e565357990d715ee30a0cfd337a008af90c03bdeb0
var _ = kitPinTraceID[trace.TraceID]

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceID.IsValid method func() bool doc:fe76a9a3a33e55ff82dd62863b0961629468f0cd346ebfb0401be5749fb1c4c0
var _ func(trace.TraceID) bool = trace.TraceID.IsValid

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceID.String method func() string doc:d311f46bd4f0c7147dd7d6d900302362f55b61e842e3e1292bf98b5a475c4b2e
var _ func(trace.TraceID) string = trace.TraceID.String

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceIDHexLen const int doc:8c4b520975e48907937070918941b3d7e635b0f772adeacda97e2a4fd10d6172
func _() {
	x := trace.TraceIDHexLen
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.TraceIDHexLen == 32: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.TraceIDLen const int doc:48fd0a95a9c5063532bd9f4c721ed87a99fbcf4acdd86f009e261ce990c888e7
func _() {
	x := trace.TraceIDLen
	var _ *int = &x
	_ = map[bool]int{false: 0, trace.TraceIDLen == 16: 1}
}

// go:github.com/kitsunium/sdk/internal/core/observe/trace.Tracer type interface{Start(ctx context.Context, name string, params github.com/kitsunium/sdk/internal/core/observe/trace.SpanParams) (child context.Context, span github.com/kitsunium/sdk/internal/core/observe/trace.Span)} doc:c3081117492d3f569cb4ae48b7ba72aaee633511af19e807f9d1e8b332d411cb
// go:github.com/kitsunium/sdk/internal/core/observe/trace.Tracer.Start method func(ctx context.Context, name string, params github.com/kitsunium/sdk/internal/core/observe/trace.SpanParams) (child context.Context, span github.com/kitsunium/sdk/internal/core/observe/trace.Span) doc:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
var (
	_ interface {
		Start(ctx context.Context, name string, params trace.SpanParams) (child context.Context, span trace.Span)
	} = trace.Tracer(nil)
	_ trace.Tracer = interface {
		Start(ctx context.Context, name string, params trace.SpanParams) (child context.Context, span trace.Span)
	}(nil)
)

// go:github.com/kitsunium/sdk/internal/core/observe/trace.UnknownExporter var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:277da75a2518f65576dc562c5170b32969bbf4c242c1f8e0394739512b8e1851
var _ **errs.Error = &trace.UnknownExporter

// go:github.com/kitsunium/sdk/internal/core/observe/trace.ValidateAttrs func func(sorted []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue) doc:bae93a9882764d05b41b25a3549b30118720091400de4118295497677bbd0e44
var _ func(sorted []coreotel.AttrValue) = trace.ValidateAttrs
