// Code generated by kit from design/data/vfs.yaml (sha256 068afcdfafd4040f7212bc837da00e24dae39256c6aa5a721f849cbc1372ee6e, body f386c88b40ce4d51aadd9cf9c7021013b6e5ee7148306ae3e0fd3a63c768f5c8). DO NOT EDIT.

package vfs_test

// package github.com/kitsunium/sdk/pkg/v1/data/vfs doc:fca12738dd5998316ec82e845e9fea9223e683f50d2ccf75c5cefa04561a638c

import (
	corevfs "github.com/kitsunium/sdk/internal/core/data/vfs"
	"github.com/kitsunium/sdk/pkg/v1/data/vfs"
)

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.AtomicWriter alias github.com/kitsunium/sdk/internal/core/data/vfs.AtomicWriter doc:d39c47ef1d04846b9244a161e04e2a804617ad33e03a6bd23a56d216f89f8b05
var _ *corevfs.AtomicWriter = (*vfs.AtomicWriter)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.DirectoryNotEmpty var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:6a82ba8492e50aa4110c829832337dcb75bed546f4d668bbb00fa0d16697410a
func _() {
	x := &vfs.DirectoryNotEmpty
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.DirectorySyncFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:812fbd34808db85acfd7879dc11330fb26459173428e277afd1ccd281d0505c8
func _() {
	x := &vfs.DirectorySyncFailed
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.FS alias github.com/kitsunium/sdk/internal/core/data/vfs.FS doc:9f405c9d38e1a63aea547bea2db329b1905c6a1ea04bc934d499015f070c7cb7
var _ *corevfs.FS = (*vfs.FS)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.FullFS alias github.com/kitsunium/sdk/internal/core/data/vfs.FullFS doc:44e98db8b8cb2a860f8213a99789888b8f63f155b6da1978b91b62fbb6a149a8
var _ *corevfs.FullFS = (*vfs.FullFS)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.InvalidPath var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:2de4fe4342a7c313ddadaf10133933fb96aefe939d69240bdf939a154deeb598
func _() {
	x := &vfs.InvalidPath
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.InvalidPermission var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:4bb1723979853c9d024f8e3557bf41b7f834ab3364341119f39d7c52df2d0765
func _() {
	x := &vfs.InvalidPermission
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.NewMem func func() github.com/kitsunium/sdk/pkg/v1/data/vfs.FullFS doc:553c06eb0ee8dbe19888c00e0cccad291d8cd38db84dffcf9528e6c858987592
var _ func() vfs.FullFS = vfs.NewMem

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.NewOS func func(root string) (filesystem github.com/kitsunium/sdk/pkg/v1/data/vfs.FullFS, err error) doc:4156d10dcd55397ed92c94a612c3dd0980b29bc7b808d5a2c10ca274cd8a23bc
var _ func(root string) (filesystem vfs.FullFS, err error) = vfs.NewOS

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.NotRegularFile var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:d53637e9a16efb387de6037439d22953a67b3fcc7ba7991592291546a8dbb7a3
func _() {
	x := &vfs.NotRegularFile
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.PathEscaped var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:301559bb641034e5d14bb08558f1cd3b8a56fd9f98e570026da2d4343836366c
func _() {
	x := &vfs.PathEscaped
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.PublishFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:4afacddd1d19c739ee7fdb5b5bd246da44b81afa2783daefe1ce0f39930d8ca6
func _() {
	x := &vfs.PublishFailed
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.ReadFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:91e716ad7ca529d0536f7905e2513ec8312af239147d93b6067b30e58848ff3d
func _() {
	x := &vfs.ReadFailed
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.RootUnavailable var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:ba5322fec3e4bb89b93baff6f5e626dcfdba08c499f069084a93f8c4fd61630b
func _() {
	x := &vfs.RootUnavailable
	x = &corevfs.DirectoryNotEmpty
	_ = x
}

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.WritableFS alias github.com/kitsunium/sdk/internal/core/data/vfs.WritableFS doc:6d772c2c0600181a4abb4c9fc9dab9568d274e67d9d42eb938cbaa2710e8e9ac
var _ *corevfs.WritableFS = (*vfs.WritableFS)(nil)

// go:github.com/kitsunium/sdk/pkg/v1/data/vfs.WriteFailed var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:7230cddceff4eddcd15757d2de047470738b36604e3587daa27eb7ea611c2f34
func _() {
	x := &vfs.WriteFailed
	x = &corevfs.DirectoryNotEmpty
	_ = x
}
