load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "authz",
    srcs = [
        "abac.go",
        "authz.go",
        "combinators.go",
        "combine.go",
        "conditions.go",
        "decl_gen.go",
        "doc.go",
        "rbac.go",
        "validate.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/security/authz",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/security/authz",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":authz",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "authz_test",
    size = "small",
    srcs = [
        "abac_external_test.go",
        "api_gen_test.go",
        "authz_bench_test.go",
        "check_external_test.go",
        "combine_external_test.go",
        "conditions_external_test.go",
        "rbac_external_test.go",
    ],
    deps = [
        ":authz",
        "//internal/core/security/authz",
        "//internal/kernel/errs",
    ],
)
