load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "asn1",
    srcs = [
        "codec.go",
        "codes.go",
        "errors.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/codec/asn1",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":asn1",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "asn1_test",
    srcs = [
        "codec_external_test.go",
        "codec_internal_test.go",
    ],
    embed = [":asn1"],
    deps = [
        "//internal/core/codec",
        "//internal/kernel/errs",
    ],
)
