// Code generated by kit from design/proc.yaml (sha256 262996f254edc28898bf98f5fb221bbca59f14b5dd921719524681ed50e619c3, body 3d12aae8d783b45e235dc7cf0987b77946aea5500680f6af4c2c1158a31c9c3b). DO NOT EDIT.

//go:build windows

package signal_test

import (
	coreproc "github.com/kitsunium/sdk/internal/core/proc"
	"github.com/kitsunium/sdk/internal/service/proc/signal"
)

// go:github.com/kitsunium/sdk/internal/service/proc/signal.Relay func func(src <-chan github.com/kitsunium/sdk/internal/core/proc.Signal, target github.com/kitsunium/sdk/internal/service/proc/signal.Target) error
var _ func(src <-chan coreproc.Signal, target signal.Target) error = signal.Relay
