// Code generated by kit from design/proc.yaml (sha256 d15f4cabf0802f72fb868dca38b67f2697057ff68af6d126988d175c9b6c9862, body 4e2f0c1be6135276838032e3669510eefabc759161b70c8801c81321a00b0aeb). DO NOT EDIT.

//go:build unix

package signal_test

// package github.com/kitsunium/sdk/internal/service/proc/signal doc:9addb901049aae599a19b6e0d8f6ff55417b0eab3d5877b02db8194e6bdcfe8a

import (
	coreproc "github.com/kitsunium/sdk/internal/core/proc"
	"github.com/kitsunium/sdk/internal/service/proc/signal"
)

// go:github.com/kitsunium/sdk/internal/service/proc/signal.Relay func func(src <-chan github.com/kitsunium/sdk/internal/core/proc.Signal, target github.com/kitsunium/sdk/internal/service/proc/signal.Target) error doc:02a30af8b8bbc727bee3ba51f1365cf910e7289abb84e0f5002394f9fc3fdbed
var _ func(src <-chan coreproc.Signal, target signal.Target) error = signal.Relay
