load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "signal",
    srcs = [
        "relay_other.go",
        "relay_unix.go",
        "signal.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/proc/signal",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/proc",
    ] + select({
        "@rules_go//go/platform:aix": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:android": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:darwin": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:freebsd": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:illumos": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:ios": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:linux": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:netbsd": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:openbsd": [
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:solaris": [
            "//internal/kernel/errs",
        ],
        "//conditions:default": [],
    }),
)

alias(
    name = "go_default_library",
    actual = ":signal",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "signal_test",
    srcs = [
        "relay_other_test.go",
        "signal_external_test.go",
    ],
    deps = select({
        "@rules_go//go/platform:aix": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:android": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:darwin": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:dragonfly": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:freebsd": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:illumos": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:ios": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:js": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:linux": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:netbsd": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:openbsd": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:osx": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:plan9": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:qnx": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:solaris": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:windows": [
            ":signal",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "//conditions:default": [],
    }),
)
