// Code generated by kit from design/data/codec/jsonpatch.yaml (sha256 333fc7fd328eab93797a710f07645a765a8aedc34e26b41a5edfaaa252548273, body ed41c74804cb198596080592ec1290f82c9bd300a9f3861fba3d038d138feadb). DO NOT EDIT.

package jsonpatch_test

// package github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch doc:7e5f6637f871dc544c92827b37fbb764b8b79ba91e1f62c692ab7f8210814a1f

import (
	"encoding/json"

	"github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch"
)

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Add const github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Op doc:cd25a7a7e9658f88ce1930aee9b8e15e18d468159a636d2478e27155c2487fb0
func _() {
	x := jsonpatch.Add
	var _ *jsonpatch.Op = &x
	_ = map[bool]int{false: 0, jsonpatch.Add == "add": 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Diff func func(from []byte, to []byte) ([]github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.EditValue, error) doc:ef4abf736b0436c266151a188d9974825a8ef5ff71b65c6258bef9e53e6b355d
var _ func(from, to []byte) ([]jsonpatch.EditValue, error) = jsonpatch.Diff

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.EditValue type struct{Op github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Op "json:\"op\""; Path string "json:\"path\""; Value encoding/json.RawMessage "json:\"value,omitempty\""; Old encoding/json.RawMessage "json:\"old,omitempty\""} doc:2f6c328a8be922640b1b79380338aa919b690fbde48c48b9c4e610f8fedaabec
func _(x jsonpatch.EditValue) {
	var _ *jsonpatch.Op = &x.Op
	var _ *string = &x.Path
	var _ *json.RawMessage = &x.Value
	var _ *json.RawMessage = &x.Old
}

func kitPinOp[X ~string]() {}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Op type string doc:705a18da42e668f371339088af97d4f7097c9bfa0db03a85c7556ebeca6123b5
var _ = kitPinOp[jsonpatch.Op]

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Remove const github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Op doc:82e3c589ab1e13e86e871b3915856b535bb8b1b3b8c9d80ac294b62fb7482e4f
func _() {
	x := jsonpatch.Remove
	var _ *jsonpatch.Op = &x
	_ = map[bool]int{false: 0, jsonpatch.Remove == "remove": 1}
}

// go:github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Replace const github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch.Op doc:b93fc857e8eef21b0c793ec3082f31378b360b236bd4c4e538ce1f1fa2ff0ec8
func _() {
	x := jsonpatch.Replace
	var _ *jsonpatch.Op = &x
	_ = map[bool]int{false: 0, jsonpatch.Replace == "replace": 1}
}
