load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "jsonpatch",
    srcs = [
        "decl_gen.go",
        "doc.go",
        "jsonpatch.go",
        "tree.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/data/codec/jsonpatch",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/data/codec/jsonpatch",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":jsonpatch",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "jsonpatch_test",
    srcs = [
        "api_gen_test.go",
        "jsonpatch_external_test.go",
        "tree_internal_test.go",
    ],
    embed = [":jsonpatch"],
    deps = [
        "//internal/core/data/codec/jsonpatch",
        "//internal/kernel/errs",
    ],
)
