load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "multi",
    srcs = [
        "doc.go",
        "multi.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/observe/logger/middleware/multi",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/observe/logger",
        "//internal/core/observe/logger/middleware/multi",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":multi",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "multi_test",
    srcs = [
        "api_gen_test.go",
        "multi_external_test.go",
        "multi_internal_test.go",
    ],
    embed = [":multi"],
    deps = [
        "//internal/core/observe/logger",
        "//internal/core/observe/logger/level",
        "//internal/core/observe/logger/middleware/multi",
        "//internal/kernel/errs",
        "//internal/service/observe/logger/sink/console",
    ],
)
