// Code generated by kit from design/crypto.yaml (sha256 fcdf412b06317e35532b814da96e4407340f303c4f49fe41495b6195a61beab1, body 8f57f778e887d51ccb5acc41477016af0e4698222b60a78730c3fd6825b87ede). DO NOT EDIT.

package commonpw_test

// package github.com/kitsunium/sdk/internal/service/crypto/password/commonpw doc:0be989d071dd275dfdd590b0923b7410782dadd018c65a401ecf59cd1e1d367f

import "github.com/kitsunium/sdk/internal/service/crypto/password/commonpw"

// go:github.com/kitsunium/sdk/internal/service/crypto/password/commonpw.IsCommon func func(password []byte) bool doc:f283b0bc51735bd6ea13bd860d80d646320ba11d6682c0ac49d77ab086613dcb
var _ func(password []byte) bool = commonpw.IsCommon

// go:github.com/kitsunium/sdk/internal/service/crypto/password/commonpw.Len func func() int doc:49f1ead36cca6c9e5ecd81ab1d74a1bb196e0c4e8437e57eb13db2f1e8ac2bcd
var _ func() int = commonpw.Len
