load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "commonpw",
    srcs = ["commonpw.go"],
    embedsrcs = ["xato-net-10-million-passwords-10000.txt"],
    importpath = "github.com/kitsunium/sdk/internal/service/crypto/password/commonpw",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

alias(
    name = "go_default_library",
    actual = ":commonpw",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "commonpw_test",
    srcs = [
        "api_gen_test.go",
        "commonpw_external_test.go",
        "export_test.go",
    ],
    embed = [":commonpw"],
)
