// Code generated by kit from design/proc.yaml (sha256 fed56107ef01d02b7fc15ab89ee1fdbe2f6c8ef1e779eacb3a6ca7d3c43fa5bc, body ec55d97ea17ef39921e3963caa1dcc0361ec33bac00e28fa12a3326379d163da). DO NOT EDIT.

//go:build freebsd || dragonfly

package reaper_test

// package github.com/kitsunium/sdk/internal/service/proc/reaper doc:ce8107a017ada227d3e1a025e387787bb5f3855f645ba6027162ea0009c01d50

import "github.com/kitsunium/sdk/internal/service/proc/reaper"

// go:github.com/kitsunium/sdk/internal/service/proc/reaper.SetChildSubreaper func func() error doc:15055895de3fe6045034b0c042843a93c9e1ac8367d8ad856c19cc6a42d01f51
var _ func() error = reaper.SetChildSubreaper
