// Code generated by kit from design/proc.yaml (sha256 07c7a38135b742fc65ead25a148dfd3834c34ca802c8c757654a277191b0efb4, body 9f204ba9b917b5977afd1a983fda2bb80b14b89a8c580d1294769fe11693e54c). DO NOT EDIT.

//go:build freebsd || dragonfly

package reaper_test

import "github.com/kitsunium/sdk/internal/service/proc/reaper"

// go:github.com/kitsunium/sdk/internal/service/proc/reaper.SetChildSubreaper func func() error
var _ func() error = reaper.SetChildSubreaper
