load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "reaper",
    srcs = [
        "reaper.go",
        "reaper_other.go",
        "reaper_unix.go",
        "subreaper_bsd.go",
        "subreaper_dragonfly.go",
        "subreaper_freebsd.go",
        "subreaper_linux.go",
        "subreaper_other.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/proc/reaper",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = select({
        "@rules_go//go/platform:aix": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:android": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:darwin": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:freebsd": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:illumos": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:ios": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:js": [
            "//internal/core/proc",
        ],
        "@rules_go//go/platform:linux": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:netbsd": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:openbsd": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:osx": [
            "//internal/core/proc",
        ],
        "@rules_go//go/platform:plan9": [
            "//internal/core/proc",
        ],
        "@rules_go//go/platform:qnx": [
            "//internal/core/proc",
        ],
        "@rules_go//go/platform:solaris": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:windows": [
            "//internal/core/proc",
        ],
        "//conditions:default": [],
    }),
)

alias(
    name = "go_default_library",
    actual = ":reaper",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "reaper_test",
    srcs = [
        "reaper_external_test.go",
        "reaper_internal_test.go",
        "reaper_unix_bench_test.go",
        "reaper_unix_external_test.go",
        "reaper_unix_internal_test.go",
        "subreaper_linux_external_test.go",
    ],
    embed = [":reaper"],
    deps = select({
        "@rules_go//go/platform:aix": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:android": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:darwin": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:dragonfly": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:freebsd": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:illumos": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:ios": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:linux": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:netbsd": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:openbsd": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:solaris": [
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "//conditions:default": [],
    }),
)
