// Code generated by kit from design/proc.yaml (sha256 d15f4cabf0802f72fb868dca38b67f2697057ff68af6d126988d175c9b6c9862, body a72e2f860c6e8cf1081d2e26b618f77b7d6138bef91c1c048a4de0ed4b356aee). DO NOT EDIT.

package reaper

// Option configures a reaper returned by New. Options are applied in order; an
// unknown or zero option is a no-op. The set is intentionally small — a reaper
// has little to tune beyond an optional sweep callback for observability.
type Option func(*config)
