// Code generated by kit from design/data/codec/flatbuffers.yaml (sha256 14609b165c1a8b5671c222896b38759c8bd5b8b4ca5afa5013b6bfc0d8275649, body d1878eeafa2878e58f9377ca151c95f82bcc77205c68748c20ee65a151fb5c0a). DO NOT EDIT.

package flatbuffers_test

import (
	"github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.CodeFlatbuffersBadTarget const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := flatbuffers.CodeFlatbuffersBadTarget
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeFlatbuffersBadTarget == 0x00_03_17_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.CodeFlatbuffersBadType const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := flatbuffers.CodeFlatbuffersBadType
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeFlatbuffersBadType == 0x00_03_17_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.CodeFlatbuffersTruncated const github.com/kitsunium/sdk/internal/kernel/errs.Code
func _() {
	x := flatbuffers.CodeFlatbuffersTruncated
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeFlatbuffersTruncated == 0x00_03_17_03: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.FlatbuffersBadTarget var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &flatbuffers.FlatbuffersBadTarget

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.FlatbuffersBadType var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &flatbuffers.FlatbuffersBadType

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.FlatbuffersTruncated var *github.com/kitsunium/sdk/internal/kernel/errs.Error
var _ **errs.Error = &flatbuffers.FlatbuffersTruncated
