// Code generated by kit from design/data/codec/flatbuffers.yaml (sha256 c58480e63d0de5f4a6d186e411e07825acad9d9ce862a383e518a5759eff63b0, body 77b7bbdab889c1d9aeda5139e04d9a41be35ef4b0ccd9dde6bd4b36463440d1c). DO NOT EDIT.

package flatbuffers_test

// package github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers doc:7780a9343b542c53ca7c25e43a54d6ee3f2a165c090aae0216b61c6d9d0535d9

import (
	"github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers"
	"github.com/kitsunium/sdk/internal/kernel/errs"
)

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.CodeFlatbuffersBadTarget const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:c112afa741c225c38c22fe780ace3a00d99fbac3d1853061765324190a4b552d
func _() {
	x := flatbuffers.CodeFlatbuffersBadTarget
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeFlatbuffersBadTarget == 0x00_03_17_02: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.CodeFlatbuffersBadType const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:643d553b51b0b6202da8e05da545240bd3d9c3f0cda8e7bbffe4634dfe8f7a8f
func _() {
	x := flatbuffers.CodeFlatbuffersBadType
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeFlatbuffersBadType == 0x00_03_17_01: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.CodeFlatbuffersTruncated const github.com/kitsunium/sdk/internal/kernel/errs.Code doc:a58710aae4003251afbe7b2c640337d687c1b0163f467a0d5d1125eee37570de
func _() {
	x := flatbuffers.CodeFlatbuffersTruncated
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, flatbuffers.CodeFlatbuffersTruncated == 0x00_03_17_03: 1}
}

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.FlatbuffersBadTarget var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:90fd3b3ea2b6fdcf3f2f7569b12698fd47ea6bc644c350a846f4bb4cec6e6395
var _ **errs.Error = &flatbuffers.FlatbuffersBadTarget

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.FlatbuffersBadType var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:aea64a581a96c3cab600520305221ac61539c6d5798a479f6fae9fa6cec0a4d2
var _ **errs.Error = &flatbuffers.FlatbuffersBadType

// go:github.com/kitsunium/sdk/internal/core/data/codec/flatbuffers.FlatbuffersTruncated var *github.com/kitsunium/sdk/internal/kernel/errs.Error doc:ccb6745bb8d98729965cd63f6dfc505bc001bef1fa6b7089fd5d07492228ff0d
var _ **errs.Error = &flatbuffers.FlatbuffersTruncated
