load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "heap",
    srcs = [
        "doc.go",
        "facade_gen.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/collections/heap",
    visibility = ["//visibility:public"],
    deps = ["//internal/kernel/collections/heap"],
)

alias(
    name = "go_default_library",
    actual = ":heap",
    visibility = ["//visibility:public"],
)

go_test(
    name = "heap_test",
    srcs = [
        "api_gen_test.go",
        "heap_external_test.go",
    ],
    deps = [
        ":heap",
        "//internal/kernel/collections/heap",
    ],
)
