// Code generated by kit from design/proc.yaml (sha256 f6f7644eb6f21da80a05f3358ba2b5c2796a7d07076480c8919168b289cf4994, body 3ae4ffed75f1feedac748257a851ce789ea78eb224f8fe80322d737798f47fb4). DO NOT EDIT.

//go:build windows

package exec_test

import (
	"context"

	coreproc "github.com/kitsunium/sdk/internal/core/proc"
	"github.com/kitsunium/sdk/internal/service/proc/exec"
)

// go:github.com/kitsunium/sdk/internal/service/proc/exec.Start func func(ctx context.Context, spec github.com/kitsunium/sdk/internal/core/proc.Spec) (proc github.com/kitsunium/sdk/internal/core/proc.Process, err error)
var _ func(ctx context.Context, spec coreproc.Spec) (proc coreproc.Process, err error) = exec.Start
