load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "exec",
    srcs = [
        "attrs_unix.go",
        "cgroup_placement_linux.go",
        "cgroup_placement_other.go",
        "cgroup_placement_windows.go",
        "creds_unix.go",
        "exec.go",
        "exec_other.go",
        "exec_unix.go",
        "exec_windows.go",
        "handle_unix.go",
        "handle_windows.go",
        "handshake_unix.go",
        "joblimits_windows.go",
        "limits_unix.go",
        "limittable_as.go",
        "limittable_openbsd.go",
        "limittable_unix.go",
        "maxrss_rss32_unix.go",
        "maxrss_rss64_unix.go",
        "procfile_unix.go",
        "rlimit_value_default.go",
        "rlimit_value_signed.go",
        "stdio.go",
        "trampoline_unix.go",
        "wrap.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/proc/exec",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/proc",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":exec",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "exec_test",
    srcs = [
        "attrs_unix_internal_test.go",
        "cgroup_placement_linux_internal_test.go",
        "creds_unix_internal_test.go",
        "exec_internal_test.go",
        "exec_other_test.go",
        "exec_unix_external_test.go",
        "exec_unix_internal_test.go",
        "exec_windows_test.go",
        "handle_unix_internal_test.go",
        "handshake_unix_internal_test.go",
        "limits_unix_internal_test.go",
        "limittable_as_internal_test.go",
        "limittable_unix_internal_test.go",
        "maxrss_rss64_unix_internal_test.go",
        "procfile_unix_internal_test.go",
        "rlimit_value_default_internal_test.go",
        "stdio_internal_test.go",
        "trampoline_unix_internal_test.go",
        "wrap_internal_test.go",
    ],
    embed = [":exec"],
    deps = [
        "//internal/core/proc",
        "//internal/kernel/errs",
    ],
)
