load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "exec",
    srcs = [
        "attrs_unix.go",
        "creds_unix.go",
        "exec.go",
        "exec_other.go",
        "exec_unix.go",
        "handle_unix.go",
        "handshake_unix.go",
        "limits_unix.go",
        "limittable_as.go",
        "limittable_openbsd.go",
        "limittable_unix.go",
        "procfile_unix.go",
        "rlimit_value_default.go",
        "rlimit_value_signed.go",
        "stdio_unix.go",
        "trampoline_unix.go",
        "wrap.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/service/proc/exec",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/proc",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":exec",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "exec_test",
    srcs = [
        "exec_external_test.go",
        "stdio_external_test.go",
    ],
    deps = select({
        "@rules_go//go/platform:aix": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:android": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:darwin": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:dragonfly": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:freebsd": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:illumos": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:ios": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:linux": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:netbsd": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:openbsd": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "@rules_go//go/platform:solaris": [
            ":exec",
            "//internal/core/proc",
            "//internal/kernel/errs",
        ],
        "//conditions:default": [],
    }),
)
