// Code generated by kit from design/observe/internal/otlp.yaml (sha256 223e084d1b65f201f89606fad1b0c297a253a9beec9446188aa0b07439db7786, body 8b88f577ee3814c311891b984e30f3f886e954498bd79b5abfc9949de724d501). DO NOT EDIT.

package otlp_test

import (
	"io"
	"net/http"
	"time"

	coreotel "github.com/kitsunium/sdk/internal/core/observe/otel"
	"github.com/kitsunium/sdk/internal/kernel/errs"
	"github.com/kitsunium/sdk/internal/service/observe/internal/otlp"
)

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.AnyValue type struct{StringValue *string "json:\"stringValue,omitempty\""; BoolValue *bool "json:\"boolValue,omitempty\""; IntValue *github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Int64 "json:\"intValue,omitempty\""; DoubleValue *github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Double "json:\"doubleValue,omitempty\""}
func _(x otlp.AnyValue) {
	var _ **string = &x.StringValue
	var _ **bool = &x.BoolValue
	var _ **otlp.Int64 = &x.IntValue
	var _ **otlp.Double = &x.DoubleValue
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Attrs func func(attrs []github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue) []github.com/kitsunium/sdk/internal/service/observe/internal/otlp.KeyValue
var _ func(attrs []coreotel.AttrValue) []otlp.KeyValue = otlp.Attrs

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.DecodeRejected func func(payload []byte, into github.com/kitsunium/sdk/internal/service/observe/internal/otlp.RejectedCounter) int64
var _ func(payload []byte, into otlp.RejectedCounter) int64 = otlp.DecodeRejected

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.DefaultMaxResponseBytes const int64
func _() {
	x := otlp.DefaultMaxResponseBytes
	var _ *int64 = &x
	_ = map[bool]int{false: 0, otlp.DefaultMaxResponseBytes == (1 << 20): 1}
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.DefaultTimeout const time.Duration
func _() {
	x := otlp.DefaultTimeout
	var _ *time.Duration = &x
	_ = map[bool]int{false: 0, otlp.DefaultTimeout == 10000000000: 1}
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.DocumentTerminator const byte
func _() {
	x := otlp.DocumentTerminator
	var _ *byte = &x
	_ = map[bool]int{false: 0, otlp.DocumentTerminator == '\n': 1}
}

func kitPinDouble[X ~float64]() {}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Double type float64
var _ = kitPinDouble[otlp.Double]

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Double.MarshalJSON method func() (encoded []byte, err error)
var _ func(otlp.Double) (encoded []byte, err error) = otlp.Double.MarshalJSON

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.HTTPConfig type struct{Endpoint string; Client *net/http.Client; Headers map[string]string; Timeout time.Duration; MaxResponseBytes int64}
func _(x otlp.HTTPConfig) {
	var _ *string = &x.Endpoint
	var _ **http.Client = &x.Client
	var _ *map[string]string = &x.Headers
	var _ *time.Duration = &x.Timeout
	var _ *int64 = &x.MaxResponseBytes
}

func kitPinInt64[X ~int64]() {}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Int64 type int64
var _ = kitPinInt64[otlp.Int64]

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Int64.MarshalJSON method func() (encoded []byte, err error)
var _ func(otlp.Int64) (encoded []byte, err error) = otlp.Int64.MarshalJSON

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.KeyValue type struct{Key string "json:\"key\""; Value github.com/kitsunium/sdk/internal/service/observe/internal/otlp.AnyValue "json:\"value\""}
func _(x otlp.KeyValue) {
	var _ *string = &x.Key
	var _ *otlp.AnyValue = &x.Value
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.KeyValueOf func func(attr github.com/kitsunium/sdk/internal/core/observe/otel.AttrValue) github.com/kitsunium/sdk/internal/service/observe/internal/otlp.KeyValue
var _ func(attr coreotel.AttrValue) otlp.KeyValue = otlp.KeyValueOf

func kitPinLenientInt64[X ~int64]() {}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.LenientInt64 type int64
var _ = kitPinLenientInt64[otlp.LenientInt64]

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.(*LenientInt64).UnmarshalJSON method func(data []byte) error
var _ func(_ *otlp.LenientInt64, data []byte) error = (*otlp.LenientInt64).UnmarshalJSON

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Marshal[...] func func[R any](request R, failure *github.com/kitsunium/sdk/internal/kernel/errs.WrapParams) (doc []byte, err error)
func _[R any]() {
	var _ func(request R, failure *errs.WrapParams) (doc []byte, err error) = otlp.Marshal[R]
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.NewSender func func(cfg *github.com/kitsunium/sdk/internal/service/observe/internal/otlp.HTTPConfig, signal *github.com/kitsunium/sdk/internal/service/observe/internal/otlp.SignalSpec) (sender *github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Sender, err error)
var _ func(cfg *otlp.HTTPConfig, signal *otlp.SignalSpec) (sender *otlp.Sender, err error) = otlp.NewSender

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.NewStream func func(dst io.Writer, failure *github.com/kitsunium/sdk/internal/kernel/errs.WrapParams) *github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Stream
var _ func(dst io.Writer, failure *errs.WrapParams) *otlp.Stream = otlp.NewStream

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.RejectedCounter type interface{RejectedCount() int64}
// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.RejectedCounter.RejectedCount method func() int64
var (
	_ interface {
		RejectedCount() int64
	} = otlp.RejectedCounter(nil)
	_ otlp.RejectedCounter = interface {
		RejectedCount() int64
	}(nil)
)

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.ResourceMessage type struct{Attributes []github.com/kitsunium/sdk/internal/service/observe/internal/otlp.KeyValue "json:\"attributes,omitempty\""}
func _(x otlp.ResourceMessage) {
	var _ *[]otlp.KeyValue = &x.Attributes
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.ResourceOf func func(resource github.com/kitsunium/sdk/internal/core/observe/otel.ResourceValue) github.com/kitsunium/sdk/internal/service/observe/internal/otlp.ResourceMessage
var _ func(resource coreotel.ResourceValue) otlp.ResourceMessage = otlp.ResourceOf

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.ScopeMessage type struct{Name string "json:\"name,omitempty\""; Version string "json:\"version,omitempty\""}
func _(x otlp.ScopeMessage) {
	var _ *string = &x.Name
	var _ *string = &x.Version
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.ScopeOf func func(scope github.com/kitsunium/sdk/internal/core/observe/otel.ScopeValue) github.com/kitsunium/sdk/internal/service/observe/internal/otlp.ScopeMessage
var _ func(scope coreotel.ScopeValue) otlp.ScopeMessage = otlp.ScopeOf

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Sender type struct{}
var _ *otlp.Sender

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.(*Sender).Post method func(body []byte) error
var _ func(_ *otlp.Sender, body []byte) error = (*otlp.Sender).Post

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.SignalSpec type struct{EndpointInvalid *github.com/kitsunium/sdk/internal/kernel/errs.Error; EndpointUnparsable github.com/kitsunium/sdk/internal/kernel/errs.WrapParams; RequestUnbuildable github.com/kitsunium/sdk/internal/kernel/errs.WrapParams; TransportFault github.com/kitsunium/sdk/internal/kernel/errs.WrapParams; Rejected *github.com/kitsunium/sdk/internal/kernel/errs.Error; Unavailable *github.com/kitsunium/sdk/internal/kernel/errs.Error; PartialSuccess *github.com/kitsunium/sdk/internal/kernel/errs.Error; RejectedField string; DecodeRejected func(payload []byte) int64}
func _(x otlp.SignalSpec) {
	var _ **errs.Error = &x.EndpointInvalid
	var _ *errs.WrapParams = &x.EndpointUnparsable
	var _ *errs.WrapParams = &x.RequestUnbuildable
	var _ *errs.WrapParams = &x.TransportFault
	var _ **errs.Error = &x.Rejected
	var _ **errs.Error = &x.Unavailable
	var _ **errs.Error = &x.PartialSuccess
	var _ *string = &x.RejectedField
	var _ *func(payload []byte) int64 = &x.DecodeRejected
}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Stream type struct{}
var _ *otlp.Stream

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.(*Stream).Emit method func(doc []byte) error
var _ func(_ *otlp.Stream, doc []byte) error = (*otlp.Stream).Emit

func kitPinUint64[X ~uint64]() {}

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Uint64 type uint64
var _ = kitPinUint64[otlp.Uint64]

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Uint64.MarshalJSON method func() (encoded []byte, err error)
var _ func(otlp.Uint64) (encoded []byte, err error) = otlp.Uint64.MarshalJSON

// go:github.com/kitsunium/sdk/internal/service/observe/internal/otlp.UnixNano func func(instant time.Time) github.com/kitsunium/sdk/internal/service/observe/internal/otlp.Uint64
var _ func(instant time.Time) otlp.Uint64 = otlp.UnixNano
