// Code generated by kit from design/framework/selfupdate.yaml (sha256 e4a5acf953c7ffdabda398ea747c8d581b39734697ea53c3e4055e0f2b30ebff, body 050d0e531ccbe2d0120c5deb115383c02b19e575881364e194c25658f1f1b56f). DO NOT EDIT.

package selfupdate

// NewWithDeps returns a Service with its three ports injected, for a caller that
// supplies its own HTTP policy or a test that supplies doubles. A nil fs or
// copier is legal on paths that never reach the disk.
func NewWithDeps(version string, src Source, client Getter, fs FileSystem, copier Copier) *Service {
	return newWithDeps(version, src, client, fs, copier)
}

// StdinIsTerminal reports whether a human could answer a prompt on this
// process's standard input.
//
// It is a free function rather than something AuthoriseUnattendedUpgrade works
// out for itself, and that is the point: the consent decision stays testable
// without a pty, because the CALLER supplies the answer. Pass the result as the
// interactive argument.
func StdinIsTerminal() bool {
	return stdinIsTerminal()
}
