load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "tlv",
    srcs = [
        "doc.go",
        "facade_gen.go",
        "tlv.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/v1/data/codec/tlv",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/data/codec/tlv",
        "//internal/kernel/errs",
        "//internal/service/data/codec/tlv",
    ],
)

alias(
    name = "go_default_library",
    actual = ":tlv",
    visibility = ["//visibility:public"],
)

go_test(
    name = "tlv_test",
    srcs = [
        "api_gen_test.go",
        "tlv_external_test.go",
    ],
    deps = [
        ":tlv",
        "//internal/core/data/codec",
        "//internal/kernel/errs",
        "//pkg/v1/errs",
    ],
)
