// Code generated by kit from design/observe/logger/middleware/recover.yaml (sha256 552415edb84fbb91f337c073525116269e9ef7e636052895cfb1838dd5e17837, body 4f74fd91ef425b771ab2b946abc4fec217e96bf62681f7edffa409134386f659). DO NOT EDIT.

package recover_test

// package github.com/kitsunium/sdk/internal/service/observe/logger/middleware/recover doc:4c376ca08dca86c91c0eed39f3c35572145d222af1eaebacb06f296f05ddb40c

import (
	corelogger "github.com/kitsunium/sdk/internal/core/observe/logger"
	recoverpkg "github.com/kitsunium/sdk/internal/service/observe/logger/middleware/recover"
)

// go:github.com/kitsunium/sdk/internal/service/observe/logger/middleware/recover.Config type struct{OnPanic func(err error)} doc:38f789bee8e4ce54ee14fb0bba4e3c7de8bee49c08d76c47eaf5f3177569166d
func _(x recoverpkg.Config) {
	var _ *func(err error) = &x.OnPanic
}

// go:github.com/kitsunium/sdk/internal/service/observe/logger/middleware/recover.New func func(downstream github.com/kitsunium/sdk/internal/core/observe/logger.Sink) (sink github.com/kitsunium/sdk/internal/core/observe/logger.Sink, err error) doc:83bb3852ebb81ad2239d0a80ddb86de0688cbb37af274514ad2dc0a35089ee1f
var _ func(downstream corelogger.Sink) (sink corelogger.Sink, err error) = recoverpkg.New

// go:github.com/kitsunium/sdk/internal/service/observe/logger/middleware/recover.NewWithConfig func func(downstream github.com/kitsunium/sdk/internal/core/observe/logger.Sink, cfg github.com/kitsunium/sdk/internal/service/observe/logger/middleware/recover.Config) (sink github.com/kitsunium/sdk/internal/core/observe/logger.Sink, err error) doc:e149bf4e7f12aa64851a7ddc91fa724b6be27d082c3208b19aeca1d6f3a52851
var _ func(downstream corelogger.Sink, cfg recoverpkg.Config) (sink corelogger.Sink, err error) = recoverpkg.NewWithConfig
