// Code generated by kit from design/net.yaml (sha256 26239c10aa78ed1003b3367fa43c0db0328b0e1e4c1e8686ff5bc6672a04afc8, body 472166f49fb5dbed7e71235bfa415198e20a4a8822b9117bb04badbe42011efe). DO NOT EDIT.

package tlsid_test

// package github.com/kitsunium/sdk/internal/service/net/tlsid doc:9544548d7930391c64803a953967cc59a75026d52e59326aeaf9d5cb4b5b4996

import (
	corenet "github.com/kitsunium/sdk/internal/core/net"
	"github.com/kitsunium/sdk/internal/service/net/tlsid"
)

// go:github.com/kitsunium/sdk/internal/service/net/tlsid.Load func func(p github.com/kitsunium/sdk/internal/core/net.IdentityFileParams) (id github.com/kitsunium/sdk/internal/core/net.IdentityValue, err error) doc:61f8a09368aedba11ab5fedf0bafaa66c1fa4970d950ebe5a2037b3e557210d4
var _ func(p corenet.IdentityFileParams) (id corenet.IdentityValue, err error) = tlsid.Load
