load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/service:service_consumers"])

go_library(
    name = "tlsid",
    srcs = ["tlsid.go"],
    importpath = "github.com/kitsunium/sdk/internal/service/net/tlsid",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
    deps = [
        "//internal/core/net",
        "//internal/kernel/errs",
    ],
)

alias(
    name = "go_default_library",
    actual = ":tlsid",
    visibility = [
        "//:__subpackages__",
        "//internal/service:service_consumers",
    ],
)

go_test(
    name = "tlsid_test",
    srcs = [
        "tlsid_external_test.go",
        "tlsid_internal_test.go",
    ],
    embed = [":tlsid"],
    deps = [
        "//internal/core/net",
        "//internal/kernel/errs",
    ],
)
