// Code generated by kit from design/crypto.yaml (sha256 577c3f96523a547b3b254db5fe68cbf7a380c6192ec46ce7608f8b01e1299de0, body 7a92d39b57b12c6fe4945362c0ae969b3f027436072dd7ecc08ebc27d10ad121). DO NOT EDIT.

package keytree_test

// package github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree doc:18eb8753e6bca77b9e7099095bcfc7d213fb2c4e76e0d42a16ba5b48c64e3ed9

import (
	corecrypto "github.com/kitsunium/sdk/internal/core/crypto"
	"github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree"
)

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree type struct{} doc:72b6839a566d7f8486158adceedcfeb88f5dad1e46e09ffcc5458902b2c12d48
var _ *keytree.KeyTree

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree.Child method func(segment string) github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree doc:707ed2e6d943b99546678f090e89be8ad476028f40b469229c9fbaafdfbfe599
var _ func(_ keytree.KeyTree, segment string) keytree.KeyTree = keytree.KeyTree.Child

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree.DeriveKey method func() (key github.com/kitsunium/sdk/internal/core/crypto.Key, err error) doc:e53fa1404be17e71151e33abc7bf33210903a546c28034caf52f8a9debf4c444
var _ func(keytree.KeyTree) (key corecrypto.Key, err error) = keytree.KeyTree.DeriveKey

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.NewKeyTree func func(algo github.com/kitsunium/sdk/internal/core/crypto.Algorithm, master github.com/kitsunium/sdk/internal/core/crypto.Key) github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree doc:559e330112e993466fb5cfcc31830c582c5a227c4d8e2101e30fed50f6dbcaed
var _ func(algo corecrypto.Algorithm, master corecrypto.Key) keytree.KeyTree = keytree.NewKeyTree
