// Code generated by kit from design/crypto.yaml (sha256 45f36234f0d46bd0103c6be7603273559b0ee0a032bd95fbb29d055b5b4884c9, body 5a715c0b674ede7cf78913a7b2d495f655f9b72a346f548b0bd382d1c373641e). DO NOT EDIT.

package keytree_test

import (
	corecrypto "github.com/kitsunium/sdk/internal/core/crypto"
	"github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree"
)

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree type struct{}
var _ *keytree.KeyTree

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree.Child method func(segment string) github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree
var _ func(_ keytree.KeyTree, segment string) keytree.KeyTree = keytree.KeyTree.Child

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree.DeriveKey method func() (key github.com/kitsunium/sdk/internal/core/crypto.Key, err error)
var _ func(keytree.KeyTree) (key corecrypto.Key, err error) = keytree.KeyTree.DeriveKey

// go:github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.NewKeyTree func func(algo github.com/kitsunium/sdk/internal/core/crypto.Algorithm, master github.com/kitsunium/sdk/internal/core/crypto.Key) github.com/kitsunium/sdk/internal/service/crypto/kdf/keytree.KeyTree
var _ func(algo corecrypto.Algorithm, master corecrypto.Key) keytree.KeyTree = keytree.NewKeyTree
