// Code generated by kit from design/crypto.yaml (sha256 c27f86517b997beb39a859eb5f25e1b06031e0232be1133dd36c039bda2b7c53, body ecb319a44527a7a097372e01be13713db8e6e16b3b366f1916985748122efd55). DO NOT EDIT.

package keytree

import corecrypto "github.com/kitsunium/sdk/internal/core/crypto"

// KeyTree is an immutable node in a path-addressed key-derivation tree. It
// holds the derivation algorithm, a shared master Key, and the accumulated
// path; Child returns a new node and never mutates the receiver.
type KeyTree struct {
	algo   corecrypto.Algorithm
	master corecrypto.Key
	path   []string
}
