// Code generated by kit from design/crypto.yaml (sha256 577c3f96523a547b3b254db5fe68cbf7a380c6192ec46ce7608f8b01e1299de0, body f7c487baf94d14a39413b41ab4c8a74235ae0d40e177f46fa44065ec37ccfcc5). DO NOT EDIT.

package keytree

import corecrypto "github.com/kitsunium/sdk/internal/core/crypto"

// KeyTree is an immutable node in a path-addressed key-derivation tree. It
// holds the derivation algorithm, a shared master Key, and the accumulated
// path; Child returns a new node and never mutates the receiver.
type KeyTree struct {
	algo   corecrypto.Algorithm
	master corecrypto.Key
	path   []string
}

// Child returns a new KeyTree one segment deeper; the receiver is unchanged.
func (k KeyTree) Child(segment string) KeyTree {
	return k.child(segment)
}

// NewKeyTree returns the root KeyTree for master, deriving children under algo.
func NewKeyTree(algo corecrypto.Algorithm, master corecrypto.Key) KeyTree {
	return newKeyTree(algo, master)
}
