// Code generated by kit from design/framework/kit.yaml (sha256 29a1335819918859d25c96651fc250aa1ebd20dc5c9a5a655606eff492e9fae8, body 18c23cd6589be53dd27b79b2634ff865792aa1aed80300f953cede6aa2e3e4db). DO NOT EDIT.

package kit_test

// package github.com/kitsunium/sdk/framework/kit doc:65be438217120b8361427bfac01c1e6758caf009627cf648862e0dec053bfe83

import (
	"context"
	"io"
	"io/fs"
	"net/http"
	"time"

	ikit "github.com/kitsunium/sdk/framework/internal/kit"
	"github.com/kitsunium/sdk/framework/kit"
	"github.com/kitsunium/sdk/framework/model"
	"github.com/kitsunium/sdk/pkg/v1/clock"
	"github.com/kitsunium/sdk/pkg/v1/data/sql"
	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/sdk/pkg/v1/observe/logger"
	"github.com/kitsunium/sdk/pkg/v1/security/secret"
)

// go:github.com/kitsunium/sdk/framework/kit.Activity alias github.com/kitsunium/sdk/framework/internal/kit.ActivityHandler doc:898afa02e6cb2331e8d328ebccbadfc59db12f7969b6e59b258011f8c09bb62d
var _ *ikit.ActivityHandler = (*kit.Activity)(nil)

// go:github.com/kitsunium/sdk/framework/kit.After func func(ctx context.Context, d time.Duration) <-chan time.Time doc:55c10c6a9be4912844923353c853dd7bdfefe16e61656828778f6145218a4093
var _ func(ctx context.Context, d time.Duration) <-chan time.Time = kit.After

// go:github.com/kitsunium/sdk/framework/kit.AllowPeers func func(uids []int, gids []int) github.com/kitsunium/sdk/framework/kit.ListenerOption doc:39a6077668433ea76bd14fb434fca875bf91afd9710d3415cf5152f69e6f47fc
var _ func(uids, gids []int) kit.ListenerOption = kit.AllowPeers

// go:github.com/kitsunium/sdk/framework/kit.Analyze func func(on bool) github.com/kitsunium/sdk/framework/kit.AppOption doc:85236ed1a003c161eb02a8d18301e56573caf7aa0f30188632d37116b13c6dda
var _ func(on bool) kit.AppOption = kit.Analyze

// go:github.com/kitsunium/sdk/framework/kit.AnalyzeFunc alias github.com/kitsunium/sdk/framework/internal/kit.AnalyzeFunc doc:9b324ff06172d313ad5c02ab9e92fc230a45a00cbda8e1cffdee80b39f4e8aa7
var _ *ikit.AnalyzeFunc = (*kit.AnalyzeFunc)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Analyzer func func(fn github.com/kitsunium/sdk/framework/kit.AnalyzeFunc) github.com/kitsunium/sdk/framework/kit.AppOption doc:46c88c02bad4f4347773d189d02bb7938fe48c254f5c97f959f3c29298a9d5db
var _ func(fn kit.AnalyzeFunc) kit.AppOption = kit.Analyzer

// go:github.com/kitsunium/sdk/framework/kit.Anonymise[...] func func[T any](fn func(*T)) github.com/kitsunium/sdk/framework/kit.StoreOption doc:dcadebc89738f50625003ebe276e6af5c72fb5fb4c7d2ef555043124603c96c1
func _[T any]() {
	var _ func(fn func(*T)) kit.StoreOption = kit.Anonymise[T]
}

// go:github.com/kitsunium/sdk/framework/kit.AnyUser func func() github.com/kitsunium/sdk/framework/kit.ExposeOption doc:9e1d7b8cdba0950ed6d12dc57f685737d0f4970ae4bdcd104368c927488c3b41
var _ func() kit.ExposeOption = kit.AnyUser

// go:github.com/kitsunium/sdk/framework/kit.Anyone func func() github.com/kitsunium/sdk/framework/kit.ExposeOption doc:7964904ce7d6b3f9dc9f782644b6654c3165c546326a6d5f6a9e19afaec39fd9
var _ func() kit.ExposeOption = kit.Anyone

// go:github.com/kitsunium/sdk/framework/kit.App alias github.com/kitsunium/sdk/framework/internal/kit.App doc:6f954926462ea009b3bee57b47a5ed5becb94b71edea55f6bf1a758a1d96c0df
var _ *ikit.App = (*kit.App)(nil)

// go:github.com/kitsunium/sdk/framework/kit.AppOption alias github.com/kitsunium/sdk/framework/internal/kit.AppConfigurer doc:3a53947a29480530cc653fcc51818f8039136d8864f8e75e100dea7264487ab4
var _ *ikit.AppConfigurer = (*kit.AppOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Auth func func() github.com/kitsunium/sdk/framework/kit.OperationOption doc:454b706ec9ed44da99fa4b5d1bf8dce7ed353061c2236cf032fb1b1dc48d3276
var _ func() kit.OperationOption = kit.Auth

// go:github.com/kitsunium/sdk/framework/kit.AuthData[...] func func[D any](ctx context.Context) (D, bool) doc:93b4b6208ceeb17c7682a64b461bb7e478d4e34b02e614c3e9215485ec424b4c
func _[D any]() {
	var _ func(ctx context.Context) (D, bool) = kit.AuthData[D]
}

// go:github.com/kitsunium/sdk/framework/kit.AuthOptional func func() github.com/kitsunium/sdk/framework/kit.OperationOption doc:7775991eb6fd9742c34d63017b886066a2c89d4f6eecdd72eab240d59229ab89
var _ func() kit.OperationOption = kit.AuthOptional

// go:github.com/kitsunium/sdk/framework/kit.Authenticator alias [P, D any] github.com/kitsunium/sdk/framework/internal/kit.AuthenticatorHandler[P, D] doc:7a8c5be6cff5aa9a0e12767f9907389119392e3757bba90e12021f0320325984
func _[P, D any]() {
	var _ *ikit.AuthenticatorHandler[P, D] = (*kit.Authenticator[P, D])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.Binary alias github.com/kitsunium/sdk/framework/internal/kit.Binary doc:32408293f74a4493e756fddedc34b9fdbc7614b1e9b9f54218ebfccba8fa4ff9
var _ *ikit.Binary = (*kit.Binary)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Bind[...] func func[Req, Resp any](port *github.com/kitsunium/sdk/framework/internal/kit.PortService[Req, Resp], op github.com/kitsunium/sdk/framework/internal/kit.Operation[Req, Resp]) interface{github.com/kitsunium/sdk/framework/kit.AppOption; github.com/kitsunium/sdk/framework/kit.MountOption} doc:908722ad1034023a197493ff94f8914c72e2b9bf5817b1f9dcab1c56e133972f
func _[Req, Resp any]() {
	var _ func(port *ikit.PortService[Req, Resp], op ikit.Operation[Req, Resp]) interface {
		kit.AppOption
		kit.MountOption
	} = kit.Bind[Req, Resp]
}

// go:github.com/kitsunium/sdk/framework/kit.Bulkhead func func(maxConcurrent int) github.com/kitsunium/sdk/framework/kit.OperationOption doc:ffdae89d0fdd023eaeccd937a8c9d0ac17dcbf17e55b0c76f36228f96e3f64c8
var _ func(maxConcurrent int) kit.OperationOption = kit.Bulkhead

// go:github.com/kitsunium/sdk/framework/kit.CLI alias github.com/kitsunium/sdk/framework/internal/kit.CLI doc:b223a364c4bab9ef80d09a229443812a127f238e30bffa3f21eb174aead761da
var _ *ikit.CLI = (*kit.CLI)(nil)

// go:github.com/kitsunium/sdk/framework/kit.CLIFunc alias github.com/kitsunium/sdk/framework/internal/kit.CLIFunc doc:4f0d680b256276a9fb9c5f32512e22a2befabac195b77b2a9938ff5feae7437c
var _ *ikit.CLIFunc = (*kit.CLIFunc)(nil)

// go:github.com/kitsunium/sdk/framework/kit.CLIOption alias github.com/kitsunium/sdk/framework/internal/kit.CommandLineConfigurer doc:9df76841ba6e77506840b937394914934e455bc312082ce5146ed91d609c280a
var _ *ikit.CommandLineConfigurer = (*kit.CLIOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Catalog func func() []github.com/kitsunium/sdk/framework/model.Mechanic doc:47fee59c78487e3e4dddac4584e2db18d23089a8684c52790de1ae8f9ec64967
var _ func() []model.Mechanic = kit.Catalog

// go:github.com/kitsunium/sdk/framework/kit.Change alias [E any, S comparable] github.com/kitsunium/sdk/framework/internal/kit.ChangeEvent[E, S] doc:7c9a17dd4b526bbcc70286f17fbd6e18df1a7a006566f8c291b16464a02bcf2a
func _[E any, S comparable]() {
	var _ *ikit.ChangeEvent[E, S] = (*kit.Change[E, S])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.ClearCookie func func(ctx context.Context, name string) doc:40ae6b7f594a8f14fe02c48c61096ca672d033d776dfb5f50a289762b0c04a42
var _ func(ctx context.Context, name string) = kit.ClearCookie

// go:github.com/kitsunium/sdk/framework/kit.ClientIP func func(ctx context.Context) string doc:b69ddabd1eff783092325cef92f0aa72a1a3c951d20471a317051212495e93bb
var _ func(ctx context.Context) string = kit.ClientIP

// go:github.com/kitsunium/sdk/framework/kit.Clock func func(c github.com/kitsunium/sdk/pkg/v1/clock.Timed) github.com/kitsunium/sdk/framework/kit.AppOption doc:4fc0bc065f5310cdc329abb15a6a08df33c075b761354f14bc48ad620c10ed2c
var _ func(c clock.Timed) kit.AppOption = kit.Clock

// go:github.com/kitsunium/sdk/framework/kit.CodeAppConfig const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:6c4d2759ebc09cc618ad68f75ee2c7872f0ac267cde15d1ffc97c944b3942f6e
func _() {
	x := kit.CodeAppConfig
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeAppConfig == 0x00_04_02_10: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeAppListen const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:2d0cfeddb12c534e3404ea7efc826709bf2a76a4273611cf188da99a3348ff2f
func _() {
	x := kit.CodeAppListen
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeAppListen == 0x00_04_02_12: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeAppRunning const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:f0eb0fe6387071bc1e4dc911e0315e1fa81cf940d1f6689adef41143ac07f3af
func _() {
	x := kit.CodeAppRunning
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeAppRunning == 0x00_04_02_11: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeCLIFailed const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:859db52709a3280db85dc222b6c3dbc1afd6912ba52e048a85cfb9d9d8006215
func _() {
	x := kit.CodeCLIFailed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeCLIFailed == 0x00_04_02_3B: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeCatalogue const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:9ff0b14ebc784a6cb3e146aa2428ff620bb881bce3edfe9e7965522381d19938
func _() {
	x := kit.CodeCatalogue
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeCatalogue == 0x00_04_02_38: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeCommandEncode const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:2cec3864629962a0557c58425a21dd9701657f4c7b45c3f2ac53362c904ffb93
func _() {
	x := kit.CodeCommandEncode
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeCommandEncode == 0x00_04_02_2E: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeCommandKey const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:98be1edd72d88b99e5e5485bb711b039a0a39f7082148a94a06215941c72bd39
func _() {
	x := kit.CodeCommandKey
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeCommandKey == 0x00_04_02_2C: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeCommandQueue const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:c5a2d56a2c16ed7dbfc273dff8d56b73d264fac018401b464c3e0fc33c89b181
func _() {
	x := kit.CodeCommandQueue
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeCommandQueue == 0x00_04_02_2D: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeCommandReentrant const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:81aaaf62aa2b1637cbc1515bd469b5105c08fa4b29ac36c5da1a9194e0a56150
func _() {
	x := kit.CodeCommandReentrant
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeCommandReentrant == 0x00_04_02_2B: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeDatabaseConfig const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:b9d69658eac2f0fa0cd5479f53fbbf21b3a85e5c9ec941e1b0878cff07b179bb
func _() {
	x := kit.CodeDatabaseConfig
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeDatabaseConfig == 0x00_04_02_22: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeDatabaseMigrate const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:f832bfc94e4dc6f2c1140fc45e1e60bddcd6c65e80ce58552b42ffbe28e6f0e1
func _() {
	x := kit.CodeDatabaseMigrate
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeDatabaseMigrate == 0x00_04_02_20: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeDatabaseOpen const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:78c4f45a67369d0ffe23b7995a560128f4f4f63e1a2cb66239143a39d9974a94
func _() {
	x := kit.CodeDatabaseOpen
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeDatabaseOpen == 0x00_04_02_1F: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeDatabaseUnavailable const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:bc04b22c70b9f606256aec120bb3d517a7b9ccb840e23e3ff9cd6af4a68f9fc4
func _() {
	x := kit.CodeDatabaseUnavailable
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeDatabaseUnavailable == 0x00_04_02_21: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeHandlerPanic const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:e8ce32331ba0e143a546d82745be9877ea0195f289acea6136fb8bd5e328f9ad
func _() {
	x := kit.CodeHandlerPanic
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeHandlerPanic == 0x00_04_02_0A: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeHistoryLoad const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:6492ec17c24e88b0b1dfe56130befabbb56ff1ca60e2b433f8270ef1ef48578f
func _() {
	x := kit.CodeHistoryLoad
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeHistoryLoad == 0x00_04_02_27: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeHistoryMoved const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:fdd849c56c650b1378af36bec830baa8e96dc06ae49e149251f5bc5b21dfc28a
func _() {
	x := kit.CodeHistoryMoved
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeHistoryMoved == 0x00_04_02_32: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeHistoryRead const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:b1eebf1e566c15d01bd152d803f93ac32dd160ac98714e6214131550664ca690
func _() {
	x := kit.CodeHistoryRead
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeHistoryRead == 0x00_04_02_29: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeHistoryWrite const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:98b2bafb318ac6a952c842643bce2546f3e2443e9cab0269a710990b4bf876e8
func _() {
	x := kit.CodeHistoryWrite
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeHistoryWrite == 0x00_04_02_28: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeJobOverlapped const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:0cf50f853bbcc3265ab36245644db0f5dd6de02b1d57033340d18fbca8e41e1a
func _() {
	x := kit.CodeJobOverlapped
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeJobOverlapped == 0x00_04_02_31: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeKeyRekeyed const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:7f36c375c42bbc717a6b308e25366f032695c0b847a7162e904ebd35990b80aa
func _() {
	x := kit.CodeKeyRekeyed
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeKeyRekeyed == 0x00_04_02_36: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeLoopNotMounted const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:c6833b17d4b0f6c4412f0aadee258e836a7644b2fef91960bea7fa830a6974df
func _() {
	x := kit.CodeLoopNotMounted
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeLoopNotMounted == 0x00_04_02_19: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeLoopPanic const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:e2fbbfa63060cb5fef53b8ffa4094c40c980faa84b517ed908b11034ac71a83c
func _() {
	x := kit.CodeLoopPanic
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeLoopPanic == 0x00_04_02_18: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeLoopStart const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:53ab2abd22b8ed8fc8534d35c14b52f25fbefb7a7b904ef0d85b57adc483b56f
func _() {
	x := kit.CodeLoopStart
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeLoopStart == 0x00_04_02_1A: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeMailConfig const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:be74c82b24281442d6cdd48d7177cd90df9ba7d43627e28ae0adcfc1701b7938
func _() {
	x := kit.CodeMailConfig
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeMailConfig == 0x00_04_02_13: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeMailEncode const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:0f0fe44852ca0c5d4a62b86932ba6b96812efbcef6964838d4c5e8e86454c513
func _() {
	x := kit.CodeMailEncode
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeMailEncode == 0x00_04_02_14: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeMailPanic const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:a28059dea6f926384c36a668a8598bd35327730b1bd66d807b3fba75d57f81c5
func _() {
	x := kit.CodeMailPanic
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeMailPanic == 0x00_04_02_17: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeMailQueue const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:b2ef1cd89e872e1c53fca387aa4654e569fe6c9ef94c6a04ca7b1634dce84bc8
func _() {
	x := kit.CodeMailQueue
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeMailQueue == 0x00_04_02_15: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeMailUndecodable const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:dd12e154e2492996f5701117898863e5d7706aa08b6a35aca1dd2c7ebc02dadc
func _() {
	x := kit.CodeMailUndecodable
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeMailUndecodable == 0x00_04_02_16: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeMigrateRefused const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:2b375e7734638c46e072de302deb2e83d470600c7aa3cce57cddeff9ca66717d
func _() {
	x := kit.CodeMigrateRefused
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeMigrateRefused == 0x00_04_02_37: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeNotMounted const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:e0ac1e256276c67297ec777ffd2ea3f20748c5f231c9979baa19786ed3f74176
func _() {
	x := kit.CodeNotMounted
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeNotMounted == 0x00_04_02_0B: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeNotSource const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:424c8314c828df888b4a3cee5d1c60bc821dea1f43ece163ec2bfd652097c018
func _() {
	x := kit.CodeNotSource
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeNotSource == 0x00_04_02_33: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeNothingToErase const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:372830c487bc08d1e4ed37c526821da857cc05e12c7dee146631c23701c62e2b
func _() {
	x := kit.CodeNothingToErase
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeNothingToErase == 0x00_04_02_35: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodePasswordHash const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:2bbed0bd6051da4afc33475c858763960fc22b3ef9ca692448c38565e9b67f96
func _() {
	x := kit.CodePasswordHash
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodePasswordHash == 0x00_04_02_2A: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodePasswordMoved const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:9bb79857c11ba4b95603974dd07d620397f5718d2f96b20e83614ce192a7a46a
func _() {
	x := kit.CodePasswordMoved
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodePasswordMoved == 0x00_04_02_34: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodePrivacyData const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:823760a25870b2772706d9da9e74ec72fba97084ac23eba2362d317d120ca626
func _() {
	x := kit.CodePrivacyData
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodePrivacyData == 0x00_04_02_26: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodePrivacyErase const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:dedee8d79dd5073f3800890a8482ee7427fda60d9180e19472d0c1ad11db2105
func _() {
	x := kit.CodePrivacyErase
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodePrivacyErase == 0x00_04_02_24: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodePrivacyJournal const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:ba08988f74f1b02041b117b145411a53388ae5b20ffdab8ddf1e5eccccef97b3
func _() {
	x := kit.CodePrivacyJournal
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodePrivacyJournal == 0x00_04_02_25: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodePrivacyKey const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:a52821af4bab3d72040a87b9c84cd0e9824ed7753f5466635f09c38599fd00f1
func _() {
	x := kit.CodePrivacyKey
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodePrivacyKey == 0x00_04_02_23: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeProfileRead const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:fe2b2c5244f2b4acd41399880c380530a0fc55fc01f89440faa13f33712e019f
func _() {
	x := kit.CodeProfileRead
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeProfileRead == 0x00_04_02_30: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeQueueOpen const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:03877b416789dd413642db122206dfd01e6a641a971e52f73071d95117330bca
func _() {
	x := kit.CodeQueueOpen
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeQueueOpen == 0x00_04_02_08: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeResealInPlace const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:3ef6b225d0bc95c1b9f23c29e51b7c451faf957f8cbdd809036e5fa7bb109119
func _() {
	x := kit.CodeResealInPlace
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeResealInPlace == 0x00_04_02_48: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeResealMoved const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:ad9c02db0551b15b027f0824c2c3bab7fe148ee0ac6a8f841b872c07dc4fff7f
func _() {
	x := kit.CodeResealMoved
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeResealMoved == 0x00_04_02_49: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeRetentionPanic const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:336d064a88803cc70b6c1ea2353da747634fa113ac132fbccf6ba8eb260eba5e
func _() {
	x := kit.CodeRetentionPanic
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeRetentionPanic == 0x00_04_02_39: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeRevisionDecode const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:33169151b85b44b3a2041850da14445bd91ec548f9911b42bfdc1f8128e743a0
func _() {
	x := kit.CodeRevisionDecode
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeRevisionDecode == 0x00_04_02_45: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeRevisionRead const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:06f355615945a8cd811be3bcbdefe28e9e0fb642450c88346dbf6598f46f00c4
func _() {
	x := kit.CodeRevisionRead
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeRevisionRead == 0x00_04_02_43: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeRevisionWrite const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:6865588884ba2a4658d3b306c3dded498854fccf30607e7e46289c5a94a3cdb3
func _() {
	x := kit.CodeRevisionWrite
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeRevisionWrite == 0x00_04_02_44: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeScopeUnknown const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:5b2a1ff38be090098bdf75b8aad25369c9740213d5c23e1e904624cfd909d5fb
func _() {
	x := kit.CodeScopeUnknown
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeScopeUnknown == 0x00_04_02_3C: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSealErased const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:85ab8755f02ee3ca6788bcfae8570f7a1ffa5d93f1e499134749d7b664ee9330
func _() {
	x := kit.CodeSealErased
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSealErased == 0x00_04_02_46: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSealKey const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:007f61c791ab1409957a6cbc6847b4a2efb5a82dbd73f363d48573a9aa16ec6d
func _() {
	x := kit.CodeSealKey
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSealKey == 0x00_04_02_3D: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSealKeyMoved const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:b9770f089e8bbfedd08301bc1d3b25d1c49accbf37396f580d9e173a8ee07600
func _() {
	x := kit.CodeSealKeyMoved
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSealKeyMoved == 0x00_04_02_47: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSealOpen const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:5f0b9f6f73905659c7cc53b5afa7d421fefa13216c4406579fd04b5a8261c414
func _() {
	x := kit.CodeSealOpen
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSealOpen == 0x00_04_02_3F: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSealRewrap const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:7b715a8c596350796e3622124e96f8abc7673cee6960aae4b9b3d8b311d5ef66
func _() {
	x := kit.CodeSealRewrap
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSealRewrap == 0x00_04_02_40: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSealShred const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:c71165626110a062fe7b1c371dc151b23098d04b8a15b7980b33fe49afe79483
func _() {
	x := kit.CodeSealShred
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSealShred == 0x00_04_02_41: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSealWrite const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:ea3e39cdb7a336649c3e19c7cdea70d1c2001233d33c2049540c730b1415d2ee
func _() {
	x := kit.CodeSealWrite
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSealWrite == 0x00_04_02_3E: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSecretMissing const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:4873fc722ac4bbfb2c2cc2bcff46e1023705574c8b8e2a05e54752afce371928
func _() {
	x := kit.CodeSecretMissing
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSecretMissing == 0x00_04_02_1C: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSecretRead const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:7c76a43580c6143ba07905118a9f8ab849adef6ebb7d091c56bec54caf7f1bd6
func _() {
	x := kit.CodeSecretRead
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSecretRead == 0x00_04_02_1D: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSecretRotate const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:21f8b5b70d6e44d9bb63d058ee3cceaf0f5a26ed9eb5166cd716f5073d9be2af
func _() {
	x := kit.CodeSecretRotate
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSecretRotate == 0x00_04_02_1E: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSecretStore const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:ff7a49ee7040bbeda8727688099ac2102c66aa5dfddd2f3ae080a42eeeb51c54
func _() {
	x := kit.CodeSecretStore
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSecretStore == 0x00_04_02_1B: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeSingletonHeld const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:e8d17c2896be609dadca6793743361680b77890653f4f0f0e4b9c3796a937f96
func _() {
	x := kit.CodeSingletonHeld
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeSingletonHeld == 0x00_04_02_3A: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeStoreDecode const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:0acd88fb1791f15425cc760a7ee2a411ed631c29d5c41ff8d0a4b3b7c5dc4ef5
func _() {
	x := kit.CodeStoreDecode
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeStoreDecode == 0x00_04_02_01: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeStoreEncode const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:42d7f7ea89f3490e77494c19fba1770bfaa2a34a1d5eaf26ebc42b5ccf23e4da
func _() {
	x := kit.CodeStoreEncode
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeStoreEncode == 0x00_04_02_02: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeStoreIndex const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:d260e36bee47af4995f24650d7c61d0df7396354126e17906edf0f3f8b4de1b6
func _() {
	x := kit.CodeStoreIndex
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeStoreIndex == 0x00_04_02_05: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeStoreLoad const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:45edd56b3d00a1d433dcc1f651d48e744427c930b63d7eadf64c7b2accf82d5a
func _() {
	x := kit.CodeStoreLoad
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeStoreLoad == 0x00_04_02_04: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeStorePersist const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:c49b78d52d4728ee44c061483f5d18c1708723998a6a513a83e512f81683eed9
func _() {
	x := kit.CodeStorePersist
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeStorePersist == 0x00_04_02_03: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeTopicEncode const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:490554f800f10833f9ab78db5f85b4fef862ea573003d7b1d61098de8d40d237
func _() {
	x := kit.CodeTopicEncode
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeTopicEncode == 0x00_04_02_06: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeTopicPublish const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:a4f0f1b1e68c8c1921917f423baafac6575c82d6eeadd7880719b6b9b27d297b
func _() {
	x := kit.CodeTopicPublish
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeTopicPublish == 0x00_04_02_07: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeTransactionPanic const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:c75524f6233f0848753b908901781f3242273500484a6f5356e3a17052d7ee6f
func _() {
	x := kit.CodeTransactionPanic
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeTransactionPanic == 0x00_04_02_4B: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeTransactionSpan const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:fd361037598c07019e73decfe381b97eb7bd880a3e23a7918f55d67e8d39e737
func _() {
	x := kit.CodeTransactionSpan
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeTransactionSpan == 0x00_04_02_42: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeUndecodable const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:6c53f3e5f26afd24d6a7230d65e41164b40a8ccb9cfe77f5db0d5326d533a799
func _() {
	x := kit.CodeUndecodable
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeUndecodable == 0x00_04_02_09: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeWatchQueue const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:f5d44f17a45b87b4777b1533b60554ac9859763603712afd039eca4e09d59232
func _() {
	x := kit.CodeWatchQueue
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeWatchQueue == 0x00_04_02_2F: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeWorkflowHookChange const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:dc5bdb23918d3d3e9554ab417d445c3d261746870ef36c42c78429fea0ec3d53
func _() {
	x := kit.CodeWorkflowHookChange
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeWorkflowHookChange == 0x00_04_02_0E: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeWorkflowHookPanic const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:967edc91e210a16cf664641d974dfa9bc8d2df41a8a1ac3af02c1e34fac40a15
func _() {
	x := kit.CodeWorkflowHookPanic
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeWorkflowHookPanic == 0x00_04_02_0D: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeWorkflowLoad const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:f4d9916a69dbafe7ad022ded1e0e43401202a38d4fafa454c977061b541d0654
func _() {
	x := kit.CodeWorkflowLoad
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeWorkflowLoad == 0x00_04_02_0C: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeWorkflowNotInPlace const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:a25b7a3df611d88032b9d7c52b0374fbc4a94c2d8197710b7c456b21b4cdbe7a
func _() {
	x := kit.CodeWorkflowNotInPlace
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeWorkflowNotInPlace == 0x00_04_02_4A: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.CodeWorkflowReentrant const github.com/kitsunium/sdk/pkg/v1/errs.Code doc:cc58babec3ecdec6f373fb76b39f1f926b20dbd5f4883481a79242bf6b948b90
func _() {
	x := kit.CodeWorkflowReentrant
	var _ *errs.Code = &x
	_ = map[bool]int{false: 0, kit.CodeWorkflowReentrant == 0x00_04_02_0F: 1}
}

// go:github.com/kitsunium/sdk/framework/kit.Command alias [C, R any] github.com/kitsunium/sdk/framework/internal/kit.Command[C, R] doc:03f546da96bb5b979685c976912cf3b90643cd7756f763cc04a7a1a963033b07
func _[C, R any]() {
	var _ *ikit.Command[C, R] = (*kit.Command[C, R])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.CommandOption alias github.com/kitsunium/sdk/framework/internal/kit.CommandConfigurer doc:9474f7de383374c4dcde723d1154c3748ce35f5e45cdd24fe44f4e7003c34432
var _ *ikit.CommandConfigurer = (*kit.CommandOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.ConfigFiles func func(fsys io/fs.FS) github.com/kitsunium/sdk/framework/kit.AppOption doc:30c48b24b44ad1b117ab481aeeea767e627fe42bed276765fa3173b973d3a788
var _ func(fsys fs.FS) kit.AppOption = kit.ConfigFiles

// go:github.com/kitsunium/sdk/framework/kit.Conflict func func(message string) *github.com/kitsunium/sdk/framework/kit.Error doc:e0d8ac67f14aa011848e873bd4ca0ad09644d8f79c31d0a8481b733fd2dd3e09
var _ func(message string) *kit.Error = kit.Conflict

// go:github.com/kitsunium/sdk/framework/kit.DataDir func func(dir string) github.com/kitsunium/sdk/framework/kit.AppOption doc:6317cfcb095d573e3e8f68be60385065672ce9100dd6c3b61721fb808fc6237f
var _ func(dir string) kit.AppOption = kit.DataDir

// go:github.com/kitsunium/sdk/framework/kit.Database func func(name string, engine github.com/kitsunium/sdk/framework/kit.Engine, opts ...github.com/kitsunium/sdk/framework/kit.DatabaseOption) github.com/kitsunium/sdk/framework/kit.AppOption doc:daf0c6239814d982c34646686cad7832cd5bb7e4a6cc8caff32bc206909d476d
var _ func(name string, engine kit.Engine, opts ...kit.DatabaseOption) kit.AppOption = kit.Database

// go:github.com/kitsunium/sdk/framework/kit.DatabaseOption alias github.com/kitsunium/sdk/framework/internal/kit.DatabaseConfigurer doc:fcce286bc55738d17199028e15d9978ee5329c2fd3e7a4c0a077a638cf020360
var _ *ikit.DatabaseConfigurer = (*kit.DatabaseOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.DatabaseURL alias github.com/kitsunium/sdk/framework/internal/kit.DatabaseURLValue doc:1322d2c89542348d4300ad1c5ed720172a7e1c7d8e048e03f227b0ff17ece1e4
var _ *ikit.DatabaseURLValue = (*kit.DatabaseURL)(nil)

// go:github.com/kitsunium/sdk/framework/kit.DefaultCommand func func() github.com/kitsunium/sdk/framework/kit.CLIOption doc:7a61bfda58974f7a36125d3d29b5520c89e744e1f767aaaa4f2fd72cc02dee10
var _ func() kit.CLIOption = kit.DefaultCommand

// go:github.com/kitsunium/sdk/framework/kit.DefaultMaxBody const int64 doc:2402078e38042af89b826918dba1e644dd060817701da0e66ba5b3e8ee0deffa
func _() {
	x := kit.DefaultMaxBody
	var _ *int64 = &x
	_ = map[bool]int{false: 0, kit.DefaultMaxBody == (1 << 20): 1}
}

// go:github.com/kitsunium/sdk/framework/kit.Delay alias github.com/kitsunium/sdk/framework/internal/kit.Delay doc:29a980d5a372a76e1f981ab200612d84f7795a08a7f602dc022779f4d6bf86a7
func _[X kit.Delay]() {}

// go:github.com/kitsunium/sdk/framework/kit.DeleteAfter[...] func func[T any, D github.com/kitsunium/sdk/framework/kit.Delay](delay D, since func(T) (time.Time, bool)) github.com/kitsunium/sdk/framework/kit.StoreOption doc:3f19374d9e4e55d85a7f1dbe590066a82b2d59be5dd0dfd46750969703596188
func _[T any, D kit.Delay]() {
	var _ func(delay D, since func(T) (time.Time, bool)) kit.StoreOption = kit.DeleteAfter[T, D]
}

// go:github.com/kitsunium/sdk/framework/kit.DeleteAt[...] func func[T any](at func(T) (time.Time, bool)) github.com/kitsunium/sdk/framework/kit.StoreOption doc:c0cf26ba7ca952c3f88b504008771d6304cf8e149b6f2eba8228a797fe9b3e64
func _[T any]() {
	var _ func(at func(T) (time.Time, bool)) kit.StoreOption = kit.DeleteAt[T]
}

// go:github.com/kitsunium/sdk/framework/kit.DeleteOnErasure func func() github.com/kitsunium/sdk/framework/kit.StoreOption doc:348b59aba49f8bc9f6294e1f976435c18f11270a11a19630742d4907fdffb8d9
var _ func() kit.StoreOption = kit.DeleteOnErasure

// go:github.com/kitsunium/sdk/framework/kit.DeliveryOption alias github.com/kitsunium/sdk/framework/internal/kit.DeliveryOption doc:f4eb8960a516d653f7fa88cea540044f875bf135ac95b8e6b2029e7ac75d6624
var _ *ikit.DeliveryOption = (*kit.DeliveryOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.DesignDigest func func(digest string) github.com/kitsunium/sdk/framework/kit.AppOption doc:e816b2a0e0ba44a7ea4fd35ccfd36f3a9ef058997bf74f7226f260ddc29aafa9
var _ func(digest string) kit.AppOption = kit.DesignDigest

// go:github.com/kitsunium/sdk/framework/kit.DiagnosticsError alias github.com/kitsunium/sdk/framework/internal/kit.DiagnosticsError doc:12a045be1844eb099450c3bf9747ddeba39ca8b20b9dc47db5fcfe8a35884417
var _ *ikit.DiagnosticsError = (*kit.DiagnosticsError)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Edit alias github.com/kitsunium/sdk/framework/internal/kit.Edit doc:64bfaebae24bd4407721dce7df722e7fdc823ac027537958bf073b6bf4e73e7e
var _ *ikit.Edit = (*kit.Edit)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Empty alias github.com/kitsunium/sdk/framework/internal/kit.EmptyValue doc:55729b01577a2ba1b754edc06a5d33b1ce11ad8ce1402236b97bf7b53e44c9dc
var _ *ikit.EmptyValue = (*kit.Empty)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Endpoint alias [Req, Resp any] github.com/kitsunium/sdk/framework/internal/kit.EndpointService[Req, Resp] doc:66838eb74212fdf927ab563b7b945d6310fb79972a238443b0b4fd53f9bfef43
func _[Req, Resp any]() {
	var _ *ikit.EndpointService[Req, Resp] = (*kit.Endpoint[Req, Resp])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.EndpointOption alias github.com/kitsunium/sdk/framework/internal/kit.EndpointConfigurer doc:d14c48a30937324fde95f1a3c414960d37f1ab0acbce9d95cf7858d2f49fb06c
var _ *ikit.EndpointConfigurer = (*kit.EndpointOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Engine alias github.com/kitsunium/sdk/framework/internal/kit.Engine doc:2b5c1e921c022aa8cafaa17c3365cb4c4a64dea08235e715ee83d2edfafe956d
var _ *ikit.Engine = (*kit.Engine)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Env func func(env string) github.com/kitsunium/sdk/framework/kit.AppOption doc:6d5f5563a4063fc135fef33719e257b42a8cba1a0ca4731341cea3594211ebd4
var _ func(env string) kit.AppOption = kit.Env

// go:github.com/kitsunium/sdk/framework/kit.EnvDev const string doc:00bc9ab3acd36b55a3f9b3d0852f5750b71e5fe826f9ea53a46c1733c4229fba
func _() {
	x := kit.EnvDev
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.EnvDev == "dev": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.EnvProduction const string doc:c3ddf0f0e6f916f7761f16cc6af92fcf07a920c262047274542bc0018d854f9f
func _() {
	x := kit.EnvProduction
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.EnvProduction == "production": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.Erase func func(ctx context.Context, reason string, ids ...string) (github.com/kitsunium/sdk/framework/kit.Erasure, error) doc:8aad6da71fd836ccce73277f3c7952e51d0a0641beb3435df14c77d387faa3b5
var _ func(ctx context.Context, reason string, ids ...string) (kit.Erasure, error) = kit.Erase

// go:github.com/kitsunium/sdk/framework/kit.EraseAfter[...] func func[T any, D github.com/kitsunium/sdk/framework/kit.Delay](delay D, since func(T) (time.Time, bool)) github.com/kitsunium/sdk/framework/kit.StoreOption doc:cb5a12b53c2d9bf997bd646392511b733f00f98da5be7f1cefac7b2e50080616
func _[T any, D kit.Delay]() {
	var _ func(delay D, since func(T) (time.Time, bool)) kit.StoreOption = kit.EraseAfter[T, D]
}

// go:github.com/kitsunium/sdk/framework/kit.EraseAt[...] func func[T any](at func(T) (time.Time, bool)) github.com/kitsunium/sdk/framework/kit.StoreOption doc:704a2afc293eb26f3393816b9f7ac250340751b07269bce2b14fad522a2564e4
func _[T any]() {
	var _ func(at func(T) (time.Time, bool)) kit.StoreOption = kit.EraseAt[T]
}

// go:github.com/kitsunium/sdk/framework/kit.Erasure alias github.com/kitsunium/sdk/framework/internal/kit.Erasure doc:83da9d56166517fee79b1b25c18a38982a2b638c1aad2b1a1a6298b390b69046
var _ *ikit.Erasure = (*kit.Erasure)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Error alias github.com/kitsunium/sdk/framework/internal/kit.Error doc:849042fff8d2b7f787c721f9248f3d8230b9ff1735f44b0db44aca6292687100
var _ *ikit.Error = (*kit.Error)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Export func func(ctx context.Context, ids ...string) (github.com/kitsunium/sdk/framework/kit.PersonalData, error) doc:905bea0ec29fe60b3d4bce0e844f88721d6d418a70bac3154a6b32bea243b580
var _ func(ctx context.Context, ids ...string) (kit.PersonalData, error) = kit.Export

// go:github.com/kitsunium/sdk/framework/kit.ExposeOption alias github.com/kitsunium/sdk/framework/internal/kit.ExposeConfigurer doc:54b36b34c3ca117ae4c8c73894a5dc04facbbe8dcd33c89a6386a64a0b84db93
var _ *ikit.ExposeConfigurer = (*kit.ExposeOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.FailSafe func func() github.com/kitsunium/sdk/framework/kit.CLIOption doc:e0e4024ccb53a8b93b6be878c36e0d3ebfcf3112e759610adfe55164a480dbce
var _ func() kit.CLIOption = kit.FailSafe

// go:github.com/kitsunium/sdk/framework/kit.Fallback[...] func func[Req, Resp any](op github.com/kitsunium/sdk/framework/internal/kit.Operation[Req, Resp]) github.com/kitsunium/sdk/framework/internal/kit.PortConfigurer[Req, Resp] doc:e74871835a07d3e6290c5e5b88d33eaa543f1ad6393a831841cd9cf2d4c557d0
func _[Req, Resp any]() {
	var _ func(op ikit.Operation[Req, Resp]) ikit.PortConfigurer[Req, Resp] = kit.Fallback[Req, Resp]
}

// go:github.com/kitsunium/sdk/framework/kit.FieldRef alias github.com/kitsunium/sdk/framework/internal/kit.FieldRefValue doc:5c14c8704698a06c998d7a86fa8169749ff8818d3263437314f1f3bdc6515f1a
var _ *ikit.FieldRefValue = (*kit.FieldRef)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Forbidden func func(message string) *github.com/kitsunium/sdk/framework/kit.Error doc:169065257bc7d2c49b0976e2b2215cbcefbd4d81ea438b1a1572be88d2734d0d
var _ func(message string) *kit.Error = kit.Forbidden

// go:github.com/kitsunium/sdk/framework/kit.Former alias github.com/kitsunium/sdk/framework/internal/kit.Former doc:656a41478a6bcf0c22b7dd12ca20678bc5c9acd27bf4e0c3836b71943f2b3278
var _ *ikit.Former = (*kit.Former)(nil)

// go:github.com/kitsunium/sdk/framework/kit.From func func(name string, addr string) github.com/kitsunium/sdk/framework/kit.MailerOption doc:7bd96c9811b76dadfd3c966b1ea0a594aca707247cf73dca3de8cd3ee0b4613f
var _ func(name, addr string) kit.MailerOption = kit.From

// go:github.com/kitsunium/sdk/framework/kit.Frontend alias github.com/kitsunium/sdk/framework/internal/kit.Frontend doc:2e926324bb2f40d052ccada8ff312b5a43d2bd9eeb5bb7e6b253ed00e52dad47
var _ *ikit.Frontend = (*kit.Frontend)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Generated func func(bytes int) github.com/kitsunium/sdk/framework/kit.SecretOption doc:4147250f12b2f091b857b30e6d2bc33211f3bcfb7d914e958e157c3300300c10
var _ func(bytes int) kit.SecretOption = kit.Generated

// go:github.com/kitsunium/sdk/framework/kit.HeldUntil[...] func func[T any](until func(T) (time.Time, bool), reason string) github.com/kitsunium/sdk/framework/kit.StoreOption doc:0b5a9d6064f5ebd4ba3f65227cfa9c0806e220a7628057911c66a2592f802c3d
func _[T any]() {
	var _ func(until func(T) (time.Time, bool), reason string) kit.StoreOption = kit.HeldUntil[T]
}

// go:github.com/kitsunium/sdk/framework/kit.HoldSubject func func(ctx context.Context, reason string, ids ...string) error doc:7c0f0d6dc655f006ae5c557e45e909c74ae2169f1d84f81c3ccf432b5e73b272
var _ func(ctx context.Context, reason string, ids ...string) error = kit.HoldSubject

// go:github.com/kitsunium/sdk/framework/kit.IdleStop func func(d time.Duration) github.com/kitsunium/sdk/framework/kit.AppOption doc:84fd22c5c4539ade1ba8956bc21cb594fd720179bd92dc99011a6b9065fb6d34
var _ func(d time.Duration) kit.AppOption = kit.IdleStop

// go:github.com/kitsunium/sdk/framework/kit.InMemory func func() interface{github.com/kitsunium/sdk/framework/kit.StoreOption; github.com/kitsunium/sdk/framework/kit.AppOption} doc:5c1ad33d7c057efc94808e2165b1ca4d1e628b66304b0be9625ead317754f587
var _ func() interface {
	kit.StoreOption
	kit.AppOption
} = kit.InMemory

// go:github.com/kitsunium/sdk/framework/kit.Index[...] func func[T any](name string, keys func(T) []string) github.com/kitsunium/sdk/framework/kit.StoreOption doc:ecbad822f5da5c08c7c7c7c4721a0d807fbac8833b2c1135187e021732309145
func _[T any]() {
	var _ func(name string, keys func(T) []string) kit.StoreOption = kit.Index[T]
}

// go:github.com/kitsunium/sdk/framework/kit.Invalid func func(message string) *github.com/kitsunium/sdk/framework/kit.Error doc:d082d7ca8e42248993a97993145c15fac764e37859d891551744ebebb7b42885
var _ func(message string) *kit.Error = kit.Invalid

// go:github.com/kitsunium/sdk/framework/kit.Job alias github.com/kitsunium/sdk/framework/internal/kit.Job doc:9864b52d11baecef15e8e6dac1a0b1da77a48cfe29819537594e62875965b50d
var _ *ikit.Job = (*kit.Job)(nil)

// go:github.com/kitsunium/sdk/framework/kit.KeepVersions func func(n int) github.com/kitsunium/sdk/framework/kit.SecretOption doc:1073a9e007961d9dfe09f7787af2a1a55cd742183b5a2db99ea6bbcca0f33693
var _ func(n int) kit.SecretOption = kit.KeepVersions

// go:github.com/kitsunium/sdk/framework/kit.Keepable alias github.com/kitsunium/sdk/framework/internal/kit.Keeper doc:da0112dc50344a1c09ed11a2c233d5847524311dcd302748005f243192783d7d
var _ *ikit.Keeper = (*kit.Keepable)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Keeps func func(things ...github.com/kitsunium/sdk/framework/kit.Keepable) github.com/kitsunium/sdk/framework/kit.DatabaseOption doc:a75d6fa7d67e60c79fb275360b9909dde2e33d355567ed7526c12979700a3d7e
var _ func(things ...kit.Keepable) kit.DatabaseOption = kit.Keeps

// go:github.com/kitsunium/sdk/framework/kit.Listen func func(addr string) github.com/kitsunium/sdk/framework/kit.AppOption doc:52e9530ebb4c6a605f3c4a25b73f33c82e2e15d446f114c34f66b37683b8d363
var _ func(addr string) kit.AppOption = kit.Listen

// go:github.com/kitsunium/sdk/framework/kit.ListenHandler alias github.com/kitsunium/sdk/framework/internal/kit.ListenHandler doc:cff862612414ce518784a67d7d693e2833c0b49a9afb07d07c88bff90f86f737
var _ *ikit.ListenHandler = (*kit.ListenHandler)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Listener alias github.com/kitsunium/sdk/framework/internal/kit.Listener doc:8ae9d5bbafb0bc0fba3965b5c183de7a11fe32f4d0b53b40033f8270f496bc0a
var _ *ikit.Listener = (*kit.Listener)(nil)

// go:github.com/kitsunium/sdk/framework/kit.ListenerOption alias github.com/kitsunium/sdk/framework/internal/kit.ListenerConfigurer doc:545eb17555d6384b41f96bd769b6024fb945a4bf0afd1a6559acc3f17488893f
var _ *ikit.ListenerConfigurer = (*kit.ListenerOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Log func func(ctx context.Context) github.com/kitsunium/sdk/pkg/v1/observe/logger.Logger doc:c04a7afc2653ec9e33277decc7ea77f7d162d9c4ceac992661497b3f88e6f4e9
var _ func(ctx context.Context) logger.Logger = kit.Log

// go:github.com/kitsunium/sdk/framework/kit.Logs func func(w io.Writer) github.com/kitsunium/sdk/framework/kit.AppOption doc:825c5434e2a3fcdeb9a33a10c9085317044f6ac780f4128ece877b544aae0066
var _ func(w io.Writer) kit.AppOption = kit.Logs

// go:github.com/kitsunium/sdk/framework/kit.Loop alias github.com/kitsunium/sdk/framework/internal/kit.Loop doc:6bb8fff8e56b579d615ce8a8d9e431f684bf01e594eb6aa4e3d25cdc55c98590
var _ *ikit.Loop = (*kit.Loop)(nil)

// go:github.com/kitsunium/sdk/framework/kit.LoopOption alias github.com/kitsunium/sdk/framework/internal/kit.LoopConfigurer doc:183a27bb468a41024a31bcd0c2c71f68692679ac6e02127083a2a7a4d16f6f2d
var _ *ikit.LoopConfigurer = (*kit.LoopOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.MailAttempts func func(n int) github.com/kitsunium/sdk/framework/kit.MailerOption doc:aedd79d1d50fde8ed3fe2f679d3e7048959a7fd67d3236ee73b827d5f02af47c
var _ func(n int) kit.MailerOption = kit.MailAttempts

// go:github.com/kitsunium/sdk/framework/kit.Mailer alias github.com/kitsunium/sdk/framework/internal/kit.Mailer doc:96c89b721454bfd1433cb3610c3267ff1f5afc9b656a1eb980d442e26cd7a33c
var _ *ikit.Mailer = (*kit.Mailer)(nil)

// go:github.com/kitsunium/sdk/framework/kit.MailerOption alias github.com/kitsunium/sdk/framework/internal/kit.MailerConfigurer doc:b4f91e3e6ce5e440d342e5befca99a24b8b419257cac9990987feb8f517f653b
var _ *ikit.MailerConfigurer = (*kit.MailerOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Mark alias github.com/kitsunium/sdk/framework/internal/kit.Mark doc:0df1611b287cba25fa40af5f563635222dace05c12a8bc79e53903829a450e2f
var _ *ikit.Mark = (*kit.Mark)(nil)

// go:github.com/kitsunium/sdk/framework/kit.MaxBody func func(bytes int64) github.com/kitsunium/sdk/framework/kit.EndpointOption doc:2b83b9b5f8bacd0390caa9682c76e1c285daeb5bec47b80e64b85ebc92d9a8fd
var _ func(bytes int64) kit.EndpointOption = kit.MaxBody

// go:github.com/kitsunium/sdk/framework/kit.MaxDeliveries func func(n int) github.com/kitsunium/sdk/framework/kit.DeliveryOption doc:94100b04e153e43caaa81632bcec32bc282753deed500c0aaf007a443e3a9c7d
var _ func(n int) kit.DeliveryOption = kit.MaxDeliveries

// go:github.com/kitsunium/sdk/framework/kit.Migrations func func(m ...github.com/kitsunium/sdk/pkg/v1/data/sql.Migration) interface{github.com/kitsunium/sdk/framework/kit.DatabaseOption; github.com/kitsunium/sdk/framework/kit.ModulePart} doc:1dac20a9bc03838fe6ef948d65fc5238a70166c73084702f3c44275beffa3cae
var _ func(m ...sql.Migration) interface {
	kit.DatabaseOption
	kit.ModulePart
} = kit.Migrations

// go:github.com/kitsunium/sdk/framework/kit.MinLength func func(n int) github.com/kitsunium/sdk/framework/kit.PasswordOption doc:307025a3cf3bf7793bc92ebc6a123c69fdc74dfe33fe187d008160e1754bd03d
var _ func(n int) kit.PasswordOption = kit.MinLength

// go:github.com/kitsunium/sdk/framework/kit.Moderated const github.com/kitsunium/sdk/framework/kit.Mark doc:ea97ef0c59aebc668aefaf4802642feee31f9ab5a911f9811aae47d85a1c8552
func _() {
	x := kit.Moderated
	var _ *kit.Mark = &x
	_ = map[bool]int{false: 0, kit.Moderated == "moderated": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.Module alias github.com/kitsunium/sdk/framework/internal/kit.Module doc:9b6b88ee29b98149ba1234884d9cb4a80de6838abac31fcc368dbaf41a283a63
var _ *ikit.Module = (*kit.Module)(nil)

// go:github.com/kitsunium/sdk/framework/kit.ModulePart alias github.com/kitsunium/sdk/framework/internal/kit.ModuleConfigurer doc:2228f87788a67e0e37d6236e8732056074200c5b7e4c4ca9c2644ff9b2afedbe
var _ *ikit.ModuleConfigurer = (*kit.ModulePart)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Mount func func(m *github.com/kitsunium/sdk/framework/kit.Module, opts ...github.com/kitsunium/sdk/framework/kit.MountOption) github.com/kitsunium/sdk/framework/kit.AppOption doc:4a43c60746f78e7ca43db6587ce3ecb905b884f5f6db17acef4dae29034ac1e6
var _ func(m *kit.Module, opts ...kit.MountOption) kit.AppOption = kit.Mount

// go:github.com/kitsunium/sdk/framework/kit.MountOption alias github.com/kitsunium/sdk/framework/internal/kit.MountConfigurer doc:0c6dfb0bb4fab34a2eaffaa3ba204ff65de865a25f4e9c2d6810a8efbc4876c1
var _ *ikit.MountConfigurer = (*kit.MountOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Name func func(name string) github.com/kitsunium/sdk/framework/kit.EndpointOption doc:a0afed2e7b796ecf7ca414f5f5400af66b6b073d521dbd133c29739d2e7a4239
var _ func(name string) kit.EndpointOption = kit.Name

// go:github.com/kitsunium/sdk/framework/kit.NewApp func func(name string, services ...*github.com/kitsunium/sdk/framework/kit.Service) *github.com/kitsunium/sdk/framework/kit.App doc:e270d7f13d902b46f2d5b865088128b3ea31fd0c85b4897b2789f28959f5ee05
var _ func(name string, services ...*kit.Service) *kit.App = kit.NewApp

// go:github.com/kitsunium/sdk/framework/kit.NewBinary func func(name string, doc string) *github.com/kitsunium/sdk/framework/kit.Binary doc:fa6be1402dbefda5fbed10b7920b772d9821f313318c61634ddb027afacc492e
var _ func(name, doc string) *kit.Binary = kit.NewBinary

// go:github.com/kitsunium/sdk/framework/kit.NewID func func(prefix string) string doc:9e051124a1569cfb308139605e0ba661939d429e1abeb74876d065ad53b9694f
var _ func(prefix string) string = kit.NewID

// go:github.com/kitsunium/sdk/framework/kit.NewModule func func(name string, doc string, parts ...github.com/kitsunium/sdk/framework/kit.ModulePart) *github.com/kitsunium/sdk/framework/kit.Module doc:610dbcc53a094d436ecbcd35660fb354e4287f4c313514f91ca02509f3d4d9a9
var _ func(name, doc string, parts ...kit.ModulePart) *kit.Module = kit.NewModule

// go:github.com/kitsunium/sdk/framework/kit.NewService func func(name string, doc string) *github.com/kitsunium/sdk/framework/kit.Service doc:4ac2f37fbfcb365faa7161c76d6ba1ad49d2d2d221ac240aa806c4d74bb82413
var _ func(name, doc string) *kit.Service = kit.NewService

// go:github.com/kitsunium/sdk/framework/kit.NewTicker func func(ctx context.Context, d time.Duration) github.com/kitsunium/sdk/pkg/v1/clock.Ticker doc:fee3f9a010faef4b21b01723082376858d69292c4f507a40f42105f91169b19f
var _ func(ctx context.Context, d time.Duration) clock.Ticker = kit.NewTicker

// go:github.com/kitsunium/sdk/framework/kit.NoTransaction func func() github.com/kitsunium/sdk/framework/kit.CommandOption doc:ba7443a210d4fb75ba7cf02c3f532c89892870f484a69cf40bbba20ddb0cee57
var _ func() kit.CommandOption = kit.NoTransaction

// go:github.com/kitsunium/sdk/framework/kit.NotCommon func func() github.com/kitsunium/sdk/framework/kit.PasswordOption doc:d15232646fd7b690c63a58e614befae62cb4641592329487c4f8d6cee2df257e
var _ func() kit.PasswordOption = kit.NotCommon

// go:github.com/kitsunium/sdk/framework/kit.NotFound func func(message string) *github.com/kitsunium/sdk/framework/kit.Error doc:135dd54e0ab123fe714f45f4658f5a18a140e9388a644aa59e2c598da7deb453
var _ func(message string) *kit.Error = kit.NotFound

// go:github.com/kitsunium/sdk/framework/kit.NotReused func func(n int) github.com/kitsunium/sdk/framework/kit.PasswordOption doc:600a58beb378e8689bef18362f330d316276d5a70ce698269a377d1b057a7664
var _ func(n int) kit.PasswordOption = kit.NotReused

// go:github.com/kitsunium/sdk/framework/kit.Now func func(ctx context.Context) time.Time doc:f6260a92fdd4fa86ee2e3970fa1cfc1c3b0697ae40927a8119fcc90229b492b8
var _ func(ctx context.Context) time.Time = kit.Now

// go:github.com/kitsunium/sdk/framework/kit.Operation alias [Req, Resp any] github.com/kitsunium/sdk/framework/internal/kit.Operation[Req, Resp] doc:d4a75ac5b712932be647e31cc09d17c7c9b7b68eb611d0ff0603e7bea0cfb499
func _[Req, Resp any]() {
	var _ *ikit.Operation[Req, Resp] = (*kit.Operation[Req, Resp])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.OperationOption alias github.com/kitsunium/sdk/framework/internal/kit.OperationOption doc:98a65b90f7b16ac924d6748449f9184763252b89495444dd9747bb294335191e
var _ *ikit.OperationOption = (*kit.OperationOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Optional func func() github.com/kitsunium/sdk/framework/kit.SecretOption doc:42aabf1bf589b1a14b220a3efd86adb7e9a2d12175109870a2e5d4ef0b310ff1
var _ func() kit.SecretOption = kit.Optional

// go:github.com/kitsunium/sdk/framework/kit.OwnStores func func() github.com/kitsunium/sdk/framework/kit.SubscriptionOption doc:c3a64274ae3cda4e4021ea46574d95ca420f89b4a8e57ae270cfdc15c497ca77
var _ func() kit.SubscriptionOption = kit.OwnStores

// go:github.com/kitsunium/sdk/framework/kit.Parallelism func func(n int) github.com/kitsunium/sdk/framework/kit.DeliveryOption doc:4e24da16fd84373c3a35517b3c85b34664295ba35377a3202e5c776ab26b83db
var _ func(n int) kit.DeliveryOption = kit.Parallelism

// go:github.com/kitsunium/sdk/framework/kit.PasswordOption alias github.com/kitsunium/sdk/framework/internal/kit.PasswordConfigurer doc:30d0200f9f29a04ba61525027af09d64b7e05dd8a3936d350aa98f0d111dbda1
var _ *ikit.PasswordConfigurer = (*kit.PasswordOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.PasswordPolicy alias [T any] github.com/kitsunium/sdk/framework/internal/kit.PasswordPolicyService[T] doc:ec14a85aaf884b20e8eff4161d1ed663f5680e7338a236d3e98c70872a0bc6aa
func _[T any]() {
	var _ *ikit.PasswordPolicyService[T] = (*kit.PasswordPolicy[T])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.PerConfigDir var github.com/kitsunium/sdk/framework/kit.Scope doc:663f2f65c17be024586e63d8a369658c74ef4fcac3b83839051e20ebdb0ff001
var _ *kit.Scope = &kit.PerConfigDir

// go:github.com/kitsunium/sdk/framework/kit.PerEnv func func(name string, fallback string) github.com/kitsunium/sdk/framework/kit.Scope doc:ad60c472cad0d996d5894b5a4c613128fff2fa8009a79796ec622552a0cb1cea
var _ func(name, fallback string) kit.Scope = kit.PerEnv

// go:github.com/kitsunium/sdk/framework/kit.PerExecutable var github.com/kitsunium/sdk/framework/kit.Scope doc:83885af493826045eac148a6dee9e42a2431654d6f02483ff2ebf4a6013223a8
var _ *kit.Scope = &kit.PerExecutable

// go:github.com/kitsunium/sdk/framework/kit.PerUID var github.com/kitsunium/sdk/framework/kit.Scope doc:8ff9c4b7a79d84fe9f196914e8731c16b734698148e4c33df4ca465e4bd72f11
var _ *kit.Scope = &kit.PerUID

// go:github.com/kitsunium/sdk/framework/kit.Personal const github.com/kitsunium/sdk/framework/kit.Mark doc:126515e27947fe9227c3a2292ab253c855b482af3087acd19846d6565a0138dd
func _() {
	x := kit.Personal
	var _ *kit.Mark = &x
	_ = map[bool]int{false: 0, kit.Personal == "personal": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.PersonalData alias github.com/kitsunium/sdk/framework/internal/kit.PersonalData doc:a303aafb99019a31ffce27c06048ba43c21dfae224a54a47c5364506e854fccd
var _ *ikit.PersonalData = (*kit.PersonalData)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Port alias [Req, Resp any] github.com/kitsunium/sdk/framework/internal/kit.PortService[Req, Resp] doc:f3fb09f2996f35aa7ae68bd0fe40601cee717692e04929f1c7bbf86fc06b125d
func _[Req, Resp any]() {
	var _ *ikit.PortService[Req, Resp] = (*kit.Port[Req, Resp])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.PortOption alias [Req, Resp any] github.com/kitsunium/sdk/framework/internal/kit.PortConfigurer[Req, Resp] doc:41836aa9fc577ede1ff73a0665efc654ebe553f3468f6ed379f2abdb36d75e66
func _[Req, Resp any]() {
	var _ *ikit.PortConfigurer[Req, Resp] = (*kit.PortOption[Req, Resp])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.Prefix func func(prefix string) github.com/kitsunium/sdk/framework/kit.MountOption doc:c48579730f24b12d46f02c66e6e3e14c412d49977f80672f3b87bbfe6e88cdea
var _ func(prefix string) kit.MountOption = kit.Prefix

// go:github.com/kitsunium/sdk/framework/kit.Principal alias github.com/kitsunium/sdk/framework/internal/kit.AttrsProvider doc:fa1f4ad0db9a6230063cfe7e6d79dadd560ae51f7b5cbd4b8e173e7fe07dda72
var _ *ikit.AttrsProvider = (*kit.Principal)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Privacy var *github.com/kitsunium/sdk/framework/kit.Service doc:18c0c0acf6105d42f276e535851d9b0d83a3242944bede6ba1aa620fe2a96393
var _ **kit.Service = &kit.Privacy

// go:github.com/kitsunium/sdk/framework/kit.Profile func func(p string) github.com/kitsunium/sdk/framework/kit.AppOption doc:dd6c7b7e1957aeb289a8f44b0b4d1c5e17c1dc23ba092c14380724be676a66b1
var _ func(p string) kit.AppOption = kit.Profile

// go:github.com/kitsunium/sdk/framework/kit.Purpose func func(text string) github.com/kitsunium/sdk/framework/kit.StoreOption doc:93da1b4a412a052b7bb4612278b79aac16fa1899da9419431a856973f4bcd1a2
var _ func(text string) kit.StoreOption = kit.Purpose

// go:github.com/kitsunium/sdk/framework/kit.Query alias [Q, R any] github.com/kitsunium/sdk/framework/internal/kit.Query[Q, R] doc:e2f4d05c92c2eca2d10a739c4747fbe053e2443777fcd31c67d818714ab01b56
func _[Q, R any]() {
	var _ *ikit.Query[Q, R] = (*kit.Query[Q, R])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.QueryOption alias github.com/kitsunium/sdk/framework/internal/kit.QueryConfigurer doc:2625692429693c9c1dacd32a6ba7d581005127d11ed1314fe33002eefb426448
var _ *ikit.QueryConfigurer = (*kit.QueryOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Queued func func() github.com/kitsunium/sdk/framework/kit.CommandOption doc:668a23a53df452964b751facf05757fd341f7a690e60c952ef5794e31fd63086
var _ func() kit.CommandOption = kit.Queued

// go:github.com/kitsunium/sdk/framework/kit.RateLimit func func(perSecond float64, burst int) github.com/kitsunium/sdk/framework/kit.OperationOption doc:c26b37e18bfea86723d96cc8b1d7ba682da4c768ba11c5afc3475eeab6387f41
var _ func(perSecond float64, burst int) kit.OperationOption = kit.RateLimit

// go:github.com/kitsunium/sdk/framework/kit.RateLimitPerClient func func(perSecond float64, burst int) github.com/kitsunium/sdk/framework/kit.OperationOption doc:8f81bb4397ce3f5f536ac886db867ea34e33d9454ef07307867a2f6b750e67f6
var _ func(perSecond float64, burst int) kit.OperationOption = kit.RateLimitPerClient

// go:github.com/kitsunium/sdk/framework/kit.ReadModel func func() github.com/kitsunium/sdk/framework/kit.StoreOption doc:9ee746e8a1af30ba79e1ba5da3a39ceb4f8eea756c4396fc96906109a4487d7a
var _ func() kit.StoreOption = kit.ReadModel

// go:github.com/kitsunium/sdk/framework/kit.Records alias github.com/kitsunium/sdk/framework/internal/kit.RecordsService doc:5764e864e1bbb72eba76c634e2e1d8f0959b59c0c6ba2caddec1e8595c9cb706
var _ *ikit.RecordsService = (*kit.Records)(nil)

// go:github.com/kitsunium/sdk/framework/kit.RecordsOf func func(ctx context.Context, store string) (github.com/kitsunium/sdk/framework/kit.Records, error) doc:a6cdfe354727c400d97be6076db22a30b42aecea033a7a1561756ce391336efd
var _ func(ctx context.Context, store string) (kit.Records, error) = kit.RecordsOf

// go:github.com/kitsunium/sdk/framework/kit.Replace[...] func func[Req, Resp any](op github.com/kitsunium/sdk/framework/internal/kit.Operation[Req, Resp], fn func(context.Context, Req) (Resp, error)) github.com/kitsunium/sdk/framework/kit.AppOption doc:171c01052530eafdffe30a0908d714d6f9e27454101ac6079c26aae47660e25d
func _[Req, Resp any]() {
	var _ func(op ikit.Operation[Req, Resp], fn func(context.Context, Req) (Resp, error)) kit.AppOption = kit.Replace[Req, Resp]
}

// go:github.com/kitsunium/sdk/framework/kit.Required func func() github.com/kitsunium/sdk/framework/kit.SettingOption doc:76217cba11cd6296ef3eb047e794803da42b232aab35315fb719ea85e730527c
var _ func() kit.SettingOption = kit.Required

// go:github.com/kitsunium/sdk/framework/kit.Requires func func(other *github.com/kitsunium/sdk/framework/kit.Module) github.com/kitsunium/sdk/framework/kit.ModulePart doc:2463e3413af71e6fde4073ab6484d86347194c79ae0a7b09c9f5ae6109cb3cae
var _ func(other *kit.Module) kit.ModulePart = kit.Requires

// go:github.com/kitsunium/sdk/framework/kit.RetentionByProduct func func(limits string) github.com/kitsunium/sdk/framework/kit.StoreOption doc:aa88276b65df4357135f84f604cebf92e80d641cf466dec9f7257dd3ee40b344
var _ func(limits string) kit.StoreOption = kit.RetentionByProduct

// go:github.com/kitsunium/sdk/framework/kit.Revision alias [T any] github.com/kitsunium/sdk/framework/internal/kit.RevisionEvent[T] doc:f6914fa0ca1c194a09d81e1c2ceca872c97074401bc993b829df757275f47d36
func _[T any]() {
	var _ *ikit.RevisionEvent[T] = (*kit.Revision[T])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.Revisions func func(n int) github.com/kitsunium/sdk/framework/kit.StoreOption doc:3f09bfc0c33f7230b36b8fa458d9e41833993ad63fadc1420f0dc9684f72ed43
var _ func(n int) kit.StoreOption = kit.Revisions

// go:github.com/kitsunium/sdk/framework/kit.Root func func(dir string) github.com/kitsunium/sdk/framework/kit.StaticOption doc:71b5533d48e969e04dc1de517675c6f064d48c3a4b9de1ea7088590b5bd0f7f5
var _ func(dir string) kit.StaticOption = kit.Root

// go:github.com/kitsunium/sdk/framework/kit.RotateEvery func func(d time.Duration) github.com/kitsunium/sdk/framework/kit.SecretOption doc:209ae026c5ecdeb931018b68fb5e17bbc200a48566feaacbc20e024a802c2b76
var _ func(d time.Duration) kit.SecretOption = kit.RotateEvery

// go:github.com/kitsunium/sdk/framework/kit.Routine alias github.com/kitsunium/sdk/framework/internal/kit.Routine doc:9fe9a99d4d8d997bd80357273b10ecc2d1a8188d36df51e7ce36a2ab37b9b5cd
var _ *ikit.Routine = (*kit.Routine)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Scope alias github.com/kitsunium/sdk/framework/internal/kit.ScopeValue doc:d8945b9cc24557490b22b83d93adfba384c92d64e0cbaff3aa1c830bfd313f74
var _ *ikit.ScopeValue = (*kit.Scope)(nil)

// go:github.com/kitsunium/sdk/framework/kit.ScopeKey func func(scopes ...github.com/kitsunium/sdk/framework/kit.Scope) (string, error) doc:46019cc1e1dba46856a03e09a067a448018744e79892c6509e534b08d3a9b0d7
var _ func(scopes ...kit.Scope) (string, error) = kit.ScopeKey

// go:github.com/kitsunium/sdk/framework/kit.Secret alias github.com/kitsunium/sdk/framework/internal/kit.Secret doc:d1feb2ee2c489126f2856f802fe3b7349384f60cc3109a5fe88097b7c6409d1b
var _ *ikit.Secret = (*kit.Secret)(nil)

// go:github.com/kitsunium/sdk/framework/kit.SecretOption alias github.com/kitsunium/sdk/framework/internal/kit.SecretConfigurer doc:ff98321fb10bb81b479ea9275172ca5b176d80092f0112312d57e678886995ae
var _ *ikit.SecretConfigurer = (*kit.SecretOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.SecretStore func func(store github.com/kitsunium/sdk/pkg/v1/security/secret.Store) github.com/kitsunium/sdk/framework/kit.AppOption doc:1459c0968c5bb0afcea4089e514835d7581687af6e5124027d6f7ee6f4cf1d57
var _ func(store secret.Store) kit.AppOption = kit.SecretStore

// go:github.com/kitsunium/sdk/framework/kit.Service alias github.com/kitsunium/sdk/framework/internal/kit.Service doc:498bf1b6fb012c334ca9099b81630b485850492f867eca1a69676e73c03a0a96
var _ *ikit.Service = (*kit.Service)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Set[...] func func[V any](name string, value V) github.com/kitsunium/sdk/framework/kit.AppOption doc:929289d8afef5b2e24982c6c24bc8d58507ba66dd88ab7d8d8f510772de913c6
func _[V any]() {
	var _ func(name string, value V) kit.AppOption = kit.Set[V]
}

// go:github.com/kitsunium/sdk/framework/kit.SetCookie func func(ctx context.Context, c *net/http.Cookie) doc:4490189bfde910436de77c8129ea4129b5e134a013b187ca557d671e0b9cd740
var _ func(ctx context.Context, c *http.Cookie) = kit.SetCookie

// go:github.com/kitsunium/sdk/framework/kit.Setting alias [T github.com/kitsunium/sdk/framework/kit.SettingValue] github.com/kitsunium/sdk/framework/internal/kit.SettingService[T] doc:3d6292ed7ed643188794f7538a9840b0e411f1cf3e54270555cffa12651a567c
func _[T kit.SettingValue]() {
	var _ *ikit.SettingService[T] = (*kit.Setting[T])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.SettingOption alias github.com/kitsunium/sdk/framework/internal/kit.SettingConfigurer doc:9c1dda2946f966bf85370e9d6bd4171dc146f02c4335a65dfaf985978cc80af9
var _ *ikit.SettingConfigurer = (*kit.SettingOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.SettingValue alias github.com/kitsunium/sdk/framework/internal/kit.SettingValue doc:25829b985dbadb121cf086820461a8d0f361f85341976dfbc2b3f7e93b665845
func _[X kit.SettingValue]() {}

// go:github.com/kitsunium/sdk/framework/kit.Singleton func func(scope string) github.com/kitsunium/sdk/framework/kit.AppOption doc:f86a681448e5c700b80df4d2563e13cf720f7e0d26ec4753ec2f99c4926dc25c
var _ func(scope string) kit.AppOption = kit.Singleton

// go:github.com/kitsunium/sdk/framework/kit.SingletonPer func func(scopes ...github.com/kitsunium/sdk/framework/kit.Scope) github.com/kitsunium/sdk/framework/kit.AppOption doc:fe996fd7e6983d2bc5b8e0e76d46eb0e798f5e21e70bb886d83261092ff845ae
var _ func(scopes ...kit.Scope) kit.AppOption = kit.SingletonPer

// go:github.com/kitsunium/sdk/framework/kit.SocketPath func func(path string) github.com/kitsunium/sdk/framework/kit.ListenerOption doc:9bc25f0b4813140007dfd8ebaa439a8cbdc3c6479389190a252780d75b34d542
var _ func(path string) kit.ListenerOption = kit.SocketPath

// go:github.com/kitsunium/sdk/framework/kit.SocketPathFor func func(product string, service string, name string, scopes ...github.com/kitsunium/sdk/framework/kit.Scope) (string, error) doc:9081e534638787c95890e757fd45ef3d0e156573465005d7fc5b4c3eefbe2781
var _ func(product, service, name string, scopes ...kit.Scope) (string, error) = kit.SocketPathFor

// go:github.com/kitsunium/sdk/framework/kit.SocketPer func func(scopes ...github.com/kitsunium/sdk/framework/kit.Scope) github.com/kitsunium/sdk/framework/kit.ListenerOption doc:5156d5f1d3cee3dd1b48a962e52cbf337b0c6843600db4e0389afed8fb1bf12f
var _ func(scopes ...kit.Scope) kit.ListenerOption = kit.SocketPer

// go:github.com/kitsunium/sdk/framework/kit.Special const github.com/kitsunium/sdk/framework/kit.Mark doc:625db985a2a6a75f3b0ba7a040094e34ca3dc2901ac1a1eac34403c7fcf14e55
func _() {
	x := kit.Special
	var _ *kit.Mark = &x
	_ = map[bool]int{false: 0, kit.Special == "special": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.StaticOption alias github.com/kitsunium/sdk/framework/internal/kit.StaticConfigurer doc:a32c791eb007263a9f11ae5b69fb5ac11a75eaf40997d44e6a6daa0c1d87ac1e
var _ *ikit.StaticConfigurer = (*kit.StaticOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Stdio alias github.com/kitsunium/sdk/framework/internal/kit.StdioValue doc:411c72d307b87a71e5bcce6897bbf29869708ba030db7bc603fb30a1da6687d9
var _ *ikit.StdioValue = (*kit.Stdio)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Stop func func(ctx context.Context) bool doc:1693578c1769feec1d1a52c8cd1b5f92d9a5bf50ad52dccbced1fdec46b551c3
var _ func(ctx context.Context) bool = kit.Stop

// go:github.com/kitsunium/sdk/framework/kit.Store alias [T any] github.com/kitsunium/sdk/framework/internal/kit.StoreService[T] doc:48ab470f47980cb6dab9e7382f6f07ba34b0fcdc37a6663541479aa63a8cc092
func _[T any]() {
	var _ *ikit.StoreService[T] = (*kit.Store[T])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.StoreOption alias github.com/kitsunium/sdk/framework/internal/kit.StoreConfigurer doc:7319a079b94a965c662c6429c7b49660064e79004d12be3d6778ffcdf3fe5aad
var _ *ikit.StoreConfigurer = (*kit.StoreOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Studio func func(on bool) github.com/kitsunium/sdk/framework/kit.AppOption doc:f80ec064e30810ee6e6842b2316654ac3acbfe9d859faf431eb035709e3c72fb
var _ func(on bool) kit.AppOption = kit.Studio

// go:github.com/kitsunium/sdk/framework/kit.Subscription alias [T any] github.com/kitsunium/sdk/framework/internal/kit.SubscriptionWorker[T] doc:583d695c5a809ff4daf2dceb2a44f924f473bd324f2b680c6b26ad8beed5b0de
func _[T any]() {
	var _ *ikit.SubscriptionWorker[T] = (*kit.Subscription[T])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.SubscriptionOption alias github.com/kitsunium/sdk/framework/internal/kit.SubscriptionConfigurer doc:e5cde57f6b5c0275665aa666769765c50ca8481db88b3ef157824236902c00ad
var _ *ikit.SubscriptionConfigurer = (*kit.SubscriptionOption)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Telemetry func func(path string, gids ...int) github.com/kitsunium/sdk/framework/kit.AppOption doc:77bc904bce33fb25f388e0744ca5987a5360c4d5f2d9868ede611558f37a8504
var _ func(path string, gids ...int) kit.AppOption = kit.Telemetry

// go:github.com/kitsunium/sdk/framework/kit.Timeout func func(d time.Duration) github.com/kitsunium/sdk/framework/kit.OperationOption doc:035fe95830bd201426c4960b3707723aa563e6d4d39768af542f96af98235c26
var _ func(d time.Duration) kit.OperationOption = kit.Timeout

// go:github.com/kitsunium/sdk/framework/kit.Topic alias [T any] github.com/kitsunium/sdk/framework/internal/kit.TopicService[T] doc:2595c6255ac9112ad221edaaf4b7b03cea50b6098b94ffdccdca0b580c08e6ed
func _[T any]() {
	var _ *ikit.TopicService[T] = (*kit.Topic[T])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.Transact func func(ctx context.Context, fn func(context.Context) error) error doc:e7a8ca5f0241de597cb1128ef3f588443eb2ae5bc7c4e3f81a20b7ab9561f86e
var _ func(ctx context.Context, fn func(context.Context) error) error = kit.Transact

// go:github.com/kitsunium/sdk/framework/kit.UID alias github.com/kitsunium/sdk/framework/internal/kit.UID doc:d5d06a2ea302d9c6cffebfb3641234301f4473f78aaa252dcc5e219302ffabc9
var _ *ikit.UID = (*kit.UID)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Unauthenticated func func(message string) *github.com/kitsunium/sdk/framework/kit.Error doc:42b303dc4da230479bd801637e5d47c1312ba9ea290e64d5b91d06830ddf9c23
var _ func(message string) *kit.Error = kit.Unauthenticated

// go:github.com/kitsunium/sdk/framework/kit.Unavailable func func(message string) *github.com/kitsunium/sdk/framework/kit.Error doc:bf24b5b77920f0af80019c50fb031fdca5e168cf8639c42628bb944861a19932
var _ func(message string) *kit.Error = kit.Unavailable

// go:github.com/kitsunium/sdk/framework/kit.Unique[...] func func[T any](name string, key func(T) string) github.com/kitsunium/sdk/framework/kit.StoreOption doc:54ecd62b6512e35ef29133cbcde558632443ebbdc4e061ea57091d0e95919d28
func _[T any]() {
	var _ func(name string, key func(T) string) kit.StoreOption = kit.Unique[T]
}

// go:github.com/kitsunium/sdk/framework/kit.UserAgent func func(ctx context.Context) string doc:9306225ef462f9522fdc85d1205959a64ef6cc9646c85ff122abc1c8c170819f
var _ func(ctx context.Context) string = kit.UserAgent

// go:github.com/kitsunium/sdk/framework/kit.UserID func func(ctx context.Context) (github.com/kitsunium/sdk/framework/kit.UID, bool) doc:f2fa2b802e87dfd3ff57e4ed06b98be8b008cc8e0d34424708d889e1c8f0233a
var _ func(ctx context.Context) (kit.UID, bool) = kit.UserID

// go:github.com/kitsunium/sdk/framework/kit.Violation alias github.com/kitsunium/sdk/framework/internal/kit.ViolationMessage doc:37789a6c80505166f41d615113b123bc82f1ace6c23b65a63505886904c6b202
var _ *ikit.ViolationMessage = (*kit.Violation)(nil)

// go:github.com/kitsunium/sdk/framework/kit.Wake alias github.com/kitsunium/sdk/framework/internal/kit.WakeEvent doc:aa40878cd3eb106d26761888d815d3bea078dabc71c71b7ec8a03d72d6e9a298
var _ *ikit.WakeEvent = (*kit.Wake)(nil)

// go:github.com/kitsunium/sdk/framework/kit.WakeAt func func(next func(context.Context) (time.Time, bool)) github.com/kitsunium/sdk/framework/kit.LoopOption doc:da96dde0f3436ec0705777b8c4bfd4ba4281347d336c349d02a441eb24e0aec1
var _ func(next func(context.Context) (time.Time, bool)) kit.LoopOption = kit.WakeAt

// go:github.com/kitsunium/sdk/framework/kit.WakeEvery func func(d time.Duration) github.com/kitsunium/sdk/framework/kit.LoopOption doc:8bcc1f052afd804d65c0fee983ee9f9c76f62569d816d7b6b0ce13b6f767dc47
var _ func(d time.Duration) kit.LoopOption = kit.WakeEvery

// go:github.com/kitsunium/sdk/framework/kit.WakeOn[...] func func[T any](topic *github.com/kitsunium/sdk/framework/internal/kit.TopicService[T]) github.com/kitsunium/sdk/framework/kit.LoopOption doc:b2a21299065ff6dddb3067777dd2307ddd73ef3f8d714b43be9195a0cbe5ccba
func _[T any]() {
	var _ func(topic *ikit.TopicService[T]) kit.LoopOption = kit.WakeOn[T]
}

// go:github.com/kitsunium/sdk/framework/kit.Watch alias github.com/kitsunium/sdk/framework/internal/kit.Watch doc:a8936a75a5df5bb46faf0a834606f7046009943d9be3e21bfce46de1f8c7ead5
var _ *ikit.Watch = (*kit.Watch)(nil)

// go:github.com/kitsunium/sdk/framework/kit.WireCanceled const string doc:c6b9c4456ce147826e38aacaf2037083bec50f8fb514306c2ee95551036d7d13
func _() {
	x := kit.WireCanceled
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireCanceled == "canceled": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireConflict const string doc:cdfeaf1ca45f99d677862f381473d9bd519ffce3f185e561bd965d9fec3623c5
func _() {
	x := kit.WireConflict
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireConflict == "conflict": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireForbidden const string doc:089fab8077ac4e773e10fd696b616f0d1cfbff9cfd88c991e2727be183f49ccb
func _() {
	x := kit.WireForbidden
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireForbidden == "permission_denied": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireInternal const string doc:f72176ee733cc5ef42eb99b82d62363c4b338bf78a464334334c8caedc6e70fd
func _() {
	x := kit.WireInternal
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireInternal == "internal": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireInvalid const string doc:75abc7962256488dbe91a9bede94ff3ac02532dc6af0df6c2292a8edfed06866
func _() {
	x := kit.WireInvalid
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireInvalid == "invalid_argument": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireNotFound const string doc:fa2880e12e53477d8e6b544a0ebb9d82a422c4389c965e8541349ad6770740ec
func _() {
	x := kit.WireNotFound
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireNotFound == "not_found": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireRateLimited const string doc:15fd7bf6fc7bb84fa8bf32acff68c54b9ad5ff4744a0025b71aee4547a78f267
func _() {
	x := kit.WireRateLimited
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireRateLimited == "rate_limited": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireTimeout const string doc:c86394a98b7ad43ef1d00db05768be510ae3e2a27340bfae636e93f8fbea3e0b
func _() {
	x := kit.WireTimeout
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireTimeout == "deadline_exceeded": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireTooLarge const string doc:005f912e9d24119fb02f3ca057ec9886cf2b88a131e788735f40b5ffce823d58
func _() {
	x := kit.WireTooLarge
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireTooLarge == "too_large": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireUnauth const string doc:948d7129d2c4b713be8e6f1eb63dc229dde5939b111123211f99cd71f5408404
func _() {
	x := kit.WireUnauth
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireUnauth == "unauthenticated": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireUnavailable const string doc:1d9a0ace28f67c259c8b14ecc6ed8dc68fd240b1bc72f46048d3bb541544be34
func _() {
	x := kit.WireUnavailable
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireUnavailable == "unavailable": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WireUnsupported const string doc:d0f954ac949fc2b639ef9e81f141af45558dd49b7d7cde5d4c83fa6b8763cf81
func _() {
	x := kit.WireUnsupported
	var _ *string = &x
	_ = map[bool]int{false: 0, kit.WireUnsupported == "unsupported_media_type": 1}
}

// go:github.com/kitsunium/sdk/framework/kit.WithUser[...] func func[D any](ctx context.Context, uid github.com/kitsunium/sdk/framework/kit.UID, data D) context.Context doc:2f8b88eeff07057f99d604731be787c0a92cd4c8fefc7f5b53967e39a59cf134
func _[D any]() {
	var _ func(ctx context.Context, uid kit.UID, data D) context.Context = kit.WithUser[D]
}

// go:github.com/kitsunium/sdk/framework/kit.Workflow alias [E any, S comparable] github.com/kitsunium/sdk/framework/internal/kit.WorkflowService[E, S] doc:c669b4efb885dd8f8d254baff3916a4f5f3d3c8e438fd98244548a981c27e5a8
func _[E any, S comparable]() {
	var _ *ikit.WorkflowService[E, S] = (*kit.Workflow[E, S])(nil)
}

// go:github.com/kitsunium/sdk/framework/kit.Written alias github.com/kitsunium/sdk/framework/internal/kit.WrittenEvent doc:3769afe880d83dc6136c43f62c904c2b95830764060c2fa512df6163695ee792
var _ *ikit.WrittenEvent = (*kit.Written)(nil)
