// Code generated by kit from design/framework/kit.yaml (sha256 eb8217c1acede87675ab11af2f7c648211139f6aa96a3e8dfa862047468ce3da, body c2264edf959d62ba47c4a41487ced42b10da9ff646d054e288d483691900a457). DO NOT EDIT.

package kit

import (
	"context"
	"io"
	"io/fs"
	"net/http"
	"time"

	"github.com/kitsunium/sdk/framework/model"
	"github.com/kitsunium/sdk/pkg/v1/clock"
	"github.com/kitsunium/sdk/pkg/v1/data/sql"
	"github.com/kitsunium/sdk/pkg/v1/observe/logger"
	"github.com/kitsunium/sdk/pkg/v1/security/secret"
)

// Analyzer runs fn in the background once the product serves, in dev and when
// KIT_ANALYZE allows it. Without one, the graph is the runtime's alone.
func Analyzer(fn AnalyzeFunc) AppOption {
	return analyzer(fn)
}

// Profile selects the app's process profile: model.ProfileServer (the
// default), model.ProfileDaemon or model.ProfileCLI.
func Profile(p string) AppOption {
	return profile(p)
}

// IdleStop makes a daemon stop itself once, for d, no connection was open on
// any of its listeners and no activity of its services (Service.Activity)
// said it was busy: a daemon launched on demand by its clients ends when
// they stop coming. It is refused outside the daemon profile.
func IdleStop(d time.Duration) AppOption {
	return idleStop(d)
}

// Singleton keeps one process of the app alive per scope on this machine: the
// start takes an exclusive file lock named after scope in the app's runtime
// directory (pkg/v1/app/lock: flock, LockFileEx) and holds it until the process
// ends. A second process refuses to start with CodeSingletonHeld — for a
// daemon's client, the sign to talk to the one that runs. The kernel drops
// the lock with a dead process.
func Singleton(scope string) AppOption {
	return singleton(scope)
}

// SingletonPer keeps one process of the app alive per value of scopes on
// this machine — per user, per installed executable, per configuration
// directory ([PerUID], [PerExecutable], [PerConfigDir], [PerEnv]) —: the lock
// is named after the scopes' key ([ScopeKey]), computed at the start, and
// held as Singleton's is. A client that must find the process computes the
// same key from the same scopes.
func SingletonPer(scopes ...Scope) AppOption {
	return singletonPer(scopes...)
}

// Stop asks the app ctx runs in to end its run: Run returns as it does on a
// signal, its stop draining every component — a daemon told "stop" by its
// client, on its listener, ends itself so. It returns at once, before the
// stop; it reports false when ctx runs in no app — a handler's, a loop's, a
// command's context does — or the app does not run.
func Stop(ctx context.Context) bool {
	return stop(ctx)
}

// Auth makes an endpoint require an authenticated caller: the app's auth
// handler runs first, and a request without valid credentials is answered
// 401 before the handler runs. A command or a query that asks for one is
// refused 401 when its caller carries no user: an in-process dispatch
// carries its caller's, and is not authenticated again.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Auth() OperationOption {
	return auth()
}

// AuthOptional runs the app's auth handler when the request carries
// credentials, and serves anonymous callers too: [UserID] tells which.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func AuthOptional() OperationOption {
	return authOptional()
}

// Catalog lists the generic mechanics kit offers: the building blocks a node
// composes rather than implements, each one backed by an SDK package. It is
// part of every graph, so the Studio — and an AI agent reading the graph —
// knows what can be added to a product and the exact code that adds it.
func Catalog() []model.Mechanic {
	return catalog()
}

// NewID returns a new identifier with the given prefix: a TypeID, time
// ordered, like "todo_01k5zq7m3xe8tvbfg0s7zr4w6c". The prefix must be one to
// sixty-three lower-case letters, with '_' only between two letters; any
// other prefix is a programming error and panics.
func NewID(prefix string) string {
	return newID(prefix)
}

// DefaultCommand makes the command Main's default: it runs with every
// argument when the first names no other command — neither one of the
// product's nor one of Main's (serve, help…) —, and with none when there
// is none. Main then never answers a usage error. One command of an app may
// be its default.
//
// IFACE-OPAQUE: CLIOption is sealed — its one method is unexported — so
// only this package makes one, and a caller only passes it to CLI.
func DefaultCommand() CLIOption {
	return defaultCommand()
}

// FailSafe makes the command's status always 0: a status line, a prompt
// hook, anything a shell runs on every keystroke must never fail the shell.
// A non-zero status, a start that fails and a panic are logged instead.
//
// IFACE-OPAQUE: CLIOption is sealed — its one method is unexported — so
// only this package makes one, and a caller only passes it to CLI.
func FailSafe() CLIOption {
	return failSafe()
}

// Queued sends a command to the background. Dispatch returns once the
// command's own queue accepted it — a file queue under the data directory,
// memory without one —, and a consumer handles it, [Parallelism] at a time,
// retried after half a second up to [MaxDeliveries] attempts (5), then
// dead-lettered. It answers nothing: its result is [Empty], and exposed, it
// answers 202 Accepted.
//
// Delivery is at least once: Queued is the product's promise that the
// handler tolerates a redelivery, and a [Command].Key narrows the duplicates
// without removing them. The handler runs in the dispatcher's trace, as the
// user who dispatched it ([UserID]); what the auth handler said about that
// user is not queued. A queued command's input is a contract with the
// messages already queued: add a field, never rename one.
func Queued() CommandOption {
	return queued()
}

// NoTransaction runs a command outside a transaction of its own: its
// writes land as its handler makes them, and its effects leave when made —
// a failed command may have written or announced something. On the data
// directory and in memory, where a writing command's transaction takes the
// writer turn, it lets such commands run side by side. Dispatched inside
// another command, it still runs in that one's transaction.
func NoTransaction() CommandOption {
	return noTransaction()
}

// Listen sets the listening address, instead of KIT_ADDR or PORT. ":0" picks
// a free port; App.URL tells which.
func Listen(addr string) AppOption {
	return listen(addr)
}

// DataDir sets where stores and queues persist, instead of KIT_DATA_DIR.
func DataDir(dir string) AppOption {
	return dataDir(dir)
}

// Studio switches the Studio on or off in dev. It is always off in
// production.
func Studio(on bool) AppOption {
	return studio(on)
}

// Analyze switches the in-process static analysis on or off in dev.
func Analyze(on bool) AppOption {
	return analyze(on)
}

// Logs sends the app's logs to w instead of standard error.
func Logs(w io.Writer) AppOption {
	return logs(w)
}

// InMemory keeps data in memory. On an app, it overrides the data directory
// for every store and queue — what a test wants. On a store, it keeps that
// store in memory even when the app has a data directory.
func InMemory() interface {
	StoreOption
	AppOption
} {
	return inMemory()
}

// Keeps says what the database keeps: a service's stores, a store, a
// module's stores. The most precise wins: a store kept by name, then its
// service, then its module, then the default database — the one declared
// without Keeps —, then the data directory, then memory. [InMemory] wins
// over all of them, on the app as on a store.
func Keeps(things ...Keepable) DatabaseOption {
	return keeps(things...)
}

// Migrations are migrations, values of the SDK's sql.Migration, run when
// the database starts (<name>-migrate: start) or by `<product> migrate up`,
// kit's own first, each set under its own version table — and so its own
// lock. On MySQL a DDL statement commits by itself: write one per migration.
//
// Given to [Database], they are the product's, under schema_migrations.
// Given to [NewModule], they are the module's (ADR 0008), for the data it
// keeps outside kit's stores: run on the database that keeps the module,
// under <module>_migrations.
func Migrations(m ...sql.Migration) interface {
	DatabaseOption
	ModulePart
} {
	return migrations(m...)
}

// MaxBody bounds the request body the endpoint reads. The default is
// [DefaultMaxBody].
func MaxBody(bytes int64) EndpointOption {
	return maxBody(bytes)
}

// RateLimit puts a token bucket in front of the handler: perSecond tokens a
// second, up to burst at once. An empty bucket answers 429 at once. It is the
// SDK's resilience rate limiter.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func RateLimit(perSecond float64, burst int) OperationOption {
	return rateLimit(perSecond, burst)
}

// Timeout cancels the handler's context after d and answers 504. It is the
// SDK's resilience timeout.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Timeout(d time.Duration) OperationOption {
	return timeout(d)
}

// Bulkhead caps how many requests the handler serves at once; the overflow
// answers 503. It is the SDK's resilience bulkhead.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Bulkhead(maxConcurrent int) OperationOption {
	return bulkhead(maxConcurrent)
}

// Anyone says that an exposure is open to everyone, on purpose: its
// operation declares no permission and no rule, and whoever reaches the
// route may run it — a public form, say. It says so on the exposure's node,
// where the diagram and the API page read it. An exposure whose operation
// declares no rule refuses the start unless it says this, or [AnyUser].
//
//	var Report = Service.Command("report", file).Expose("POST /reports", kit.Anyone())
//
// It adds no authentication: an operation that asks for a user ([Auth])
// takes [AnyUser] instead, and one with [AuthOptional] still knows the
// caller who signed in.
func Anyone() ExposeOption {
	return anyone()
}

// AnyUser says that an exposure is open to any signed-in user, on purpose:
// its operation asks for a user ([Auth]) and declares no permission and no
// rule — its handler reads [UserID] and keeps to what that user owns.
//
//	var MyOrders = Service.Query("my-orders", myOrders, kit.Auth()).Expose("GET /orders", kit.AnyUser())
//
// It adds no authentication of its own: an exposure authenticates as its
// operation asks, so the operation declares [Auth].
func AnyUser() ExposeOption {
	return anyUser()
}

// HoldSubject places a legal hold on every record whose subject is one of
// ids, in every store of the app: an authority's request about a person.
// It holds the records they have now; a record written later is not held.
// reason is kept as Store.Hold keeps it.
func HoldSubject(ctx context.Context, reason string, ids ...string) error {
	return holdSubject(ctx, reason, ids...)
}

// SocketPath places the listener's socket at path — absolute, at most 103
// bytes — instead of <runtime dir of the app>/<service>-<name>.sock.
//
// IFACE-OPAQUE: ListenerOption is sealed — its one method is unexported —
// so only this package makes one, and a caller only passes it to Listen.
func SocketPath(path string) ListenerOption {
	return socketPath(path)
}

// SocketPer names the listener's socket after the value of scopes in this
// process — <runtime dir of the app>/<service>-<name>-<key>.sock, the key
// being [ScopeKey]'s —: one daemon per user, per executable, per
// configuration directory. A client finds it with SocketPathIn or DialIn,
// which compute the same key from the same declaration.
//
// IFACE-OPAQUE: ListenerOption is sealed — its one method is unexported —
// so only this package makes one, and a caller only passes it to Listen.
func SocketPer(scopes ...Scope) ListenerOption {
	return socketPer(scopes...)
}

// AllowPeers admits accounts besides the product's own: an on-call group
// declared at deployment. The kernel checks them where it names the peer; the
// socket's directory must still let them through, which is the deployment's
// to arrange.
//
// IFACE-OPAQUE: ListenerOption is sealed — its one method is unexported —
// so only this package makes one, and a caller only passes it to Listen.
func AllowPeers(uids, gids []int) ListenerOption {
	return allowPeers(uids, gids)
}

// WakeEvery wakes the loop every d.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func WakeEvery(d time.Duration) LoopOption {
	return wakeEvery(d)
}

// WakeAt wakes the loop at the time next returns, asked again after every
// run; false means "no deadline for now". It is how a loop sleeps exactly
// until its next piece of work — the next reminder due — rather than polling.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func WakeAt(next func(context.Context) (time.Time, bool)) LoopOption {
	return wakeAt(next)
}

// From sets the sender of every message that names none.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func From(name, addr string) MailerOption {
	return from(name, addr)
}

// MailAttempts is how many deliveries a message gets before it is
// dead-lettered. The default is 6, backing off from one second.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func MailAttempts(n int) MailerOption {
	return mailAttempts(n)
}

// Requires says the module needs other: an app that mounts the module and
// not other mounts other at its defaults, and starts it first. The Go import
// this takes makes a cycle impossible. A collaboration a module can do
// without is a port with a fallback instead ([Fallback]).
func Requires(other *Module) ModulePart {
	return requires(other)
}

// MinLength refuses a password shorter than n characters, counted as NIST
// counts them: one per Unicode code point. The default is 15, NIST's figure
// for a password used alone; 8 is the floor NIST allows with a second
// factor, and a smaller n is refused. There is no composition rule, ever:
// NIST says SHALL NOT.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func MinLength(n int) PasswordOption {
	return minLength(n)
}

// NotReused refuses a password that the current hash, or any of the n
// former ones, verifies — n from 1 to 100. It is a compliance policy, off by
// default: PCI DSS asks for it, OWASP ASVS 4.0.3 asks most products not to
// impose it. kit keeps the field's last n hashes, so it implies history=n,
// and a tag whose history is smaller than n is refused.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func NotReused(n int) PasswordOption {
	return notReused(n)
}

// NotCommon refuses a password among the ten thousand most common ones —
// the SDK's password.IsCommon, which compares them without regard to case —:
// the blocklist NIST SP 800-63B-4 requires a verifier to check, beyond the
// three thousand OWASP ASVS 5.0 (6.2.4) asks for. Every policy checks it (ADR
// 0007 §2: on by default once the SDK has the list); the option says so
// where a policy is declared. Beside NIST's fifteen characters the list has
// little left to refuse; beside a shorter MinLength, it matters.
func NotCommon() PasswordOption {
	return notCommon()
}

// RateLimitPerClient gives every client of an endpoint a token bucket of its
// own: perSecond tokens a second, up to burst at once. A client is the
// authenticated user when there is one, and the client's address otherwise
// ([ClientIP]); in-process calls through [Endpoint].Call share one bucket. One
// client emptying its bucket is answered 429; the others are not — which is
// what a sign-in endpoint needs, where one shared bucket would let a single
// client lock everybody out.
//
// Buckets unused for ten minutes are forgotten, and at most 10 000 are kept:
// the least recently used goes first. It is the SDK's keyed rate limiter.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func RateLimitPerClient(perSecond float64, burst int) OperationOption {
	return rateLimitPerClient(perSecond, burst)
}

// SetCookie adds a Set-Cookie header to the HTTP response of the endpoint
// ctx serves. kit fills what a cookie left zero with safe defaults — Path
// "/", HttpOnly, SameSite Lax, and Secure outside dev — so a session cookie
// is hardened unless the code says otherwise. In an in-process
// [Endpoint].Call there is no response: the cookie is dropped.
//
// HttpOnly is always set, and Secure always outside dev (and in dev for
// SameSite=None, which browsers require): a boolean has no "unset" a default
// could fill, and kit chooses the hardened reading. A cookie set more than
// once in one response keeps its last value, and cookies set before an error
// are sent with the error — clearing a stale session on a 401 works.
func SetCookie(ctx context.Context, c *http.Cookie) {
	setCookie(ctx, c)
}

// ClearCookie tells the browser to forget the cookie called name.
func ClearCookie(ctx context.Context, name string) {
	clearCookie(ctx, name)
}

// ClientIP returns the address of the client of the request ctx serves: the
// connection's peer, or — only when KIT_TRUST_PROXY=on — the last address of
// X-Forwarded-For, the one the trusted proxy appended. It is "" outside an HTTP request.
func ClientIP(ctx context.Context) string {
	return clientIP(ctx)
}

// UserAgent returns the User-Agent of the request ctx serves, clipped.
func UserAgent(ctx context.Context) string {
	return userAgent(ctx)
}

// Now returns the app's time: the system clock, or the clock a test gave
// with [Clock]. Product code that compares with a deadline reads it rather
// than time.Now, so that a test's manual clock reaches it.
func Now(ctx context.Context) time.Time {
	return now(ctx)
}

// NewTicker is a ticker of period d on the app's clock, for a loop written by
// hand ([Service].Go): a test's manual clock drives it like every timer kit
// runs itself, where a time.Ticker would tick on the wall clock whatever the
// test does. It panics on a non-positive d, as time.NewTicker does.
func NewTicker(ctx context.Context, d time.Duration) clock.Ticker {
	return newTicker(ctx, d)
}

// After is time.After on the app's clock.
func After(ctx context.Context, d time.Duration) <-chan time.Time {
	return after(ctx, d)
}

// Log returns the app's logger, for the node ctx runs inside. In dev, every
// record it writes inside a span is also kept beside that span, so the
// Studio shows a request's logs with its trace.
func Log(ctx context.Context) logger.Logger {
	return log(ctx)
}

// Purpose says why the store keeps its records (GDPR art. 30(1)(b)): the
// register lists it, and a person's export carries it.
func Purpose(text string) StoreOption {
	return purpose(text)
}

// DeleteOnErasure makes a person's erasure (kit.Erase) delete the store's
// records instead of clearing them, as sessions and accounts want.
func DeleteOnErasure() StoreOption {
	return deleteOnErasure()
}

// RetentionByProduct says the product keeps the store's retention itself:
// its own code erases and deletes what it no longer needs — a record whose
// life the product's own rules end, a lifecycle kit cannot read from the
// entity. limits says, in the product's words, for how long and how, which
// the register publishes as the store's time limits (GDPR art. 30(1)(f));
// "" says only that the product keeps them.
//
// kit then runs no retention for the store, and warns of neither a missing
// retention nor a missing subject. Its classified fields keep every other
// promise: sealed at rest, never shown, exported with their person — when
// the store names one — and erased by kit.Erase and Store.Erase. It goes
// with kit.Purpose, kit.HeldUntil, kit.Anonymise and kit.DeleteOnErasure;
// with kit.EraseAfter, kit.EraseAt, kit.DeleteAfter or kit.DeleteAt it is
// refused: a store's retention is kit's or the product's, never both.
func RetentionByProduct(limits string) StoreOption {
	return retentionByProduct(limits)
}

// Revisions keeps the n previous versions of each record of the store, n
// from 1 to 100, as WordPress keeps a post's revisions: every write that
// changes a record makes a version, numbered from 1 and never renumbered,
// stamped with when it was made, the caller's user and the command that
// made it; the oldest beyond n are pruned by the write that makes a newer
// one, unless a legal hold keeps the record.
//
//	var Pages = Service.Store("pages", Page.Key, kit.Revisions(20))
//
//	revs, err := Pages.Revisions(ctx, id)                            // newest first
//	edits, err := Pages.Diff(ctx, id, revs[3].Number, revs[0].Number)
//	page, err := Pages.Restore(ctx, id, revs[3].Number)              // a new version
//	page, err = Pages.Restore(ctx, id, revs[3].Number, "/title")     // the title only
//
// A store with Revisions(n) holds up to n+1 times its records: in memory
// with the store in the data directory, in the table <table>___vs on a
// database, which kit's migrations create.
func Revisions(n int) StoreOption {
	return revisions(n)
}

// PerEnv is the environment variable name, else fallback when it is unset
// or empty; a leading "~/" in either is the user's home directory. The
// status line's is PerEnv("CLAUDE_CONFIG_DIR", "~/.claude"): one daemon per
// Claude configuration.
func PerEnv(name, fallback string) Scope {
	return perEnv(name, fallback)
}

// Generated makes the secret kit's to make: versions of bytes random bytes —
// 32 for a key — the first made on the first start, a new one every 30 days,
// the last 3 kept, unless [RotateEvery] and [KeepVersions] say otherwise.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Generated(bytes int) SecretOption {
	return generated(bytes)
}

// RotateEvery is how often kit makes a new version of a generated secret.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func RotateEvery(d time.Duration) SecretOption {
	return rotateEvery(d)
}

// KeepVersions is how many versions of a generated secret a rotation leaves,
// the new one included: at least 2, so that what the version it replaces
// sealed or signed still opens and verifies. Cover the longest-lived box or
// signature in flight: its lifetime divided by the interval, plus one.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func KeepVersions(n int) SecretOption {
	return keepVersions(n)
}

// Optional makes a provided secret one the product can do without — the key
// of a feature that stays off while nobody gives it. A start where it is set
// nowhere goes on; [Secret].Present says whether it is set now, and a use of
// it while it is absent — [Secret].Value, Seal, Open, Sign or Verify —
// answers an error errs.HasCode matches with [CodeSecretMissing]. It is read
// where it lives at every use, as every provided secret is: given later —
// `secrets set` in the environment's store, a new content in the file its
// _FILE variable names —, it is found at its next use. A generated secret
// is kit's to make and never absent: Optional with [Generated] is refused.
func Optional() SecretOption {
	return optional()
}

// SecretStore keeps the secrets in store instead of the environment's: a
// test gives a store holding what its provided secrets hold. The
// environment's variables are still read first.
func SecretStore(store secret.Store) AppOption {
	return secretStore(store)
}

// Required drops a setting's default: a start without a value for it fails,
// saying where to give one.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Required() SettingOption {
	return required()
}

// ConfigFiles gives kit the product's configuration files: config/config.<ext>,
// which every environment reads, and config/<env>.<ext>, the environment's
// own — <env> being KIT_ENV as written, dev when kit dev runs the product —
// in JSON, YAML or TOML (json, yaml or yml, toml). A file maps the names of
// the settings to their values; it never holds a secret, and a key no
// service declares stops the start. The files belong in the binary:
//
//	//go:embed config
//	var configFiles embed.FS
//
//	app := kit.NewApp("todo", ...).With(kit.ConfigFiles(configFiles))
func ConfigFiles(fsys fs.FS) AppOption {
	return configFiles(fsys)
}

// Root serves the sub-directory dir of the file system rather than its root —
// "assets" for a //go:embed assets directive.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Root(dir string) StaticOption {
	return root(dir)
}

// ReadModel marks a store as derived from others (ADR 0005): written by
// projections — the subscriptions that keep it from the write side's
// events —, read by queries. It changes nothing of how the store runs; the
// diagram draws it on its domain's read side, and the static analysis warns
// of a read model written by anything but a subscription. kit's topics are
// queues, not logs: a read model cannot be replayed from its events, and one
// fed by a topic lags the commands that feed it — a query that must read its
// own writes reads the write side.
//
//	var Summaries = Service.Store("summaries", Summary.Key, kit.ReadModel())
func ReadModel() StoreOption {
	return readModel()
}

// Telemetry exports the app's telemetry on the private socket at path —
// absolute, and short enough for a Unix socket (pkg/v1/proc/ipc) — admitting the groups gids besides the
// product's own account. It wins over KIT_TELEMETRY.
func Telemetry(path string, gids ...int) AppOption {
	return telemetry(path, gids...)
}

// DesignDigest records the digest of the design the product's code was
// generated from — what the generated wiring passes —, so the telemetry
// handshake can say it and a tool attached to the product can tell a process
// built from another design.
func DesignDigest(digest string) AppOption {
	return designDigest(digest)
}

// MaxDeliveries is how many attempts a message gets before it is
// dead-lettered — a subscription's, or a queued command's. The default is
// 5.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func MaxDeliveries(n int) DeliveryOption {
	return maxDeliveries(n)
}

// Parallelism is how many messages are handled at once — a subscription's,
// or a queued command's. The default is 1.
//
// IFACE-OPAQUE: the option is sealed — its method is unexported — so a caller
// only hands it to the declaration it configures.
func Parallelism(n int) DeliveryOption {
	return parallelism(n)
}

// OwnStores lets a watch ([Service].Watch) hear the stores of its own
// module too — the product's own, for a watch of the product's —, which a
// watch never hears by default. Such a watch never hears the writes its own
// handler makes, in its handler's context — a handler that writes what it
// watches, a screening that stamps the record it screened, would otherwise
// hear itself forever —; a write the handler only causes, later and
// elsewhere — a queued command's handling, a topic's delivery — is heard.
// A subscription to a topic refuses it: a topic has no stores.
func OwnStores() SubscriptionOption {
	return ownStores()
}

// Transact runs fn in one transaction and returns fn's error: nil commits
// what fn wrote, an error undoes it — a panic too, which then continues.
//
//	err := kit.Transact(ctx, func(ctx context.Context) error {
//		if _, err := Cases.Update(ctx, id, closeCase); err != nil {
//			return err // what this function wrote is undone
//		}
//		if err := Decisions.Insert(ctx, d); err != nil {
//			return err
//		}
//		return Changes.Publish(ctx, Closed{ID: id}) // held: queued after the commit
//	})
//
// A transaction belongs to one database: the one its first store call
// reaches — at its first call on a database, at its first write on the data
// directory, which counts as one, memory with it. Inside it, a store of
// another database is read as usual; writing one is refused ([Invalid],
// [CodeTransactionSpan]). A Transact inside another is a savepoint: its
// failure undoes its own writes, and the outer transaction goes on if its
// caller handles the error.
//
// What leaves the process waits for the outermost commit: a topic's
// publish, a queued command's dispatch, a mail — whose outbox ID [Mailer].Send
// returns at once —, a watch's notice, the store's write hooks that wake
// workflows and loops, a workflow's OnTransition hooks. Each is checked when
// it is made, so a caller's mistake returns to the caller; a rollback drops
// them, and a savepoint's rollback its own. One a queue refuses after the
// commit is logged and reported, and the commit stands; a process that dies
// between the commit and the release loses what was held.
//
// On a database the transaction is the database's own, at its default
// isolation. On the data directory and in memory kit keeps its own: it takes
// the data's writer turn — one transaction at a time; a write outside any
// waits for it, and such writes share the turn among themselves —, its
// writes land at once, and an error writes each entity's previous value
// back, newest first. It is atomic against an error, not against a crash,
// and a reader may see a write before its commit. A store kept in memory by
// [InMemory] — a cache — is in no transaction: its writes land and stay.
//
// A command's handler runs in one already ([NoTransaction] opts out), and
// so does a workflow's transition.
func Transact(ctx context.Context, fn func(context.Context) error) error {
	return transact(ctx, fn)
}
