// Code generated by kit from design/data/sql.yaml (sha256 6c036733e56c9d3b1d0c665279858ebff46ad2dcb4d1c51393bd3cd7995a1aeb, body c21de6e2b86ef57930073c191317095890867497929cc286750bf3ed87ac624a). DO NOT EDIT.

package sql

import "context"

// Transact runs fn inside a transaction with the driver's default isolation.
//
// It is the ergonomic form of [Transactor].Transact for the common case. The
// port itself keeps the options parameter so it never needs a second method
// (ADR 0039); this helper keeps the call site short.
func Transact(ctx context.Context, tm Transactor, fn TxFunc) error {
	return transact(ctx, tm, fn)
}
