load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//internal/kernel:kernel_consumers"])

go_library(
    name = "recycler",
    srcs = ["recycler.go"],
    importpath = "github.com/kitsunium/sdk/internal/kernel/recycler",
    visibility = ["//internal/kernel:kernel_consumers"],
)

alias(
    name = "go_default_library",
    actual = ":recycler",
    visibility = ["//internal/kernel:kernel_consumers"],
)

go_test(
    name = "recycler_test",
    size = "small",
    srcs = [
        "recycler_external_test.go",
        "recycler_internal_test.go",
    ],
    embed = [":recycler"],
)

filegroup(
    name = "audit_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//:__pkg__"],
)
